# インポート

In [9]:
import create_population
import create_population_dirt_sonoda
import create_population_dirt_urawa
import create_population_dirt_saga
import create_population_dirt_ooi
import create_population_dirt_nagoya
import create_population_dirt_morioka
import create_population_dirt_monbetu
import create_population_dirt_mizusawa
import create_population_dirt_kouti
import create_population_dirt_kawasaki
import create_population_dirt_kasamatu
import create_population_dirt_kanazawa
import create_population_dirt_funabasi
import preprocessing_nar
from feature_engineering import FeatureCreator



import pandas as pd
import numpy as np

import race_grade_maker

from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_niti_cross_in3 import Trainer_lightgbm_rank_niti_cv_in3

from train_lightgbm_time import Trainer_lightgbm_time
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki

from evaluation_shaft_time_kaiki_cross import Evaluator_lightgbm_time_kaiki_shaft

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross
from evaluation_shaft_rank_cross import Evaluator_lightgbm_rank_niti_shaft

from evaluation_lgbm_rank_niti_cross_ex_value import Evaluator_lightgbm_rank_niti_cross_ex_value

from evaluation_lgbm_rank_niti_cross_in3 import Evaluator_lightgbm_rank_niti_cross_in3

%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
%autoreload

In [6]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 800)

# 学習母集団の作成
- ここで何年までのデータを使うか設定してください
- 2016-01-01から、2024-11-30まではスクレイピングしてあります
- 特徴量が多いため、あまり年月が嵩むと処理が止まる恐れがあります

In [18]:

population_dirt_nagoya = create_population_dirt_nagoya.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_nagoya

            race_id       date    horse_id
0      202048010101 2020-01-01  2016102293
1      202048010101 2020-01-01  2016103605
2      202048010101 2020-01-01  2016102254
3      202048010101 2020-01-01  2016102330
4      202048010101 2020-01-01  2016104199
...             ...        ...         ...
73071  202548022812 2025-02-28  2020106938
73072  202548022812 2025-02-28  2020101617
73073  202548022812 2025-02-28  2018105551
73074  202548022812 2025-02-28  2017103142
73075  202548022812 2025-02-28  2021101386

[73076 rows x 3 columns]

In [19]:
population_all = create_population.create(from_="2020-01-01", to_="2025-02-28")
population_all

             race_id       date    horse_id
0       202045010101 2020-01-01  2017100321
1       202045010101 2020-01-01  2017102172
2       202045010101 2020-01-01  2017101060
3       202045010101 2020-01-01  2017104920
4       202045010101 2020-01-01  2017102986
...              ...        ...         ...
700185  202548022812 2025-02-28  2020106938
700186  202548022812 2025-02-28  2020101617
700187  202548022812 2025-02-28  2018105551
700188  202548022812 2025-02-28  2017103142
700189  202548022812 2025-02-28  2021101386

[700190 rows x 3 columns]

In [20]:
population_dirt_funabasi = create_population_dirt_funabasi.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_funabasi

            race_id       date    horse_id
0      202043010701 2020-01-07  2016105249
1      202043010701 2020-01-07  2016106244
2      202043010701 2020-01-07  2016110053
3      202043010701 2020-01-07  2016100771
4      202043010701 2020-01-07  2016102836
...             ...        ...         ...
38762  202543021412 2025-02-14  2020104733
38763  202543021412 2025-02-14  2021101338
38764  202543021412 2025-02-14  2021106957
38765  202543021412 2025-02-14  2021100847
38766  202543021412 2025-02-14  2020105653

[38767 rows x 3 columns]

In [45]:
population_dirt_sonoda = create_population_dirt_sonoda.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_sonoda

            race_id       date    horse_id
0      202050010201 2020-01-02  2015103856
1      202050010201 2020-01-02  2016101204
2      202050010201 2020-01-02  2016103711
3      202050010201 2020-01-02  2016105511
4      202050010201 2020-01-02  2015102592
...             ...        ...         ...
99227  202551022712 2025-02-27  2019105527
99228  202551022712 2025-02-27  2020100619
99229  202551022712 2025-02-27  2021101265
99230  202551022712 2025-02-27  2021102974
99231  202551022712 2025-02-27  2017106535

[99232 rows x 3 columns]

In [30]:
population_dirt_kanazawa = create_population_dirt_kanazawa.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_kanazawa

            race_id       date    horse_id
0      202046031501 2020-03-15  2017106443
1      202046031501 2020-03-15  2017100514
2      202046031501 2020-03-15  2017106069
3      202046031501 2020-03-15  2017105827
4      202046031501 2020-03-15  2017110091
...             ...        ...         ...
43591  202446122811 2024-12-28  2019102158
43592  202446122811 2024-12-28  2018105954
43593  202446122811 2024-12-28  2021102177
43594  202446122811 2024-12-28  2017101928
43595  202446122811 2024-12-28  2020104945

[43596 rows x 3 columns]

In [31]:
population_dirt_kasamatu = create_population_dirt_kasamatu.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_kasamatu

            race_id       date    horse_id
0      202035051701 2020-05-17  2016103780
1      202035051701 2020-05-17  2016104092
2      202035051701 2020-05-17  2013105706
3      202035051701 2020-05-17  2016103661
4      202035051701 2020-05-17  2016100654
...             ...        ...         ...
33594  202435111212 2024-11-12  2020102035
33595  202435111212 2024-11-12  2020104124
33596  202435111212 2024-11-12  2018102019
33597  202435111212 2024-11-12  2020105926
33598  202435111212 2024-11-12  2019105744

[33599 rows x 3 columns]

In [32]:
population_dirt_kawasaki = create_population_dirt_kawasaki.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_kawasaki

            race_id       date    horse_id
0      202045010101 2020-01-01  2017100321
1      202045010101 2020-01-01  2017102172
2      202045010101 2020-01-01  2017101060
3      202045010101 2020-01-01  2017104920
4      202045010101 2020-01-01  2017102986
...             ...        ...         ...
43843  202545020812 2025-02-08  2021101536
43844  202545020812 2025-02-08  2019100513
43845  202545020812 2025-02-08  2017105088
43846  202545020812 2025-02-08  2020106043
43847  202545020812 2025-02-08  2019106634

[43848 rows x 3 columns]

In [33]:
population_dirt_kouti = create_population_dirt_kouti.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_kouti

            race_id       date    horse_id
0      202054010101 2020-01-01  2016102561
1      202054010101 2020-01-01  2016105234
2      202054010101 2020-01-01  2016100154
3      202054010101 2020-01-01  2015103435
4      202054010101 2020-01-01  2016100245
...             ...        ...         ...
63904  202554022510 2025-02-25  2020100325
63905  202554022510 2025-02-25  2021103674
63906  202554022510 2025-02-25  2021102889
63907  202554022510 2025-02-25  2020104683
63908  202554022510 2025-02-25  2019109146

[63909 rows x 3 columns]

In [34]:
population_dirt_mizusawa = create_population_dirt_mizusawa.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_mizusawa

            race_id       date    horse_id
0      202036010201 2020-01-02  2016110136
1      202036010201 2020-01-02  2016100781
2      202036010201 2020-01-02  2016109053
3      202036010201 2020-01-02  2016102629
4      202036010201 2020-01-02  2016104092
...             ...        ...         ...
34350  202436123112 2024-12-31  2015103452
34351  202436123112 2024-12-31  2018100116
34352  202436123112 2024-12-31  2016100846
34353  202436123112 2024-12-31  2017109066
34354  202436123112 2024-12-31  2015105502

[34355 rows x 3 columns]

In [35]:
population_dirt_monbetu = create_population_dirt_monbetu.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_monbetu

            race_id       date    horse_id
0      202030041501 2020-04-15  2017104894
1      202030041501 2020-04-15  2017103560
2      202030041501 2020-04-15  2017102260
3      202030041501 2020-04-15  2017104530
4      202030041501 2020-04-15  2017100489
...             ...        ...         ...
47730  202430110712 2024-11-07  2014105851
47731  202430110712 2024-11-07  2017100630
47732  202430110712 2024-11-07  2018100955
47733  202430110712 2024-11-07  2020100492
47734  202430110712 2024-11-07  2021104428

[47735 rows x 3 columns]

In [36]:
population_dirt_morioka = create_population_dirt_morioka.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_morioka

            race_id       date    horse_id
0      202035051701 2020-05-17  2016103780
1      202035051701 2020-05-17  2016104092
2      202035051701 2020-05-17  2013105706
3      202035051701 2020-05-17  2016103661
4      202035051701 2020-05-17  2016100654
...             ...        ...         ...
33594  202435111212 2024-11-12  2020102035
33595  202435111212 2024-11-12  2020104124
33596  202435111212 2024-11-12  2018102019
33597  202435111212 2024-11-12  2020105926
33598  202435111212 2024-11-12  2019105744

[33599 rows x 3 columns]

In [37]:
population_dirt_ooi = create_population_dirt_ooi.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_ooi

            race_id       date    horse_id
0      202044012001 2020-01-20  2017101093
1      202044012001 2020-01-20  2017105697
2      202044012001 2020-01-20  2017105605
3      202044012001 2020-01-20  2017106156
4      202044012001 2020-01-20  2017103645
...             ...        ...         ...
74361  202544022112 2025-02-21  2021103631
74362  202544022112 2025-02-21  2020107159
74363  202544022112 2025-02-21  2021105206
74364  202544022112 2025-02-21  2021104843
74365  202544022112 2025-02-21  2020100449

[74366 rows x 3 columns]

In [38]:
population_dirt_saga = create_population_dirt_saga.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_saga

            race_id       date    horse_id
0      202055010301 2020-01-03  2017106458
1      202055010301 2020-01-03  2017102469
2      202055010301 2020-01-03  2017105780
3      202055010301 2020-01-03  2017100532
4      202055010301 2020-01-03  2017102085
...             ...        ...         ...
66174  202555022311 2025-02-23  2020101339
66175  202555022311 2025-02-23  2021104819
66176  202555022311 2025-02-23  2021102289
66177  202555022311 2025-02-23  2020101415
66178  202555022311 2025-02-23  2019100882

[66179 rows x 3 columns]

In [39]:
population_dirt_urawa = create_population_dirt_urawa.create(from_="2020-01-01", to_="2025-02-28")
population_dirt_urawa

            race_id       date    horse_id
0      202042011401 2020-01-14  2017104382
1      202042011401 2020-01-14  2017105808
2      202042011401 2020-01-14  2017104603
3      202042011401 2020-01-14  2017101873
4      202042011401 2020-01-14  2017103069
...             ...        ...         ...
38159  202542022812 2025-02-28  2021102500
38160  202542022812 2025-02-28  2021100930
38161  202542022812 2025-02-28  2017101498
38162  202542022812 2025-02-28  2019106220
38163  202542022812 2025-02-28  2021102321

[38164 rows x 3 columns]

NameError: name 'input_dir' is not defined

# データ加工

In [6]:
#まとめて実行_all
# レース結果テーブルの前処理
results_preprocessed_all = preprocessing_nar.process_results(
    populaton_filename = "population_all.csv",
    output_filename = "results_all.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_all = preprocessing_nar.process_horse_results(
    populaton_filename = "population_all.csv",
    output_filename = "horse_results_all.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_all = preprocessing_nar.process_race_info(
    populaton_filename = "population_all.csv",
    output_filename = "race_info_all_before.csv",       
)
# 騎手リーディングテーブルの前処理
# jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# # 調教師リーディングテーブルの前処理
# trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
# peds_preprocessed = preprocessing.process_peds(
#     populaton_filename = "population_all.csv",  
#     output_filename= "peds_all.csv",    
# )
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_all = preprocessing_nar.process_return_tables(
    populaton_filename = "population_all.csv",
    output_filename = "return_tables_all.pickle",    
)

In [5]:
# 重複チェック
results_preprocessed_all.duplicated(subset=["race_id", "horse_id"]).sum()

0

In [6]:
# 欠損チェック
results_preprocessed_all.isnull().sum()

race_id                    0
horse_id                   0
jockey_id                  0
trainer_id                 0
owner_id                   0
rank                       0
rank_per_horse             0
time                       0
nobori                    96
umaban                     0
wakuban                    0
tansho_odds                0
popularity                 0
impost                     0
sex                        0
age                        0
weight                     0
weight_diff                0
impost_percent             0
n_horses                   0
corner_1_per_horse         0
corner_2_per_horse      6543
corner_3_per_horse    139437
corner_4_per_horse    275111
mean_age                   0
median_age                 0
mean_age_kirisute          0
umaban_odd                 0
corner_1                   0
corner_2                6543
corner_3              139437
corner_4              275111
dtype: int64

In [7]:
# 欠損チェック
horse_results_preprocessed_all.isnull().sum()

horse_id                                                         0
rank_per_horse                                                   0
date                                                             0
rank                                                             0
prize                                                            0
rank_diff                                                        0
umaban                                                           0
wakuban                                                          0
weather                                                          0
race_type                                                        0
course_len                                                       0
impost                                                           0
ground_state                                                     0
race_class                                                       0
n_horses                                                         0
time                                                             0
time_courselen                                                   0
nobori                                                         216
win                                                              0
rentai                                                           0
show                                                             0
place                                                            0
goal_range                                                       0
curve                                                            0
goal_slope                                                       0
goal_range_100                                               15969
place_course_category                                            0
place_course_tough                                               0
weight                                                         338
weight_diff                                                    338
corner_1_per_horse                                               0
corner_2_per_horse                                            9173
corner_3_per_horse                                          282565
corner_4_per_horse                                          466720
race_position                                                    0
race_grade                                                       0
race_grade_scaled                                                0
pace_diff                                                    37032
pace_category                                                37032
place_season_condition_type_categori                          6978
course_len_type                                                  0
course_type                                                      0
age_n                                                            0
umaban_odd                                                       0
season                                                           0
place_season                                                     0
place_season_type                                                0
place_season_condition_type                                      0
season_turf_condition                                            0
curve_amount                                                     0
start_point                                                      0
start_range                                                      0
straight_total                                                   0
curve_total                                                      0
curve_R12                                                        0
curve_R34                                                        0
height_diff                                                      0
width                                                            0
start_slope                                                      0
flont_slope                                                      0
first_curve_slope                                                0
last_curve_slope                                                 0
season_turf                                                      0
day_season_turf                                                  0
umaban_judge                                                     0
first_corner                                                     0
nobori_pace_diff_slope_range_groundstate_position            43707
nobori_pace_diff_slope_range_groundstate_position_umaban     43707
course_len_allfix                                            43684
corner_1                                                         0
corner_2                                                      9173
corner_3                                                    282565
corner_4                                                    466720
pace_1                                                       37032
pace_2                                                       37032
dtype: int64

In [8]:
# 重複チェック
horse_results_preprocessed_all.duplicated(subset=["horse_id", "date"]).sum()

0

In [9]:
# race_info_preprocessed_allの'race_class'列に含まれる数字（ユニークな値）の種類を確認する方法
unique_race_class_values = race_info_preprocessed_all['race_class'].unique()
print(unique_race_class_values)

[-12 -11 -10  -8  -6  -5 -14  -9   1  -7 -13 -15  -4   6   8   7   5  -2
  -3  -1]

In [7]:
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_all.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)

In [30]:
fc_grade

,race_id,date,race_type,around,course_len,weather,ground_state,race_class,place,season_level,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,place_season_type_course_len,lap_type,race_day_count,race_date_day_count,goal_range_100,course_type,course_len_type,curve_amount,start_point,start_range,straight_total,curve_total,curve_R12,curve_R34,height_diff,width,start_slope,flont_slope,first_curve_slope,last_curve_slope,season_turf,day_season_turf,season_turf_condition,race_grade,age_season,race_grade_scaled
0,202045010101,2020-01-01,0,1,1500,1,0,-12,45,1,4,454,4540,1,10,1,10,1,10,454010,1,4540,-2.0,1045,-1,300.0,1.0,0.0,45401500,-1,1,73693601,3.0,45015001,1,4.0,1.0,400.0,1100.0,400.0,81.0,81.0,0.0,25.0,0.0,0.0,0.0,0.0,2.0,12,3.75,49,31.0,4.9
1,202045010102,2020-01-01,0,1,1400,1,0,-12,45,1,4,454,4540,2,20,1,10,1,10,454010,1,4540,-2.0,1045,-1,300.0,1.0,0.0,45401400,-1,2,73693602,3.0,45014001,1,4.0,1.0,300.0,1000.0,400.0,81.0,81.0,0.0,25.0,0.0,0.0,0.0,0.0,2.0,12,3.75,49,31.0,4.9
2,202045010103,2020-01-01,0,1,1400,1,0,-12,45,1,4,454,4540,3,30,1,10,1,10,454010,1,4540,-2.0,1045,-1,300.0,1.0,0.0,45401400,-1,3,73693603,3.0,45014001,1,4.0,1.0,300.0,1000.0,400.0,81.0,81.0,0.0,25.0,0.0,0.0,0.0,0.0,2.0,12,3.75,49,31.0,4.9
3,202045010104,2020-01-01,0,1,900,1,0,-12,45,1,4,454,4540,4,40,1,10,1,10,454010,1,4540,-2.0,1045,-1,300.0,1.0,0.0,4540900,-1,4,73693604,3.0,4509001,1,2.0,1.0,400.0,700.0,200.0,0.0,81.0,0.0,25.0,0.0,0.0,0.0,0.0,2.0,12,3.75,49,61.0,4.9
4,202045010105,2020-01-01,0,1,1400,1,0,-12,45,1,4,454,4540,5,50,1,10,1,10,454010,1,4540,-2.0,1045,-1,300.0,1.0,0.0,45401400,-1,5,73693605,3.0,45014001,1,4.0,1.0,300.0,1000.0,400.0,81.0,81.0,0.0,25.0,0.0,0.0,0.0,0.0,2.0,12,3.75,49,51.0,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68499,202548022808,2025-02-28,0,0,1500,2,0,-7,48,1,4,484,4840,8,80,28,280,2,20,484280,2,4840,-3.0,1048,-1,240.0,1.0,0.0,48401500,-1,8,73881908,2.4,48015001,1,4.0,1.0,380.0,920.0,580.0,70.0,70.0,0.0,30.0,0.0,0.0,0.0,0.0,2.0,282,44.25,67,41.0,6.7
68500,202548022809,2025-02-28,0,0,1500,2,0,-5,48,1,4,484,4840,9,90,28,280,2,20,484280,2,4840,-3.0,1048,-1,240.0,1.0,0.0,48401500,-1,9,73881909,2.4,48015001,1,4.0,1.0,380.0,920.0,580.0,70.0,70.0,0.0,30.0,0.0,0.0,0.0,0.0,2.0,282,44.25,73,51.0,7.3
68501,202548022810,2025-02-28,0,0,1500,2,0,-11,48,1,4,484,4840,10,100,28,280,2,20,484280,2,4840,-3.0,1048,-1,240.0,1.0,0.0,48401500,-1,10,73881910,2.4,48015001,1,4.0,1.0,380.0,920.0,580.0,70.0,70.0,0.0,30.0,0.0,0.0,0.0,0.0,2.0,282,44.25,48,41.0,4.8
68502,202548022811,2025-02-28,0,0,1700,2,0,-5,48,1,4,484,4840,11,110,28,280,2,20,484280,2,4840,-3.0,1048,-1,240.0,1.0,0.0,48401700,-1,11,73881911,2.4,48017001,1,5.0,1.0,135.0,975.0,725.0,70.0,70.0,0.0,30.0,0.0,0.0,0.0,0.0,2.0,282,44.25,73,51.0,7.3
68503,202548022812,2025-02-28,0,0,1700,2,0,-8,48,1,4,484,4840,12,120,28,280,2,20,484280,2,4840,-3.0,1048,-1,240.0,1.0,0.0,48401700,-1,12,73881912,2.4,48017001,1,5.0,1.0,135.0,975.0,725.0,70.0,70.0,0.0,30.0,0.0,0.0,0.0,0.0,2.0,282,44.25,62,51.0,6.2

#  特徴量作成

In [8]:
#_turfの特徴量作成
fc_funabasi = FeatureCreator(
    poplation_filename="population_dirt_funabasi.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_funabasi.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_funabasi = fc_funabasi.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [43]:
# 重複チェック
features_funabasi.duplicated(subset=["race_id", "horse_id"]).sum()

0

In [31]:
#特徴量を変更した場合に実行、"config_lightgbm_niti_new.yaml"に特徴量リストが入る
list(features_turf.columns)
import yaml
feature_cols = {
    "features": features_turf.columns.drop(
        ["date","rank","rank_per_horse","time","nobori","corner_1","corner_2","corner_3","corner_4",
                        "corner_1_per_horse","corner_2_per_horse",
                        "corner_3_per_horse",
                        "corner_4_per_horse", "owner_id"]
    ).to_list()
}
print(feature_cols)
with open("config_lightgbm_niti_new.yaml","w") as file:
    yaml.dump(feature_cols,file
              )

{'features': ['race_id', 'horse_id', 'jockey_id', 'trainer_id', 'umaban', 'wakuban', 'tansho_odds', 'popularity', 'impost', 'sex', 'age', 'weight', 'weight_diff', 'impost_percent', 'n_horses', 'mean_age', 'median_age', 'mean_age_kirisute', 'umaban_odd', 'race_type', 'around', 'course_len', 'weather', 'ground_state', 'race_class', 'place', 'season', 'place_season', 'place_season_type', 'kaisai_race', 'kaisai_race_type', 'day', 'day_type', 'kaisai_count', 'kaisai_count_type', 'place_season_day_type', 'day_condition', 'place_season_condition_type', 'place_season_condition_type_categori_x', 'place_course_category', 'place_course_tough', 'goal_range', 'curve', 'goal_slope', 'place_season_type_course_len', 'lap_type', 'race_day_count', 'race_date_day_count', 'goal_range_100', 'course_type', 'course_len_type', 'curve_amount', 'start_point', 'start_range', 'straight_total', 'curve_total', 'curve_R12', 'curve_R34', 'height_diff', 'width', 'start_slope', 'flont_slope', 'first_curve_slope', 'last_curve_slope', 'age_season', 'race_grade', 'race_grade_scaled', 'rank_1races', 'rank_per_horse_1races', 'prize_1races', 'rank_3races', 'rank_per_horse_3races', 'prize_3races', 'rank_5races', 'rank_per_horse_5races', 'prize_5races', 'rank_10races', 'rank_per_horse_10races', 'prize_10races', 'rank_1000races', 'rank_per_horse_1000races', 'prize_1000races', 'course_len_mean_1races_relative', 'course_len_max_1races_relative', 'course_len_min_1races_relative', 'course_len_diff_mean_1races_relative', 'course_len_diff_max_1races_relative', 'course_len_diff_min_1races_relative', 'n_horses_mean_1races_relative', 'n_horses_max_1races_relative', 'n_horses_min_1races_relative', 'n_horses_diff_mean_1races_relative', 'n_horses_diff_max_1races_relative', 'n_horses_diff_min_1races_relative', 'course_len_mean_1races', 'course_len_max_1races', 'course_len_min_1races', 'course_len_diff_mean_1races', 'course_len_diff_max_1races', 'course_len_diff_min_1races', 'n_horses_mean_1races', 'n_horses_max_1races', 'n_horses_min_1races', 'n_horses_diff_mean_1races', 'n_horses_diff_max_1races', 'n_horses_diff_min_1races', 'course_len_mean_3races_relative', 'course_len_max_3races_relative', 'course_len_min_3races_relative', 'course_len_diff_mean_3races_relative', 'course_len_diff_max_3races_relative', 'course_len_diff_min_3races_relative', 'n_horses_mean_3races_relative', 'n_horses_max_3races_relative', 'n_horses_min_3races_relative', 'n_horses_diff_mean_3races_relative', 'n_horses_diff_max_3races_relative', 'n_horses_diff_min_3races_relative', 'course_len_mean_3races', 'course_len_max_3races', 'course_len_min_3races', 'course_len_diff_mean_3races', 'course_len_diff_max_3races', 'course_len_diff_min_3races', 'n_horses_mean_3races', 'n_horses_max_3races', 'n_horses_min_3races', 'n_horses_diff_mean_3races', 'n_horses_diff_max_3races', 'n_horses_diff_min_3races', 'course_len_mean_5races_relative', 'course_len_max_5races_relative', 'course_len_min_5races_relative', 'course_len_diff_mean_5races_relative', 'course_len_diff_max_5races_relative', 'course_len_diff_min_5races_relative', 'n_horses_mean_5races_relative', 'n_horses_max_5races_relative', 'n_horses_min_5races_relative', 'n_horses_diff_mean_5races_relative', 'n_horses_diff_max_5races_relative', 'n_horses_diff_min_5races_relative', 'course_len_mean_5races', 'course_len_max_5races', 'course_len_min_5races', 'course_len_diff_mean_5races', 'course_len_diff_max_5races', 'course_len_diff_min_5races', 'n_horses_mean_5races', 'n_horses_max_5races', 'n_horses_min_5races', 'n_horses_diff_mean_5races', 'n_horses_diff_max_5races', 'n_horses_diff_min_5races', 'course_len_mean_10races_relative', 'course_len_max_10races_relative', 'course_len_min_10races_relative', 'course_len_diff_mean_10races_relative', 'course_len_diff_max_10races_relative', 'course_len_diff_min_10races_relative', 'n_horses_mean_10races_relative', 'n_horses_max_10races_relative', 'n_horses_min_10races_relative', 'n_horses_diff_mean_10races_relative', 'n_horses_diff_max_10races_relative', 'n_horses_diff_min_10races_relative', 'course_len_mean_10races', 'course_len_max_10races', 'course_len_min_10races', 'course_len_diff_mean_10races', 'course_len_diff_max_10races', 'course_len_diff_min_10races', 'n_horses_mean_10races', 'n_horses_max_10races', 'n_horses_min_10races', 'n_horses_diff_mean_10races', 'n_horses_diff_max_10races', 'n_horses_diff_min_10races', 'umaban_relative', 'start_point_umaban', 'wakuban_relative', 'impost_relative', 'age_relative', 'weight_relative', 'weight_diff_relative', 'impost_percent_relative', 'time_mean_1races_per_course_len_relative', 'time_min_1races_per_course_len_relative', 'nobori_mean_1races_per_course_len_relative', 'nobori_min_1races_per_course_len_relative', 'time_mean_3races_per_course_len_relative', 'time_min_3races_per_course_len_relative', 'nobori_mean_3races_per_course_len_relative', 'nobori_min_3races_per_course_len_relative', 'time_mean_5races_per_course_len_relative', 'time_min_5races_per_course_len_relative', 'nobori_mean_5races_per_course_len_relative', 'nobori_min_5races_per_course_len_relative', 'time_mean_10races_per_course_len_relative', 'time_min_10races_per_course_len_relative', 'nobori_mean_10races_per_course_len_relative', 'nobori_min_10races_per_course_len_relative', 'time_mean_1races_per_ground_state_race_type_relative', 'time_max_1races_per_ground_state_race_type_relative', 'time_min_1races_per_ground_state_race_type_relative', 'nobori_mean_1races_per_ground_state_race_type_relative', 'nobori_max_1races_per_ground_state_race_type_relative', 'nobori_min_1races_per_ground_state_race_type_relative', 'corner_1_per_horse_mean_1races_per_ground_state_race_type_relative', 'corner_1_per_horse_max_1races_per_ground_state_race_type_relative', 'corner_1_per_horse_min_1races_per_ground_state_race_type_relative', 'corner_2_per_horse_mean_1races_per_ground_state_race_type_relative', 'corner_2_per_horse_max_1races_per_ground_state_race_type_relative', 'corner_2_per_horse_min_1races_per_ground_state_race_type_relative', 'corner_3_per_horse_mean_1races_per_ground_state_race_type_relative', 'corner_3_per_horse_max_1races_per_ground_state_race_type_relative', 'corner_3_per_horse_min_1races_per_ground_state_race_type_relative', 'corner_4_per_horse_mean_1races_per_ground_state_race_type_relative', 'corner_4_per_horse_max_1races_per_ground_state_race_type_relative', 'corner_4_per_horse_min_1races_per_ground_state_race_type_relative', 'time_mean_3races_per_ground_state_race_type_relative', 'time_max_3races_per_ground_state_race_type_relative', 'time_min_3races_per_ground_state_race_type_relative', 'nobori_mean_3races_per_ground_state_race_type_relative', 'nobori_max_3races_per_ground_state_race_type_relative', 'nobori_min_3races_per_ground_state_race_type_relative', 'corner_1_per_horse_mean_3races_per_ground_state_race_type_relative', 'corner_1_per_horse_max_3races_per_ground_state_race_type_relative', 'corner_1_per_horse_min_3races_per_ground_state_race_type_relative', 'corner_2_per_horse_mean_3races_per_ground_state_race_type_relative', 'corner_2_per_horse_max_3races_per_ground_state_race_type_relative', 'corner_2_per_horse_min_3races_per_ground_state_race_type_relative', 'corner_3_per_horse_mean_3races_per_ground_state_race_type_relative', 'corner_3_per_horse_max_3races_per_ground_state_race_type_relative', 'corner_3_per_horse_min_3races_per_ground_state_race_type_relative', 'corner_4_per_horse_mean_3races_per_ground_state_race_type_relative', 'corner_4_per_horse_max_3races_per_ground_state_race_type_relative', 'corner_4_per_horse_min_3races_per_ground_state_race_type_relative', 'time_mean_5races_per_ground_state_race_type_relative', 'time_max_5races_per_ground_state_race_type_relative', 'time_min_5races_per_ground_state_race_type_relative', 'nobori_mean_5races_per_ground_state_race_type_relative', 'nobori_max_5races_per_ground_state_race_type_relative', 'nobori_min_5races_per_ground_state_race_type_relative', 'corner_1_per_horse_mean_5races_per_ground_state_race_type_relative', 'corner_1_per_horse_max_5races_per_ground_state_race_type_relative', 'corner_1_per_horse_min_5races_per_ground_state_race_type_relative', 'corner_2_per_horse_mean_5races_per_ground_state_race_type_relative', 'corner_2_per_horse_max_5races_per_ground_state_race_type_relative', 'corner_2_per_horse_min_5races_per_ground_state_race_type_relative', 'corner_3_per_horse_mean_5races_per_ground_state_race_type_relative', 'corner_3_per_horse_max_5races_per_ground_state_race_type_relative', 'corner_3_per_horse_min_5races_per_ground_state_race_type_relative', 'corner_4_per_horse_mean_5races_per_ground_state_race_type_relative', 'corner_4_per_horse_max_5races_per_ground_state_race_type_relative', 'corner_4_per_horse_min_5races_per_ground_state_race_type_relative', 'time_mean_10races_per_ground_state_race_type_relative', 'time_max_10races_per_ground_state_race_type_relative', 'time_min_10races_per_ground_state_race_type_relative', 'nobori_mean_10races_per_ground_state_race_type_relative', 'nobori_max_10races_per_ground_state_race_type_relative', 'nobori_min_10races_per_ground_state_race_type_relative', 'corner_1_per_horse_mean_10races_per_ground_state_race_type_relative', 'corner_1_per_horse_max_10races_per_ground_state_race_type_relative', 'corner_1_per_horse_min_10races_per_ground_state_race_type_relative', 'corner_2_per_horse_mean_10races_per_ground_state_race_type_relative', 'corner_2_per_horse_max_10races_per_ground_state_race_type_relative', 'corner_2_per_horse_min_10races_per_ground_state_race_type_relative', 'corner_3_per_horse_mean_10races_per_ground_state_race_type_relative', 'corner_3_per_horse_max_10races_per_ground_state_race_type_relative', 'corner_3_per_horse_min_10races_per_ground_state_race_type_relative', 'corner_4_per_horse_mean_10races_per_ground_state_race_type_relative', 'corner_4_per_horse_max_10races_per_ground_state_race_type_relative', 'corner_4_per_horse_min_10races_per_ground_state_race_type_relative', 'time_mean_1races_per_race_type_relative', 'time_max_1races_per_race_type_relative', 'time_min_1races_per_race_type_relative', 'nobori_mean_1races_per_race_type_relative', 'nobori_max_1races_per_race_type_relative', 'nobori_min_1races_per_race_type_relative', 'corner_1_per_horse_mean_1races_per_race_type_relative', 'corner_1_per_horse_max_1races_per_race_type_relative', 'corner_1_per_horse_min_1races_per_race_type_relative', 'corner_2_per_horse_mean_1races_per_race_type_relative', 'corner_2_per_horse_max_1races_per_race_type_relative', 'corner_2_per_horse_min_1races_per_race_type_relative', 'corner_3_per_horse_mean_1races_per_race_type_relative', 'corner_3_per_horse_max_1races_per_race_type_relative', 'corner_3_per_horse_min_1races_per_race_type_relative', 'corner_4_per_horse_mean_1races_per_race_type_relative', 'corner_4_per_horse_max_1races_per_race_type_relative', 'corner_4_per_horse_min_1races_per_race_type_relative', 'time_mean_3races_per_race_type_relative', 'time_max_3races_per_race_type_relative', 'time_min_3races_per_race_type_relative', 'nobori_mean_3races_per_race_type_relative', 'nobori_max_3races_per_race_type_relative', 'nobori_min_3races_per_race_type_relative', 'corner_1_per_horse_mean_3races_per_race_type_relative', 'corner_1_per_horse_max_3races_per_race_type_relative', 'corner_1_per_horse_min_3races_per_race_type_relative', 'corner_2_per_horse_mean_3races_per_race_type_relative', 'corner_2_per_horse_max_3races_per_race_type_relative', 'corner_2_per_horse_min_3races_per_race_type_relative', 'corner_3_per_horse_mean_3races_per_race_type_relative', 'corner_3_per_horse_max_3races_per_race_type_relative', 'corner_3_per_horse_min_3races_per_race_type_relative', 'corner_4_per_horse_mean_3races_per_race_type_relative', 'corner_4_per_horse_max_3races_per_race_type_relative', 'corner_4_per_horse_min_3races_per_race_type_relative', 'time_mean_5races_per_race_type_relative', 'time_max_5races_per_race_type_relative', 'time_min_5races_per_race_type_relative', 'nobori_mean_5races_per_race_type_relative', 'nobori_max_5races_per_race_type_relative', 'nobori_min_5races_per_race_type_relative', 'corner_1_per_horse_mean_5races_per_race_type_relative', 'corner_1_per_horse_max_5races_per_race_type_relative', 'corner_1_per_horse_min_5races_per_race_type_relative', 'corner_2_per_horse_mean_5races_per_race_type_relative', 'corner_2_per_horse_max_5races_per_race_type_relative', 'corner_2_per_horse_min_5races_per_race_type_relative', 'corner_3_per_horse_mean_5races_per_race_type_relative', 'corner_3_per_horse_max_5races_per_race_type_relative', 'corner_3_per_horse_min_5races_per_race_type_relative', 'corner_4_per_horse_mean_5races_per_race_type_relative', 'corner_4_per_horse_max_5races_per_race_type_relative', 'corner_4_per_horse_min_5races_per_race_type_relative', 'time_mean_10races_per_race_type_relative', 'time_max_10races_per_race_type_relative', 'time_min_10races_per_race_type_relative', 'nobori_mean_10races_per_race_type_relative', 'nobori_max_10races_per_race_type_relative', 'nobori_min_10races_per_race_type_relative', 'corner_1_per_horse_mean_10races_per_race_type_relative', 'corner_1_per_horse_max_10races_per_race_type_relative', 'corner_1_per_horse_min_10races_per_race_type_relative', 'corner_2_per_horse_mean_10races_per_race_type_relative', 'corner_2_per_horse_max_10races_per_race_type_relative', 'corner_2_per_horse_min_10races_per_race_type_relative', 'corner_3_per_horse_mean_10races_per_race_type_relative', 'corner_3_per_horse_max_10races_per_race_type_relative', 'corner_3_per_horse_min_10races_per_race_type_relative', 'corner_4_per_horse_mean_10races_per_race_type_relative', 'corner_4_per_horse_max_10races_per_race_type_relative', 'corner_4_per_horse_min_10races_per_race_type_relative', 'time_mean_1races_per_race_place_len_relative', 'time_max_1races_per_race_place_len_relative', 'time_min_1races_per_race_place_len_relative', 'nobori_mean_1races_per_race_place_len_relative', 'nobori_max_1races_per_race_place_len_relative', 'nobori_min_1races_per_race_place_len_relative', 'corner_1_per_horse_mean_1races_per_race_place_len_relative', 'corner_1_per_horse_max_1races_per_race_place_len_relative', 'corner_1_per_horse_min_1races_per_race_place_len_relative', 'corner_2_per_horse_mean_1races_per_race_place_len_relative', 'corner_2_per_horse_max_1races_per_race_place_len_relative', 'corner_2_per_horse_min_1races_per_race_place_len_relative', 'corner_3_per_horse_mean_1races_per_race_place_len_relative', 'corner_3_per_horse_max_1races_per_race_place_len_relative', 'corner_3_per_horse_min_1races_per_race_place_len_relative', 'corner_4_per_horse_mean_1races_per_race_place_len_relative', 'corner_4_per_horse_max_1races_per_race_place_len_relative', 'corner_4_per_horse_min_1races_per_race_place_len_relative', 'time_mean_3races_per_race_place_len_relative', 'time_max_3races_per_race_place_len_relative', 'time_min_3races_per_race_place_len_relative', 'nobori_mean_3races_per_race_place_len_relative', 'nobori_max_3races_per_race_place_len_relative', 'nobori_min_3races_per_race_place_len_relative', 'corner_1_per_horse_mean_3races_per_race_place_len_relative', 'corner_1_per_horse_max_3races_per_race_place_len_relative', 'corner_1_per_horse_min_3races_per_race_place_len_relative', 'corner_2_per_horse_mean_3races_per_race_place_len_relative', 'corner_2_per_horse_max_3races_per_race_place_len_relative', 'corner_2_per_horse_min_3races_per_race_place_len_relative', 'corner_3_per_horse_mean_3races_per_race_place_len_relative', 'corner_3_per_horse_max_3races_per_race_place_len_relative', 'corner_3_per_horse_min_3races_per_race_place_len_relative', 'corner_4_per_horse_mean_3races_per_race_place_len_relative', 'corner_4_per_horse_max_3races_per_race_place_len_relative', 'corner_4_per_horse_min_3races_per_race_place_len_relative', 'time_mean_5races_per_race_place_len_relative', 'time_max_5races_per_race_place_len_relative', 'time_min_5races_per_race_place_len_relative', 'nobori_mean_5races_per_race_place_len_relative', 'nobori_max_5races_per_race_place_len_relative', 'nobori_min_5races_per_race_place_len_relative', 'corner_1_per_horse_mean_5races_per_race_place_len_relative', 'corner_1_per_horse_max_5races_per_race_place_len_relative', 'corner_1_per_horse_min_5races_per_race_place_len_relative', 'corner_2_per_horse_mean_5races_per_race_place_len_relative', 'corner_2_per_horse_max_5races_per_race_place_len_relative', 'corner_2_per_horse_min_5races_per_race_place_len_relative', 'corner_3_per_horse_mean_5races_per_race_place_len_relative', 'corner_3_per_horse_max_5races_per_race_place_len_relative', 'corner_3_per_horse_min_5races_per_race_place_len_relative', 'corner_4_per_horse_mean_5races_per_race_place_len_relative', 'corner_4_per_horse_max_5races_per_race_place_len_relative', 'corner_4_per_horse_min_5races_per_race_place_len_relative', 'time_mean_10races_per_race_place_len_relative', 'time_max_10races_per_race_place_len_relative', 'time_min_10races_per_race_place_len_relative', 'nobori_mean_10races_per_race_place_len_relative', 'nobori_max_10races_per_race_place_len_relative', 'nobori_min_10races_per_race_place_len_relative', 'corner_1_per_horse_mean_10races_per_race_place_len_relative', 'corner_1_per_horse_max_10races_per_race_place_len_relative', 'corner_1_per_horse_min_10races_per_race_place_len_relative', 'corner_2_per_horse_mean_10races_per_race_place_len_relative', 'corner_2_per_horse_max_10races_per_race_place_len_relative', 'corner_2_per_horse_min_10races_per_race_place_len_relative', 'corner_3_per_horse_mean_10races_per_race_place_len_relative', 'corner_3_per_horse_max_10races_per_race_place_len_relative', 'corner_3_per_horse_min_10races_per_race_place_len_relative', 'corner_4_per_horse_mean_10races_per_race_place_len_relative', 'corner_4_per_horse_max_10races_per_race_place_len_relative', 'corner_4_per_horse_min_10races_per_race_place_len_relative', 'interval', 'wakuban_race_type', 'wakuban_around', 'umaban_race_type', 'umaban_around', 'sin_date_sex', 'cos_date_sex', 'distance_type_encoded', 'distance_place_type_encoded', 'distance_place_type_race_grade_encoded', 'distance_place_type_wakuban_encoded', 'distance_place_type_umaban_encoded', 'distance_place_type_wakuban_race_grade_encoded', 'distance_place_type_umaban_race_grade_encoded', 'distance_place_type_wakuban_straight_encoded', 'distance_place_type_umaban_straight_encoded', 'distance_place_type_wakuban_ground_state_encoded', 'distance_place_type_umaban_ground_state_encoded', 'distance_place_type_wakuban_ground_state_straight_encoded', 'distance_place_type_umaban_ground_state_straight_encoded', 'distance_type_weather_encoded', 'distance_place_type_weather_encoded', 'distance_place_type_race_grade_weather_encoded', 'distance_type_ground_state_encoded', 'distance_place_type_ground_state_encoded', 'distance_place_type_race_grade_ground_state_encoded', 'distance_type_sex_encoded', 'distance_place_type_sex_encoded', 'distance_place_type_race_grade_sex_encoded', 'distance_type_sex_weather_encoded', 'distance_place_type_sex_weather_encoded', 'distance_place_type_race_grade_sex_weather_encoded', 'distance_type_sex_ground_state_encoded', 'distance_place_type_sex_ground_state_encoded', 'distance_place_type_race_grade_sex_ground_state_encoded', 'distance_type_straight_encoded', 'distance_place_type_straight_encoded', 'distance_place_type_race_grade_straight_encoded', 'distance_type_straight_ground_state_encoded', 'distance_place_type_straight_ground_state_encoded', 'distance_place_type_race_grade_straight_ground_state_encoded', 'distance_place_type_race_grade_around_weather_ground_state_encoded', 'distance_place_type_umaban_race_grade_around_weather_ground_state_encoded', 'distance_place_type_ground_state_weather_encoded', 'distance_place_type_umaban_race_grade_around_weather_ground_state_nobori_encoded', 'distance_place_type_race_grade_nobori_encoded', 'distance_place_type_ground_state_weather_nobori_encoded', 'distance_place_type_nobori_encoded', 'mean_fukusho_rate_wakuban', 'mean_fukusho_rate_umaban', 'distanc

In [ ]:
features_funabasi.head(100)

In [4]:
#もしもカーネルがリセットした場合、ここからfeatureをとる
features_turf = pd.read_csv("../data/02_features/features_turf.csv", sep="\t")

In [57]:
#もしもカーネルがリセットした場合、ここからfeatureをとる
features_dirt = pd.read_csv("../data/02_features/features_dirt.csv", sep="\t")

In [58]:
#もしもカーネルがリセットした場合、ここからfeatureをとる
features_obstract = pd.read_csv("../data/02_features/features_obstract.csv", sep="\t")

In [66]:
features_funabasi

            race_id        date    horse_id jockey_id trainer_id owner_id  \
0      202043010701  2020-01-07  2016105249     jocke      train    owner
1      202043010701  2020-01-07  2016106244     jocke      train    owner
2      202043010701  2020-01-07  2016110053     jocke      train    owner
3      202043010701  2020-01-07  2016100771     jocke      train    owner
4      202043010701  2020-01-07  2016102836     jocke      train    owner
...             ...         ...         ...       ...        ...      ...
38096  202543021412  2025-02-14  2020104733     jocke      train    owner
38097  202543021412  2025-02-14  2021101338     jocke      train    owner
38098  202543021412  2025-02-14  2021106957     jocke      train    owner
38099  202543021412  2025-02-14  2021100847     jocke      train    owner
38100  202543021412  2025-02-14  2020105653     jocke      train    owner

       rank  rank_per_horse   time  nobori  umaban  wakuban  tansho_odds  \
0         1        0.142857   75.8    39.8       7        7          5.3
1         2        0.285714   76.1    40.1       6        6         10.4
2         3        0.428571   76.9    40.1       5        5         17.7
3         4        0.571429   77.0    40.8       4        4         22.3
4         5        0.714286   78.1    41.3       3        3         16.2
...     ...             ...    ...     ...     ...      ...          ...
38096     9        0.692308  151.9    40.8       8        6          6.9
38097    10        0.769231  151.9    39.8       3        3         89.0
38098    11        0.846154  152.6    41.1       5        4        224.8
38099    12        0.923077  152.8    42.4       4        4         60.1
38100    13        1.000000  153.4    42.9      13        8         13.6

       popularity  impost  sex  age  weight  weight_diff  impost_percent  \
0               2    56.5    0    4     562            0        0.100534
1               3    54.5    1    4     493           -5        0.110548
2               5    56.5    0    4     573            8        0.098604
3               6    54.5    1    4     525            0        0.103810
4               4    54.5    1    4     456           -4        0.119518
...           ...     ...  ...  ...     ...          ...             ...
38096           3    56.0    0    5     541          -10        0.103512
38097          12    56.0    0    4     479            3        0.116910
38098          13    56.0    0    4     504            2        0.111111
38099          11    54.0    1    4     417            6        0.129496
38100           7    54.0    1    5     436            3        0.123853

       n_horses  corner_1_per_horse  corner_2_per_horse  corner_3_per_horse  \
0             7            0.142857            0.142857            0.142857
1             7            0.285714            0.285714            0.285714
2             7            0.714286            0.714286            0.571429
3             7            0.571429            0.428571            0.428571
4             7            0.857143            0.714286            0.857143
...         ...                 ...                 ...                 ...
38096        13            0.923077            0.769231            0.769231
38097        13            0.846154            1.000000            1.000000
38098        13            0.692308            0.846154            0.923077
38099        13            0.076923            0.076923            0.076923
38100        13            0.230769            0.307692            0.307692

       corner_4_per_horse  mean_age  median_age  mean_age_kirisute  \
0                     NaN  4.000000         4.0                  4
1                     NaN  4.000000         4.0                  4
2                     NaN  4.000000         4.0                  4
3                     NaN  4.000000         4.0                  4
4                     NaN  4.000000         4.0                  4
...                   ...       ...         ...                ...
38096            0.846154  4.615385         4.0                  4
38097            1.000000  4.615385         4.0                  4
38098            0.923077  4.615385         4.0                  4
38099            0.076923  4.615385         4.0                  4
38100            0.615385  4.615385         4.0                  4

       umaban_odd  corner_1  corner_2  corner_3  corner_4  race_type  around  \
0               1         1       1.0       1.0       NaN          0       1
1               0         2       2.0       2.0       NaN          0       1
2               1         5       5.0       4.0       NaN          0       1
3               0         4       3.0       3.0       NaN          0       1
4               1         6       5.0       6.0       NaN          0       1
...           ...       ...       ...       ...       ...        ...     ...
38096           0        12      10.0      10.0      11.0          0       1
38097           1        11      13.0      13.0      13.0          0       1
38098           1         9      11.0      12.0      12.0          0       1
38099           0         1       1.0       1.0       1.0          0       1
38100           1         3       4.0       4.0       8.0          0       1

       course_len  weather  ground_state  race_class  place  season  \
0            1200        2             0         -12     43       4
1            1200        2             0         -12     43       4
2            1200        2             0         -12     43       4
3            1200        2             0         -12     43       4
4            1200        2             0         -12     43       4
...           ...      ...           ...         ...    ...     ...
38096        2200        1             0         -11     43       4
38097        2200        1             0         -11     43       4
38098        2200        1             0         -11     43       4
38099        2200        1             0         -11     43       4
38100        2200        1             0         -11     43       4

       place_season  place_season_type  kaisai_race  kaisai_race_type  day  \
0               434               4340            1                10    7
1               434               4340            1                10    7
2               434               4340            1                10    7
3               434               4340            1                10    7
4               434               4340            1                10    7
...             ...                ...          ...               ...  ...
38096           434               4340           12               120   14
38097           434               4340           12               120   14
38098           434               4340           12               120   14
38099           434               4340           12               120   14
38100           434               4340           12               120   14

       day_type  kaisai_count  kaisai_count_type  place_season_day_type  \
0            70             1                 10                 434070
1            70             1                 10                 434070
2            70             1                 10                 434070
3            70             1                 10                 434070
4            70             1                 10                 434070
...         ...           ...                ...                    ...
38096       140             2                 20                 434140
38097       140             2                 20                 434140
38098       140             2                 20                 434140
38099       140             2                 20                 434140
38100       140             2                 20                 434140

       day_condition  place_season_condition_type  \
0                  2                         4340
1                  2                         4340
2                  2                         4340
3                  2                         4340
4                  2                         4340
...              ...                          ...
38096              2                         4340
38097              2                         4340
38098              2                         4340
38099              2                         4340
38100              2                         4340

       place_season_condition_type_categori_x  place_course_category  \
0                                        -3.0                   1043
1                                        -3.0                   1043
2                                        -3.0                   1043
3                                        -3.0                   1043
4                                        -3.0                   1043
...                                       ...                    ...
38096                                    -3.0                   1043
38097                                    -3.0                   1043
38098                                    -3.0                   1043
38099                                    -3.0                   1043
38100                                    -3.0                   1043

       place_course_tough  goal_range  curve  goal_slope  \
0                      -1       308.0    4.0         0.0
1                      -1       308.0    4.0         0.0
2                      -1       308.0    4.0         0.0
3                      -1       308.0    4.0         0.0
4                      -1       308.0    4.0         0.0
...                   ...         ...    ...         ...
38096                  -1       308.0    4.0         0.0
38097                  -1       308.0    4.0         0.0
38098                  -1       308.0    4.0         0.0
38099                  -1       308.0    4.0         0.0
38100                  -1       308.0    4.0         0.0

       place_season_type_course_len  lap_type  race_day_count  \
0                          43401200        -1               1
1                          43401200        -1               1
2                          43401200        -1               1
3                          43401200        -1               1
4                          43401200        -1               1
...                             ...       ...             ...
38096                      43402200        -1              12
38097                      43402200        -1              12
38098                      43402200        -1              12
38099                      43402200        -1              12
38100                      43402200        -1              12

       race_date_day_count  goal_range_100  course_type  course_len_type  \
0                 73694201            3.08     43012001                1
1                 73694201            3.08     43012001                1
2                 73694201            3.08     43012001                1
3                 73694201            3.08     43012001                1
4                 73694201            3.08     43012001                1
...                    ...             ...          ...              ...
38096             73880512            3.08     43022001                1
38097             73880512            3.08     43022001                1
38098             73880512            3.08     43022001                1
38099             73880512            3.08     43022001                1
38100             73880512            3.08     43022001                1

       curve_amount  start_point  start_range  straight_total  curve_total  \
0               2.0          1.0        540.0           848.0        352.0
1               2.0          1.0        540.0           848.0        352.0
2               2.0          1.0        540.0           848.0        352.0
3               2.0          1.0        540.0           848.0        352.0
4               2.0          1.0        540.0           848.0        352.0
...             ...          ...          ...             ...          ...
38096           6.0          1.0        140.0          1222.0       1178.0
38097           6.0          1.0        140.0          1222.0       1178.0
38098           6.0          1.0        140.0          1222.0       1178.0
38099           6.0          1.0        140.0          1222.0       1178.0
38100           6.0          1.0        140.0          1222.0       1178.0

       curve_R12  curve_R34  height_diff  width  start_slope  flont_slope  \
0            0.0       99.0          0.0   25.0          0.0          0.0
1            0.0       99.0          0.0   25.0          0.0          0.0
2            0.0       99.0          0.0   25.0          0.0          0.0
3            0.0       99.0          0.0   25.0          0.0          0.0
4            0.0       99.0          0.0   25.0          0.0          0.0
...          ...        ...          ...    ...          ...          ...
38096       99.0       99.0          0.0   25.0          0.0          0.0
38097       99.0       99.0          0.0   25.0          0.0          0.0
38098       99.0       99.0          0.0   25.0          0.0          0.0
38099       99.0       99.0          0.0   25.0          0.0          0.0
38100       99.0       99.0          0.0   25.0          0.0          0.0

       first_curve_slope  last_curve_slope  season_turf  day_season_turf  \
0                    0.0               0.0          2.0               72
1                    0.0               0.0          2.0               72
2                    0.0               0.0          2.0               72
3                    0.0               0.0          2.0               72
4                    0.0               0.0          2.0               72
...                  ...               ...          ...              ...
38096                0.0               0.0          2.0              142
38097                0.0               0.0          2.0              142
38098                0.0               0.0          2.0              142
38099                0.0               0.0          2.0              142
38100                0.0               0.0          2.0              142

       season_turf_condition  age_season  race_grade  race_grade_scaled  \
0                      12.75          51          89                8.9
1                      12.75          51          89                8.9
2                      12.75          51          89                8.9
3                      12.75          51          89                8.9
4                      12.75          51          89                8.9
...                      ...         ...         ...                ...
38096                  23.25          54          56                5.6
38097                  23.25          54          56                5.6
38098                  23.25          54          56                5.6
38099                  23.25          54          56                5.6
38100                  23.25          54          56                5.6

       rank_1races  rank_per_horse_1races  prize_1races  rank_3races  \
0              NaN                    NaN           NaN          NaN
1              4.0               0.444444          16.5     4.000000
2              6.0               0.666667           0.0     6.000000
3              NaN                    NaN           NaN          NaN
4              5.0               0.555556          11.0     5.000000
...            ...                    ...           ...          ...
38096          6.0               0.461538           0.0     5.000000
38097         11.0               0.846154           0.0     6.000000
38098          8.0               0.666667           0.0    10.000000
38099         12.0               1.000000           0.0    10.000000
38100          5.0               0.384615          15.0     4.333333

       rank_per_horse_3races  prize_3races  rank_5races  \
0                        NaN           NaN          NaN
1                   0.444444     16.500000          4.0
2                   0.666667      0.000000          6.0
3                        NaN           NaN          NaN
4                   0.555556     11.000000          5.0
...                      ...           ...          ...
38096               0.396703     12.500000          4.6
38097               0.503263      4.966667          6.0
38098               0.888889      0.000000          9.6
38099               0.785714      5.000000          8.2
38100               0.356777     20.000000          6.0

       rank_per_horse_5races  prize_5races  rank_10races  \
0                        NaN           NaN           NaN
1                   0.444444         16.50           4.0
2                   0.666667          0.00           6.0
3                        NaN           NaN           NaN
4                   0.555556         11.00           5.0
...                      ...           ...           ...
38096               0.352308         18.50           5.0
38097               0.508019          4.16           5.2
38098               0.795971          2.00           9.8
38099               0.663636         17.40           7.8
38100               0.542637         12.00           5.3

       rank_per_horse_10races  prize_10races  rank_1000races  \
0                         NaN            NaN             NaN
1                    0.444444          16.50        4.000000
2                    0.666667           0.00        6.000000
3                         NaN            NaN             NaN
4                    0.555556          11.00        5.000000
...                       ...            ...             ...
38096                0.458741          14.50        4.482759
38097                0.460828           5.24        5.766667
38098                0.850042           1.00        8.947368
38099                0.675606          23.70        6.678571
38100                0.482980          27.50        6.250000

       rank_per_horse_1000races  prize_1000races  \
0                           NaN              NaN
1                      0.444444        16.500000
2                      0.666667         0.000000
3                           NaN              NaN
4                      0.555556        11.000000
...                         ...              ...
38096                  0.448228        18.665517
38097                  0.567056        16.613333
38098                  0.742607        15.263158
38099                  0.644408        13.896429
38100                  0.493941        25.000000

       course_len_mean_1races_relative  course_len_max_1races_relative  \
0                                  NaN                             NaN
1                                  NaN                             NaN
2                                  NaN                             NaN
3                                  NaN                             NaN
4                                  NaN                             NaN
...                                ...                             ...
38096                         0.801337                        0.801337
38097                         0.801337                        0.801337
38098                        -1.021704                       -1.021704
38099                        -1.803008                       -1.803008
38100                         0.801337                        0.801337

       course_len_min_1races_relative  course_len_diff_mean_1races_relative  \
0                                 NaN                                   NaN
1                                 NaN                                   NaN
2                                 NaN                                   NaN
3                                 NaN                                   NaN

In [92]:
# rank_1races 列が None の行を抽出
none_rows = features_turf[features_turf["rank_1races"].isna()]
# none_rows の行数を確認
num_rows = none_rows.shape[0]
print(f"rank_1races が None の行数: {num_rows}")
# 表示したい列を指定
columns_to_display = ["horse_id", "date","rank_1races", "race_id"]  # 必要な列名をリストで指定
filtered_none_rows = none_rows[columns_to_display]

filtered_none_rows 
# horse_id 列をリストに変換
horse_id_list = filtered_none_rows["horse_id"].tolist()

# 結果を表示
print(horse_id_list)

rank_1races が None の行数: 0
[]

In [59]:
# rank_1races 列が None の行を抽出
none_rows = features_dirt[features_dirt["rank_1races"].isna()]
# none_rows の行数を確認
num_rows = none_rows.shape[0]
print(f"rank_1races が None の行数: {num_rows}")
# 表示したい列を指定
columns_to_display = ["horse_id", "date","rank_1races", "race_id"]  # 必要な列名をリストで指定
filtered_none_rows = none_rows[columns_to_display]

filtered_none_rows 
# horse_id 列をリストに変換
horse_id_list = filtered_none_rows["horse_id"].tolist()

# 結果を表示
print(horse_id_list)

rank_1races が None の行数: 268
[2012110013, 2012101875, 2013100031, 2013102968, 2012105604, 2013100952, 2012105288, 2012102691, 2012105867, 2013102612, 2013102691, 2012106270, 2013106219, 2012101902, 2014104778, 2012100153, 2012101291, 2014101402, 2014100201, 2014102630, 2012104995, 2012110078, 2013102489, 2014101733, 2013103885, 2010100864, 2014101921, 2014104130, 2014106430, 2011105881, 2014106298, 2013106337, 2013100901, 2014101899, 2013106316, 2014104450, 2014104093, 2014103893, 2014104443, 2014104431, 2014102921, 2014104193, 2013104373, 2014101431, 2014104013, 2015102606, 2013105325, 2014106207, 2012105623, 2015104996, 2015106066, 2014105615, 2014101766, 2014104519, 2014104165, 2015106046, 2014104082, 2012104368, 2014110114, 2015106510, 2014103443, 2014102327, 2014101691, 2015106413, 2014103884, 2015101484, 2014105824, 2014110053, 2015102656, 2014101962, 2013106436, 2013103863, 2013100965, 2015104460, 2014105570, 2014190002, 2014105066, 2016100446, 2014106530, 2015101191, 2016103831, 2016102970, 2015106065, 2014101844, 2016100927, 2016102782, 2016102190, 2016102888, 2016104655, 2017101853, 2016102790, 2016101451, 2017103774, 2017103932, 2016106005, 2016103405, 2017104506, 2015105676, 2017106686, 2016102423, 2015102421, 2015100116, 2017103176, 2016103364, 2015100411, 2017101064, 2015100284, 2016105707, 2017101358, 2017100663, 2016101637, 2016110104, 2018105667, 2016100112, 2017100657, 2018103276, 2017101486, 2017100505, 2014105019, 2018106480, 2017102123, 2017102696, 2018101704, 2016100075, 2017100038, 2017100123, 2017101838, 2017100032, 2018101146, 2017100359, 2017100468, 2018104022, 2018104069, 2018102797, 2018103622, 2018105675, 2018102290, 2018104705, 2018109119, 2018101744, 2016104163, 2018104946, 2017104135, 2018105949, 2018102073, 2018102219, 2018101216, 2017103414, 2019102398, 2018104154, 2018106729, 2018100346, 2019102970, 2018103641, 2018103173, 2018101069, 2017100424, 2019102306, 2019101329, 2019103954, 2019103762, 2017106216, 2019101663, 2017100660, 2020103833, 2018101345, 2018103315, 2020104590, 2019102282, 2020106375, 2020107163, 2019104385, 2020106550, 2019103705, 2019106572, 2020103755, 2019102512, 2017190001, 2019102654, 2019101325, 2020101937, 2019102218, 2018102810, 2018105955, 2020102301, 2019106885, 2020106497, 2020101481, 2020104196, 2019104041, 2019101233, 2019100437, 2019101228, 2019100632, 2019101736, 2019105359, 2019102232, 2017101536, 2019101433, 2020104616, 2020102263, 2020101809, 2020104621, 2018103738, 2019100899, 2020104593, 2020103937, 2019103578, 2019106385, 2020105869, 2019106449, 2021110067, 2020104376, 2021102729, 2018100991, 2021102236, 2019103983, 2021102729, 2021103020, 2021103223, 2020105564, 2021110067, 2020101174, 2021102603, 2021103020, 2021110165, 2021110067, 2020101174, 2021103557, 2021101727, 2020106995, 2021110067, 2021102729, 2020110017, 2021110127, 2021103242, 2021104722, 2021110147, 2021103242, 2021104780, 2020101660, 2021100169, 2021103020, 2021110127, 2022104957, 2022104120, 2019110016, 2021106639, 2021110067, 2020101174, 2022104120, 2021110105, 2020101174, 2021103242, 2021103242, 2021106639, 2021110165, 2022106395, 2019107061, 2022104674, 2019110016, 2021110067, 2022110007, 2022104674, 2022110134, 2020101174, 2021110147, 2019100415]

In [60]:
# rank_1races 列が None の行を抽出
none_rows = features_obstract[features_obstract["rank_1races"].isna()]
# none_rows の行数を確認
num_rows = none_rows.shape[0]
print(f"rank_1races が None の行数: {num_rows}")
# 表示したい列を指定
columns_to_display = ["horse_id", "date","rank_1races", "race_id"]  # 必要な列名をリストで指定
filtered_none_rows = none_rows[columns_to_display]

filtered_none_rows 
# horse_id 列をリストに変換
horse_id_list = filtered_none_rows["horse_id"].tolist()

# 結果を表示
print(horse_id_list)

rank_1races が None の行数: 8
[2010101798, 2013102275, 2016103841, 2017106471, 2017101493, 2019104410, 2017101170, 2019104437]

In [9]:
#_himeziの特徴量作成
fc_sonoda = FeatureCreator(
    poplation_filename="population_dirt_sonoda.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_sonoda.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_sonoda = fc_sonoda.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [10]:
#_kanazawaの特徴量作成
fc_kanazawa = FeatureCreator(
    poplation_filename="population_dirt_kanazawa.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_kanazawa.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_kanazawa = fc_kanazawa.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [11]:
#_kasamatuの特徴量作成
fc_kasamatu = FeatureCreator(
    poplation_filename="population_dirt_kasamatu.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_kasamatu.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_kasamatu = fc_kasamatu.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [12]:
#_kawasakiの特徴量作成
fc_kawasaki = FeatureCreator(
    poplation_filename="population_dirt_kawasaki.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_kawasaki.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_kawasaki = fc_kawasaki.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [13]:
#_koutiの特徴量作成
fc_kouti = FeatureCreator(
    poplation_filename="population_dirt_kouti.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_kouti.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_kouti = fc_kouti.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [14]:
#_mizusawaの特徴量作成
fc_mizusawa = FeatureCreator(
    poplation_filename="population_dirt_mizusawa.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_mizusawa.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_mizusawa = fc_mizusawa.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [15]:
#_monbetuの特徴量作成
fc_monbetu = FeatureCreator(
    poplation_filename="population_dirt_monbetu.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_monbetu.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_monbetu = fc_monbetu.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [16]:
#_moriokaの特徴量作成
fc_morioka = FeatureCreator(
    poplation_filename="population_dirt_morioka.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_morioka.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_morioka = fc_morioka.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [4]:
#_nagoyaの特徴量作成
fc_nagoya = FeatureCreator(
    poplation_filename="population_dirt_nagoya.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_nagoya.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_nagoya = fc_nagoya.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [5]:
#_ooiの特徴量作成
fc_ooi = FeatureCreator(
    poplation_filename="population_dirt_ooi.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_ooi.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_ooi = fc_ooi.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [6]:
#_sagaの特徴量作成
fc_saga = FeatureCreator(
    poplation_filename="population_dirt_saga.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_saga.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_saga = fc_saga.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [7]:
#_urawaの特徴量作成
fc_urawa = FeatureCreator(
    poplation_filename="population_dirt_urawa.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all.csv",
    horse_results_filename="horse_results_all.csv",
    output_filename = "features_dirt_urawa.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
features_urawa = fc_urawa.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

# 学習
- 特徴量にオッズを利用したもの、利用していないもの
- rank列を二値分類で予測したもの、回帰で予測したもの、time列を予測したもの
- ホールドアウト法、cv(クロスバリデーション)を利用したもの
- その他、独自の特徴量のみを利用したものなど、さまざまな学習モデルを作成する段階です
- config_filepath="config_lightgbm_kaiki_odds_removed.yaml"の部分を変更することで、特徴量やハイパーパラメータを変更できます
- 好きな特徴量を選んで、学習させてください（保存先のファイル名の変更も忘れずに）

In [ ]:
# # _turfオッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_turf",
#     model_filename="model_lightgbm_time_cv_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_turf.csv",
#     final_model_filename = "model_lightgbm_time_cv_turf.pkl"
# )

In [4]:
# # _turfオッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_turf",
#     model_filename="model_lightgbm_time_cv_nopast_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_turf.pkl"
# )

Training fold 1/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.387689 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 490610
[LightGBM] [Info] Number of data points in the train set: 39887, number of used features: 1999
[LightGBM] [Info] Start training from score 101.132825
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 9.59508
[200]	valid_0's rmse: 3.69277
[300]	valid_0's rmse: 1.79183
[400]	valid_0's rmse: 1.3458
[500]	valid_0's rmse: 1.26818
[600]	valid_0's rmse: 1.24726
[700]	valid_0's rmse: 1.23772
[800]	valid_0's rmse: 1.23289
[900]	valid_0's rmse: 1.22871
[1000]	valid_0's rmse: 1.226
[1100]	valid_0's rmse: 1.22443
[1200]	valid_0's rmse: 1.22326
[1300]	valid_0's rmse: 1.22272
[1400]	valid_0's rmse: 1.22266
[1500]	valid_0's rmse: 1.22245
[1600]	valid_0's rmse: 1.22221
[1700]	valid_0's rmse: 1.22233
Early stopping, best iteration is:
[1612]	valid_0's rmse: 1.22216

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2222
値が1に近いほど良いR²: 0.9978
test_df's root_mean_squared_error: 1.2221625120111164
Training fold 2/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.979883 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 491219
[LightGBM] [Info] Number of data points in the train set: 79774, number of used features: 1999
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's rmse: 1.30963
[1800]	valid_0's rmse: 1.29896
[1900]	valid_0's rmse: 1.29079
[2000]	valid_0's rmse: 1.28803
[2100]	valid_0's rmse: 1.28632
[2200]	valid_0's rmse: 1.28567
[2300]	valid_0's rmse: 1.28548
Early stopping, best iteration is:
[2250]	valid_0's rmse: 1.28523

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2852
値が1に近いほど良いR²: 0.9976
test_df's root_mean_squared_error: 1.2852315431741437
Training fold 3/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.318891 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 491542
[LightGBM] [Info] Number of data points in the train set: 119661, number of used features: 1999
Training until validation scores don't improve for 100 rounds
[2300]	valid_0's rmse: 1.1646
[2400]	valid_0's rmse: 1.15409
[2500]	valid_0's rmse: 1.15263
Early stopping, best iteration is:
[2434]	valid_0's rmse: 1.15189

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.1519
値が1に近いほど良いR²: 0.9981
test_df's root_mean_squared_error: 1.151890559194216
Training fold 4/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.872882 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 491611
[LightGBM] [Info] Number of data points in the train set: 159548, number of used features: 1999
Training until validation scores don't improve for 100 rounds
[2500]	valid_0's rmse: 1.16306
[2600]	valid_0's rmse: 1.15622
[2700]	valid_0's rmse: 1.15317
[2800]	valid_0's rmse: 1.15187
[2900]	valid_0's rmse: 1.15075
[3000]	valid_0's rmse: 1.15036
[3100]	valid_0's rmse: 1.15018
[3200]	valid_0's rmse: 1.14995
[3300]	valid_0's rmse: 1.14969
[3400]	valid_0's rmse: 1.1493
[3500]	valid_0's rmse: 1.14921
[3600]	valid_0's rmse: 1.14891
[3700]	valid_0's rmse: 1.14862
Early stopping, best iteration is:
[3692]	valid_0's rmse: 1.14858

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.1486
値が1に近いほど良いR²: 0.9981
test_df's root_mean_squared_error: 1.1485778227898624
Training final model using all data...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.287397 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 491729
[LightGBM] [Info] Number of data points in the train set: 199438, number of used features: 1999
Final model training completed.

In [138]:
# # _turfオッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf",
#     model_filename="model_lightgbm_time_cv_dev_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf.pkl"
# )

Training fold 1/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.220860 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 442629
[LightGBM] [Info] Number of data points in the train set: 22416, number of used features: 1811
[LightGBM] [Info] Start training from score 101.169477
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 10.0914
[200]	valid_0's rmse: 3.91441
[300]	valid_0's rmse: 1.91883
[400]	valid_0's rmse: 1.43604
[500]	valid_0's rmse: 1.34681
[600]	valid_0's rmse: 1.32123
[700]	valid_0's rmse: 1.3124
[800]	valid_0's rmse: 1.30739
[900]	valid_0's rmse: 1.304
[1000]	valid_0's rmse: 1.30285
[1100]	valid_0's rmse: 1.30146
[1200]	valid_0's rmse: 1.30022
[1300]	valid_0's rmse: 1.29983
[1400]	valid_0's rmse: 1.29923
[1500]	valid_0's rmse: 1.29928
[1600]	valid_0's rmse: 1.29898
[1700]	valid_0's rmse: 1.29881
[1800]	valid_0's rmse: 1.29862
[1900]	valid_0's rmse: 1.29867
Early stopping, best iteration is:
[1813]	valid_0's rmse: 1.29856

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2986
値が1に近いほど良いR²: 0.9977
test_df's root_mean_squared_error: 1.29856027076834
Training fold 2/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.422789 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 443342
[LightGBM] [Info] Number of data points in the train set: 44832, number of used features: 1811
Training until validation scores don't improve for 100 rounds
[1900]	valid_0's rmse: 1.35129
[2000]	valid_0's rmse: 1.3398
[2100]	valid_0's rmse: 1.33517
[2200]	valid_0's rmse: 1.33362
Early stopping, best iteration is:
[2198]	valid_0's rmse: 1.33342

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.3334
値が1に近いほど良いR²: 0.9977
test_df's root_mean_squared_error: 1.3334221100117554
Training fold 3/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.698224 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 443695
[LightGBM] [Info] Number of data points in the train set: 67248, number of used features: 1811
Training until validation scores don't improve for 100 rounds
[2200]	valid_0's rmse: 1.24124
[2300]	valid_0's rmse: 1.2141
[2400]	valid_0's rmse: 1.201
[2500]	valid_0's rmse: 1.19714
[2600]	valid_0's rmse: 1.1955
[2700]	valid_0's rmse: 1.19507
[2800]	valid_0's rmse: 1.19405
[2900]	valid_0's rmse: 1.19385
[3000]	valid_0's rmse: 1.19371
[3100]	valid_0's rmse: 1.19388
Early stopping, best iteration is:
[3019]	valid_0's rmse: 1.19356

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.1936
値が1に近いほど良いR²: 0.9982
test_df's root_mean_squared_error: 1.1935584474437688
Training fold 4/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.860243 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 443853
[LightGBM] [Info] Number of data points in the train set: 89664, number of used features: 1811
Training until validation scores don't improve for 100 rounds
[3100]	valid_0's rmse: 1.26819
[3200]	valid_0's rmse: 1.26365
[3300]	valid_0's rmse: 1.26234
[3400]	valid_0's rmse: 1.26132
[3500]	valid_0's rmse: 1.26063
[3600]	valid_0's rmse: 1.26029
[3700]	valid_0's rmse: 1.26008
[3800]	valid_0's rmse: 1.25952
[3900]	valid_0's rmse: 1.25924
[4000]	valid_0's rmse: 1.25912
[4100]	valid_0's rmse: 1.25893
[4200]	valid_0's rmse: 1.25902
Early stopping, best iteration is:
[4101]	valid_0's rmse: 1.25892

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2589
値が1に近いほど良いR²: 0.9980
test_df's root_mean_squared_error: 1.2589249401231282
Training final model using all data...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.303858 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 443929
[LightGBM] [Info] Number of data points in the train set: 112082, number of used features: 1811
Final model training completed.

In [32]:
# # _turfオッズと人気を特徴量から省いたindex、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_index_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_index_cv_dev_turf",
#     model_filename="model_lightgbm_index_cv_dev_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_index_cv_dev_turf.csv",
#     final_model_filename = "model_lightgbm_index_cv_full_dev_turf.pkl"
# )

Training fold 1/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.244502 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 430421
[LightGBM] [Info] Number of data points in the train set: 22416, number of used features: 1763
[LightGBM] [Info] Start training from score 78.928801
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 2.13565
[200]	valid_0's rmse: 1.6025
[300]	valid_0's rmse: 1.43423
[400]	valid_0's rmse: 1.36772
[500]	valid_0's rmse: 1.33621
[600]	valid_0's rmse: 1.31597
[700]	valid_0's rmse: 1.30449
[800]	valid_0's rmse: 1.29722
[900]	valid_0's rmse: 1.2926
[1000]	valid_0's rmse: 1.2897
[1100]	valid_0's rmse: 1.2878
[1200]	valid_0's rmse: 1.28608
[1300]	valid_0's rmse: 1.28539
[1400]	valid_0's rmse: 1.2847
[1500]	valid_0's rmse: 1.28408
[1600]	valid_0's rmse: 1.28362
[1700]	valid_0's rmse: 1.28334
[1800]	valid_0's rmse: 1.28308
[1900]	valid_0's rmse: 1.28302
[2000]	valid_0's rmse: 1.28294
[2100]	valid_0's rmse: 1.28276
[2200]	valid_0's rmse: 1.28263
[2300]	valid_0's rmse: 1.28265
Early stopping, best iteration is:
[2246]	valid_0's rmse: 1.28261

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2826
値が1に近いほど良いR²: 0.8915
test_df's root_mean_squared_error: 1.2826063965346344
Training fold 2/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.627498 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 431071
[LightGBM] [Info] Number of data points in the train set: 44832, number of used features: 1763
Training until validation scores don't improve for 100 rounds
[2300]	valid_0's rmse: 1.35369
Early stopping, best iteration is:
[2277]	valid_0's rmse: 1.34939

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.3494
値が1に近いほど良いR²: 0.8811
test_df's root_mean_squared_error: 1.3493901132873873
Training fold 3/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.600766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 431430
[LightGBM] [Info] Number of data points in the train set: 67248, number of used features: 1763
Training until validation scores don't improve for 100 rounds
[2300]	valid_0's rmse: 1.26401
[2400]	valid_0's rmse: 1.22365
[2500]	valid_0's rmse: 1.21297
[2600]	valid_0's rmse: 1.20863
[2700]	valid_0's rmse: 1.20519
[2800]	valid_0's rmse: 1.20383
[2900]	valid_0's rmse: 1.20273
[3000]	valid_0's rmse: 1.20165
[3100]	valid_0's rmse: 1.20084
[3200]	valid_0's rmse: 1.20025
[3300]	valid_0's rmse: 1.20005
[3400]	valid_0's rmse: 1.19963
[3500]	valid_0's rmse: 1.19942
[3600]	valid_0's rmse: 1.19918
[3700]	valid_0's rmse: 1.19893
[3800]	valid_0's rmse: 1.19902
Early stopping, best iteration is:
[3739]	valid_0's rmse: 1.19888

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.1989
値が1に近いほど良いR²: 0.9054
test_df's root_mean_squared_error: 1.1988840106641399
Training fold 4/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.978322 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 431578
[LightGBM] [Info] Number of data points in the train set: 89664, number of used features: 1763
Training until validation scores don't improve for 100 rounds
[3800]	valid_0's rmse: 1.24527
Early stopping, best iteration is:
[3752]	valid_0's rmse: 1.24116

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2412
値が1に近いほど良いR²: 0.9042
test_df's root_mean_squared_error: 1.2411634158212193
Training final model using all data...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.101213 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 431663
[LightGBM] [Info] Number of data points in the train set: 112082, number of used features: 1763
Final model training completed.

In [ ]:
# #_turf_newbie オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_turf_newbie",
#     model_filename="model_lightgbm_time_cv_turf_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_turf_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_turf_newbie.pkl"
# )

In [ ]:
# # _turf_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_turf_newbie",
#     model_filename="model_lightgbm_time_cv_nopast_turf_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_turf_newbie.pkl"
# )

In [ ]:
# # _turf_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf_newbie",
#     model_filename="model_lightgbm_time_cv_dev_turf_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf_newbie.pkl"
# )

In [ ]:
# #_turf_nowin オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_turf_nowin",
#     model_filename="model_lightgbm_time_cv_turf_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_turf_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_turf_nowin.pkl"
# )

In [ ]:
# # _turf_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_turf_nowin",
#     model_filename="model_lightgbm_time_cv_nopast_turf_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_turf_nowin.pkl"
# )

In [35]:
# # _turf_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf_nowin",
#     model_filename="model_lightgbm_time_cv_dev_turf_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf_nowin.pkl"
# )

Training fold 1/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.093781 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 424719
[LightGBM] [Info] Number of data points in the train set: 12872, number of used features: 1756
[LightGBM] [Info] Start training from score 102.434431
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 8.4528
[200]	valid_0's rmse: 3.35594
[300]	valid_0's rmse: 1.76338
[400]	valid_0's rmse: 1.40944
[500]	valid_0's rmse: 1.34377
[600]	valid_0's rmse: 1.32975
[700]	valid_0's rmse: 1.32687
[800]	valid_0's rmse: 1.32508
[900]	valid_0's rmse: 1.32439
[1000]	valid_0's rmse: 1.32422
Early stopping, best iteration is:
[985]	valid_0's rmse: 1.32418

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.3242
値が1に近いほど良いR²: 0.9966
test_df's root_mean_squared_error: 1.3241770520890765
Training fold 2/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.234675 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 426241
[LightGBM] [Info] Number of data points in the train set: 25744, number of used features: 1756
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's rmse: 1.48977
[1100]	valid_0's rmse: 1.49141
Early stopping, best iteration is:
[1030]	valid_0's rmse: 1.48578

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.4858
値が1に近いほど良いR²: 0.9960
test_df's root_mean_squared_error: 1.4857848880606679
Training fold 3/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.332115 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 426849
[LightGBM] [Info] Number of data points in the train set: 38616, number of used features: 1756
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's rmse: 1.46142
[1200]	valid_0's rmse: 1.46549
Early stopping, best iteration is:
[1116]	valid_0's rmse: 1.45687

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.4569
値が1に近いほど良いR²: 0.9962
test_df's root_mean_squared_error: 1.456873462091066
Training fold 4/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.450283 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 427216
[LightGBM] [Info] Number of data points in the train set: 51488, number of used features: 1756
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's rmse: 1.49376
[1300]	valid_0's rmse: 1.47727
[1400]	valid_0's rmse: 1.46911
[1500]	valid_0's rmse: 1.46538
[1600]	valid_0's rmse: 1.46294
[1700]	valid_0's rmse: 1.46154
[1800]	valid_0's rmse: 1.46096
[1900]	valid_0's rmse: 1.4604
[2000]	valid_0's rmse: 1.46027
[2100]	valid_0's rmse: 1.46044
Early stopping, best iteration is:
[2025]	valid_0's rmse: 1.46014

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.4601
値が1に近いほど良いR²: 0.9961
test_df's root_mean_squared_error: 1.4601396017271637
Training final model using all data...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.652930 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 427413
[LightGBM] [Info] Number of data points in the train set: 64363, number of used features: 1756
Final model training completed.

In [ ]:
# #_dirt オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dirt",
#     model_filename="model_lightgbm_time_cv_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dirt.csv",
#     final_model_filename = "model_lightgbm_time_cv_dirt.pkl"
# )

In [ ]:
# # _dirt オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_dirt",
#     model_filename="model_lightgbm_time_cv_nopast_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_dirt.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_dirt.pkl"
# )

In [139]:
# # _dirt オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt",
#     model_filename="model_lightgbm_time_cv_dev_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dirt.pkl"
# )

Training fold 1/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.208637 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 411656
[LightGBM] [Info] Number of data points in the train set: 22863, number of used features: 1699
[LightGBM] [Info] Start training from score 96.011022
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 7.72464
[200]	valid_0's rmse: 3.07654
[300]	valid_0's rmse: 1.62792
[400]	valid_0's rmse: 1.30888
[500]	valid_0's rmse: 1.25944
[600]	valid_0's rmse: 1.25385
[700]	valid_0's rmse: 1.25227
[800]	valid_0's rmse: 1.25042
[900]	valid_0's rmse: 1.2501
Early stopping, best iteration is:
[882]	valid_0's rmse: 1.24986

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2499
値が1に近いほど良いR²: 0.9964
test_df's root_mean_squared_error: 1.2498584966770998
Training fold 2/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.391688 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 412918
[LightGBM] [Info] Number of data points in the train set: 45726, number of used features: 1699
Training until validation scores don't improve for 100 rounds
[900]	valid_0's rmse: 1.22319
[1000]	valid_0's rmse: 1.20864
[1100]	valid_0's rmse: 1.20443
[1200]	valid_0's rmse: 1.20186
[1300]	valid_0's rmse: 1.19958
[1400]	valid_0's rmse: 1.19827
[1500]	valid_0's rmse: 1.19743
[1600]	valid_0's rmse: 1.19684
[1700]	valid_0's rmse: 1.19664
[1800]	valid_0's rmse: 1.19614
[1900]	valid_0's rmse: 1.19579
[2000]	valid_0's rmse: 1.19585
Early stopping, best iteration is:
[1947]	valid_0's rmse: 1.19575

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.1958
値が1に近いほど良いR²: 0.9968
test_df's root_mean_squared_error: 1.1957539316740304
Training fold 3/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.734665 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 413284
[LightGBM] [Info] Number of data points in the train set: 68589, number of used features: 1699
Training until validation scores don't improve for 100 rounds
[2000]	valid_0's rmse: 1.22808
[2100]	valid_0's rmse: 1.21937
[2200]	valid_0's rmse: 1.21931
Early stopping, best iteration is:
[2147]	valid_0's rmse: 1.21902

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.2190
値が1に近いほど良いR²: 0.9966
test_df's root_mean_squared_error: 1.2190176247905518
Training fold 4/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.035401 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 413403
[LightGBM] [Info] Number of data points in the train set: 91452, number of used features: 1699
Training until validation scores don't improve for 100 rounds
[2200]	valid_0's rmse: 1.42073
[2300]	valid_0's rmse: 1.41952
[2400]	valid_0's rmse: 1.41687
[2500]	valid_0's rmse: 1.41514
[2600]	valid_0's rmse: 1.41397
[2700]	valid_0's rmse: 1.41337
[2800]	valid_0's rmse: 1.41316
[2900]	valid_0's rmse: 1.4128
[3000]	valid_0's rmse: 1.41247
[3100]	valid_0's rmse: 1.41257
Early stopping, best iteration is:
[3071]	valid_0's rmse: 1.41243

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.4124
値が1に近いほど良いR²: 0.9954
test_df's root_mean_squared_error: 1.4124263536610526
Training final model using all data...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.075204 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 413621
[LightGBM] [Info] Number of data points in the train set: 114317, number of used features: 1699
Final model training completed.

In [ ]:
# #_dirt_newbie オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dirt_newbie",
#     model_filename="model_lightgbm_time_cv_dirt_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dirt_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_dirt_newbie.pkl"
# )

In [ ]:
# # _dirt_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_dirt_newbie",
#     model_filename="model_lightgbm_time_cv_nopast_dirt_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_dirt_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_dirt_newbie.pkl"
# )

In [ ]:
# # _dirt_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt_newbie",
#     model_filename="model_lightgbm_time_cv_dev_dirt_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dirt_newbie.pkl"
# )

In [ ]:
# #_dirt_nowin オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dirt_nowin",
#     model_filename="model_lightgbm_time_cv_dirt_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dirt_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_dirt_nowin.pkl"
# )

In [ ]:
# # _dirt_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_dirt_nowin",
#     model_filename="model_lightgbm_time_cv_nopast_dirt_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_dirt_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_dirt_nowin.pkl"
# )

In [37]:
# # _dirt_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt_nowin",
#     model_filename="model_lightgbm_time_cv_dev_dirt_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dirt_nowin.pkl"
# )

Training fold 1/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.026145 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 106552
[LightGBM] [Info] Number of data points in the train set: 16789, number of used features: 520
[LightGBM] [Info] Start training from score 96.906486
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 7.52882
[200]	valid_0's rmse: 3.24832
[300]	valid_0's rmse: 2.01147
[400]	valid_0's rmse: 1.75327
[500]	valid_0's rmse: 1.69983
[600]	valid_0's rmse: 1.68556
[700]	valid_0's rmse: 1.68062
[800]	valid_0's rmse: 1.678
[900]	valid_0's rmse: 1.67505
[1000]	valid_0's rmse: 1.67296
[1100]	valid_0's rmse: 1.67204
[1200]	valid_0's rmse: 1.66855
[1300]	valid_0's rmse: 1.66818
[1400]	valid_0's rmse: 1.66776
Early stopping, best iteration is:
[1364]	valid_0's rmse: 1.66741

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.6674
値が1に近いほど良いR²: 0.9930
test_df's root_mean_squared_error: 1.6674073079662832
Training fold 2/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.051309 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 107462
[LightGBM] [Info] Number of data points in the train set: 33578, number of used features: 520
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's rmse: 1.63143
[1500]	valid_0's rmse: 1.62167
[1600]	valid_0's rmse: 1.61628
[1700]	valid_0's rmse: 1.61052
[1800]	valid_0's rmse: 1.61002
[1900]	valid_0's rmse: 1.6086
[2000]	valid_0's rmse: 1.60668
[2100]	valid_0's rmse: 1.60695
Early stopping, best iteration is:
[2003]	valid_0's rmse: 1.60646

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.6065
値が1に近いほど良いR²: 0.9937
test_df's root_mean_squared_error: 1.606460153916162
Training fold 3/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.070437 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 108442
[LightGBM] [Info] Number of data points in the train set: 50367, number of used features: 520
Training until validation scores don't improve for 100 rounds
[2100]	valid_0's rmse: 1.58973
Early stopping, best iteration is:
[2060]	valid_0's rmse: 1.58764

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.5876
値が1に近いほど良いR²: 0.9940
test_df's root_mean_squared_error: 1.5876381876634065
Training fold 4/5...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.086587 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 109184
[LightGBM] [Info] Number of data points in the train set: 67156, number of used features: 520
Training until validation scores don't improve for 100 rounds
[2100]	valid_0's rmse: 1.7225
[2200]	valid_0's rmse: 1.7105
[2300]	valid_0's rmse: 1.70565
[2400]	valid_0's rmse: 1.7038
[2500]	valid_0's rmse: 1.70317
[2600]	valid_0's rmse: 1.70316
[2700]	valid_0's rmse: 1.70282
[2800]	valid_0's rmse: 1.70271
[2900]	valid_0's rmse: 1.70289
Early stopping, best iteration is:
[2805]	valid_0's rmse: 1.70267

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 1.7027
値が1に近いほど良いR²: 0.9928
test_df's root_mean_squared_error: 1.7026694277848808
Training final model using all data...
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.041499 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 109839
[LightGBM] [Info] Number of data points in the train set: 83948, number of used features: 520
Final model training completed.

In [ ]:
# #_obstract オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_obstract",
#     model_filename="model_lightgbm_time_cv_obstract.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_obstract.csv",
#     final_model_filename = "model_lightgbm_time_cv_obstract.pkl"
# )

In [ ]:
# # _obstract オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_obstract",
#     model_filename="model_lightgbm_time_cv_nopast_obstract.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_obstract.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_obstract.pkl"
# )

In [140]:
# # _obstract オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_obstract.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 3,
#     importance_filename="importance_lightgbm_time_cv_dev_obstract",
#     model_filename="model_lightgbm_time_cv_dev_obstract.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_obstract.pkl"
# )

Training fold 1/3...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.028157 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 314283
[LightGBM] [Info] Number of data points in the train set: 4167, number of used features: 1332
[LightGBM] [Info] Start training from score 203.518838
Training until validation scores don't improve for 100 rounds
[100]	valid_0's rmse: 7.5586
[200]	valid_0's rmse: 4.2079
[300]	valid_0's rmse: 3.51441
[400]	valid_0's rmse: 3.40381
[500]	valid_0's rmse: 3.3787
[600]	valid_0's rmse: 3.36874
[700]	valid_0's rmse: 3.3676
Early stopping, best iteration is:
[654]	valid_0's rmse: 3.36674

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 3.3667
値が1に近いほど良いR²: 0.9676
test_df's root_mean_squared_error: 3.3667402054769715
Training fold 2/3...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062468 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 317698
[LightGBM] [Info] Number of data points in the train set: 8334, number of used features: 1336
Training until validation scores don't improve for 100 rounds
[700]	valid_0's rmse: 3.22697
Early stopping, best iteration is:
[660]	valid_0's rmse: 3.19277

/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/opt/anaconda3/envs/horse/lib/python3.11/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

-------------------- Metrics --------------------
RMSE: 3.1928
値が1に近いほど良いR²: 0.9723
test_df's root_mean_squared_error: 3.192773944399713
Training final model using all data...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.057148 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 318955
[LightGBM] [Info] Number of data points in the train set: 12503, number of used features: 1338
Final model training completed.

In [8]:
missing_count = features_ooi["speed_index"].isna().sum()
print(f"speed_index の欠損数: {missing_count}")

speed_index の欠損数: 608

In [155]:
%autoreload

### スピード指数

In [158]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_time_cv(
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_kaiki_dev_dirt10.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_kaiki_cv_dev_dirt_sonoda",
    model_filename="model_lightgbm_kaikii_cv_dev_dirt_sonoda.pkl",
    evaluation_filename="evaluation_lightgbm_kaiki_cv_dev_dirt_sonoda.csv",
    final_model_filename = "model_lightgbm_kaiki_cv_full_dev_dirt_sonoda.pkl",
    final_num_boost_round = 2000
)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_time_cv(
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_kaiki_dev_dirt10.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_kaiki_cv_dev_dirt_sonoda",
    model_filename="model_lightgbm_kaikii_cv_dev_dirt_sonoda.pkl",
    evaluation_filename="evaluation_lightgbm_kaiki_cv_dev_dirt_sonoda.csv",
    final_model_filename = "model_lightgbm_kaiki_cv_full_dev_dirt_sonoda.pkl",
    final_num_boost_round = 2000
)

In [ ]:

名古屋7

笠松3

園田10


高知6

紋別５

金沢4

佐賀７

浦和４
船橋4
川崎4

多い７


盛岡３
水沢4

yamlを少ないverと多いverに分ける
4,7,10

### 二値分類

In [8]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt10.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_sonoda",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_sonoda.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_sonoda.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_sonoda.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.280428
[200]	valid_0's binary_logloss: 0.27115
[300]	valid_0's binary_logloss: 0.268517
[400]	valid_0's binary_logloss: 0.267664
[500]	valid_0's binary_logloss: 0.267712
Early stopping, best iteration is:
[446]	valid_0's binary_logloss: 0.267622
-------------------- Metrics --------------------
Accuracy: 0.6470
Precision: 0.1923
Recall: 0.8048
F1 Score: 0.3104
ROC AUC: 0.7985
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.265834
[600]	valid_0's binary_logloss: 0.264307
[700]	valid_0's binary_logloss: 0.263305
[800]	valid_0's binary_logloss: 0.262865
[900]	valid_0's binary_logloss: 0.262599
[1000]	valid_0's binary_logloss: 0.262286
[1100]	valid_0's binary_logloss: 0.262285
Early stopping, best iteration is:
[1026]	valid_0's binary_logloss: 0.2622
-------------------- Metrics --------------------
Accuracy: 0.6547
Precision: 0.2028
Recall: 0.8271
F1 Score: 0.3257
ROC AUC: 0.8160
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.262769
[1200]	valid_0's binary_logloss: 0.262146
[1300]	valid_0's binary_logloss: 0.261836
[1400]	valid_0's binary_logloss: 0.261571
[1500]	valid_0's binary_logloss: 0.261475
[1600]	valid_0's binary_logloss: 0.261389
Early stopping, best iteration is:
[1560]	valid_0's binary_logloss: 0.26136
-------------------- Metrics --------------------
Accuracy: 0.6504
Precision: 0.2057
Recall: 0.8379
F1 Score: 0.3303
ROC AUC: 0.8233
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1600]	valid_0's binary_logloss: 0.260472
[1700]	valid_0's binary_logloss: 0.260049
[1800]	valid_0's binary_logloss: 0.259877
[1900]	valid_0's binary_logloss: 0.259744
[2000]	valid_0's binary_logloss: 0.259629
[2100]	valid_0's binary_logloss: 0.259584
[2200]	valid_0's binary_logloss: 0.259521
[2300]	valid_0's binary_logloss: 0.259518
Early stopping, best iteration is:
[2229]	valid_0's binary_logloss: 0.259486
-------------------- Metrics --------------------
Accuracy: 0.6661
Precision: 0.2079
Recall: 0.8372
F1 Score: 0.3330
ROC AUC: 0.8220
Training final model using all data...
Final model training completed.

In [9]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_urawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_urawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_urawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_urawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_urawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.268276
[200]	valid_0's binary_logloss: 0.262162
[300]	valid_0's binary_logloss: 0.261621
Early stopping, best iteration is:
[269]	valid_0's binary_logloss: 0.261366
-------------------- Metrics --------------------
Accuracy: 0.6853
Precision: 0.1868
Recall: 0.7263
F1 Score: 0.2972
ROC AUC: 0.7805
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.275207
[400]	valid_0's binary_logloss: 0.272998
[500]	valid_0's binary_logloss: 0.272427
[600]	valid_0's binary_logloss: 0.272806
Early stopping, best iteration is:
[540]	valid_0's binary_logloss: 0.272239
-------------------- Metrics --------------------
Accuracy: 0.6940
Precision: 0.2031
Recall: 0.7452
F1 Score: 0.3192
ROC AUC: 0.7795
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.270351
[700]	valid_0's binary_logloss: 0.269851
[800]	valid_0's binary_logloss: 0.269829
Early stopping, best iteration is:
[746]	valid_0's binary_logloss: 0.269769
-------------------- Metrics --------------------
Accuracy: 0.6640
Precision: 0.1866
Recall: 0.7546
F1 Score: 0.2992
ROC AUC: 0.7764
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.263378
[900]	valid_0's binary_logloss: 0.262971
Early stopping, best iteration is:
[856]	valid_0's binary_logloss: 0.26295
-------------------- Metrics --------------------
Accuracy: 0.6387
Precision: 0.1798
Recall: 0.7997
F1 Score: 0.2935
ROC AUC: 0.7858
Training final model using all data...
Final model training completed.

In [10]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_saga.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_saga",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_saga.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_saga.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_saga.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.265538
[200]	valid_0's binary_logloss: 0.254696
[300]	valid_0's binary_logloss: 0.251951
[400]	valid_0's binary_logloss: 0.251261
Early stopping, best iteration is:
[396]	valid_0's binary_logloss: 0.251233
-------------------- Metrics --------------------
Accuracy: 0.7181
Precision: 0.2316
Recall: 0.7859
F1 Score: 0.3578
ROC AUC: 0.8310
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.270276
[500]	valid_0's binary_logloss: 0.267801
[600]	valid_0's binary_logloss: 0.266917
[700]	valid_0's binary_logloss: 0.266534
[800]	valid_0's binary_logloss: 0.266428
[900]	valid_0's binary_logloss: 0.266543
Early stopping, best iteration is:
[836]	valid_0's binary_logloss: 0.266384
-------------------- Metrics --------------------
Accuracy: 0.6874
Precision: 0.2184
Recall: 0.7970
F1 Score: 0.3429
ROC AUC: 0.8149
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.257289
[1000]	valid_0's binary_logloss: 0.256671
[1100]	valid_0's binary_logloss: 0.256353
[1200]	valid_0's binary_logloss: 0.256203
[1300]	valid_0's binary_logloss: 0.25617
Early stopping, best iteration is:
[1275]	valid_0's binary_logloss: 0.256087
-------------------- Metrics --------------------
Accuracy: 0.6784
Precision: 0.2075
Recall: 0.8131
F1 Score: 0.3306
ROC AUC: 0.8209
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.247125
[1400]	valid_0's binary_logloss: 0.246786
[1500]	valid_0's binary_logloss: 0.246586
[1600]	valid_0's binary_logloss: 0.246475
[1700]	valid_0's binary_logloss: 0.246408
Early stopping, best iteration is:
[1641]	valid_0's binary_logloss: 0.246348
-------------------- Metrics --------------------
Accuracy: 0.6966
Precision: 0.2209
Recall: 0.8165
F1 Score: 0.3478
ROC AUC: 0.8395
Training final model using all data...
Final model training completed.

In [11]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_ooi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_ooi",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_ooi.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_ooi.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_ooi.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.239419
[200]	valid_0's binary_logloss: 0.232606
[300]	valid_0's binary_logloss: 0.230614
[400]	valid_0's binary_logloss: 0.230382
Early stopping, best iteration is:
[377]	valid_0's binary_logloss: 0.230273
-------------------- Metrics --------------------
Accuracy: 0.7109
Precision: 0.1796
Recall: 0.7530
F1 Score: 0.2900
ROC AUC: 0.7997
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.233649
[500]	valid_0's binary_logloss: 0.233125
[600]	valid_0's binary_logloss: 0.232734
[700]	valid_0's binary_logloss: 0.232782
Early stopping, best iteration is:
[651]	valid_0's binary_logloss: 0.232692
-------------------- Metrics --------------------
Accuracy: 0.7036
Precision: 0.1814
Recall: 0.7589
F1 Score: 0.2928
ROC AUC: 0.8026
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.238829
[800]	valid_0's binary_logloss: 0.238404
[900]	valid_0's binary_logloss: 0.238244
[1000]	valid_0's binary_logloss: 0.238182
[1100]	valid_0's binary_logloss: 0.238241
Early stopping, best iteration is:
[1021]	valid_0's binary_logloss: 0.238175
-------------------- Metrics --------------------
Accuracy: 0.6893
Precision: 0.1793
Recall: 0.7654
F1 Score: 0.2905
ROC AUC: 0.7992
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.234329
[1200]	valid_0's binary_logloss: 0.23411
Early stopping, best iteration is:
[1177]	valid_0's binary_logloss: 0.234043
-------------------- Metrics --------------------
Accuracy: 0.6891
Precision: 0.1780
Recall: 0.7666
F1 Score: 0.2889
ROC AUC: 0.8060
Training final model using all data...
Final model training completed.

In [12]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_nagoya.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nagoya",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nagoya.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nagoya.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nagoya.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.27543
[200]	valid_0's binary_logloss: 0.26564
[300]	valid_0's binary_logloss: 0.263635
[400]	valid_0's binary_logloss: 0.263943
Early stopping, best iteration is:
[335]	valid_0's binary_logloss: 0.263608
-------------------- Metrics --------------------
Accuracy: 0.6953
Precision: 0.2182
Recall: 0.7869
F1 Score: 0.3416
ROC AUC: 0.8159
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.25119
[500]	valid_0's binary_logloss: 0.250624
[600]	valid_0's binary_logloss: 0.250203
[700]	valid_0's binary_logloss: 0.250292
Early stopping, best iteration is:
[613]	valid_0's binary_logloss: 0.250109
-------------------- Metrics --------------------
Accuracy: 0.7025
Precision: 0.2094
Recall: 0.7859
F1 Score: 0.3307
ROC AUC: 0.8176
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.244563
[800]	valid_0's binary_logloss: 0.24417
[900]	valid_0's binary_logloss: 0.243852
[1000]	valid_0's binary_logloss: 0.243642
[1100]	valid_0's binary_logloss: 0.243472
[1200]	valid_0's binary_logloss: 0.243418
Early stopping, best iteration is:
[1168]	valid_0's binary_logloss: 0.243389
-------------------- Metrics --------------------
Accuracy: 0.6958
Precision: 0.2063
Recall: 0.8083
F1 Score: 0.3287
ROC AUC: 0.8246
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.249565
[1300]	valid_0's binary_logloss: 0.248745
[1400]	valid_0's binary_logloss: 0.24823
[1500]	valid_0's binary_logloss: 0.248014
[1600]	valid_0's binary_logloss: 0.247815
[1700]	valid_0's binary_logloss: 0.247718
[1800]	valid_0's binary_logloss: 0.247757
Early stopping, best iteration is:
[1706]	valid_0's binary_logloss: 0.247697
-------------------- Metrics --------------------
Accuracy: 0.6933
Precision: 0.1968
Recall: 0.7814
F1 Score: 0.3144
ROC AUC: 0.8068
Training final model using all data...
Final model training completed.

In [13]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_morioka.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_morioka",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_morioka.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_morioka.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_morioka.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.29673
[200]	valid_0's binary_logloss: 0.288965
[300]	valid_0's binary_logloss: 0.287908
Early stopping, best iteration is:
[285]	valid_0's binary_logloss: 0.287723
-------------------- Metrics --------------------
Accuracy: 0.6617
Precision: 0.2169
Recall: 0.7921
F1 Score: 0.3405
ROC AUC: 0.7943
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.2727
[400]	valid_0's binary_logloss: 0.270805
[500]	valid_0's binary_logloss: 0.270835
Early stopping, best iteration is:
[454]	valid_0's binary_logloss: 0.270617
-------------------- Metrics --------------------
Accuracy: 0.6581
Precision: 0.2117
Recall: 0.8068
F1 Score: 0.3354
ROC AUC: 0.8157
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.283912
[600]	valid_0's binary_logloss: 0.282698
[700]	valid_0's binary_logloss: 0.281874
[800]	valid_0's binary_logloss: 0.281452
[900]	valid_0's binary_logloss: 0.281195
[1000]	valid_0's binary_logloss: 0.281195
Early stopping, best iteration is:
[943]	valid_0's binary_logloss: 0.28102
-------------------- Metrics --------------------
Accuracy: 0.6667
Precision: 0.2158
Recall: 0.8003
F1 Score: 0.3399
ROC AUC: 0.7995
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.269935
[1100]	valid_0's binary_logloss: 0.269065
[1200]	valid_0's binary_logloss: 0.268502
[1300]	valid_0's binary_logloss: 0.268484
Early stopping, best iteration is:
[1280]	valid_0's binary_logloss: 0.268378
-------------------- Metrics --------------------
Accuracy: 0.6591
Precision: 0.1969
Recall: 0.7942
F1 Score: 0.3156
ROC AUC: 0.7965
Training final model using all data...
Final model training completed.

In [14]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_monbetu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_monbetu",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_monbetu.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_monbetu.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_monbetu.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.27712
[200]	valid_0's binary_logloss: 0.264497
[300]	valid_0's binary_logloss: 0.260978
[400]	valid_0's binary_logloss: 0.25995
[500]	valid_0's binary_logloss: 0.260345
Early stopping, best iteration is:
[409]	valid_0's binary_logloss: 0.259857
-------------------- Metrics --------------------
Accuracy: 0.6818
Precision: 0.2229
Recall: 0.8268
F1 Score: 0.3512
ROC AUC: 0.8305
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.273066
[600]	valid_0's binary_logloss: 0.272145
[700]	valid_0's binary_logloss: 0.271956
[800]	valid_0's binary_logloss: 0.271718
[900]	valid_0's binary_logloss: 0.27185
Early stopping, best iteration is:
[835]	valid_0's binary_logloss: 0.271607
-------------------- Metrics --------------------
Accuracy: 0.6774
Precision: 0.2242
Recall: 0.8220
F1 Score: 0.3523
ROC AUC: 0.8194
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.257706
[1000]	valid_0's binary_logloss: 0.257515
[1100]	valid_0's binary_logloss: 0.257943
Early stopping, best iteration is:
[1015]	valid_0's binary_logloss: 0.257488
-------------------- Metrics --------------------
Accuracy: 0.6778
Precision: 0.2149
Recall: 0.8321
F1 Score: 0.3415
ROC AUC: 0.8285
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.260152
[1200]	valid_0's binary_logloss: 0.260161
Early stopping, best iteration is:
[1129]	valid_0's binary_logloss: 0.260015
-------------------- Metrics --------------------
Accuracy: 0.6817
Precision: 0.2176
Recall: 0.8169
F1 Score: 0.3437
ROC AUC: 0.8252
Training final model using all data...
Final model training completed.

In [15]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_mizusawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_mizusawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_mizusawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_mizusawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_mizusawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.301865
[200]	valid_0's binary_logloss: 0.293767
[300]	valid_0's binary_logloss: 0.291315
[400]	valid_0's binary_logloss: 0.291868
Early stopping, best iteration is:
[344]	valid_0's binary_logloss: 0.290934
-------------------- Metrics --------------------
Accuracy: 0.6579
Precision: 0.2052
Recall: 0.7658
F1 Score: 0.3236
ROC AUC: 0.7741
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.28728
[500]	valid_0's binary_logloss: 0.286074
[600]	valid_0's binary_logloss: 0.286065
Early stopping, best iteration is:
[576]	valid_0's binary_logloss: 0.285951
-------------------- Metrics --------------------
Accuracy: 0.6355
Precision: 0.1986
Recall: 0.8053
F1 Score: 0.3187
ROC AUC: 0.7820
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.291312
[700]	valid_0's binary_logloss: 0.29073
[800]	valid_0's binary_logloss: 0.290806
Early stopping, best iteration is:
[751]	valid_0's binary_logloss: 0.290431
-------------------- Metrics --------------------
Accuracy: 0.6202
Precision: 0.1926
Recall: 0.8108
F1 Score: 0.3113
ROC AUC: 0.7760
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.263693
[900]	valid_0's binary_logloss: 0.263118
[1000]	valid_0's binary_logloss: 0.262914
[1100]	valid_0's binary_logloss: 0.262735
[1200]	valid_0's binary_logloss: 0.262612
[1300]	valid_0's binary_logloss: 0.262561
Early stopping, best iteration is:
[1252]	valid_0's binary_logloss: 0.262396
-------------------- Metrics --------------------
Accuracy: 0.6442
Precision: 0.1991
Recall: 0.8416
F1 Score: 0.3220
ROC AUC: 0.8132
Training final model using all data...
Final model training completed.

In [16]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kouti.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kouti",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kouti.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kouti.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kouti.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.267247
[200]	valid_0's binary_logloss: 0.255578
[300]	valid_0's binary_logloss: 0.252284
[400]	valid_0's binary_logloss: 0.251447
[500]	valid_0's binary_logloss: 0.251814
Early stopping, best iteration is:
[412]	valid_0's binary_logloss: 0.251438
-------------------- Metrics --------------------
Accuracy: 0.7164
Precision: 0.2361
Recall: 0.8082
F1 Score: 0.3655
ROC AUC: 0.8391
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.252466
[600]	valid_0's binary_logloss: 0.251947
[700]	valid_0's binary_logloss: 0.251493
[800]	valid_0's binary_logloss: 0.251336
[900]	valid_0's binary_logloss: 0.251265
Early stopping, best iteration is:
[890]	valid_0's binary_logloss: 0.251223
-------------------- Metrics --------------------
Accuracy: 0.7106
Precision: 0.2337
Recall: 0.8075
F1 Score: 0.3626
ROC AUC: 0.8390
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.254204
[1000]	valid_0's binary_logloss: 0.253747
Early stopping, best iteration is:
[972]	valid_0's binary_logloss: 0.25365
-------------------- Metrics --------------------
Accuracy: 0.7041
Precision: 0.2301
Recall: 0.8183
F1 Score: 0.3592
ROC AUC: 0.8344
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.254765
[1100]	valid_0's binary_logloss: 0.254212
[1200]	valid_0's binary_logloss: 0.254152
[1300]	valid_0's binary_logloss: 0.253805
[1400]	valid_0's binary_logloss: 0.253797
Early stopping, best iteration is:
[1340]	valid_0's binary_logloss: 0.253747
-------------------- Metrics --------------------
Accuracy: 0.6876
Precision: 0.2225
Recall: 0.8245
F1 Score: 0.3505
ROC AUC: 0.8366
Training final model using all data...
Final model training completed.

In [17]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kawasaki.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kawasaki",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kawasaki.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kawasaki.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kawasaki.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.267568
[200]	valid_0's binary_logloss: 0.260907
[300]	valid_0's binary_logloss: 0.259905
Early stopping, best iteration is:
[282]	valid_0's binary_logloss: 0.259815
-------------------- Metrics --------------------
Accuracy: 0.6817
Precision: 0.1817
Recall: 0.7290
F1 Score: 0.2909
ROC AUC: 0.7795
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.259219
[400]	valid_0's binary_logloss: 0.2573
[500]	valid_0's binary_logloss: 0.256847
[600]	valid_0's binary_logloss: 0.25672
[700]	valid_0's binary_logloss: 0.256882
Early stopping, best iteration is:
[660]	valid_0's binary_logloss: 0.256602
-------------------- Metrics --------------------
Accuracy: 0.6843
Precision: 0.1864
Recall: 0.7436
F1 Score: 0.2980
ROC AUC: 0.7860
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.260307
[800]	valid_0's binary_logloss: 0.259748
[900]	valid_0's binary_logloss: 0.259673
Early stopping, best iteration is:
[811]	valid_0's binary_logloss: 0.259652
-------------------- Metrics --------------------
Accuracy: 0.6600
Precision: 0.1808
Recall: 0.7741
F1 Score: 0.2931
ROC AUC: 0.7867
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.25393
[1000]	valid_0's binary_logloss: 0.2534
[1100]	valid_0's binary_logloss: 0.253072
[1200]	valid_0's binary_logloss: 0.253136
Early stopping, best iteration is:
[1115]	valid_0's binary_logloss: 0.252993
-------------------- Metrics --------------------
Accuracy: 0.6603
Precision: 0.1840
Recall: 0.7934
F1 Score: 0.2987
ROC AUC: 0.7981
Training final model using all data...
Final model training completed.

In [18]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kasamatu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kasamatu",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kasamatu.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kasamatu.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kasamatu.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.29673
[200]	valid_0's binary_logloss: 0.288965
[300]	valid_0's binary_logloss: 0.287908
Early stopping, best iteration is:
[285]	valid_0's binary_logloss: 0.287723
-------------------- Metrics --------------------
Accuracy: 0.6617
Precision: 0.2169
Recall: 0.7921
F1 Score: 0.3405
ROC AUC: 0.7943
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.2727
[400]	valid_0's binary_logloss: 0.270805
[500]	valid_0's binary_logloss: 0.270835
Early stopping, best iteration is:
[454]	valid_0's binary_logloss: 0.270617
-------------------- Metrics --------------------
Accuracy: 0.6581
Precision: 0.2117
Recall: 0.8068
F1 Score: 0.3354
ROC AUC: 0.8157
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.283912
[600]	valid_0's binary_logloss: 0.282698
[700]	valid_0's binary_logloss: 0.281874
[800]	valid_0's binary_logloss: 0.281452
[900]	valid_0's binary_logloss: 0.281195
[1000]	valid_0's binary_logloss: 0.281195
Early stopping, best iteration is:
[943]	valid_0's binary_logloss: 0.28102
-------------------- Metrics --------------------
Accuracy: 0.6667
Precision: 0.2158
Recall: 0.8003
F1 Score: 0.3399
ROC AUC: 0.7995
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.269935
[1100]	valid_0's binary_logloss: 0.269065
[1200]	valid_0's binary_logloss: 0.268502
[1300]	valid_0's binary_logloss: 0.268484
Early stopping, best iteration is:
[1280]	valid_0's binary_logloss: 0.268378
-------------------- Metrics --------------------
Accuracy: 0.6591
Precision: 0.1969
Recall: 0.7942
F1 Score: 0.3156
ROC AUC: 0.7965
Training final model using all data...
Final model training completed.

In [19]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kanazawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kanazawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kanazawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kanazawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kanazawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.289464
[200]	valid_0's binary_logloss: 0.275802
[300]	valid_0's binary_logloss: 0.273231
[400]	valid_0's binary_logloss: 0.273432
Early stopping, best iteration is:
[355]	valid_0's binary_logloss: 0.272957
-------------------- Metrics --------------------
Accuracy: 0.6946
Precision: 0.2522
Recall: 0.8179
F1 Score: 0.3856
ROC AUC: 0.8375
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.28207
[500]	valid_0's binary_logloss: 0.279436
[600]	valid_0's binary_logloss: 0.278791
Early stopping, best iteration is:
[568]	valid_0's binary_logloss: 0.278651
-------------------- Metrics --------------------
Accuracy: 0.6792
Precision: 0.2401
Recall: 0.8169
F1 Score: 0.3711
ROC AUC: 0.8292
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.275615
[700]	valid_0's binary_logloss: 0.27473
[800]	valid_0's binary_logloss: 0.274556
[900]	valid_0's binary_logloss: 0.274239
Early stopping, best iteration is:
[890]	valid_0's binary_logloss: 0.274186
-------------------- Metrics --------------------
Accuracy: 0.6798
Precision: 0.2451
Recall: 0.8544
F1 Score: 0.3809
ROC AUC: 0.8401
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.264806
[1000]	valid_0's binary_logloss: 0.263938
[1100]	valid_0's binary_logloss: 0.263452
[1200]	valid_0's binary_logloss: 0.263112
[1300]	valid_0's binary_logloss: 0.263172
Early stopping, best iteration is:
[1274]	valid_0's binary_logloss: 0.263095
-------------------- Metrics --------------------
Accuracy: 0.6822
Precision: 0.2396
Recall: 0.8366
F1 Score: 0.3725
ROC AUC: 0.8430
Training final model using all data...
Final model training completed.

In [20]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_funabasi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_funabasi",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_funabasi.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_funabasi.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_funabasi.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.268066
[200]	valid_0's binary_logloss: 0.26088
[300]	valid_0's binary_logloss: 0.260069
Early stopping, best iteration is:
[258]	valid_0's binary_logloss: 0.259961
-------------------- Metrics --------------------
Accuracy: 0.7072
Precision: 0.2097
Recall: 0.7629
F1 Score: 0.3290
ROC AUC: 0.8008
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.278025
[400]	valid_0's binary_logloss: 0.276805
[500]	valid_0's binary_logloss: 0.277135
Early stopping, best iteration is:
[400]	valid_0's binary_logloss: 0.276805
-------------------- Metrics --------------------
Accuracy: 0.6845
Precision: 0.1953
Recall: 0.7279
F1 Score: 0.3080
ROC AUC: 0.7703
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.26662
[600]	valid_0's binary_logloss: 0.266537
[700]	valid_0's binary_logloss: 0.266308
Early stopping, best iteration is:
[679]	valid_0's binary_logloss: 0.266245
-------------------- Metrics --------------------
Accuracy: 0.6526
Precision: 0.1952
Recall: 0.8072
F1 Score: 0.3144
ROC AUC: 0.7964
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.262188
[800]	valid_0's binary_logloss: 0.261807
[900]	valid_0's binary_logloss: 0.261548
[1000]	valid_0's binary_logloss: 0.261441
[1100]	valid_0's binary_logloss: 0.261517
Early stopping, best iteration is:
[1057]	valid_0's binary_logloss: 0.261348
-------------------- Metrics --------------------
Accuracy: 0.6720
Precision: 0.2035
Recall: 0.8035
F1 Score: 0.3248
ROC AUC: 0.8078
Training final model using all data...
Final model training completed.

In [ ]:
# #全体のレースを学習した際、最後のブースト回数よりも多いか確認
# import lightgbm as lgb
# import pickle

# from pathlib import Path
# DATA_DIR = Path("..", "data")
# INPUT_DIR = DATA_DIR / "02_features"
# OUTPUT_DIR = DATA_DIR / "03_train"

# # モデルの読み込み
# with open(OUTPUT_DIR/"model_lightgbm_rank_niti_cv_full_dev_turf.pkl", "rb") as f:
#     model = pickle.load(f)

# # ブースト回数の取得
# num_trees = model.num_trees()

# print(f"ブースト回数（num_boost_round）: {num_trees}")

### 体重なし

In [21]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight10.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_sonoda",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_sonoda.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_sonoda.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_sonoda.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.280348
[200]	valid_0's binary_logloss: 0.271135
[300]	valid_0's binary_logloss: 0.268566
[400]	valid_0's binary_logloss: 0.26756
[500]	valid_0's binary_logloss: 0.267259
Early stopping, best iteration is:
[482]	valid_0's binary_logloss: 0.267223
-------------------- Metrics --------------------
Accuracy: 0.6515
Precision: 0.1944
Recall: 0.8048
F1 Score: 0.3131
ROC AUC: 0.7997
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.267446
[600]	valid_0's binary_logloss: 0.265438
[700]	valid_0's binary_logloss: 0.264525
[800]	valid_0's binary_logloss: 0.264078
[900]	valid_0's binary_logloss: 0.263763
[1000]	valid_0's binary_logloss: 0.263631
[1100]	valid_0's binary_logloss: 0.26358
Early stopping, best iteration is:
[1090]	valid_0's binary_logloss: 0.263567
-------------------- Metrics --------------------
Accuracy: 0.6552
Precision: 0.2024
Recall: 0.8226
F1 Score: 0.3248
ROC AUC: 0.8126
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.264318
[1200]	valid_0's binary_logloss: 0.262919
[1300]	valid_0's binary_logloss: 0.2623
[1400]	valid_0's binary_logloss: 0.262121
[1500]	valid_0's binary_logloss: 0.261966
[1600]	valid_0's binary_logloss: 0.261839
[1700]	valid_0's binary_logloss: 0.261763
[1800]	valid_0's binary_logloss: 0.261729
[1900]	valid_0's binary_logloss: 0.261654
Early stopping, best iteration is:
[1895]	valid_0's binary_logloss: 0.261632
-------------------- Metrics --------------------
Accuracy: 0.6584
Precision: 0.2099
Recall: 0.8394
F1 Score: 0.3358
ROC AUC: 0.8232
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1900]	valid_0's binary_logloss: 0.26117
[2000]	valid_0's binary_logloss: 0.260767
[2100]	valid_0's binary_logloss: 0.260579
Early stopping, best iteration is:
[2099]	valid_0's binary_logloss: 0.260571
-------------------- Metrics --------------------
Accuracy: 0.6596
Precision: 0.2046
Recall: 0.8377
F1 Score: 0.3289
ROC AUC: 0.8200
Training final model using all data...
Final model training completed.

In [22]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_urawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_urawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_urawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_urawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_urawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.269583
[200]	valid_0's binary_logloss: 0.264083
[300]	valid_0's binary_logloss: 0.26413
Early stopping, best iteration is:
[244]	valid_0's binary_logloss: 0.263587
-------------------- Metrics --------------------
Accuracy: 0.6728
Precision: 0.1807
Recall: 0.7278
F1 Score: 0.2895
ROC AUC: 0.7752
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.275916
[400]	valid_0's binary_logloss: 0.274248
[500]	valid_0's binary_logloss: 0.27399
Early stopping, best iteration is:
[490]	valid_0's binary_logloss: 0.273975
-------------------- Metrics --------------------
Accuracy: 0.6832
Precision: 0.1953
Recall: 0.7341
F1 Score: 0.3085
ROC AUC: 0.7745
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.271829
[600]	valid_0's binary_logloss: 0.270041
[700]	valid_0's binary_logloss: 0.270212
Early stopping, best iteration is:
[616]	valid_0's binary_logloss: 0.269985
-------------------- Metrics --------------------
Accuracy: 0.6621
Precision: 0.1861
Recall: 0.7574
F1 Score: 0.2988
ROC AUC: 0.7759
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.26307
[800]	valid_0's binary_logloss: 0.262361
[900]	valid_0's binary_logloss: 0.262176
Early stopping, best iteration is:
[867]	valid_0's binary_logloss: 0.262142
-------------------- Metrics --------------------
Accuracy: 0.6415
Precision: 0.1810
Recall: 0.7997
F1 Score: 0.2952
ROC AUC: 0.7886
Training final model using all data...
Final model training completed.

In [23]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_saga.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_saga",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_saga.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_saga.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_saga.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.2655
[200]	valid_0's binary_logloss: 0.254521
[300]	valid_0's binary_logloss: 0.252011
[400]	valid_0's binary_logloss: 0.251706
[500]	valid_0's binary_logloss: 0.252106
Early stopping, best iteration is:
[413]	valid_0's binary_logloss: 0.251684
-------------------- Metrics --------------------
Accuracy: 0.7222
Precision: 0.2342
Recall: 0.7844
F1 Score: 0.3607
ROC AUC: 0.8311
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.268255
[600]	valid_0's binary_logloss: 0.267295
[700]	valid_0's binary_logloss: 0.266893
[800]	valid_0's binary_logloss: 0.266868
[900]	valid_0's binary_logloss: 0.267035
Early stopping, best iteration is:
[833]	valid_0's binary_logloss: 0.266793
-------------------- Metrics --------------------
Accuracy: 0.6941
Precision: 0.2225
Recall: 0.7970
F1 Score: 0.3478
ROC AUC: 0.8144
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.25868
[1000]	valid_0's binary_logloss: 0.258295
[1100]	valid_0's binary_logloss: 0.258351
[1200]	valid_0's binary_logloss: 0.258274
[1300]	valid_0's binary_logloss: 0.258386
Early stopping, best iteration is:
[1221]	valid_0's binary_logloss: 0.258211
-------------------- Metrics --------------------
Accuracy: 0.6810
Precision: 0.2089
Recall: 0.8131
F1 Score: 0.3324
ROC AUC: 0.8174
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.248928
[1400]	valid_0's binary_logloss: 0.248565
[1500]	valid_0's binary_logloss: 0.248319
[1600]	valid_0's binary_logloss: 0.248186
[1700]	valid_0's binary_logloss: 0.248202
Early stopping, best iteration is:
[1660]	valid_0's binary_logloss: 0.248111
-------------------- Metrics --------------------
Accuracy: 0.6886
Precision: 0.2181
Recall: 0.8288
F1 Score: 0.3453
ROC AUC: 0.8367
Training final model using all data...
Final model training completed.

In [24]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_ooi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_ooi",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_ooi.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_ooi.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_ooi.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.239886
[200]	valid_0's binary_logloss: 0.233202
[300]	valid_0's binary_logloss: 0.231806
[400]	valid_0's binary_logloss: 0.231737
Early stopping, best iteration is:
[330]	valid_0's binary_logloss: 0.231645
-------------------- Metrics --------------------
Accuracy: 0.7050
Precision: 0.1751
Recall: 0.7443
F1 Score: 0.2835
ROC AUC: 0.7954
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.233672
[500]	valid_0's binary_logloss: 0.233302
[600]	valid_0's binary_logloss: 0.233315
Early stopping, best iteration is:
[551]	valid_0's binary_logloss: 0.233244
-------------------- Metrics --------------------
Accuracy: 0.7016
Precision: 0.1798
Recall: 0.7555
F1 Score: 0.2905
ROC AUC: 0.8003
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.23922
[700]	valid_0's binary_logloss: 0.238837
[800]	valid_0's binary_logloss: 0.238588
[900]	valid_0's binary_logloss: 0.238475
Early stopping, best iteration is:
[877]	valid_0's binary_logloss: 0.238395
-------------------- Metrics --------------------
Accuracy: 0.6864
Precision: 0.1793
Recall: 0.7752
F1 Score: 0.2913
ROC AUC: 0.7990
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.235536
[1000]	valid_0's binary_logloss: 0.235039
[1100]	valid_0's binary_logloss: 0.234811
[1200]	valid_0's binary_logloss: 0.23489
Early stopping, best iteration is:
[1106]	valid_0's binary_logloss: 0.234774
-------------------- Metrics --------------------
Accuracy: 0.6923
Precision: 0.1799
Recall: 0.7690
F1 Score: 0.2916
ROC AUC: 0.8048
Training final model using all data...
Final model training completed.

In [25]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_nagoya.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_nagoya",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_nagoya.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_nagoya.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_nagoya.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.276192
[200]	valid_0's binary_logloss: 0.266493
[300]	valid_0's binary_logloss: 0.264361
[400]	valid_0's binary_logloss: 0.264248
Early stopping, best iteration is:
[365]	valid_0's binary_logloss: 0.263986
-------------------- Metrics --------------------
Accuracy: 0.6986
Precision: 0.2198
Recall: 0.7841
F1 Score: 0.3433
ROC AUC: 0.8156
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.25262
[500]	valid_0's binary_logloss: 0.251338
[600]	valid_0's binary_logloss: 0.250967
Early stopping, best iteration is:
[581]	valid_0's binary_logloss: 0.250912
-------------------- Metrics --------------------
Accuracy: 0.6992
Precision: 0.2076
Recall: 0.7867
F1 Score: 0.3285
ROC AUC: 0.8176
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.24691
[700]	valid_0's binary_logloss: 0.245866
[800]	valid_0's binary_logloss: 0.245496
[900]	valid_0's binary_logloss: 0.245409
[1000]	valid_0's binary_logloss: 0.245364
[1100]	valid_0's binary_logloss: 0.245194
[1200]	valid_0's binary_logloss: 0.245162
Early stopping, best iteration is:
[1139]	valid_0's binary_logloss: 0.245036
-------------------- Metrics --------------------
Accuracy: 0.6898
Precision: 0.2026
Recall: 0.8060
F1 Score: 0.3238
ROC AUC: 0.8208
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.250071
[1300]	valid_0's binary_logloss: 0.249588
[1400]	valid_0's binary_logloss: 0.249318
[1500]	valid_0's binary_logloss: 0.249175
[1600]	valid_0's binary_logloss: 0.249018
[1700]	valid_0's binary_logloss: 0.248996
Early stopping, best iteration is:
[1637]	valid_0's binary_logloss: 0.248958
-------------------- Metrics --------------------
Accuracy: 0.6911
Precision: 0.1947
Recall: 0.7752
F1 Score: 0.3112
ROC AUC: 0.8044
Training final model using all data...
Final model training completed.

In [26]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_morioka.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_morioka",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_morioka.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_morioka.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_morioka.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.297189
[200]	valid_0's binary_logloss: 0.289999
[300]	valid_0's binary_logloss: 0.289218
Early stopping, best iteration is:
[289]	valid_0's binary_logloss: 0.28905
-------------------- Metrics --------------------
Accuracy: 0.6632
Precision: 0.2155
Recall: 0.7784
F1 Score: 0.3376
ROC AUC: 0.7916
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.274049
[400]	valid_0's binary_logloss: 0.272299
[500]	valid_0's binary_logloss: 0.271648
[600]	valid_0's binary_logloss: 0.271634
[700]	valid_0's binary_logloss: 0.272267
Early stopping, best iteration is:
[626]	valid_0's binary_logloss: 0.271532
-------------------- Metrics --------------------
Accuracy: 0.6738
Precision: 0.2187
Recall: 0.7969
F1 Score: 0.3432
ROC AUC: 0.8159
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.285526
[800]	valid_0's binary_logloss: 0.285195
[900]	valid_0's binary_logloss: 0.285066
Early stopping, best iteration is:
[831]	valid_0's binary_logloss: 0.284978
-------------------- Metrics --------------------
Accuracy: 0.6551
Precision: 0.2075
Recall: 0.7862
F1 Score: 0.3283
ROC AUC: 0.7908
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.269404
[1000]	valid_0's binary_logloss: 0.268766
[1100]	valid_0's binary_logloss: 0.26859
[1200]	valid_0's binary_logloss: 0.268444
Early stopping, best iteration is:
[1144]	valid_0's binary_logloss: 0.268367
-------------------- Metrics --------------------
Accuracy: 0.6585
Precision: 0.1964
Recall: 0.7927
F1 Score: 0.3148
ROC AUC: 0.7939
Training final model using all data...
Final model training completed.

In [27]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_monbetu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_monbetu",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_monbetu.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_monbetu.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_monbetu.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.278491
[200]	valid_0's binary_logloss: 0.26567
[300]	valid_0's binary_logloss: 0.262465
[400]	valid_0's binary_logloss: 0.261462
Early stopping, best iteration is:
[396]	valid_0's binary_logloss: 0.261454
-------------------- Metrics --------------------
Accuracy: 0.6714
Precision: 0.2180
Recall: 0.8330
F1 Score: 0.3456
ROC AUC: 0.8272
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.277328
[500]	valid_0's binary_logloss: 0.274997
[600]	valid_0's binary_logloss: 0.274379
[700]	valid_0's binary_logloss: 0.27408
[800]	valid_0's binary_logloss: 0.274095
Early stopping, best iteration is:
[717]	valid_0's binary_logloss: 0.273987
-------------------- Metrics --------------------
Accuracy: 0.6621
Precision: 0.2159
Recall: 0.8230
F1 Score: 0.3421
ROC AUC: 0.8135
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.257249
Early stopping, best iteration is:
[744]	valid_0's binary_logloss: 0.257193
-------------------- Metrics --------------------
Accuracy: 0.6704
Precision: 0.2128
Recall: 0.8459
F1 Score: 0.3401
ROC AUC: 0.8287
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.261021
[900]	valid_0's binary_logloss: 0.26078
[1000]	valid_0's binary_logloss: 0.260542
[1100]	valid_0's binary_logloss: 0.260561
Early stopping, best iteration is:
[1004]	valid_0's binary_logloss: 0.260533
-------------------- Metrics --------------------
Accuracy: 0.6636
Precision: 0.2097
Recall: 0.8295
F1 Score: 0.3347
ROC AUC: 0.8227
Training final model using all data...
Final model training completed.

In [28]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_mizusawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_mizusawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_mizusawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_mizusawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_mizusawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.301821
[200]	valid_0's binary_logloss: 0.294025
[300]	valid_0's binary_logloss: 0.291608
[400]	valid_0's binary_logloss: 0.292484
Early stopping, best iteration is:
[300]	valid_0's binary_logloss: 0.291608
-------------------- Metrics --------------------
Accuracy: 0.6383
Precision: 0.1981
Recall: 0.7824
F1 Score: 0.3162
ROC AUC: 0.7719
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.286714
[500]	valid_0's binary_logloss: 0.285832
[600]	valid_0's binary_logloss: 0.285633
Early stopping, best iteration is:
[562]	valid_0's binary_logloss: 0.285433
-------------------- Metrics --------------------
Accuracy: 0.6432
Precision: 0.2033
Recall: 0.8122
F1 Score: 0.3252
ROC AUC: 0.7846
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.290528
[700]	valid_0's binary_logloss: 0.290193
[800]	valid_0's binary_logloss: 0.290535
Early stopping, best iteration is:
[734]	valid_0's binary_logloss: 0.290111
-------------------- Metrics --------------------
Accuracy: 0.6240
Precision: 0.1939
Recall: 0.8081
F1 Score: 0.3127
ROC AUC: 0.7775
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.265296
[900]	valid_0's binary_logloss: 0.265132
Early stopping, best iteration is:
[864]	valid_0's binary_logloss: 0.265082
-------------------- Metrics --------------------
Accuracy: 0.6259
Precision: 0.1894
Recall: 0.8314
F1 Score: 0.3086
ROC AUC: 0.8072
Training final model using all data...
Final model training completed.

In [29]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kouti.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_kouti",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_kouti.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_kouti.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_kouti.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.267109
[200]	valid_0's binary_logloss: 0.255588
[300]	valid_0's binary_logloss: 0.252449
[400]	valid_0's binary_logloss: 0.251568
Early stopping, best iteration is:
[399]	valid_0's binary_logloss: 0.251566
-------------------- Metrics --------------------
Accuracy: 0.7137
Precision: 0.2329
Recall: 0.7995
F1 Score: 0.3608
ROC AUC: 0.8382
Training fold 2/5...
[400]	valid_0's binary_logloss: 0.254457
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.253073
[600]	valid_0's binary_logloss: 0.252607
[700]	valid_0's binary_logloss: 0.2522
[800]	valid_0's binary_logloss: 0.251918
Early stopping, best iteration is:
[799]	valid_0's binary_logloss: 0.251918
-------------------- Metrics --------------------
Accuracy: 0.7030
Precision: 0.2277
Recall: 0.8005
F1 Score: 0.3546
ROC AUC: 0.8366
Training fold 3/5...
[800]	valid_0's binary_logloss: 0.253801
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.25354
[1000]	valid_0's binary_logloss: 0.253541
Early stopping, best iteration is:
[937]	valid_0's binary_logloss: 0.253447
-------------------- Metrics --------------------
Accuracy: 0.7002
Precision: 0.2276
Recall: 0.8183
F1 Score: 0.3562
ROC AUC: 0.8336
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.253736
[1100]	valid_0's binary_logloss: 0.253604
Early stopping, best iteration is:
[1078]	valid_0's binary_logloss: 0.253504
-------------------- Metrics --------------------
Accuracy: 0.6864
Precision: 0.2218
Recall: 0.8237
F1 Score: 0.3494
ROC AUC: 0.8361
Training final model using all data...
Final model training completed.

In [30]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kawasaki.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_kawasaki",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_kawasaki.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_kawasaki.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_kawasaki.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.267684
[200]	valid_0's binary_logloss: 0.260977
[300]	valid_0's binary_logloss: 0.260028
Early stopping, best iteration is:
[278]	valid_0's binary_logloss: 0.259947
-------------------- Metrics --------------------
Accuracy: 0.6820
Precision: 0.1821
Recall: 0.7303
F1 Score: 0.2915
ROC AUC: 0.7793
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.258724
[400]	valid_0's binary_logloss: 0.256841
[500]	valid_0's binary_logloss: 0.256523
[600]	valid_0's binary_logloss: 0.256562
Early stopping, best iteration is:
[548]	valid_0's binary_logloss: 0.256339
-------------------- Metrics --------------------
Accuracy: 0.6801
Precision: 0.1858
Recall: 0.7538
F1 Score: 0.2982
ROC AUC: 0.7861
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.261914
[700]	valid_0's binary_logloss: 0.261301
[800]	valid_0's binary_logloss: 0.261206
[900]	valid_0's binary_logloss: 0.261305
Early stopping, best iteration is:
[827]	valid_0's binary_logloss: 0.261078
-------------------- Metrics --------------------
Accuracy: 0.6639
Precision: 0.1823
Recall: 0.7716
F1 Score: 0.2949
ROC AUC: 0.7838
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.255979
[1000]	valid_0's binary_logloss: 0.255365
[1100]	valid_0's binary_logloss: 0.254819
Early stopping, best iteration is:
[1092]	valid_0's binary_logloss: 0.254776
-------------------- Metrics --------------------
Accuracy: 0.6564
Precision: 0.1807
Recall: 0.7833
F1 Score: 0.2937
ROC AUC: 0.7942
Training final model using all data...
Final model training completed.

In [31]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kasamatu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_kasamatu",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_kasamatu.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_kasamatu.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_kasamatu.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.297189
[200]	valid_0's binary_logloss: 0.289999
[300]	valid_0's binary_logloss: 0.289218
Early stopping, best iteration is:
[289]	valid_0's binary_logloss: 0.28905
-------------------- Metrics --------------------
Accuracy: 0.6632
Precision: 0.2155
Recall: 0.7784
F1 Score: 0.3376
ROC AUC: 0.7916
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.274049
[400]	valid_0's binary_logloss: 0.272299
[500]	valid_0's binary_logloss: 0.271648
[600]	valid_0's binary_logloss: 0.271634
[700]	valid_0's binary_logloss: 0.272267
Early stopping, best iteration is:
[626]	valid_0's binary_logloss: 0.271532
-------------------- Metrics --------------------
Accuracy: 0.6738
Precision: 0.2187
Recall: 0.7969
F1 Score: 0.3432
ROC AUC: 0.8159
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.285526
[800]	valid_0's binary_logloss: 0.285195
[900]	valid_0's binary_logloss: 0.285066
Early stopping, best iteration is:
[831]	valid_0's binary_logloss: 0.284978
-------------------- Metrics --------------------
Accuracy: 0.6551
Precision: 0.2075
Recall: 0.7862
F1 Score: 0.3283
ROC AUC: 0.7908
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.269404
[1000]	valid_0's binary_logloss: 0.268766
[1100]	valid_0's binary_logloss: 0.26859
[1200]	valid_0's binary_logloss: 0.268444
Early stopping, best iteration is:
[1144]	valid_0's binary_logloss: 0.268367
-------------------- Metrics --------------------
Accuracy: 0.6585
Precision: 0.1964
Recall: 0.7927
F1 Score: 0.3148
ROC AUC: 0.7939
Training final model using all data...
Final model training completed.

In [32]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kanazawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_kanazawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_kanazawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_kanazawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_kanazawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.290806
[200]	valid_0's binary_logloss: 0.277084
[300]	valid_0's binary_logloss: 0.27411
[400]	valid_0's binary_logloss: 0.274172
Early stopping, best iteration is:
[343]	valid_0's binary_logloss: 0.273791
-------------------- Metrics --------------------
Accuracy: 0.6934
Precision: 0.2524
Recall: 0.8239
F1 Score: 0.3864
ROC AUC: 0.8368
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.282222
[500]	valid_0's binary_logloss: 0.279827
[600]	valid_0's binary_logloss: 0.279041
[700]	valid_0's binary_logloss: 0.279304
Early stopping, best iteration is:
[609]	valid_0's binary_logloss: 0.278973
-------------------- Metrics --------------------
Accuracy: 0.6899
Precision: 0.2470
Recall: 0.8179
F1 Score: 0.3794
ROC AUC: 0.8295
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.276054
[800]	valid_0's binary_logloss: 0.275805
[900]	valid_0's binary_logloss: 0.275455
[1000]	valid_0's binary_logloss: 0.27536
[1100]	valid_0's binary_logloss: 0.275431
Early stopping, best iteration is:
[1047]	valid_0's binary_logloss: 0.275256
-------------------- Metrics --------------------
Accuracy: 0.6864
Precision: 0.2487
Recall: 0.8514
F1 Score: 0.3850
ROC AUC: 0.8389
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.264715
[1200]	valid_0's binary_logloss: 0.263991
[1300]	valid_0's binary_logloss: 0.2638
[1400]	valid_0's binary_logloss: 0.263905
Early stopping, best iteration is:
[1377]	valid_0's binary_logloss: 0.26375
-------------------- Metrics --------------------
Accuracy: 0.6841
Precision: 0.2398
Recall: 0.8304
F1 Score: 0.3721
ROC AUC: 0.8420
Training final model using all data...
Final model training completed.

In [33]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_funabasi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_funabasi",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_funabasi.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_funabasi.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_funabasi.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.268079
[200]	valid_0's binary_logloss: 0.260616
[300]	valid_0's binary_logloss: 0.259737
Early stopping, best iteration is:
[263]	valid_0's binary_logloss: 0.259639
-------------------- Metrics --------------------
Accuracy: 0.7088
Precision: 0.2094
Recall: 0.7545
F1 Score: 0.3278
ROC AUC: 0.8012
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.280091
[400]	valid_0's binary_logloss: 0.279259
Early stopping, best iteration is:
[388]	valid_0's binary_logloss: 0.27919
-------------------- Metrics --------------------
Accuracy: 0.6841
Precision: 0.1922
Recall: 0.7102
F1 Score: 0.3025
ROC AUC: 0.7658
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.269441
[500]	valid_0's binary_logloss: 0.267664
[600]	valid_0's binary_logloss: 0.267429
Early stopping, best iteration is:
[576]	valid_0's binary_logloss: 0.267393
-------------------- Metrics --------------------
Accuracy: 0.6597
Precision: 0.1969
Recall: 0.7952
F1 Score: 0.3157
ROC AUC: 0.7928
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.261798
[700]	valid_0's binary_logloss: 0.261035
[800]	valid_0's binary_logloss: 0.260537
[900]	valid_0's binary_logloss: 0.260254
[1000]	valid_0's binary_logloss: 0.260243
Early stopping, best iteration is:
[935]	valid_0's binary_logloss: 0.260138
-------------------- Metrics --------------------
Accuracy: 0.6723
Precision: 0.2024
Recall: 0.7955
F1 Score: 0.3228
ROC AUC: 0.8090
Training final model using all data...
Final model training completed.

In [ ]:
# # オッズと人気を特徴量から省いたランク、日、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv(
    
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_niti_dev_turf_only.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only",
#     model_filename="model_lightgbm_rank_niti_cv_dev_turf_only.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only.pkl",
#     final_num_boost_round = 1000
# )

In [ ]:
# # オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
# evaluator = Evaluator_lightgbm_rank_niti_cross(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only.csv")
# summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only")
# summary_df_noodds_gbm

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_only.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only")
# summary_df_shaft

In [ ]:
# # オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv(
    
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_niti_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt",
#     model_filename="model_lightgbm_rank_niti_cv_dev_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt.pkl",
#     final_num_boost_round = 1200
# )

In [ ]:
# # オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
# evaluator = Evaluator_lightgbm_rank_niti_cross(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
#     return_tables_filename = "return_tables_dirt.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt.csv")
# summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
# summary_df_noodds_gbm

### only_tenkai

In [ ]:
%autoreload

In [34]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight10.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_sonoda.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.291957
[200]	valid_0's binary_logloss: 0.283602
[300]	valid_0's binary_logloss: 0.280252
[400]	valid_0's binary_logloss: 0.278798
[500]	valid_0's binary_logloss: 0.27805
[600]	valid_0's binary_logloss: 0.277883
Early stopping, best iteration is:
[587]	valid_0's binary_logloss: 0.277854
-------------------- Metrics --------------------
Accuracy: 0.6242
Precision: 0.1785
Recall: 0.7791
F1 Score: 0.2904
ROC AUC: 0.7699
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.278814
[700]	valid_0's binary_logloss: 0.277145
[800]	valid_0's binary_logloss: 0.276379
[900]	valid_0's binary_logloss: 0.275833
[1000]	valid_0's binary_logloss: 0.275559
[1100]	valid_0's binary_logloss: 0.275431
[1200]	valid_0's binary_logloss: 0.275245
[1300]	valid_0's binary_logloss: 0.275185
[1400]	valid_0's binary_logloss: 0.275121
Early stopping, best iteration is:
[1391]	valid_0's binary_logloss: 0.27509
-------------------- Metrics --------------------
Accuracy: 0.6223
Precision: 0.1858
Recall: 0.8120
F1 Score: 0.3024
ROC AUC: 0.7848
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.276085
[1500]	valid_0's binary_logloss: 0.275213
[1600]	valid_0's binary_logloss: 0.274997
[1700]	valid_0's binary_logloss: 0.274778
[1800]	valid_0's binary_logloss: 0.274709
[1900]	valid_0's binary_logloss: 0.274633
Early stopping, best iteration is:
[1888]	valid_0's binary_logloss: 0.274555
-------------------- Metrics --------------------
Accuracy: 0.6106
Precision: 0.1881
Recall: 0.8399
F1 Score: 0.3074
ROC AUC: 0.7962
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1900]	valid_0's binary_logloss: 0.272567
[2000]	valid_0's binary_logloss: 0.272109
[2100]	valid_0's binary_logloss: 0.271956
[2200]	valid_0's binary_logloss: 0.271924
[2300]	valid_0's binary_logloss: 0.271842
[2400]	valid_0's binary_logloss: 0.271729
[2500]	valid_0's binary_logloss: 0.271725
Early stopping, best iteration is:
[2447]	valid_0's binary_logloss: 0.271654
-------------------- Metrics --------------------
Accuracy: 0.6324
Precision: 0.1893
Recall: 0.8198
F1 Score: 0.3075
ROC AUC: 0.7935
Training final model using all data...
Final model training completed.

In [35]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_urawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_urawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.27908
[200]	valid_0's binary_logloss: 0.274079
[300]	valid_0's binary_logloss: 0.273236
Early stopping, best iteration is:
[295]	valid_0's binary_logloss: 0.273203
-------------------- Metrics --------------------
Accuracy: 0.6541
Precision: 0.1693
Recall: 0.7103
F1 Score: 0.2734
ROC AUC: 0.7456
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.284239
[400]	valid_0's binary_logloss: 0.279289
[500]	valid_0's binary_logloss: 0.278573
[600]	valid_0's binary_logloss: 0.278395
Early stopping, best iteration is:
[559]	valid_0's binary_logloss: 0.278179
-------------------- Metrics --------------------
Accuracy: 0.6319
Precision: 0.1777
Recall: 0.7784
F1 Score: 0.2893
ROC AUC: 0.7633
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.275792
[700]	valid_0's binary_logloss: 0.275531
Early stopping, best iteration is:
[674]	valid_0's binary_logloss: 0.275417
-------------------- Metrics --------------------
Accuracy: 0.6245
Precision: 0.1703
Recall: 0.7616
F1 Score: 0.2783
ROC AUC: 0.7576
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.27005
[800]	valid_0's binary_logloss: 0.269712
[900]	valid_0's binary_logloss: 0.269685
Early stopping, best iteration is:
[851]	valid_0's binary_logloss: 0.269556
-------------------- Metrics --------------------
Accuracy: 0.6207
Precision: 0.1711
Recall: 0.7912
F1 Score: 0.2814
ROC AUC: 0.7704
Training final model using all data...
Final model training completed.

In [36]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_saga.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_saga.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.281388
[200]	valid_0's binary_logloss: 0.271683
[300]	valid_0's binary_logloss: 0.268214
[400]	valid_0's binary_logloss: 0.266999
[500]	valid_0's binary_logloss: 0.267025
Early stopping, best iteration is:
[429]	valid_0's binary_logloss: 0.266899
-------------------- Metrics --------------------
Accuracy: 0.6924
Precision: 0.2122
Recall: 0.7661
F1 Score: 0.3323
ROC AUC: 0.7989
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.284875
[600]	valid_0's binary_logloss: 0.283348
[700]	valid_0's binary_logloss: 0.282786
[800]	valid_0's binary_logloss: 0.28258
[900]	valid_0's binary_logloss: 0.282573
Early stopping, best iteration is:
[826]	valid_0's binary_logloss: 0.282477
-------------------- Metrics --------------------
Accuracy: 0.6559
Precision: 0.1961
Recall: 0.7619
F1 Score: 0.3119
ROC AUC: 0.7780
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.271701
[1000]	valid_0's binary_logloss: 0.270953
[1100]	valid_0's binary_logloss: 0.270809
Early stopping, best iteration is:
[1077]	valid_0's binary_logloss: 0.270699
-------------------- Metrics --------------------
Accuracy: 0.6503
Precision: 0.1868
Recall: 0.7694
F1 Score: 0.3006
ROC AUC: 0.7816
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.263115
[1200]	valid_0's binary_logloss: 0.262387
[1300]	valid_0's binary_logloss: 0.262126
[1400]	valid_0's binary_logloss: 0.261876
[1500]	valid_0's binary_logloss: 0.261836
Early stopping, best iteration is:
[1476]	valid_0's binary_logloss: 0.261774
-------------------- Metrics --------------------
Accuracy: 0.6558
Precision: 0.1980
Recall: 0.8111
F1 Score: 0.3183
ROC AUC: 0.8076
Training final model using all data...
Final model training completed.

In [37]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_ooi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_ooi.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.246594
[200]	valid_0's binary_logloss: 0.239734
[300]	valid_0's binary_logloss: 0.237378
[400]	valid_0's binary_logloss: 0.236616
Early stopping, best iteration is:
[389]	valid_0's binary_logloss: 0.236585
-------------------- Metrics --------------------
Accuracy: 0.6928
Precision: 0.1660
Recall: 0.7252
F1 Score: 0.2702
ROC AUC: 0.7786
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.239902
[500]	valid_0's binary_logloss: 0.238868
[600]	valid_0's binary_logloss: 0.238619
[700]	valid_0's binary_logloss: 0.238546
[800]	valid_0's binary_logloss: 0.238533
Early stopping, best iteration is:
[755]	valid_0's binary_logloss: 0.23844
-------------------- Metrics --------------------
Accuracy: 0.6911
Precision: 0.1714
Recall: 0.7352
F1 Score: 0.2780
ROC AUC: 0.7844
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.245424
[900]	valid_0's binary_logloss: 0.245142
[1000]	valid_0's binary_logloss: 0.245062
Early stopping, best iteration is:
[976]	valid_0's binary_logloss: 0.245011
-------------------- Metrics --------------------
Accuracy: 0.6790
Precision: 0.1714
Recall: 0.7465
F1 Score: 0.2788
ROC AUC: 0.7783
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.239545
[1100]	valid_0's binary_logloss: 0.239186
[1200]	valid_0's binary_logloss: 0.239023
[1300]	valid_0's binary_logloss: 0.239004
[1400]	valid_0's binary_logloss: 0.238881
[1500]	valid_0's binary_logloss: 0.23895
Early stopping, best iteration is:
[1409]	valid_0's binary_logloss: 0.238855
-------------------- Metrics --------------------
Accuracy: 0.6890
Precision: 0.1774
Recall: 0.7632
F1 Score: 0.2879
ROC AUC: 0.7952
Training final model using all data...
Final model training completed.

In [38]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_nagoya.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_nagoya.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.292022
[200]	valid_0's binary_logloss: 0.284174
[300]	valid_0's binary_logloss: 0.281919
[400]	valid_0's binary_logloss: 0.281683
Early stopping, best iteration is:
[372]	valid_0's binary_logloss: 0.28166
-------------------- Metrics --------------------
Accuracy: 0.6466
Precision: 0.1906
Recall: 0.7759
F1 Score: 0.3061
ROC AUC: 0.7729
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.265756
[500]	valid_0's binary_logloss: 0.264088
[600]	valid_0's binary_logloss: 0.263336
[700]	valid_0's binary_logloss: 0.262939
[800]	valid_0's binary_logloss: 0.26263
[900]	valid_0's binary_logloss: 0.262455
Early stopping, best iteration is:
[884]	valid_0's binary_logloss: 0.262402
-------------------- Metrics --------------------
Accuracy: 0.6708
Precision: 0.1882
Recall: 0.7607
F1 Score: 0.3018
ROC AUC: 0.7899
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.261383
[1000]	valid_0's binary_logloss: 0.259924
[1100]	valid_0's binary_logloss: 0.25922
[1200]	valid_0's binary_logloss: 0.259133
[1300]	valid_0's binary_logloss: 0.259058
[1400]	valid_0's binary_logloss: 0.258963
Early stopping, best iteration is:
[1377]	valid_0's binary_logloss: 0.258909
-------------------- Metrics --------------------
Accuracy: 0.6706
Precision: 0.1888
Recall: 0.7812
F1 Score: 0.3042
ROC AUC: 0.7916
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.257901
[1500]	valid_0's binary_logloss: 0.257221
[1600]	valid_0's binary_logloss: 0.257009
[1700]	valid_0's binary_logloss: 0.256744
[1800]	valid_0's binary_logloss: 0.256742
Early stopping, best iteration is:
[1712]	valid_0's binary_logloss: 0.256698
-------------------- Metrics --------------------
Accuracy: 0.6635
Precision: 0.1786
Recall: 0.7606
F1 Score: 0.2892
ROC AUC: 0.7828
Training final model using all data...
Final model training completed.

In [39]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_morioka.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_morioka.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.304136
[200]	valid_0's binary_logloss: 0.297043
[300]	valid_0's binary_logloss: 0.295872
Early stopping, best iteration is:
[292]	valid_0's binary_logloss: 0.295769
-------------------- Metrics --------------------
Accuracy: 0.6439
Precision: 0.2017
Recall: 0.7538
F1 Score: 0.3182
ROC AUC: 0.7761
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.283369
[400]	valid_0's binary_logloss: 0.280683
[500]	valid_0's binary_logloss: 0.280215
[600]	valid_0's binary_logloss: 0.280107
Early stopping, best iteration is:
[569]	valid_0's binary_logloss: 0.279999
-------------------- Metrics --------------------
Accuracy: 0.6342
Precision: 0.1992
Recall: 0.8011
F1 Score: 0.3190
ROC AUC: 0.7964
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.294493
[700]	valid_0's binary_logloss: 0.293573
[800]	valid_0's binary_logloss: 0.293029
[900]	valid_0's binary_logloss: 0.29287
Early stopping, best iteration is:
[847]	valid_0's binary_logloss: 0.292805
-------------------- Metrics --------------------
Accuracy: 0.6164
Precision: 0.1895
Recall: 0.7862
F1 Score: 0.3054
ROC AUC: 0.7688
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.283318
[1000]	valid_0's binary_logloss: 0.28254
[1100]	valid_0's binary_logloss: 0.282245
[1200]	valid_0's binary_logloss: 0.282221
[1300]	valid_0's binary_logloss: 0.281978
[1400]	valid_0's binary_logloss: 0.282021
Early stopping, best iteration is:
[1389]	valid_0's binary_logloss: 0.281926
-------------------- Metrics --------------------
Accuracy: 0.6413
Precision: 0.1830
Recall: 0.7576
F1 Score: 0.2948
ROC AUC: 0.7638
Training final model using all data...
Final model training completed.

In [40]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_mizusawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_mizusawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.309431
[200]	valid_0's binary_logloss: 0.302381
[300]	valid_0's binary_logloss: 0.301054
[400]	valid_0's binary_logloss: 0.301257
Early stopping, best iteration is:
[340]	valid_0's binary_logloss: 0.30067
-------------------- Metrics --------------------
Accuracy: 0.6021
Precision: 0.1785
Recall: 0.7562
F1 Score: 0.2889
ROC AUC: 0.7443
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.299932
[500]	valid_0's binary_logloss: 0.297866
[600]	valid_0's binary_logloss: 0.297166
[700]	valid_0's binary_logloss: 0.296955
Early stopping, best iteration is:
[685]	valid_0's binary_logloss: 0.296905
-------------------- Metrics --------------------
Accuracy: 0.5715
Precision: 0.1724
Recall: 0.8025
F1 Score: 0.2839
ROC AUC: 0.7484
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.291908
[800]	valid_0's binary_logloss: 0.291863
Early stopping, best iteration is:
[761]	valid_0's binary_logloss: 0.291697
-------------------- Metrics --------------------
Accuracy: 0.5802
Precision: 0.1755
Recall: 0.8025
F1 Score: 0.2881
ROC AUC: 0.7647
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.274443
[900]	valid_0's binary_logloss: 0.273636
[1000]	valid_0's binary_logloss: 0.273147
[1100]	valid_0's binary_logloss: 0.273092
[1200]	valid_0's binary_logloss: 0.272821
[1300]	valid_0's binary_logloss: 0.272552
[1400]	valid_0's binary_logloss: 0.272449
[1500]	valid_0's binary_logloss: 0.272315
[1600]	valid_0's binary_logloss: 0.272459
Early stopping, best iteration is:
[1501]	valid_0's binary_logloss: 0.272292
-------------------- Metrics --------------------
Accuracy: 0.6211
Precision: 0.1849
Recall: 0.8138
F1 Score: 0.3013
ROC AUC: 0.7897
Training final model using all data...
Final model training completed.

In [41]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kouti.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kouti.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.28168
[200]	valid_0's binary_logloss: 0.27074
[300]	valid_0's binary_logloss: 0.266449
[400]	valid_0's binary_logloss: 0.264845
[500]	valid_0's binary_logloss: 0.264239
[600]	valid_0's binary_logloss: 0.264476
Early stopping, best iteration is:
[507]	valid_0's binary_logloss: 0.264164
-------------------- Metrics --------------------
Accuracy: 0.6853
Precision: 0.2115
Recall: 0.7751
F1 Score: 0.3323
ROC AUC: 0.8067
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.267588
[700]	valid_0's binary_logloss: 0.267248
[800]	valid_0's binary_logloss: 0.26718
[900]	valid_0's binary_logloss: 0.267164
Early stopping, best iteration is:
[848]	valid_0's binary_logloss: 0.267104
-------------------- Metrics --------------------
Accuracy: 0.6662
Precision: 0.2064
Recall: 0.7997
F1 Score: 0.3281
ROC AUC: 0.8063
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.268846
[1000]	valid_0's binary_logloss: 0.268658
Early stopping, best iteration is:
[961]	valid_0's binary_logloss: 0.268617
-------------------- Metrics --------------------
Accuracy: 0.6604
Precision: 0.2024
Recall: 0.7994
F1 Score: 0.3230
ROC AUC: 0.8005
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.266752
[1100]	valid_0's binary_logloss: 0.266149
[1200]	valid_0's binary_logloss: 0.265778
[1300]	valid_0's binary_logloss: 0.265375
[1400]	valid_0's binary_logloss: 0.265346
[1500]	valid_0's binary_logloss: 0.265356
Early stopping, best iteration is:
[1409]	valid_0's binary_logloss: 0.265298
-------------------- Metrics --------------------
Accuracy: 0.6699
Precision: 0.2094
Recall: 0.8027
F1 Score: 0.3321
ROC AUC: 0.8100
Training final model using all data...
Final model training completed.

In [42]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kawasaki.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kawasaki.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.272357
[200]	valid_0's binary_logloss: 0.266385
[300]	valid_0's binary_logloss: 0.264553
[400]	valid_0's binary_logloss: 0.264537
Early stopping, best iteration is:
[346]	valid_0's binary_logloss: 0.264287
-------------------- Metrics --------------------
Accuracy: 0.6614
Precision: 0.1700
Recall: 0.7161
F1 Score: 0.2748
ROC AUC: 0.7606
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.265028
[500]	valid_0's binary_logloss: 0.264144
[600]	valid_0's binary_logloss: 0.264071
Early stopping, best iteration is:
[574]	valid_0's binary_logloss: 0.263995
-------------------- Metrics --------------------
Accuracy: 0.6398
Precision: 0.1660
Recall: 0.7449
F1 Score: 0.2716
ROC AUC: 0.7622
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.264403
[700]	valid_0's binary_logloss: 0.264652
Early stopping, best iteration is:
[636]	valid_0's binary_logloss: 0.264285
-------------------- Metrics --------------------
Accuracy: 0.6334
Precision: 0.1700
Recall: 0.7792
F1 Score: 0.2791
ROC AUC: 0.7715
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.258012
[800]	valid_0's binary_logloss: 0.25767
[900]	valid_0's binary_logloss: 0.257544
Early stopping, best iteration is:
[873]	valid_0's binary_logloss: 0.257442
-------------------- Metrics --------------------
Accuracy: 0.6331
Precision: 0.1710
Recall: 0.7858
F1 Score: 0.2809
ROC AUC: 0.7829
Training final model using all data...
Final model training completed.

In [43]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kasamatu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kasamatu.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.304136
[200]	valid_0's binary_logloss: 0.297043
[300]	valid_0's binary_logloss: 0.295872
Early stopping, best iteration is:
[292]	valid_0's binary_logloss: 0.295769
-------------------- Metrics --------------------
Accuracy: 0.6439
Precision: 0.2017
Recall: 0.7538
F1 Score: 0.3182
ROC AUC: 0.7761
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.283369
[400]	valid_0's binary_logloss: 0.280683
[500]	valid_0's binary_logloss: 0.280215
[600]	valid_0's binary_logloss: 0.280107
Early stopping, best iteration is:
[569]	valid_0's binary_logloss: 0.279999
-------------------- Metrics --------------------
Accuracy: 0.6342
Precision: 0.1992
Recall: 0.8011
F1 Score: 0.3190
ROC AUC: 0.7964
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.294493
[700]	valid_0's binary_logloss: 0.293573
[800]	valid_0's binary_logloss: 0.293029
[900]	valid_0's binary_logloss: 0.29287
Early stopping, best iteration is:
[847]	valid_0's binary_logloss: 0.292805
-------------------- Metrics --------------------
Accuracy: 0.6164
Precision: 0.1895
Recall: 0.7862
F1 Score: 0.3054
ROC AUC: 0.7688
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.283318
[1000]	valid_0's binary_logloss: 0.28254
[1100]	valid_0's binary_logloss: 0.282245
[1200]	valid_0's binary_logloss: 0.282221
[1300]	valid_0's binary_logloss: 0.281978
[1400]	valid_0's binary_logloss: 0.282021
Early stopping, best iteration is:
[1389]	valid_0's binary_logloss: 0.281926
-------------------- Metrics --------------------
Accuracy: 0.6413
Precision: 0.1830
Recall: 0.7576
F1 Score: 0.2948
ROC AUC: 0.7638
Training final model using all data...
Final model training completed.

In [44]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_kanazawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kanazawa.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.305378
[200]	valid_0's binary_logloss: 0.290913
[300]	valid_0's binary_logloss: 0.286235
[400]	valid_0's binary_logloss: 0.284617
[500]	valid_0's binary_logloss: 0.284834
Early stopping, best iteration is:
[464]	valid_0's binary_logloss: 0.284449
-------------------- Metrics --------------------
Accuracy: 0.6796
Precision: 0.2439
Recall: 0.8259
F1 Score: 0.3766
ROC AUC: 0.8244
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.292182
[600]	valid_0's binary_logloss: 0.290701
[700]	valid_0's binary_logloss: 0.290259
[800]	valid_0's binary_logloss: 0.290204
Early stopping, best iteration is:
[765]	valid_0's binary_logloss: 0.290077
-------------------- Metrics --------------------
Accuracy: 0.6511
Precision: 0.2232
Recall: 0.8109
F1 Score: 0.3501
ROC AUC: 0.8063
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.287849
[900]	valid_0's binary_logloss: 0.287247
[1000]	valid_0's binary_logloss: 0.286944
[1100]	valid_0's binary_logloss: 0.28671
[1200]	valid_0's binary_logloss: 0.286747
Early stopping, best iteration is:
[1166]	valid_0's binary_logloss: 0.286707
-------------------- Metrics --------------------
Accuracy: 0.6392
Precision: 0.2191
Recall: 0.8301
F1 Score: 0.3466
ROC AUC: 0.8150
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.284817
[1300]	valid_0's binary_logloss: 0.283582
[1400]	valid_0's binary_logloss: 0.283153
[1500]	valid_0's binary_logloss: 0.283005
Early stopping, best iteration is:
[1497]	valid_0's binary_logloss: 0.282975
-------------------- Metrics --------------------
Accuracy: 0.6633
Precision: 0.2238
Recall: 0.8046
F1 Score: 0.3501
ROC AUC: 0.8104
Training final model using all data...
Final model training completed.

In [45]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_funabasi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_funabasi.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.276105
[200]	valid_0's binary_logloss: 0.269835
[300]	valid_0's binary_logloss: 0.268447
[400]	valid_0's binary_logloss: 0.268495
Early stopping, best iteration is:
[333]	valid_0's binary_logloss: 0.268258
-------------------- Metrics --------------------
Accuracy: 0.7035
Precision: 0.2009
Recall: 0.7225
F1 Score: 0.3144
ROC AUC: 0.7823
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.280258
[500]	valid_0's binary_logloss: 0.27929
[600]	valid_0's binary_logloss: 0.279059
[700]	valid_0's binary_logloss: 0.279038
Early stopping, best iteration is:
[651]	valid_0's binary_logloss: 0.278887
-------------------- Metrics --------------------
Accuracy: 0.6642
Precision: 0.1829
Recall: 0.7156
F1 Score: 0.2913
ROC AUC: 0.7594
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.276646
[800]	valid_0's binary_logloss: 0.276366
Early stopping, best iteration is:
[778]	valid_0's binary_logloss: 0.276275
-------------------- Metrics --------------------
Accuracy: 0.6404
Precision: 0.1850
Recall: 0.7766
F1 Score: 0.2989
ROC AUC: 0.7731
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.272139
[900]	valid_0's binary_logloss: 0.272115
Early stopping, best iteration is:
[887]	valid_0's binary_logloss: 0.272028
-------------------- Metrics --------------------
Accuracy: 0.6399
Precision: 0.1840
Recall: 0.7767
F1 Score: 0.2975
ROC AUC: 0.7826
Training final model using all data...
Final model training completed.

In [46]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_monbetu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_monbetu.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.287347
[200]	valid_0's binary_logloss: 0.276214
[300]	valid_0's binary_logloss: 0.2724
[400]	valid_0's binary_logloss: 0.271313
[500]	valid_0's binary_logloss: 0.271224
Early stopping, best iteration is:
[439]	valid_0's binary_logloss: 0.270961
-------------------- Metrics --------------------
Accuracy: 0.6457
Precision: 0.2031
Recall: 0.8217
F1 Score: 0.3258
ROC AUC: 0.8091
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.282396
[600]	valid_0's binary_logloss: 0.281687
[700]	valid_0's binary_logloss: 0.281347
[800]	valid_0's binary_logloss: 0.28124
Early stopping, best iteration is:
[787]	valid_0's binary_logloss: 0.281153
-------------------- Metrics --------------------
Accuracy: 0.6362
Precision: 0.2035
Recall: 0.8270
F1 Score: 0.3267
ROC AUC: 0.7972
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.26872
[900]	valid_0's binary_logloss: 0.268746
Early stopping, best iteration is:
[864]	valid_0's binary_logloss: 0.268622
-------------------- Metrics --------------------
Accuracy: 0.6400
Precision: 0.1956
Recall: 0.8310
F1 Score: 0.3167
ROC AUC: 0.8048
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.273148
[1000]	valid_0's binary_logloss: 0.272872
[1100]	valid_0's binary_logloss: 0.272597
[1200]	valid_0's binary_logloss: 0.272471
Early stopping, best iteration is:
[1142]	valid_0's binary_logloss: 0.272391
-------------------- Metrics --------------------
Accuracy: 0.6520
Precision: 0.2012
Recall: 0.8117
F1 Score: 0.3225
ROC AUC: 0.8002
Training final model using all data...
Final model training completed.

In [11]:
%autoreload

In [215]:
#評価

In [12]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_sonoda.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_sonoda")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_sonoda,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_sonoda,hitrate_pop,returnrate_pop
0,1,単勝,0.153252,0.756530,0.202860,0.733915
1,1,複勝,0.491708,0.803216,0.578428,0.795202
2,2,ワイド,0.170337,0.800734,0.249810,0.796975
3,2,単勝,0.267274,0.785358,0.329031,0.730087
4,2,複勝,0.735663,0.782238,0.815166,0.780757
5,2,馬単,0.047456,0.791762,0.076310,0.758498
6,2,馬連,0.047456,0.750835,0.076310,0.761010
7,3,ワイド,0.373956,0.808888,0.484055,0.760719
8,3,三連単,0.022779,0.964779,0.034169,0.695470
9,3,三連複,0.022779,0.884358,0.034169,0.685447
10,3,単勝,0.358264,0.794731,0.418249,0.758998
11,3,複勝,0.868338,0.780567,0.921762,0.760611
12,3,馬単,0.110099,0.767392,0.151987,0.717979
13,3,馬連,0.110099,0.720725,0.151987,0.698979
14,4,ワイド,0.554923,0.785588,0.672235,0.737081
15,4,三連単,0.062136,0.840458,0.082258,0.619246
16,4,三連複,0.062136,0.792878,0.082258,0.602904
17,4,単勝,0.421792,0.782704,0.472539,0.749567
18,4,複勝,0.936448,0.766325,0.967338,0.743680
19,4,馬単,0.175652,0.730026,0.220071,0.684962
20,4,馬連,0.175652,0.706290,0.220071,0.665802
21,5,ワイド,0.707163,0.741202,0.803721,0.713185
22,5,三連単,0.101873,0.703683,0.129841,0.611336
23,5,三連複,0.101873,0.656884,0.129841,0.565877
24,5,単勝,0.471147,0.774725,0.509997,0.756358
25,5,複勝,0.973794,0.748583,0.987847,0.728852
26,5,馬単,0.227284,0.673098,0.271071,0.667328
27,5,馬連,0.227284,0.648145,0.271071,0.640657

In [90]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_urawa.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_urawa")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_urawa,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_urawa,hitrate_pop,returnrate_pop
0,1,単勝,0.214660,0.696335,0.267016,0.595812
1,1,複勝,0.596859,0.890052,0.664921,0.853403
2,2,ワイド,0.308901,1.176440,0.329843,0.757592
3,2,単勝,0.413613,0.772775,0.481675,0.703927
4,2,複勝,0.785340,0.868325,0.869110,0.815445
5,2,馬単,0.130890,1.136126,0.141361,0.736126
6,2,馬連,0.130890,1.095812,0.141361,0.688482
7,3,ワイド,0.534031,0.961955,0.570681,0.808726
8,3,三連単,0.099476,0.789442,0.136126,1.076178
9,3,三連複,0.099476,0.852356,0.136126,0.936649
10,3,単勝,0.544503,0.797208,0.633508,0.751309
11,3,複勝,0.916230,0.884991,0.989529,0.851134
12,3,馬単,0.261780,0.738569,0.371728,0.881501
13,3,馬連,0.261780,0.742583,0.371728,0.856370
14,4,ワイド,0.738220,0.877749,0.801047,0.858639
15,4,三連単,0.204188,0.670877,0.298429,0.796401
16,4,三連複,0.204188,0.656937,0.298429,0.790969
17,4,単勝,0.659686,0.860733,0.748691,0.792932
18,4,複勝,0.958115,0.853403,0.989529,0.841885
19,4,馬単,0.408377,0.718630,0.539267,0.852705
20,4,馬連,0.408377,0.691012,0.539267,0.832548
21,5,ワイド,0.827225,0.821047,0.895288,0.812251
22,5,三連単,0.350785,0.595436,0.450262,0.834127
23,5,三連複,0.350785,0.600838,0.450262,0.865707
24,5,単勝,0.717277,0.777277,0.832461,0.828901
25,5,複勝,0.989529,0.821152,0.994764,0.797801
26,5,馬単,0.523560,0.637330,0.654450,0.780000
27,5,馬連,0.523560,0.630785,0.654450,0.744188

In [91]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_saga.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_saga")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_saga,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_saga,hitrate_pop,returnrate_pop
0,1,単勝,0.175,0.375000,0.450,0.725000
1,1,複勝,0.600,0.807500,0.775,0.847500
2,2,ワイド,0.350,0.757500,0.600,0.970000
3,2,単勝,0.475,0.583750,0.725,0.837500
4,2,複勝,0.775,0.757500,0.875,0.887500
5,2,馬単,0.125,0.577500,0.250,0.637500
6,2,馬連,0.125,0.630000,0.250,0.665000
7,3,ワイド,0.600,0.758333,0.725,0.660000
8,3,三連単,0.075,1.452083,0.150,0.282500
9,3,三連複,0.075,1.192500,0.150,0.575000
10,3,単勝,0.575,0.532500,0.850,0.867500
11,3,複勝,0.850,0.741667,0.975,0.795833
12,3,馬単,0.275,0.697500,0.450,0.497083
13,3,馬連,0.275,0.774167,0.450,0.558333
14,4,ワイド,0.750,0.635000,0.950,0.832917
15,4,三連単,0.250,0.594792,0.375,0.649375
16,4,三連複,0.250,0.613125,0.375,0.701875
17,4,単勝,0.725,0.620000,0.875,0.718125
18,4,複勝,0.975,0.743750,0.975,0.831250
19,4,馬単,0.400,0.481875,0.650,0.685208
20,4,馬連,0.400,0.554167,0.650,0.779583
21,5,ワイド,0.825,0.686500,1.000,0.856750
22,5,三連単,0.425,1.405833,0.600,1.350417
23,5,三連複,0.425,1.015250,0.600,1.178000
24,5,単勝,0.800,0.603000,0.900,0.655500
25,5,複勝,0.975,0.734000,1.000,0.823500
26,5,馬単,0.575,0.922250,0.750,0.834000
27,5,馬連,0.575,0.909000,0.750,0.874250

In [92]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_ooi.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_ooi")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_ooi,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_ooi,hitrate_pop,returnrate_pop
0,1,単勝,0.237624,0.755446,0.356436,0.792079
1,1,複勝,0.554455,0.831683,0.693069,0.876238
2,2,ワイド,0.237624,0.609901,0.405941,0.882178
3,2,単勝,0.356436,0.568317,0.584158,0.837624
4,2,複勝,0.712871,0.716337,0.910891,0.886139
5,2,馬単,0.089109,0.507921,0.207921,0.825743
6,2,馬連,0.089109,0.522772,0.207921,0.890099
7,3,ワイド,0.445545,0.716172,0.663366,0.772277
8,3,三連単,0.089109,0.800000,0.089109,0.422772
9,3,三連複,0.089109,0.799010,0.089109,0.544554
10,3,単勝,0.495050,0.579538,0.693069,0.766007
11,3,複勝,0.871287,0.746865,0.960396,0.823762
12,3,馬単,0.227723,0.497030,0.346535,0.644719
13,3,馬連,0.227723,0.586469,0.346535,0.665017
14,4,ワイド,0.623762,0.774752,0.792079,0.787624
15,4,三連単,0.188119,1.025371,0.306931,0.765264
16,4,三連複,0.188119,1.011881,0.306931,0.828218
17,4,単勝,0.613861,0.679703,0.821782,0.803713
18,4,複勝,0.930693,0.782178,0.980198,0.794554
19,4,馬単,0.396040,0.736799,0.514851,0.691172
20,4,馬連,0.396040,0.755446,0.514851,0.688779
21,5,ワイド,0.732673,0.860594,0.861386,0.736931
22,5,三連単,0.346535,1.018251,0.475248,0.708135
23,5,三連複,0.346535,0.977129,0.475248,0.708317
24,5,単勝,0.712871,0.698020,0.871287,0.765743
25,5,複勝,0.960396,0.800198,0.990099,0.765149
26,5,馬単,0.554455,0.755891,0.683168,0.774406
27,5,馬連,0.554455,0.803564,0.683168,0.777723

In [223]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_nagoya.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_nagoya")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_nagoya,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_nagoya,hitrate_pop,returnrate_pop
0,1,単勝,0.279070,0.768605,0.348837,0.582558
1,1,複勝,0.593023,0.796512,0.755814,0.868605
2,2,ワイド,0.313953,0.946512,0.406977,0.695349
3,2,単勝,0.453488,0.758140,0.604651,0.757558
4,2,複勝,0.837209,0.837791,0.930233,0.827907
5,2,馬単,0.151163,1.026163,0.267442,0.824419
6,2,馬連,0.151163,1.023256,0.267442,0.890698
7,3,ワイド,0.569767,1.052326,0.697674,0.782558
8,3,三連単,0.081395,0.286822,0.139535,0.843411
9,3,三連複,0.081395,0.623256,0.139535,0.675581
10,3,単勝,0.674419,1.065116,0.720930,0.725194
11,3,複勝,0.965116,0.872481,0.988372,0.823256
12,3,馬単,0.313953,1.740116,0.465116,0.947481
13,3,馬連,0.313953,1.877519,0.465116,0.951163
14,4,ワイド,0.744186,0.834690,0.872093,0.896318
15,4,三連単,0.220930,0.357364,0.360465,0.998353
16,4,三連複,0.220930,0.477326,0.360465,1.046802
17,4,単勝,0.790698,0.960465,0.802326,0.776744
18,4,複勝,0.988372,0.784884,1.000000,0.838663
19,4,馬単,0.476744,1.157752,0.651163,0.982558
20,4,馬連,0.476744,1.193798,0.651163,0.936628
21,5,ワイド,0.825581,0.735465,0.918605,0.873721
22,5,三連単,0.348837,0.578488,0.604651,0.921047
23,5,三連複,0.348837,0.638953,0.604651,0.917209
24,5,単勝,0.790698,0.768372,0.860465,0.786977
25,5,複勝,1.000000,0.763721,1.000000,0.812791
26,5,馬単,0.558140,0.815174,0.779070,0.838314
27,5,馬連,0.558140,0.821977,0.779070,0.769767

In [224]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_morioka.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_morioka")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_morioka,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_morioka,hitrate_pop,returnrate_pop
0,1,単勝,0.285714,0.514286,0.380952,0.619048
1,1,複勝,0.619048,0.871429,0.714286,0.795238
2,2,ワイド,0.238095,0.495238,0.476190,0.752381
3,2,単勝,0.380952,0.471429,0.666667,0.802381
4,2,複勝,0.857143,0.821429,1.000000,0.919048
5,2,馬単,0.047619,0.159524,0.190476,0.588095
6,2,馬連,0.047619,0.304762,0.190476,0.642857
7,3,ワイド,0.380952,0.768254,0.857143,0.879365
8,3,三連単,0.190476,0.664286,0.142857,0.420635
9,3,三連複,0.190476,1.004762,0.142857,0.380952
10,3,単勝,0.523810,0.514286,0.761905,0.663492
11,3,複勝,0.952381,0.742857,1.000000,0.893651
12,3,馬単,0.238095,0.511111,0.333333,0.388095
13,3,馬連,0.238095,0.560317,0.333333,0.393651
14,4,ワイド,0.809524,0.847619,0.952381,0.801587
15,4,三連単,0.285714,0.343056,0.380952,0.583135
16,4,三連複,0.285714,0.603571,0.380952,0.783333
17,4,単勝,0.714286,0.515476,0.809524,0.566667
18,4,複勝,1.000000,0.796429,1.000000,0.828571
19,4,馬単,0.571429,0.843651,0.523810,0.457143
20,4,馬連,0.571429,0.978571,0.523810,0.493651
21,5,ワイド,0.857143,0.588095,0.952381,0.810476
22,5,三連単,0.333333,0.163492,0.619048,0.755476
23,5,三連複,0.333333,0.260476,0.619048,0.942381
24,5,単勝,0.761905,0.467619,0.857143,0.521905
25,5,複勝,1.000000,0.684762,1.000000,0.768571
26,5,馬単,0.619048,0.540952,0.714286,0.584048
27,5,馬連,0.619048,0.616667,0.714286,0.677143

In [225]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_monbetu.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_monbetu")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_monbetu,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_monbetu,hitrate_pop,returnrate_pop
0,1,単勝,0.382353,0.702941,0.500000,0.776471
1,1,複勝,0.529412,0.608824,0.882353,1.005882
2,2,ワイド,0.470588,0.800000,0.647059,1.008824
3,2,単勝,0.647059,0.779412,0.794118,0.913235
4,2,複勝,0.941176,0.816176,0.970588,0.933824
5,2,馬単,0.235294,0.611765,0.441176,1.398529
6,2,馬連,0.235294,0.697059,0.441176,1.361765
7,3,ワイド,0.823529,1.056863,0.911765,0.947059
8,3,三連単,0.264706,0.893137,0.294118,0.816667
9,3,三連複,0.264706,1.017647,0.294118,0.926471
10,3,単勝,0.852941,0.848039,0.882353,0.785294
11,3,複勝,0.970588,0.880392,1.000000,0.869608
12,3,馬単,0.470588,0.669118,0.676471,0.846078
13,3,馬連,0.470588,0.631373,0.676471,0.837255
14,4,ワイド,0.941176,1.298529,1.000000,0.921569
15,4,三連単,0.676471,1.410662,0.647059,1.563971
16,4,三連複,0.676471,2.058088,0.647059,1.079412
17,4,単勝,0.911765,0.761029,0.941176,0.815441
18,4,複勝,0.970588,0.896324,1.000000,0.816912
19,4,馬単,0.735294,0.640931,0.852941,1.265196
20,4,馬連,0.735294,0.625490,0.852941,0.991176
21,5,ワイド,0.941176,0.976765,1.000000,0.885588
22,5,三連単,0.823529,0.749265,0.823529,0.885000
23,5,三連複,0.823529,1.111176,0.823529,0.884118
24,5,単勝,0.941176,0.633529,1.000000,0.797647
25,5,複勝,1.000000,0.760000,1.000000,0.772353
26,5,馬単,0.823529,0.433235,0.941176,0.881324
27,5,馬連,0.823529,0.427353,0.941176,0.690588

In [226]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_mizusawa.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_mizusawa")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_mizusawa,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_mizusawa,hitrate_pop,returnrate_pop
0,1,単勝,0.32,0.948000,0.52,0.976000
1,1,複勝,0.56,0.760000,0.76,0.912000
2,2,ワイド,0.24,0.992000,0.40,0.604000
3,2,単勝,0.56,1.026000,0.68,0.888000
4,2,複勝,0.76,0.768000,0.88,0.776000
5,2,馬単,0.08,0.856000,0.16,0.568000
6,2,馬連,0.08,0.692000,0.16,0.452000
7,3,ワイド,0.44,0.689333,0.60,0.609333
8,3,三連単,0.12,0.695333,0.16,0.731333
9,3,三連複,0.12,0.964000,0.16,0.664000
10,3,単勝,0.64,0.765333,0.80,0.809333
11,3,複勝,0.88,0.708000,0.96,0.733333
12,3,馬単,0.20,0.445333,0.36,0.700000
13,3,馬連,0.20,0.368000,0.36,0.642667
14,4,ワイド,0.64,0.642000,0.88,0.652667
15,4,三連単,0.16,0.255167,0.28,0.313667
16,4,三連複,0.16,0.332000,0.28,0.371000
17,4,単勝,0.80,0.866000,0.88,0.764000
18,4,複勝,1.00,0.748000,1.00,0.808000
19,4,馬単,0.32,0.785000,0.56,0.936667
20,4,馬連,0.32,0.705333,0.56,0.954000
21,5,ワイド,0.88,0.710800,0.96,0.859200
22,5,三連単,0.40,0.436733,0.64,0.523267
23,5,三連複,0.40,0.459200,0.64,0.699600
24,5,単勝,0.92,0.744000,0.92,0.694400
25,5,複勝,1.00,0.788000,1.00,0.896000
26,5,馬単,0.60,0.657200,0.84,0.815400
27,5,馬連,0.60,0.683200,0.84,0.896000

In [227]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_kouti.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kouti")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kouti,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kouti,hitrate_pop,returnrate_pop
0,1,単勝,0.50000,1.262500,0.46875,0.662500
1,1,複勝,0.78125,0.915625,0.78125,0.850000
2,2,ワイド,0.40625,0.784375,0.53125,0.837500
3,2,単勝,0.62500,0.767188,0.71875,0.762500
4,2,複勝,0.90625,0.862500,0.87500,0.825000
5,2,馬単,0.25000,0.865625,0.31250,0.662500
6,2,馬連,0.25000,0.887500,0.31250,0.725000
7,3,ワイド,0.59375,0.621875,0.75000,0.705208
8,3,三連単,0.12500,0.135937,0.15625,0.206250
9,3,三連複,0.12500,0.309375,0.15625,0.490625
10,3,単勝,0.71875,0.598958,0.81250,0.719792
11,3,複勝,0.96875,0.757292,1.00000,0.805208
12,3,馬単,0.31250,0.328646,0.43750,0.438021
13,3,馬連,0.31250,0.352083,0.43750,0.429167
14,4,ワイド,0.75000,0.612500,0.87500,0.777083
15,4,三連単,0.25000,0.173177,0.34375,0.455339
16,4,三連複,0.25000,0.410156,0.34375,0.681250
17,4,単勝,0.75000,0.473438,0.87500,0.649219
18,4,複勝,0.96875,0.718750,1.00000,0.778906
19,4,馬単,0.43750,0.247396,0.56250,0.404427
20,4,馬連,0.43750,0.300000,0.56250,0.409896
21,5,ワイド,0.75000,1.302812,0.93750,0.748437
22,5,三連単,0.43750,1.714740,0.53125,0.730469
23,5,三連複,0.43750,1.525625,0.53125,0.764687
24,5,単勝,0.75000,0.378750,0.90625,0.596875
25,5,複勝,1.00000,0.796875,1.00000,0.758125
26,5,馬単,0.53125,0.661875,0.71875,0.706562
27,5,馬連,0.53125,0.783750,0.71875,0.701562

In [228]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_kawasaki.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kawasaki")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kawasaki,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kawasaki,hitrate_pop,returnrate_pop
0,1,単勝,0.325103,0.945267,0.378601,0.812757
1,1,複勝,0.654321,0.984774,0.670782,0.829630
2,2,ワイド,0.267490,0.894650,0.316872,0.703704
3,2,単勝,0.493827,0.923868,0.555556,0.755967
4,2,複勝,0.839506,0.881893,0.880658,0.816255
5,2,馬単,0.123457,0.887860,0.144033,0.608848
6,2,馬連,0.123457,0.951440,0.144033,0.601235
7,3,ワイド,0.539095,0.889712,0.646091,0.890809
8,3,三連単,0.065844,0.601097,0.111111,0.834774
9,3,三連複,0.065844,0.791358,0.111111,1.005761
10,3,単勝,0.621399,0.838820,0.707819,0.818519
11,3,複勝,0.909465,0.846639,0.958848,0.858162
12,3,馬単,0.275720,0.786008,0.358025,0.779973
13,3,馬連,0.275720,0.822634,0.358025,0.759945
14,4,ワイド,0.695473,0.774760,0.810700,0.845062
15,4,三連単,0.197531,0.630213,0.275720,0.856310
16,4,三連複,0.197531,0.709156,0.275720,0.891872
17,4,単勝,0.707819,0.773045,0.802469,0.799897
18,4,複勝,0.942387,0.802058,0.991770,0.826749
19,4,馬単,0.419753,0.680007,0.526749,0.790466
20,4,馬連,0.419753,0.686694,0.526749,0.772634
21,5,ワイド,0.823045,0.788436,0.909465,0.899259
22,5,三連単,0.341564,0.603772,0.497942,0.895041
23,5,三連複,0.341564,0.656543,0.497942,0.938272
24,5,単勝,0.781893,0.757942,0.880658,0.819177
25,5,複勝,0.979424,0.801152,0.995885,0.817778
26,5,馬単,0.551440,0.755885,0.691358,0.827469
27,5,馬連,0.551440,0.728765,0.691358,0.810741

In [229]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_kasamatu.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kasamatu")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kasamatu,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kasamatu,hitrate_pop,returnrate_pop
0,1,単勝,0.285714,0.514286,0.380952,0.619048
1,1,複勝,0.619048,0.871429,0.714286,0.795238
2,2,ワイド,0.238095,0.495238,0.476190,0.752381
3,2,単勝,0.380952,0.471429,0.666667,0.802381
4,2,複勝,0.857143,0.821429,1.000000,0.919048
5,2,馬単,0.047619,0.159524,0.190476,0.588095
6,2,馬連,0.047619,0.304762,0.190476,0.642857
7,3,ワイド,0.380952,0.768254,0.857143,0.879365
8,3,三連単,0.190476,0.664286,0.142857,0.420635
9,3,三連複,0.190476,1.004762,0.142857,0.380952
10,3,単勝,0.523810,0.514286,0.761905,0.663492
11,3,複勝,0.952381,0.742857,1.000000,0.893651
12,3,馬単,0.238095,0.511111,0.333333,0.388095
13,3,馬連,0.238095,0.560317,0.333333,0.393651
14,4,ワイド,0.809524,0.847619,0.952381,0.801587
15,4,三連単,0.285714,0.343056,0.380952,0.583135
16,4,三連複,0.285714,0.603571,0.380952,0.783333
17,4,単勝,0.714286,0.515476,0.809524,0.566667
18,4,複勝,1.000000,0.796429,1.000000,0.828571
19,4,馬単,0.571429,0.843651,0.523810,0.457143
20,4,馬連,0.571429,0.978571,0.523810,0.493651
21,5,ワイド,0.857143,0.588095,0.952381,0.810476
22,5,三連単,0.333333,0.163492,0.619048,0.755476
23,5,三連複,0.333333,0.260476,0.619048,0.942381
24,5,単勝,0.761905,0.467619,0.857143,0.521905
25,5,複勝,1.000000,0.684762,1.000000,0.768571
26,5,馬単,0.619048,0.540952,0.714286,0.584048
27,5,馬連,0.619048,0.616667,0.714286,0.677143

In [230]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_kanazawa.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kanazawa")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kanazawa,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_kanazawa,hitrate_pop,returnrate_pop
0,1,単勝,0.448276,0.863793,0.637931,0.937931
1,1,複勝,0.741379,0.900000,0.844828,0.929310
2,2,ワイド,0.500000,1.184483,0.551724,0.781034
3,2,単勝,0.586207,0.710345,0.793103,0.720690
4,2,複勝,0.879310,0.867241,0.948276,0.846552
5,2,馬単,0.206897,0.484483,0.327586,0.672414
6,2,馬連,0.206897,0.560345,0.327586,0.779310
7,3,ワイド,0.689655,0.784483,0.844828,0.841379
8,3,三連単,0.120690,0.236207,0.224138,0.727586
9,3,三連複,0.120690,0.417241,0.224138,0.787931
10,3,単勝,0.706897,0.652874,0.827586,0.589655
11,3,複勝,0.931034,0.786782,0.965517,0.816092
12,3,馬単,0.448276,0.627299,0.568966,0.654598
13,3,馬連,0.448276,0.583908,0.568966,0.738506
14,4,ワイド,0.844828,0.928161,0.896552,0.833046
15,4,三連単,0.344828,0.599282,0.517241,0.868247
16,4,三連複,0.344828,1.078017,0.517241,0.909483
17,4,単勝,0.775862,0.514655,0.931034,0.660345
18,4,複勝,0.982759,0.819397,1.000000,0.787069
19,4,馬単,0.655172,0.648851,0.689655,0.516379
20,4,馬連,0.655172,0.796264,0.689655,0.544828
21,5,ワイド,0.879310,0.687759,0.931034,0.737931
22,5,三連単,0.517241,0.304540,0.724138,0.548305
23,5,三連複,0.517241,0.565000,0.724138,0.587241
24,5,単勝,0.844828,0.461379,0.965517,0.613448
25,5,複勝,1.000000,0.727931,1.000000,0.765172
26,5,馬単,0.706897,0.405000,0.810345,0.484741
27,5,馬連,0.706897,0.501207,0.810345,0.520172

In [231]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_funabasi.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_funabasi")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_funabasi,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_funabasi,hitrate_pop,returnrate_pop
0,1,単勝,0.453125,1.425000,0.375000,0.820312
1,1,複勝,0.661417,0.988976,0.661417,0.864567
2,2,ワイド,0.359375,1.134375,0.351562,0.770312
3,2,単勝,0.578125,1.050000,0.570312,0.787109
4,2,複勝,0.826772,0.942913,0.874016,0.844094
5,2,馬単,0.203125,1.424219,0.195312,0.934375
6,2,馬連,0.203125,1.551562,0.195312,0.922656
7,3,ワイド,0.585938,0.816927,0.656250,0.761198
8,3,三連単,0.085938,0.722917,0.093750,0.639583
9,3,三連複,0.085938,0.662500,0.093750,0.703906
10,3,単勝,0.710938,0.954167,0.687500,0.723698
11,3,複勝,0.937008,0.864304,0.944882,0.825197
12,3,馬単,0.367188,1.081120,0.351562,0.750260
13,3,馬連,0.367188,1.045573,0.351562,0.755990
14,4,ワイド,0.703125,0.653906,0.773438,0.691927
15,4,三連単,0.187500,0.506706,0.265625,0.623633
16,4,三連複,0.187500,0.498047,0.265625,0.599805
17,4,単勝,0.757812,0.853711,0.765625,0.685742
18,4,複勝,0.952756,0.778937,0.968504,0.768110
19,4,馬単,0.492188,0.854362,0.515625,0.710677
20,4,馬連,0.492188,0.813672,0.515625,0.726432
21,5,ワイド,0.851562,0.900859,0.867188,0.692969
22,5,三連単,0.328125,1.103906,0.445312,0.593607
23,5,三連複,0.328125,0.936484,0.445312,0.608281
24,5,単勝,0.804688,1.007031,0.828125,0.689063
25,5,複勝,0.984252,0.828819,0.992126,0.761890
26,5,馬単,0.601562,0.985469,0.664062,0.659023
27,5,馬連,0.601562,0.864766,0.664062,0.676094

### ３位以内モデル

In [47]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt10.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_sonoda_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_sonoda_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_sonoda_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_sonoda_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.530891
[200]	valid_0's binary_logloss: 0.50964
[300]	valid_0's binary_logloss: 0.501934
[400]	valid_0's binary_logloss: 0.498753
[500]	valid_0's binary_logloss: 0.4976
[600]	valid_0's binary_logloss: 0.496949
[700]	valid_0's binary_logloss: 0.496705
[800]	valid_0's binary_logloss: 0.496392
[900]	valid_0's binary_logloss: 0.496183
[1000]	valid_0's binary_logloss: 0.496082
[1100]	valid_0's binary_logloss: 0.496198
Early stopping, best iteration is:
[1004]	valid_0's binary_logloss: 0.496068
-------------------- Metrics --------------------
Accuracy: 0.4398
Precision: 0.3433
Recall: 0.9789
F1 Score: 0.5083
ROC AUC: 0.7816
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.490383
[1200]	valid_0's binary_logloss: 0.488525
[1300]	valid_0's binary_logloss: 0.487303
[1400]	valid_0's binary_logloss: 0.486652
[1500]	valid_0's binary_logloss: 0.486134
[1600]	valid_0's binary_logloss: 0.485836
[1700]	valid_0's binary_logloss: 0.485584
[1800]	valid_0's binary_logloss: 0.485596
Early stopping, best iteration is:
[1769]	valid_0's binary_logloss: 0.48555
-------------------- Metrics --------------------
Accuracy: 0.4592
Precision: 0.3562
Recall: 0.9798
F1 Score: 0.5224
ROC AUC: 0.7984
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1800]	valid_0's binary_logloss: 0.482139
[1900]	valid_0's binary_logloss: 0.481125
[2000]	valid_0's binary_logloss: 0.480616
[2100]	valid_0's binary_logloss: 0.480132
[2200]	valid_0's binary_logloss: 0.479905
[2300]	valid_0's binary_logloss: 0.479716
[2400]	valid_0's binary_logloss: 0.479469
[2500]	valid_0's binary_logloss: 0.479327
[2600]	valid_0's binary_logloss: 0.479259
Early stopping, best iteration is:
[2587]	valid_0's binary_logloss: 0.47924
-------------------- Metrics --------------------
Accuracy: 0.4795
Precision: 0.3704
Recall: 0.9812
F1 Score: 0.5378
ROC AUC: 0.8075
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2600]	valid_0's binary_logloss: 0.476276
[2700]	valid_0's binary_logloss: 0.475567
[2800]	valid_0's binary_logloss: 0.475179
[2900]	valid_0's binary_logloss: 0.47486
[3000]	valid_0's binary_logloss: 0.474614
[3100]	valid_0's binary_logloss: 0.474483
[3200]	valid_0's binary_logloss: 0.474249
[3300]	valid_0's binary_logloss: 0.47418
Early stopping, best iteration is:
[3271]	valid_0's binary_logloss: 0.474103
-------------------- Metrics --------------------
Accuracy: 0.4852
Precision: 0.3647
Recall: 0.9730
F1 Score: 0.5305
ROC AUC: 0.8084
Training final model using all data...
Final model training completed.

In [48]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_urawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_urawa_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_urawa_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_urawa_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_urawa_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.512344
[200]	valid_0's binary_logloss: 0.49557
[300]	valid_0's binary_logloss: 0.4905
[400]	valid_0's binary_logloss: 0.489334
[500]	valid_0's binary_logloss: 0.489733
Early stopping, best iteration is:
[409]	valid_0's binary_logloss: 0.489147
-------------------- Metrics --------------------
Accuracy: 0.4297
Precision: 0.3216
Recall: 0.9704
F1 Score: 0.4831
ROC AUC: 0.7731
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.498955
[600]	valid_0's binary_logloss: 0.497261
[700]	valid_0's binary_logloss: 0.496902
[800]	valid_0's binary_logloss: 0.496754
[900]	valid_0's binary_logloss: 0.496695
Early stopping, best iteration is:
[847]	valid_0's binary_logloss: 0.496592
-------------------- Metrics --------------------
Accuracy: 0.4432
Precision: 0.3372
Recall: 0.9731
F1 Score: 0.5008
ROC AUC: 0.7761
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.506375
[1000]	valid_0's binary_logloss: 0.504106
[1100]	valid_0's binary_logloss: 0.503122
[1200]	valid_0's binary_logloss: 0.502466
[1300]	valid_0's binary_logloss: 0.502319
[1400]	valid_0's binary_logloss: 0.502422
Early stopping, best iteration is:
[1328]	valid_0's binary_logloss: 0.502182
-------------------- Metrics --------------------
Accuracy: 0.4420
Precision: 0.3351
Recall: 0.9706
F1 Score: 0.4981
ROC AUC: 0.7671
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.490289
[1500]	valid_0's binary_logloss: 0.489572
[1600]	valid_0's binary_logloss: 0.489454
Early stopping, best iteration is:
[1571]	valid_0's binary_logloss: 0.489352
-------------------- Metrics --------------------
Accuracy: 0.4261
Precision: 0.3268
Recall: 0.9782
F1 Score: 0.4899
ROC AUC: 0.7796
Training final model using all data...
Final model training completed.

In [49]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_saga.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_saga_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_saga_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_saga_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_saga_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.514509
[200]	valid_0's binary_logloss: 0.492835
[300]	valid_0's binary_logloss: 0.486084
[400]	valid_0's binary_logloss: 0.48338
[500]	valid_0's binary_logloss: 0.482561
[600]	valid_0's binary_logloss: 0.4824
Early stopping, best iteration is:
[563]	valid_0's binary_logloss: 0.482302
-------------------- Metrics --------------------
Accuracy: 0.4529
Precision: 0.3513
Recall: 0.9733
F1 Score: 0.5162
ROC AUC: 0.7994
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.505584
[700]	valid_0's binary_logloss: 0.503668
[800]	valid_0's binary_logloss: 0.502964
[900]	valid_0's binary_logloss: 0.502816
[1000]	valid_0's binary_logloss: 0.50283
Early stopping, best iteration is:
[962]	valid_0's binary_logloss: 0.502649
-------------------- Metrics --------------------
Accuracy: 0.4369
Precision: 0.3511
Recall: 0.9811
F1 Score: 0.5172
ROC AUC: 0.7840
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.481765
[1100]	valid_0's binary_logloss: 0.480132
[1200]	valid_0's binary_logloss: 0.479299
[1300]	valid_0's binary_logloss: 0.478873
[1400]	valid_0's binary_logloss: 0.478693
[1500]	valid_0's binary_logloss: 0.478631
Early stopping, best iteration is:
[1492]	valid_0's binary_logloss: 0.478588
-------------------- Metrics --------------------
Accuracy: 0.4600
Precision: 0.3491
Recall: 0.9781
F1 Score: 0.5146
ROC AUC: 0.8011
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.467819
[1600]	valid_0's binary_logloss: 0.46705
[1700]	valid_0's binary_logloss: 0.466697
[1800]	valid_0's binary_logloss: 0.466508
[1900]	valid_0's binary_logloss: 0.466349
[2000]	valid_0's binary_logloss: 0.466337
[2100]	valid_0's binary_logloss: 0.466241
[2200]	valid_0's binary_logloss: 0.466125
[2300]	valid_0's binary_logloss: 0.465984
[2400]	valid_0's binary_logloss: 0.465974
Early stopping, best iteration is:
[2354]	valid_0's binary_logloss: 0.465918
-------------------- Metrics --------------------
Accuracy: 0.4830
Precision: 0.3623
Recall: 0.9748
F1 Score: 0.5283
ROC AUC: 0.8143
Training final model using all data...
Final model training completed.

In [50]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_ooi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_ooi_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_ooi_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_ooi_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_ooi_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.471026
[200]	valid_0's binary_logloss: 0.453902
[300]	valid_0's binary_logloss: 0.448145
[400]	valid_0's binary_logloss: 0.446096
[500]	valid_0's binary_logloss: 0.445342
[600]	valid_0's binary_logloss: 0.445168
[700]	valid_0's binary_logloss: 0.445264
Early stopping, best iteration is:
[639]	valid_0's binary_logloss: 0.444988
-------------------- Metrics --------------------
Accuracy: 0.4659
Precision: 0.3009
Recall: 0.9597
F1 Score: 0.4581
ROC AUC: 0.7881
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.457187
[800]	valid_0's binary_logloss: 0.455848
[900]	valid_0's binary_logloss: 0.455174
[1000]	valid_0's binary_logloss: 0.455124
[1100]	valid_0's binary_logloss: 0.454735
[1200]	valid_0's binary_logloss: 0.454651
Early stopping, best iteration is:
[1197]	valid_0's binary_logloss: 0.454634
-------------------- Metrics --------------------
Accuracy: 0.4735
Precision: 0.3098
Recall: 0.9553
F1 Score: 0.4679
ROC AUC: 0.7838
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.463655
[1300]	valid_0's binary_logloss: 0.461664
[1400]	valid_0's binary_logloss: 0.461083
[1500]	valid_0's binary_logloss: 0.460817
[1600]	valid_0's binary_logloss: 0.460844
Early stopping, best iteration is:
[1576]	valid_0's binary_logloss: 0.460767
-------------------- Metrics --------------------
Accuracy: 0.4569
Precision: 0.3097
Recall: 0.9595
F1 Score: 0.4683
ROC AUC: 0.7835
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1600]	valid_0's binary_logloss: 0.451453
[1700]	valid_0's binary_logloss: 0.450639
[1800]	valid_0's binary_logloss: 0.450479
[1900]	valid_0's binary_logloss: 0.450556
Early stopping, best iteration is:
[1819]	valid_0's binary_logloss: 0.450441
-------------------- Metrics --------------------
Accuracy: 0.4529
Precision: 0.3071
Recall: 0.9655
F1 Score: 0.4660
ROC AUC: 0.7934
Training final model using all data...
Final model training completed.

In [51]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_nagoya.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nagoya_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nagoya_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nagoya_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nagoya_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.519169
[200]	valid_0's binary_logloss: 0.498564
[300]	valid_0's binary_logloss: 0.492097
[400]	valid_0's binary_logloss: 0.489709
[500]	valid_0's binary_logloss: 0.488957
[600]	valid_0's binary_logloss: 0.488836
[700]	valid_0's binary_logloss: 0.48939
Early stopping, best iteration is:
[600]	valid_0's binary_logloss: 0.488836
-------------------- Metrics --------------------
Accuracy: 0.4695
Precision: 0.3599
Recall: 0.9768
F1 Score: 0.5260
ROC AUC: 0.7950
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.477347
[800]	valid_0's binary_logloss: 0.476753
[900]	valid_0's binary_logloss: 0.476251
[1000]	valid_0's binary_logloss: 0.476144
[1100]	valid_0's binary_logloss: 0.476199
Early stopping, best iteration is:
[1007]	valid_0's binary_logloss: 0.476114
-------------------- Metrics --------------------
Accuracy: 0.4624
Precision: 0.3403
Recall: 0.9736
F1 Score: 0.5043
ROC AUC: 0.7931
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.466247
[1200]	valid_0's binary_logloss: 0.465546
[1300]	valid_0's binary_logloss: 0.465113
[1400]	valid_0's binary_logloss: 0.464825
[1500]	valid_0's binary_logloss: 0.464849
Early stopping, best iteration is:
[1446]	valid_0's binary_logloss: 0.464748
-------------------- Metrics --------------------
Accuracy: 0.4670
Precision: 0.3381
Recall: 0.9709
F1 Score: 0.5015
ROC AUC: 0.8023
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.473034
[1600]	valid_0's binary_logloss: 0.472139
[1700]	valid_0's binary_logloss: 0.471921
[1800]	valid_0's binary_logloss: 0.471682
[1900]	valid_0's binary_logloss: 0.471604
[2000]	valid_0's binary_logloss: 0.471613
Early stopping, best iteration is:
[1909]	valid_0's binary_logloss: 0.471577
-------------------- Metrics --------------------
Accuracy: 0.4546
Precision: 0.3275
Recall: 0.9689
F1 Score: 0.4896
ROC AUC: 0.7902
Training final model using all data...
Final model training completed.

In [52]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_morioka.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_morioka_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_morioka_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_morioka_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_morioka_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.548978
[200]	valid_0's binary_logloss: 0.52643
[300]	valid_0's binary_logloss: 0.518917
[400]	valid_0's binary_logloss: 0.51611
[500]	valid_0's binary_logloss: 0.514789
[600]	valid_0's binary_logloss: 0.515296
Early stopping, best iteration is:
[505]	valid_0's binary_logloss: 0.514713
-------------------- Metrics --------------------
Accuracy: 0.4130
Precision: 0.3593
Recall: 0.9909
F1 Score: 0.5273
ROC AUC: 0.7841
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.5047
[700]	valid_0's binary_logloss: 0.504184
[800]	valid_0's binary_logloss: 0.504134
[900]	valid_0's binary_logloss: 0.504173
Early stopping, best iteration is:
[823]	valid_0's binary_logloss: 0.503979
-------------------- Metrics --------------------
Accuracy: 0.4255
Precision: 0.3571
Recall: 0.9859
F1 Score: 0.5243
ROC AUC: 0.7899
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.514954
[1000]	valid_0's binary_logloss: 0.513031
[1100]	valid_0's binary_logloss: 0.512184
[1200]	valid_0's binary_logloss: 0.512015
[1300]	valid_0's binary_logloss: 0.511633
[1400]	valid_0's binary_logloss: 0.511502
[1500]	valid_0's binary_logloss: 0.51152
Early stopping, best iteration is:
[1439]	valid_0's binary_logloss: 0.511316
-------------------- Metrics --------------------
Accuracy: 0.4431
Precision: 0.3627
Recall: 0.9769
F1 Score: 0.5290
ROC AUC: 0.7806
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.518864
[1600]	valid_0's binary_logloss: 0.517891
[1700]	valid_0's binary_logloss: 0.517845
Early stopping, best iteration is:
[1609]	valid_0's binary_logloss: 0.517778
-------------------- Metrics --------------------
Accuracy: 0.4238
Precision: 0.3372
Recall: 0.9726
F1 Score: 0.5008
ROC AUC: 0.7579
Training final model using all data...
Final model training completed.

In [53]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_monbetu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_monbetu_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_monbetu_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_monbetu_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_monbetu_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.521143
[200]	valid_0's binary_logloss: 0.494404
[300]	valid_0's binary_logloss: 0.485065
[400]	valid_0's binary_logloss: 0.481688
[500]	valid_0's binary_logloss: 0.480582
[600]	valid_0's binary_logloss: 0.480636
Early stopping, best iteration is:
[526]	valid_0's binary_logloss: 0.480417
-------------------- Metrics --------------------
Accuracy: 0.4820
Precision: 0.3740
Recall: 0.9764
F1 Score: 0.5409
ROC AUC: 0.8102
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.502136
[700]	valid_0's binary_logloss: 0.501579
[800]	valid_0's binary_logloss: 0.501036
[900]	valid_0's binary_logloss: 0.501179
Early stopping, best iteration is:
[829]	valid_0's binary_logloss: 0.500839
-------------------- Metrics --------------------
Accuracy: 0.4765
Precision: 0.3769
Recall: 0.9750
F1 Score: 0.5436
ROC AUC: 0.7934
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.467405
[1000]	valid_0's binary_logloss: 0.466889
[1100]	valid_0's binary_logloss: 0.466875
Early stopping, best iteration is:
[1079]	valid_0's binary_logloss: 0.466791
-------------------- Metrics --------------------
Accuracy: 0.4931
Precision: 0.3706
Recall: 0.9763
F1 Score: 0.5372
ROC AUC: 0.8170
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.466954
[1200]	valid_0's binary_logloss: 0.465799
[1300]	valid_0's binary_logloss: 0.465171
[1400]	valid_0's binary_logloss: 0.46466
[1500]	valid_0's binary_logloss: 0.46445
[1600]	valid_0's binary_logloss: 0.464246
[1700]	valid_0's binary_logloss: 0.463908
[1800]	valid_0's binary_logloss: 0.463913
Early stopping, best iteration is:
[1763]	valid_0's binary_logloss: 0.463813
-------------------- Metrics --------------------
Accuracy: 0.5131
Precision: 0.3839
Recall: 0.9759
F1 Score: 0.5510
ROC AUC: 0.8218
Training final model using all data...
Final model training completed.

In [54]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_mizusawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_mizusawa_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_mizusawa_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_mizusawa_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_mizusawa_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.563947
[200]	valid_0's binary_logloss: 0.547341
[300]	valid_0's binary_logloss: 0.540935
[400]	valid_0's binary_logloss: 0.538443
[500]	valid_0's binary_logloss: 0.537727
Early stopping, best iteration is:
[489]	valid_0's binary_logloss: 0.537494
-------------------- Metrics --------------------
Accuracy: 0.3848
Precision: 0.3415
Recall: 0.9917
F1 Score: 0.5081
ROC AUC: 0.7506
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.529571
[600]	valid_0's binary_logloss: 0.525547
[700]	valid_0's binary_logloss: 0.523845
[800]	valid_0's binary_logloss: 0.523144
[900]	valid_0's binary_logloss: 0.522801
[1000]	valid_0's binary_logloss: 0.522712
[1100]	valid_0's binary_logloss: 0.522633
[1200]	valid_0's binary_logloss: 0.522353
Early stopping, best iteration is:
[1186]	valid_0's binary_logloss: 0.522324
-------------------- Metrics --------------------
Accuracy: 0.4113
Precision: 0.3484
Recall: 0.9833
F1 Score: 0.5145
ROC AUC: 0.7676
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.527639
[1300]	valid_0's binary_logloss: 0.526423
[1400]	valid_0's binary_logloss: 0.525903
[1500]	valid_0's binary_logloss: 0.525964
Early stopping, best iteration is:
[1439]	valid_0's binary_logloss: 0.525835
-------------------- Metrics --------------------
Accuracy: 0.4216
Precision: 0.3524
Recall: 0.9782
F1 Score: 0.5181
ROC AUC: 0.7658
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.502275
[1600]	valid_0's binary_logloss: 0.501475
[1700]	valid_0's binary_logloss: 0.500944
[1800]	valid_0's binary_logloss: 0.500688
Early stopping, best iteration is:
[1747]	valid_0's binary_logloss: 0.500585
-------------------- Metrics --------------------
Accuracy: 0.4269
Precision: 0.3419
Recall: 0.9761
F1 Score: 0.5064
ROC AUC: 0.7833
Training final model using all data...
Final model training completed.

In [55]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kouti.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kouti_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kouti_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kouti_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kouti_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.509325
[200]	valid_0's binary_logloss: 0.483478
[300]	valid_0's binary_logloss: 0.475154
[400]	valid_0's binary_logloss: 0.47177
[500]	valid_0's binary_logloss: 0.470767
[600]	valid_0's binary_logloss: 0.470481
[700]	valid_0's binary_logloss: 0.470271
[800]	valid_0's binary_logloss: 0.47038
Early stopping, best iteration is:
[744]	valid_0's binary_logloss: 0.470156
-------------------- Metrics --------------------
Accuracy: 0.4997
Precision: 0.3752
Recall: 0.9756
F1 Score: 0.5419
ROC AUC: 0.8137
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.472325
[900]	valid_0's binary_logloss: 0.471499
[1000]	valid_0's binary_logloss: 0.470845
[1100]	valid_0's binary_logloss: 0.470429
[1200]	valid_0's binary_logloss: 0.470341
Early stopping, best iteration is:
[1172]	valid_0's binary_logloss: 0.470289
-------------------- Metrics --------------------
Accuracy: 0.4923
Precision: 0.3728
Recall: 0.9728
F1 Score: 0.5391
ROC AUC: 0.8144
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.480479
[1300]	valid_0's binary_logloss: 0.479692
[1400]	valid_0's binary_logloss: 0.479105
[1500]	valid_0's binary_logloss: 0.478874
[1600]	valid_0's binary_logloss: 0.478906
[1700]	valid_0's binary_logloss: 0.478758
Early stopping, best iteration is:
[1682]	valid_0's binary_logloss: 0.478707
-------------------- Metrics --------------------
Accuracy: 0.4737
Precision: 0.3634
Recall: 0.9748
F1 Score: 0.5294
ROC AUC: 0.8058
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's binary_logloss: 0.474909
[1800]	valid_0's binary_logloss: 0.474258
[1900]	valid_0's binary_logloss: 0.473929
[2000]	valid_0's binary_logloss: 0.473786
[2100]	valid_0's binary_logloss: 0.473531
[2200]	valid_0's binary_logloss: 0.473415
[2300]	valid_0's binary_logloss: 0.473202
[2400]	valid_0's binary_logloss: 0.473215
Early stopping, best iteration is:
[2368]	valid_0's binary_logloss: 0.473118
-------------------- Metrics --------------------
Accuracy: 0.4827
Precision: 0.3700
Recall: 0.9784
F1 Score: 0.5369
ROC AUC: 0.8122
Training final model using all data...
Final model training completed.

In [56]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kawasaki.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kawasaki_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kawasaki_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kawasaki_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kawasaki_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.510256
[200]	valid_0's binary_logloss: 0.494392
[300]	valid_0's binary_logloss: 0.488605
[400]	valid_0's binary_logloss: 0.486982
[500]	valid_0's binary_logloss: 0.486634
Early stopping, best iteration is:
[453]	valid_0's binary_logloss: 0.486563
-------------------- Metrics --------------------
Accuracy: 0.4344
Precision: 0.3187
Recall: 0.9724
F1 Score: 0.4800
ROC AUC: 0.7693
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.493249
[600]	valid_0's binary_logloss: 0.491228
[700]	valid_0's binary_logloss: 0.490299
[800]	valid_0's binary_logloss: 0.489957
[900]	valid_0's binary_logloss: 0.489827
[1000]	valid_0's binary_logloss: 0.489899
Early stopping, best iteration is:
[944]	valid_0's binary_logloss: 0.489696
-------------------- Metrics --------------------
Accuracy: 0.4380
Precision: 0.3219
Recall: 0.9714
F1 Score: 0.4836
ROC AUC: 0.7684
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.495623
[1100]	valid_0's binary_logloss: 0.493538
[1200]	valid_0's binary_logloss: 0.492645
[1300]	valid_0's binary_logloss: 0.49215
[1400]	valid_0's binary_logloss: 0.491795
Early stopping, best iteration is:
[1388]	valid_0's binary_logloss: 0.491773
-------------------- Metrics --------------------
Accuracy: 0.4173
Precision: 0.3166
Recall: 0.9751
F1 Score: 0.4779
ROC AUC: 0.7670
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.485916
[1500]	valid_0's binary_logloss: 0.484214
[1600]	valid_0's binary_logloss: 0.483752
[1700]	valid_0's binary_logloss: 0.483544
[1800]	valid_0's binary_logloss: 0.483577
Early stopping, best iteration is:
[1713]	valid_0's binary_logloss: 0.483417
-------------------- Metrics --------------------
Accuracy: 0.4218
Precision: 0.3180
Recall: 0.9742
F1 Score: 0.4795
ROC AUC: 0.7775
Training final model using all data...
Final model training completed.

In [57]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kasamatu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kasamatu_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kasamatu_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kasamatu_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kasamatu_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.548978
[200]	valid_0's binary_logloss: 0.52643
[300]	valid_0's binary_logloss: 0.518917
[400]	valid_0's binary_logloss: 0.51611
[500]	valid_0's binary_logloss: 0.514789
[600]	valid_0's binary_logloss: 0.515296
Early stopping, best iteration is:
[505]	valid_0's binary_logloss: 0.514713
-------------------- Metrics --------------------
Accuracy: 0.4130
Precision: 0.3593
Recall: 0.9909
F1 Score: 0.5273
ROC AUC: 0.7841
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.5047
[700]	valid_0's binary_logloss: 0.504184
[800]	valid_0's binary_logloss: 0.504134
[900]	valid_0's binary_logloss: 0.504173
Early stopping, best iteration is:
[823]	valid_0's binary_logloss: 0.503979
-------------------- Metrics --------------------
Accuracy: 0.4255
Precision: 0.3571
Recall: 0.9859
F1 Score: 0.5243
ROC AUC: 0.7899
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.514954
[1000]	valid_0's binary_logloss: 0.513031
[1100]	valid_0's binary_logloss: 0.512184
[1200]	valid_0's binary_logloss: 0.512015
[1300]	valid_0's binary_logloss: 0.511633
[1400]	valid_0's binary_logloss: 0.511502
[1500]	valid_0's binary_logloss: 0.51152
Early stopping, best iteration is:
[1439]	valid_0's binary_logloss: 0.511316
-------------------- Metrics --------------------
Accuracy: 0.4431
Precision: 0.3627
Recall: 0.9769
F1 Score: 0.5290
ROC AUC: 0.7806
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.518864
[1600]	valid_0's binary_logloss: 0.517891
[1700]	valid_0's binary_logloss: 0.517845
Early stopping, best iteration is:
[1609]	valid_0's binary_logloss: 0.517778
-------------------- Metrics --------------------
Accuracy: 0.4238
Precision: 0.3372
Recall: 0.9726
F1 Score: 0.5008
ROC AUC: 0.7579
Training final model using all data...
Final model training completed.

In [58]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kanazawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_kanazawa_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_kanazawa_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kanazawa_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_kanazawa_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.54537
[200]	valid_0's binary_logloss: 0.518732
[300]	valid_0's binary_logloss: 0.509792
[400]	valid_0's binary_logloss: 0.506294
[500]	valid_0's binary_logloss: 0.504939
[600]	valid_0's binary_logloss: 0.505249
Early stopping, best iteration is:
[561]	valid_0's binary_logloss: 0.504908
-------------------- Metrics --------------------
Accuracy: 0.4824
Precision: 0.4024
Recall: 0.9814
F1 Score: 0.5708
ROC AUC: 0.8028
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.52022
[700]	valid_0's binary_logloss: 0.516735
[800]	valid_0's binary_logloss: 0.516292
[900]	valid_0's binary_logloss: 0.515867
Early stopping, best iteration is:
[883]	valid_0's binary_logloss: 0.515681
-------------------- Metrics --------------------
Accuracy: 0.4654
Precision: 0.3927
Recall: 0.9862
F1 Score: 0.5617
ROC AUC: 0.7916
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.505157
[1000]	valid_0's binary_logloss: 0.502624
[1100]	valid_0's binary_logloss: 0.50174
[1200]	valid_0's binary_logloss: 0.501608
[1300]	valid_0's binary_logloss: 0.501442
[1400]	valid_0's binary_logloss: 0.5012
[1500]	valid_0's binary_logloss: 0.501338
Early stopping, best iteration is:
[1433]	valid_0's binary_logloss: 0.501187
-------------------- Metrics --------------------
Accuracy: 0.4826
Precision: 0.3994
Recall: 0.9852
F1 Score: 0.5684
ROC AUC: 0.8053
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.505403
[1600]	valid_0's binary_logloss: 0.50457
[1700]	valid_0's binary_logloss: 0.504248
[1800]	valid_0's binary_logloss: 0.50391
[1900]	valid_0's binary_logloss: 0.503771
[2000]	valid_0's binary_logloss: 0.503669
Early stopping, best iteration is:
[1998]	valid_0's binary_logloss: 0.50365
-------------------- Metrics --------------------
Accuracy: 0.4654
Precision: 0.3856
Recall: 0.9803
F1 Score: 0.5535
ROC AUC: 0.7969
Training final model using all data...
Final model training completed.

In [59]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_funabasi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_funabasi_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_funabasi_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_funabasi_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_funabasi_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.513848
[200]	valid_0's binary_logloss: 0.495269
[300]	valid_0's binary_logloss: 0.489931
[400]	valid_0's binary_logloss: 0.488639
[500]	valid_0's binary_logloss: 0.489008
Early stopping, best iteration is:
[401]	valid_0's binary_logloss: 0.488625
-------------------- Metrics --------------------
Accuracy: 0.4206
Precision: 0.3252
Recall: 0.9795
F1 Score: 0.4882
ROC AUC: 0.7811
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.50373
[600]	valid_0's binary_logloss: 0.502562
[700]	valid_0's binary_logloss: 0.502129
[800]	valid_0's binary_logloss: 0.502079
[900]	valid_0's binary_logloss: 0.50199
Early stopping, best iteration is:
[880]	valid_0's binary_logloss: 0.501744
-------------------- Metrics --------------------
Accuracy: 0.4360
Precision: 0.3363
Recall: 0.9724
F1 Score: 0.4998
ROC AUC: 0.7713
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.51159
[1000]	valid_0's binary_logloss: 0.509117
[1100]	valid_0's binary_logloss: 0.508461
[1200]	valid_0's binary_logloss: 0.508148
[1300]	valid_0's binary_logloss: 0.508174
Early stopping, best iteration is:
[1266]	valid_0's binary_logloss: 0.507987
-------------------- Metrics --------------------
Accuracy: 0.4299
Precision: 0.3388
Recall: 0.9751
F1 Score: 0.5029
ROC AUC: 0.7677
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.495003
[1400]	valid_0's binary_logloss: 0.493844
[1500]	valid_0's binary_logloss: 0.493221
[1600]	valid_0's binary_logloss: 0.492818
[1700]	valid_0's binary_logloss: 0.492438
[1800]	valid_0's binary_logloss: 0.492201
[1900]	valid_0's binary_logloss: 0.49246
Early stopping, best iteration is:
[1800]	valid_0's binary_logloss: 0.492201
-------------------- Metrics --------------------
Accuracy: 0.4420
Precision: 0.3432
Recall: 0.9764
F1 Score: 0.5079
ROC AUC: 0.7833
Training final model using all data...
Final model training completed.

In [60]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_sonoda.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight10.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_sonoda_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.552476
[200]	valid_0's binary_logloss: 0.534235
[300]	valid_0's binary_logloss: 0.526386
[400]	valid_0's binary_logloss: 0.522124
[500]	valid_0's binary_logloss: 0.519721
[600]	valid_0's binary_logloss: 0.518485
[700]	valid_0's binary_logloss: 0.517835
[800]	valid_0's binary_logloss: 0.517599
[900]	valid_0's binary_logloss: 0.517584
Early stopping, best iteration is:
[893]	valid_0's binary_logloss: 0.517521
-------------------- Metrics --------------------
Accuracy: 0.3831
Precision: 0.3229
Recall: 0.9899
F1 Score: 0.4870
ROC AUC: 0.7546
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.517817
[1000]	valid_0's binary_logloss: 0.515392
[1100]	valid_0's binary_logloss: 0.513985
[1200]	valid_0's binary_logloss: 0.51301
[1300]	valid_0's binary_logloss: 0.512417
[1400]	valid_0's binary_logloss: 0.511943
[1500]	valid_0's binary_logloss: 0.511553
[1600]	valid_0's binary_logloss: 0.511289
[1700]	valid_0's binary_logloss: 0.511195
[1800]	valid_0's binary_logloss: 0.511128
[1900]	valid_0's binary_logloss: 0.511064
Early stopping, best iteration is:
[1857]	valid_0's binary_logloss: 0.511017
-------------------- Metrics --------------------
Accuracy: 0.4036
Precision: 0.3347
Recall: 0.9872
F1 Score: 0.4999
ROC AUC: 0.7670
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1900]	valid_0's binary_logloss: 0.506982
[2000]	valid_0's binary_logloss: 0.505647
[2100]	valid_0's binary_logloss: 0.504858
[2200]	valid_0's binary_logloss: 0.504451
[2300]	valid_0's binary_logloss: 0.504095
[2400]	valid_0's binary_logloss: 0.503833
[2500]	valid_0's binary_logloss: 0.503731
[2600]	valid_0's binary_logloss: 0.503638
[2700]	valid_0's binary_logloss: 0.503607
[2800]	valid_0's binary_logloss: 0.503523
[2900]	valid_0's binary_logloss: 0.503424
[3000]	valid_0's binary_logloss: 0.503341
[3100]	valid_0's binary_logloss: 0.503387
Early stopping, best iteration is:
[3015]	valid_0's binary_logloss: 0.50333
-------------------- Metrics --------------------
Accuracy: 0.4244
Precision: 0.3476
Recall: 0.9868
F1 Score: 0.5142
ROC AUC: 0.7819
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[3100]	valid_0's binary_logloss: 0.501334
[3200]	valid_0's binary_logloss: 0.501018
[3300]	valid_0's binary_logloss: 0.500688
[3400]	valid_0's binary_logloss: 0.500557
[3500]	valid_0's binary_logloss: 0.500307
[3600]	valid_0's binary_logloss: 0.500149
[3700]	valid_0's binary_logloss: 0.500129
[3800]	valid_0's binary_logloss: 0.500012
[3900]	valid_0's binary_logloss: 0.499877
[4000]	valid_0's binary_logloss: 0.499669
[4100]	valid_0's binary_logloss: 0.499609
[4200]	valid_0's binary_logloss: 0.499531
[4300]	valid_0's binary_logloss: 0.49954
Early stopping, best iteration is:
[4238]	valid_0's binary_logloss: 0.499487
-------------------- Metrics --------------------
Accuracy: 0.4370
Precision: 0.3445
Recall: 0.9789
F1 Score: 0.5097
ROC AUC: 0.7799
Training final model using all data...
Final model training completed.

In [61]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_urawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_urawa_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.530853
[200]	valid_0's binary_logloss: 0.515694
[300]	valid_0's binary_logloss: 0.50984
[400]	valid_0's binary_logloss: 0.507145
[500]	valid_0's binary_logloss: 0.506487
[600]	valid_0's binary_logloss: 0.506869
Early stopping, best iteration is:
[525]	valid_0's binary_logloss: 0.506345
-------------------- Metrics --------------------
Accuracy: 0.3832
Precision: 0.3060
Recall: 0.9825
F1 Score: 0.4667
ROC AUC: 0.7511
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.511078
[700]	valid_0's binary_logloss: 0.509343
[800]	valid_0's binary_logloss: 0.508772
[900]	valid_0's binary_logloss: 0.508829
Early stopping, best iteration is:
[834]	valid_0's binary_logloss: 0.508573
-------------------- Metrics --------------------
Accuracy: 0.3957
Precision: 0.3205
Recall: 0.9861
F1 Score: 0.4837
ROC AUC: 0.7593
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.510787
[1000]	valid_0's binary_logloss: 0.509863
[1100]	valid_0's binary_logloss: 0.509536
[1200]	valid_0's binary_logloss: 0.509386
[1300]	valid_0's binary_logloss: 0.509244
[1400]	valid_0's binary_logloss: 0.509179
Early stopping, best iteration is:
[1398]	valid_0's binary_logloss: 0.509153
-------------------- Metrics --------------------
Accuracy: 0.4105
Precision: 0.3238
Recall: 0.9790
F1 Score: 0.4866
ROC AUC: 0.7562
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.500012
[1500]	valid_0's binary_logloss: 0.499795
Early stopping, best iteration is:
[1436]	valid_0's binary_logloss: 0.499716
-------------------- Metrics --------------------
Accuracy: 0.4063
Precision: 0.3194
Recall: 0.9796
F1 Score: 0.4818
ROC AUC: 0.7657
Training final model using all data...
Final model training completed.

In [62]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_saga.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_saga_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.54238
[200]	valid_0's binary_logloss: 0.523233
[300]	valid_0's binary_logloss: 0.515362
[400]	valid_0's binary_logloss: 0.511263
[500]	valid_0's binary_logloss: 0.509265
[600]	valid_0's binary_logloss: 0.508302
[700]	valid_0's binary_logloss: 0.508114
Early stopping, best iteration is:
[688]	valid_0's binary_logloss: 0.507976
-------------------- Metrics --------------------
Accuracy: 0.3738
Precision: 0.3224
Recall: 0.9878
F1 Score: 0.4861
ROC AUC: 0.7696
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.531061
[800]	valid_0's binary_logloss: 0.528615
[900]	valid_0's binary_logloss: 0.527596
[1000]	valid_0's binary_logloss: 0.527099
[1100]	valid_0's binary_logloss: 0.526999
Early stopping, best iteration is:
[1056]	valid_0's binary_logloss: 0.526849
-------------------- Metrics --------------------
Accuracy: 0.3692
Precision: 0.3266
Recall: 0.9906
F1 Score: 0.4912
ROC AUC: 0.7537
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.510796
[1200]	valid_0's binary_logloss: 0.508984
[1300]	valid_0's binary_logloss: 0.50813
[1400]	valid_0's binary_logloss: 0.50769
[1500]	valid_0's binary_logloss: 0.507146
[1600]	valid_0's binary_logloss: 0.50698
[1700]	valid_0's binary_logloss: 0.50676
[1800]	valid_0's binary_logloss: 0.506645
[1900]	valid_0's binary_logloss: 0.506569
[2000]	valid_0's binary_logloss: 0.506616
Early stopping, best iteration is:
[1911]	valid_0's binary_logloss: 0.506526
-------------------- Metrics --------------------
Accuracy: 0.3930
Precision: 0.3233
Recall: 0.9833
F1 Score: 0.4867
ROC AUC: 0.7677
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2000]	valid_0's binary_logloss: 0.497257
[2100]	valid_0's binary_logloss: 0.496651
[2200]	valid_0's binary_logloss: 0.496396
[2300]	valid_0's binary_logloss: 0.496339
Early stopping, best iteration is:
[2244]	valid_0's binary_logloss: 0.496273
-------------------- Metrics --------------------
Accuracy: 0.4041
Precision: 0.3310
Recall: 0.9853
F1 Score: 0.4955
ROC AUC: 0.7824
Training final model using all data...
Final model training completed.

In [63]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_ooi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_ooi_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.487011
[200]	valid_0's binary_logloss: 0.469151
[300]	valid_0's binary_logloss: 0.462482
[400]	valid_0's binary_logloss: 0.45919
[500]	valid_0's binary_logloss: 0.457984
[600]	valid_0's binary_logloss: 0.4574
[700]	valid_0's binary_logloss: 0.457472
Early stopping, best iteration is:
[618]	valid_0's binary_logloss: 0.45733
-------------------- Metrics --------------------
Accuracy: 0.3991
Precision: 0.2785
Recall: 0.9774
F1 Score: 0.4335
ROC AUC: 0.7714
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.466353
[800]	valid_0's binary_logloss: 0.465489
[900]	valid_0's binary_logloss: 0.465111
[1000]	valid_0's binary_logloss: 0.46488
[1100]	valid_0's binary_logloss: 0.464745
[1200]	valid_0's binary_logloss: 0.464774
Early stopping, best iteration is:
[1128]	valid_0's binary_logloss: 0.464659
-------------------- Metrics --------------------
Accuracy: 0.4267
Precision: 0.2929
Recall: 0.9657
F1 Score: 0.4494
ROC AUC: 0.7701
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.473581
[1300]	valid_0's binary_logloss: 0.473108
[1400]	valid_0's binary_logloss: 0.472683
[1500]	valid_0's binary_logloss: 0.47256
[1600]	valid_0's binary_logloss: 0.472322
[1700]	valid_0's binary_logloss: 0.472223
Early stopping, best iteration is:
[1657]	valid_0's binary_logloss: 0.472186
-------------------- Metrics --------------------
Accuracy: 0.4260
Precision: 0.2986
Recall: 0.9658
F1 Score: 0.4561
ROC AUC: 0.7674
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's binary_logloss: 0.460339
[1800]	valid_0's binary_logloss: 0.459938
[1900]	valid_0's binary_logloss: 0.459607
[2000]	valid_0's binary_logloss: 0.45954
[2100]	valid_0's binary_logloss: 0.459521
[2200]	valid_0's binary_logloss: 0.45938
[2300]	valid_0's binary_logloss: 0.459352
Early stopping, best iteration is:
[2237]	valid_0's binary_logloss: 0.459325
-------------------- Metrics --------------------
Accuracy: 0.4225
Precision: 0.2960
Recall: 0.9688
F1 Score: 0.4534
ROC AUC: 0.7826
Training final model using all data...
Final model training completed.

In [64]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_nagoya.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_nagoya_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.550997
[200]	valid_0's binary_logloss: 0.531382
[300]	valid_0's binary_logloss: 0.522986
[400]	valid_0's binary_logloss: 0.519102
[500]	valid_0's binary_logloss: 0.517289
[600]	valid_0's binary_logloss: 0.516994
[700]	valid_0's binary_logloss: 0.517303
Early stopping, best iteration is:
[618]	valid_0's binary_logloss: 0.516923
-------------------- Metrics --------------------
Accuracy: 0.3835
Precision: 0.3275
Recall: 0.9922
F1 Score: 0.4924
ROC AUC: 0.7618
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.49941
[800]	valid_0's binary_logloss: 0.498478
[900]	valid_0's binary_logloss: 0.497905
[1000]	valid_0's binary_logloss: 0.497729
[1100]	valid_0's binary_logloss: 0.497902
Early stopping, best iteration is:
[1003]	valid_0's binary_logloss: 0.4977
-------------------- Metrics --------------------
Accuracy: 0.4227
Precision: 0.3244
Recall: 0.9743
F1 Score: 0.4867
ROC AUC: 0.7678
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.492252
[1200]	valid_0's binary_logloss: 0.491176
[1300]	valid_0's binary_logloss: 0.490539
[1400]	valid_0's binary_logloss: 0.490007
[1500]	valid_0's binary_logloss: 0.489681
[1600]	valid_0's binary_logloss: 0.4895
[1700]	valid_0's binary_logloss: 0.489529
Early stopping, best iteration is:
[1620]	valid_0's binary_logloss: 0.489458
-------------------- Metrics --------------------
Accuracy: 0.4233
Precision: 0.3205
Recall: 0.9717
F1 Score: 0.4820
ROC AUC: 0.7736
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's binary_logloss: 0.486548
[1800]	valid_0's binary_logloss: 0.485839
[1900]	valid_0's binary_logloss: 0.485548
[2000]	valid_0's binary_logloss: 0.485386
[2100]	valid_0's binary_logloss: 0.485159
[2200]	valid_0's binary_logloss: 0.485079
[2300]	valid_0's binary_logloss: 0.484963
[2400]	valid_0's binary_logloss: 0.485017
Early stopping, best iteration is:
[2363]	valid_0's binary_logloss: 0.484936
-------------------- Metrics --------------------
Accuracy: 0.4093
Precision: 0.3109
Recall: 0.9769
F1 Score: 0.4717
ROC AUC: 0.7722
Training final model using all data...
Final model training completed.

In [65]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_morioka.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_morioka_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.563659
[200]	valid_0's binary_logloss: 0.54335
[300]	valid_0's binary_logloss: 0.535476
[400]	valid_0's binary_logloss: 0.532041
[500]	valid_0's binary_logloss: 0.53046
[600]	valid_0's binary_logloss: 0.530657
Early stopping, best iteration is:
[524]	valid_0's binary_logloss: 0.530288
-------------------- Metrics --------------------
Accuracy: 0.3837
Precision: 0.3486
Recall: 0.9959
F1 Score: 0.5164
ROC AUC: 0.7640
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.522824
[700]	valid_0's binary_logloss: 0.52153
[800]	valid_0's binary_logloss: 0.521601
Early stopping, best iteration is:
[742]	valid_0's binary_logloss: 0.521226
-------------------- Metrics --------------------
Accuracy: 0.3869
Precision: 0.3428
Recall: 0.9915
F1 Score: 0.5095
ROC AUC: 0.7693
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.534663
[900]	valid_0's binary_logloss: 0.533012
[1000]	valid_0's binary_logloss: 0.532404
[1100]	valid_0's binary_logloss: 0.531867
[1200]	valid_0's binary_logloss: 0.531834
[1300]	valid_0's binary_logloss: 0.531754
Early stopping, best iteration is:
[1297]	valid_0's binary_logloss: 0.531668
-------------------- Metrics --------------------
Accuracy: 0.4018
Precision: 0.3475
Recall: 0.9901
F1 Score: 0.5144
ROC AUC: 0.7546
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.529727
[1400]	valid_0's binary_logloss: 0.528597
[1500]	valid_0's binary_logloss: 0.527898
[1600]	valid_0's binary_logloss: 0.527533
[1700]	valid_0's binary_logloss: 0.52729
[1800]	valid_0's binary_logloss: 0.527226
Early stopping, best iteration is:
[1729]	valid_0's binary_logloss: 0.527085
-------------------- Metrics --------------------
Accuracy: 0.3980
Precision: 0.3280
Recall: 0.9782
F1 Score: 0.4913
ROC AUC: 0.7448
Training final model using all data...
Final model training completed.

In [66]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_monbetu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_monbetu_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.537279
[200]	valid_0's binary_logloss: 0.512192
[300]	valid_0's binary_logloss: 0.502474
[400]	valid_0's binary_logloss: 0.498539
[500]	valid_0's binary_logloss: 0.497031
[600]	valid_0's binary_logloss: 0.496923
Early stopping, best iteration is:
[584]	valid_0's binary_logloss: 0.496748
-------------------- Metrics --------------------
Accuracy: 0.4423
Precision: 0.3575
Recall: 0.9846
F1 Score: 0.5246
ROC AUC: 0.7930
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.520788
[700]	valid_0's binary_logloss: 0.519919
[800]	valid_0's binary_logloss: 0.51958
[900]	valid_0's binary_logloss: 0.5192
[1000]	valid_0's binary_logloss: 0.519473
Early stopping, best iteration is:
[904]	valid_0's binary_logloss: 0.519193
-------------------- Metrics --------------------
Accuracy: 0.4455
Precision: 0.3638
Recall: 0.9800
F1 Score: 0.5306
ROC AUC: 0.7735
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.482507
[1100]	valid_0's binary_logloss: 0.482132
[1200]	valid_0's binary_logloss: 0.481953
[1300]	valid_0's binary_logloss: 0.482212
Early stopping, best iteration is:
[1213]	valid_0's binary_logloss: 0.481876
-------------------- Metrics --------------------
Accuracy: 0.4672
Precision: 0.3596
Recall: 0.9837
F1 Score: 0.5267
ROC AUC: 0.8012
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.484592
[1400]	valid_0's binary_logloss: 0.483876
[1500]	valid_0's binary_logloss: 0.483453
[1600]	valid_0's binary_logloss: 0.483561
Early stopping, best iteration is:
[1511]	valid_0's binary_logloss: 0.483417
-------------------- Metrics --------------------
Accuracy: 0.4684
Precision: 0.3634
Recall: 0.9794
F1 Score: 0.5301
ROC AUC: 0.8027
Training final model using all data...
Final model training completed.

In [67]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_mizusawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_mizusawa_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.577632
[200]	valid_0's binary_logloss: 0.564618
[300]	valid_0's binary_logloss: 0.559941
[400]	valid_0's binary_logloss: 0.558203
[500]	valid_0's binary_logloss: 0.557644
Early stopping, best iteration is:
[457]	valid_0's binary_logloss: 0.557477
-------------------- Metrics --------------------
Accuracy: 0.3486
Precision: 0.3293
Recall: 0.9972
F1 Score: 0.4952
ROC AUC: 0.7231
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.55008
[600]	valid_0's binary_logloss: 0.547214
[700]	valid_0's binary_logloss: 0.546036
[800]	valid_0's binary_logloss: 0.54576
[900]	valid_0's binary_logloss: 0.545776
[1000]	valid_0's binary_logloss: 0.545782
Early stopping, best iteration is:
[930]	valid_0's binary_logloss: 0.545638
-------------------- Metrics --------------------
Accuracy: 0.3642
Precision: 0.3321
Recall: 0.9930
F1 Score: 0.4977
ROC AUC: 0.7356
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.543486
[1100]	valid_0's binary_logloss: 0.542721
[1200]	valid_0's binary_logloss: 0.542406
[1300]	valid_0's binary_logloss: 0.542195
Early stopping, best iteration is:
[1284]	valid_0's binary_logloss: 0.542132
-------------------- Metrics --------------------
Accuracy: 0.3744
Precision: 0.3359
Recall: 0.9912
F1 Score: 0.5018
ROC AUC: 0.7417
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.522252
[1400]	valid_0's binary_logloss: 0.521482
[1500]	valid_0's binary_logloss: 0.521364
[1600]	valid_0's binary_logloss: 0.521358
Early stopping, best iteration is:
[1521]	valid_0's binary_logloss: 0.521227
-------------------- Metrics --------------------
Accuracy: 0.3789
Precision: 0.3249
Recall: 0.9853
F1 Score: 0.4887
ROC AUC: 0.7563
Training final model using all data...
Final model training completed.

In [68]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kouti.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight7.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kouti_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.538651
[200]	valid_0's binary_logloss: 0.516039
[300]	valid_0's binary_logloss: 0.506276
[400]	valid_0's binary_logloss: 0.500989
[500]	valid_0's binary_logloss: 0.498126
[600]	valid_0's binary_logloss: 0.496763
[700]	valid_0's binary_logloss: 0.495737
[800]	valid_0's binary_logloss: 0.495221
[900]	valid_0's binary_logloss: 0.495216
Early stopping, best iteration is:
[829]	valid_0's binary_logloss: 0.495092
-------------------- Metrics --------------------
Accuracy: 0.4162
Precision: 0.3406
Recall: 0.9874
F1 Score: 0.5064
ROC AUC: 0.7883
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.499847
[1000]	valid_0's binary_logloss: 0.498828
[1100]	valid_0's binary_logloss: 0.498225
[1200]	valid_0's binary_logloss: 0.497775
[1300]	valid_0's binary_logloss: 0.497429
[1400]	valid_0's binary_logloss: 0.497524
Early stopping, best iteration is:
[1321]	valid_0's binary_logloss: 0.497376
-------------------- Metrics --------------------
Accuracy: 0.4269
Precision: 0.3458
Recall: 0.9841
F1 Score: 0.5117
ROC AUC: 0.7859
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.506575
[1500]	valid_0's binary_logloss: 0.506137
[1600]	valid_0's binary_logloss: 0.50572
[1700]	valid_0's binary_logloss: 0.50561
[1800]	valid_0's binary_logloss: 0.505542
[1900]	valid_0's binary_logloss: 0.505455
[2000]	valid_0's binary_logloss: 0.505274
Early stopping, best iteration is:
[1972]	valid_0's binary_logloss: 0.505264
-------------------- Metrics --------------------
Accuracy: 0.4187
Precision: 0.3413
Recall: 0.9824
F1 Score: 0.5066
ROC AUC: 0.7761
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2000]	valid_0's binary_logloss: 0.495196
[2100]	valid_0's binary_logloss: 0.494682
[2200]	valid_0's binary_logloss: 0.494433
[2300]	valid_0's binary_logloss: 0.494401
Early stopping, best iteration is:
[2230]	valid_0's binary_logloss: 0.494346
-------------------- Metrics --------------------
Accuracy: 0.4321
Precision: 0.3488
Recall: 0.9834
F1 Score: 0.5150
ROC AUC: 0.7878
Training final model using all data...
Final model training completed.

In [69]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kawasaki.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kawasaki_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.522344
[200]	valid_0's binary_logloss: 0.506305
[300]	valid_0's binary_logloss: 0.499929
[400]	valid_0's binary_logloss: 0.49759
[500]	valid_0's binary_logloss: 0.496909
[600]	valid_0's binary_logloss: 0.496847
Early stopping, best iteration is:
[533]	valid_0's binary_logloss: 0.496678
-------------------- Metrics --------------------
Accuracy: 0.3850
Precision: 0.3017
Recall: 0.9819
F1 Score: 0.4616
ROC AUC: 0.7551
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.501682
[700]	valid_0's binary_logloss: 0.501153
[800]	valid_0's binary_logloss: 0.500883
[900]	valid_0's binary_logloss: 0.50072
Early stopping, best iteration is:
[883]	valid_0's binary_logloss: 0.500687
-------------------- Metrics --------------------
Accuracy: 0.3929
Precision: 0.3064
Recall: 0.9817
F1 Score: 0.4670
ROC AUC: 0.7532
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.503142
[1000]	valid_0's binary_logloss: 0.501051
[1100]	valid_0's binary_logloss: 0.500184
[1200]	valid_0's binary_logloss: 0.499858
[1300]	valid_0's binary_logloss: 0.499755
Early stopping, best iteration is:
[1256]	valid_0's binary_logloss: 0.499586
-------------------- Metrics --------------------
Accuracy: 0.3802
Precision: 0.3043
Recall: 0.9844
F1 Score: 0.4649
ROC AUC: 0.7560
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.496556
[1400]	valid_0's binary_logloss: 0.496347
[1500]	valid_0's binary_logloss: 0.496561
Early stopping, best iteration is:
[1400]	valid_0's binary_logloss: 0.496347
-------------------- Metrics --------------------
Accuracy: 0.3846
Precision: 0.3049
Recall: 0.9780
F1 Score: 0.4649
ROC AUC: 0.7600
Training final model using all data...
Final model training completed.

In [70]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kasamatu.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kasamatu_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.563659
[200]	valid_0's binary_logloss: 0.54335
[300]	valid_0's binary_logloss: 0.535476
[400]	valid_0's binary_logloss: 0.532041
[500]	valid_0's binary_logloss: 0.53046
[600]	valid_0's binary_logloss: 0.530657
Early stopping, best iteration is:
[524]	valid_0's binary_logloss: 0.530288
-------------------- Metrics --------------------
Accuracy: 0.3837
Precision: 0.3486
Recall: 0.9959
F1 Score: 0.5164
ROC AUC: 0.7640
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.522824
[700]	valid_0's binary_logloss: 0.52153
[800]	valid_0's binary_logloss: 0.521601
Early stopping, best iteration is:
[742]	valid_0's binary_logloss: 0.521226
-------------------- Metrics --------------------
Accuracy: 0.3869
Precision: 0.3428
Recall: 0.9915
F1 Score: 0.5095
ROC AUC: 0.7693
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.534663
[900]	valid_0's binary_logloss: 0.533012
[1000]	valid_0's binary_logloss: 0.532404
[1100]	valid_0's binary_logloss: 0.531867
[1200]	valid_0's binary_logloss: 0.531834
[1300]	valid_0's binary_logloss: 0.531754
Early stopping, best iteration is:
[1297]	valid_0's binary_logloss: 0.531668
-------------------- Metrics --------------------
Accuracy: 0.4018
Precision: 0.3475
Recall: 0.9901
F1 Score: 0.5144
ROC AUC: 0.7546
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.529727
[1400]	valid_0's binary_logloss: 0.528597
[1500]	valid_0's binary_logloss: 0.527898
[1600]	valid_0's binary_logloss: 0.527533
[1700]	valid_0's binary_logloss: 0.52729
[1800]	valid_0's binary_logloss: 0.527226
Early stopping, best iteration is:
[1729]	valid_0's binary_logloss: 0.527085
-------------------- Metrics --------------------
Accuracy: 0.3980
Precision: 0.3280
Recall: 0.9782
F1 Score: 0.4913
ROC AUC: 0.7448
Training final model using all data...
Final model training completed.

In [71]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_kanazawa.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_kanazawa_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.570881
[200]	valid_0's binary_logloss: 0.545863
[300]	valid_0's binary_logloss: 0.535447
[400]	valid_0's binary_logloss: 0.531216
[500]	valid_0's binary_logloss: 0.529398
[600]	valid_0's binary_logloss: 0.5292
[700]	valid_0's binary_logloss: 0.528927
Early stopping, best iteration is:
[690]	valid_0's binary_logloss: 0.528922
-------------------- Metrics --------------------
Accuracy: 0.4303
Precision: 0.3801
Recall: 0.9900
F1 Score: 0.5493
ROC AUC: 0.7787
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.541192
[800]	valid_0's binary_logloss: 0.537058
[900]	valid_0's binary_logloss: 0.535259
[1000]	valid_0's binary_logloss: 0.534614
[1100]	valid_0's binary_logloss: 0.534269
[1200]	valid_0's binary_logloss: 0.534257
Early stopping, best iteration is:
[1122]	valid_0's binary_logloss: 0.534177
-------------------- Metrics --------------------
Accuracy: 0.4369
Precision: 0.3808
Recall: 0.9916
F1 Score: 0.5503
ROC AUC: 0.7711
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.527337
[1300]	valid_0's binary_logloss: 0.526146
[1400]	valid_0's binary_logloss: 0.525514
[1500]	valid_0's binary_logloss: 0.525205
[1600]	valid_0's binary_logloss: 0.52502
[1700]	valid_0's binary_logloss: 0.524817
[1800]	valid_0's binary_logloss: 0.52462
Early stopping, best iteration is:
[1785]	valid_0's binary_logloss: 0.524584
-------------------- Metrics --------------------
Accuracy: 0.4472
Precision: 0.3836
Recall: 0.9865
F1 Score: 0.5524
ROC AUC: 0.7813
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1800]	valid_0's binary_logloss: 0.526142
[1900]	valid_0's binary_logloss: 0.525474
Early stopping, best iteration is:
[1858]	valid_0's binary_logloss: 0.525373
-------------------- Metrics --------------------
Accuracy: 0.4316
Precision: 0.3715
Recall: 0.9859
F1 Score: 0.5397
ROC AUC: 0.7741
Training final model using all data...
Final model training completed.

In [72]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_funabasi.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight4.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_weight_funabasi_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.527388
[200]	valid_0's binary_logloss: 0.509087
[300]	valid_0's binary_logloss: 0.502492
[400]	valid_0's binary_logloss: 0.500589
[500]	valid_0's binary_logloss: 0.500612
Early stopping, best iteration is:
[414]	valid_0's binary_logloss: 0.5003
-------------------- Metrics --------------------
Accuracy: 0.3675
Precision: 0.3072
Recall: 0.9893
F1 Score: 0.4688
ROC AUC: 0.7667
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.512373
[600]	valid_0's binary_logloss: 0.51121
[700]	valid_0's binary_logloss: 0.510643
[800]	valid_0's binary_logloss: 0.510465
[900]	valid_0's binary_logloss: 0.510557
Early stopping, best iteration is:
[826]	valid_0's binary_logloss: 0.51044
-------------------- Metrics --------------------
Accuracy: 0.3940
Precision: 0.3212
Recall: 0.9805
F1 Score: 0.4839
ROC AUC: 0.7599
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.518593
[1000]	valid_0's binary_logloss: 0.51806
[1100]	valid_0's binary_logloss: 0.518014
[1200]	valid_0's binary_logloss: 0.517837
[1300]	valid_0's binary_logloss: 0.517782
Early stopping, best iteration is:
[1238]	valid_0's binary_logloss: 0.517667
-------------------- Metrics --------------------
Accuracy: 0.4110
Precision: 0.3324
Recall: 0.9836
F1 Score: 0.4969
ROC AUC: 0.7560
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.504216
[1400]	valid_0's binary_logloss: 0.503965
[1500]	valid_0's binary_logloss: 0.50341
[1600]	valid_0's binary_logloss: 0.503228
[1700]	valid_0's binary_logloss: 0.503085
[1800]	valid_0's binary_logloss: 0.503326
Early stopping, best iteration is:
[1722]	valid_0's binary_logloss: 0.502983
-------------------- Metrics --------------------
Accuracy: 0.4142
Precision: 0.3328
Recall: 0.9818
F1 Score: 0.4971
ROC AUC: 0.7707
Training final model using all data...
Final model training completed.

In [ ]:
#評価

In [232]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_sonoda_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_sonoda_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_sonoda_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_sonoda_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_sonoda_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.346154,0.584615,0.500000,0.823077
1,1,複勝,0.769231,0.930769,0.769231,0.846154
2,2,ワイド,0.576923,1.038462,0.615385,0.923077
3,2,単勝,0.538462,0.669231,0.692308,0.765385
4,2,複勝,0.923077,0.967308,0.923077,0.876923
5,2,馬単,0.384615,1.257692,0.384615,0.913462
6,2,馬連,0.384615,1.246154,0.384615,0.930769
7,3,ワイド,0.807692,0.652564,0.769231,0.862821
8,3,三連単,0.115385,0.134615,0.269231,1.280128
9,3,三連複,0.115385,0.261538,0.269231,1.284615
10,3,単勝,0.692308,0.641026,0.807692,0.742308
11,3,複勝,1.000000,0.810256,0.961538,0.791026
12,3,馬単,0.538462,0.615385,0.461538,0.529487
13,3,馬連,0.538462,0.692308,0.461538,0.453846
14,4,ワイド,1.000000,0.813462,0.961538,0.684615
15,4,三連単,0.384615,0.488141,0.423077,0.470513
16,4,三連複,0.384615,0.538462,0.423077,0.537500
17,4,単勝,0.730769,0.510577,0.884615,0.665385
18,4,複勝,1.000000,0.848077,1.000000,0.765385
19,4,馬単,0.730769,0.648397,0.576923,0.379487
20,4,馬連,0.730769,0.894231,0.576923,0.396795
21,5,ワイド,1.000000,0.811538,0.961538,0.820385
22,5,三連単,0.692308,0.856667,0.769231,1.031731
23,5,三連複,0.692308,0.698846,0.769231,0.836154
24,5,単勝,0.884615,0.700769,0.961538,0.776154
25,5,複勝,1.000000,0.794615,1.000000,0.778462
26,5,馬単,0.884615,0.729808,0.884615,0.763269
27,5,馬連,0.884615,0.804615,0.884615,0.819615

In [233]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_urawa_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_urawa_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_urawa_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_urawa_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_urawa_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.235602,0.631937,0.267016,0.595812
1,1,複勝,0.560209,0.788482,0.664921,0.853403
2,2,ワイド,0.308901,1.016754,0.329843,0.757592
3,2,単勝,0.424084,0.762565,0.481675,0.703927
4,2,複勝,0.759162,0.828796,0.869110,0.815445
5,2,馬単,0.125654,0.697644,0.141361,0.736126
6,2,馬連,0.125654,0.759686,0.141361,0.688482
7,3,ワイド,0.507853,0.935951,0.570681,0.808726
8,3,三連単,0.120419,1.535689,0.136126,1.076178
9,3,三連複,0.120419,1.564921,0.136126,0.936649
10,3,単勝,0.528796,0.722513,0.633508,0.751309
11,3,複勝,0.900524,0.838394,0.989529,0.851134
12,3,馬単,0.293194,0.803578,0.371728,0.881501
13,3,馬連,0.293194,0.848168,0.371728,0.856370
14,4,ワイド,0.670157,0.904014,0.801047,0.858639
15,4,三連単,0.225131,1.245899,0.298429,0.796401
16,4,三連複,0.225131,1.211257,0.298429,0.790969
17,4,単勝,0.633508,0.739660,0.748691,0.792932
18,4,複勝,0.968586,0.812958,0.989529,0.841885
19,4,馬単,0.403141,0.686169,0.539267,0.852705
20,4,馬連,0.403141,0.686911,0.539267,0.832548
21,5,ワイド,0.827225,0.883194,0.895288,0.812251
22,5,三連単,0.387435,1.074014,0.450262,0.834127
23,5,三連複,0.387435,0.998063,0.450262,0.865707
24,5,単勝,0.774869,0.880314,0.832461,0.828901
25,5,複勝,0.989529,0.814555,0.994764,0.797801
26,5,馬単,0.581152,0.833272,0.654450,0.780000
27,5,馬連,0.581152,0.779319,0.654450,0.744188

In [234]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_saga_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_saga_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_saga_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_saga_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_saga_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.275,0.652500,0.450,0.725000
1,1,複勝,0.750,0.995000,0.775,0.847500
2,2,ワイド,0.425,1.007500,0.600,0.970000
3,2,単勝,0.525,0.811250,0.725,0.837500
4,2,複勝,0.825,0.843750,0.875,0.887500
5,2,馬単,0.225,0.993750,0.250,0.637500
6,2,馬連,0.225,1.040000,0.250,0.665000
7,3,ワイド,0.650,0.679167,0.725,0.660000
8,3,三連単,0.075,0.483750,0.150,0.282500
9,3,三連複,0.075,0.290000,0.150,0.575000
10,3,単勝,0.675,0.897500,0.850,0.867500
11,3,複勝,0.975,0.853333,0.975,0.795833
12,3,馬単,0.350,0.769583,0.450,0.497083
13,3,馬連,0.350,0.879167,0.450,0.558333
14,4,ワイド,0.900,0.872917,0.950,0.832917
15,4,三連単,0.325,0.704063,0.375,0.649375
16,4,三連複,0.325,0.720625,0.375,0.701875
17,4,単勝,0.825,0.865625,0.875,0.718125
18,4,複勝,1.000,0.860625,0.975,0.831250
19,4,馬単,0.500,0.684167,0.650,0.685208
20,4,馬連,0.500,0.807500,0.650,0.779583
21,5,ワイド,0.950,1.024750,1.000,0.856750
22,5,三連単,0.625,1.257833,0.600,1.350417
23,5,三連複,0.625,1.455000,0.600,1.178000
24,5,単勝,0.925,0.778000,0.900,0.655500
25,5,複勝,1.000,0.875000,1.000,0.823500
26,5,馬単,0.775,0.878875,0.750,0.834000
27,5,馬連,0.775,1.027000,0.750,0.874250

In [235]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_ooi_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_ooi_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_ooi_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_ooi_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_ooi_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.316832,0.917822,0.356436,0.792079
1,1,複勝,0.633663,0.916832,0.693069,0.876238
2,2,ワイド,0.326733,1.034653,0.405941,0.882178
3,2,単勝,0.435644,0.679208,0.584158,0.837624
4,2,複勝,0.811881,0.886634,0.910891,0.886139
5,2,馬単,0.148515,0.884653,0.207921,0.825743
6,2,馬連,0.148515,0.889109,0.207921,0.890099
7,3,ワイド,0.564356,1.276898,0.663366,0.772277
8,3,三連単,0.148515,2.546535,0.089109,0.422772
9,3,三連複,0.148515,2.525743,0.089109,0.544554
10,3,単勝,0.603960,0.875578,0.693069,0.766007
11,3,複勝,0.930693,0.935314,0.960396,0.823762
12,3,馬単,0.366337,1.395545,0.346535,0.644719
13,3,馬連,0.366337,1.514521,0.346535,0.665017
14,4,ワイド,0.712871,0.930858,0.792079,0.787624
15,4,三連単,0.267327,1.103094,0.306931,0.765264
16,4,三連複,0.267327,1.050495,0.306931,0.828218
17,4,単勝,0.742574,0.899752,0.821782,0.803713
18,4,複勝,0.970297,0.861386,0.980198,0.794554
19,4,馬単,0.524752,1.090842,0.514851,0.691172
20,4,馬連,0.524752,1.121617,0.514851,0.688779
21,5,ワイド,0.811881,0.961188,0.861386,0.736931
22,5,三連単,0.405941,1.069637,0.475248,0.708135
23,5,三連複,0.405941,1.044455,0.475248,0.708317
24,5,単勝,0.811881,0.815842,0.871287,0.765743
25,5,複勝,0.980198,0.865743,0.990099,0.765149
26,5,馬単,0.603960,0.930594,0.683168,0.774406
27,5,馬連,0.603960,0.945842,0.683168,0.777723

In [236]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nagoya_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nagoya_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nagoya_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nagoya_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_nagoya_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.372093,1.144186,0.348837,0.582558
1,1,複勝,0.662791,0.853488,0.755814,0.868605
2,2,ワイド,0.406977,1.140698,0.406977,0.695349
3,2,単勝,0.558140,0.935465,0.604651,0.757558
4,2,複勝,0.872093,0.929070,0.930233,0.827907
5,2,馬単,0.209302,0.893023,0.267442,0.824419
6,2,馬連,0.209302,0.954651,0.267442,0.890698
7,3,ワイド,0.581395,1.070155,0.697674,0.782558
8,3,三連単,0.174419,1.847481,0.139535,0.843411
9,3,三連複,0.174419,2.003488,0.139535,0.675581
10,3,単勝,0.639535,0.805426,0.720930,0.725194
11,3,複勝,0.965116,0.928295,0.988372,0.823256
12,3,馬単,0.383721,0.838178,0.465116,0.947481
13,3,馬連,0.383721,0.823643,0.465116,0.951163
14,4,ワイド,0.755814,1.077907,0.872093,0.896318
15,4,三連単,0.348837,1.196366,0.360465,0.998353
16,4,三連複,0.348837,1.306105,0.360465,1.046802
17,4,単勝,0.732558,0.846802,0.802326,0.776744
18,4,複勝,0.988372,0.898256,1.000000,0.838663
19,4,馬単,0.558140,1.381977,0.651163,0.982558
20,4,馬連,0.558140,1.521512,0.651163,0.936628
21,5,ワイド,0.872093,1.000581,0.918605,0.873721
22,5,三連単,0.511628,0.854457,0.604651,0.921047
23,5,三連複,0.511628,0.918256,0.604651,0.917209
24,5,単勝,0.813953,0.815814,0.860465,0.786977
25,5,複勝,1.000000,0.850698,1.000000,0.812791
26,5,馬単,0.639535,0.987616,0.779070,0.838314
27,5,馬連,0.639535,1.038488,0.779070,0.769767

In [237]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_morioka_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_morioka_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_morioka_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_morioka_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_morioka_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.380952,0.790476,0.380952,0.619048
1,1,複勝,0.666667,0.900000,0.714286,0.795238
2,2,ワイド,0.333333,0.866667,0.476190,0.752381
3,2,単勝,0.523810,0.702381,0.666667,0.802381
4,2,複勝,0.809524,0.757143,1.000000,0.919048
5,2,馬単,0.238095,2.009524,0.190476,0.588095
6,2,馬連,0.238095,2.004762,0.190476,0.642857
7,3,ワイド,0.380952,0.444444,0.857143,0.879365
8,3,三連単,0.095238,0.390476,0.142857,0.420635
9,3,三連複,0.095238,0.309524,0.142857,0.380952
10,3,単勝,0.619048,0.557143,0.761905,0.663492
11,3,複勝,0.952381,0.666667,1.000000,0.893651
12,3,馬単,0.238095,0.669841,0.333333,0.388095
13,3,馬連,0.238095,0.668254,0.333333,0.393651
14,4,ワイド,0.666667,0.511111,0.952381,0.801587
15,4,三連単,0.238095,0.426984,0.380952,0.583135
16,4,三連複,0.238095,0.547619,0.380952,0.783333
17,4,単勝,0.714286,0.471429,0.809524,0.566667
18,4,複勝,0.952381,0.652381,1.000000,0.828571
19,4,馬単,0.476190,0.503175,0.523810,0.457143
20,4,馬連,0.476190,0.542857,0.523810,0.493651
21,5,ワイド,0.904762,0.762381,0.952381,0.810476
22,5,三連単,0.571429,0.654921,0.619048,0.755476
23,5,三連複,0.571429,0.722381,0.619048,0.942381
24,5,単勝,0.857143,0.820000,0.857143,0.521905
25,5,複勝,0.952381,0.743810,1.000000,0.768571
26,5,馬単,0.714286,0.579286,0.714286,0.584048
27,5,馬連,0.714286,0.539048,0.714286,0.677143

In [238]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_monbetu_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_monbetu_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_monbetu_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_monbetu_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_monbetu_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.500000,0.858824,0.500000,0.776471
1,1,複勝,0.764706,0.902941,0.882353,1.005882
2,2,ワイド,0.500000,0.952941,0.647059,1.008824
3,2,単勝,0.676471,0.785294,0.794118,0.913235
4,2,複勝,1.000000,0.894118,0.970588,0.933824
5,2,馬単,0.205882,0.533824,0.441176,1.398529
6,2,馬連,0.205882,0.617647,0.441176,1.361765
7,3,ワイド,0.852941,0.996078,0.911765,0.947059
8,3,三連単,0.205882,0.861765,0.294118,0.816667
9,3,三連複,0.205882,1.173529,0.294118,0.926471
10,3,単勝,0.823529,0.881373,0.882353,0.785294
11,3,複勝,1.000000,0.850980,1.000000,0.869608
12,3,馬単,0.558824,0.766176,0.676471,0.846078
13,3,馬連,0.558824,0.771569,0.676471,0.837255
14,4,ワイド,0.911765,1.203431,1.000000,0.921569
15,4,三連単,0.617647,1.937377,0.647059,1.563971
16,4,三連複,0.617647,1.748529,0.647059,1.079412
17,4,単勝,0.882353,0.850735,0.941176,0.815441
18,4,複勝,1.000000,0.855147,1.000000,0.816912
19,4,馬単,0.705882,1.229412,0.852941,1.265196
20,4,馬連,0.705882,0.863235,0.852941,0.991176
21,5,ワイド,0.970588,0.877941,1.000000,0.885588
22,5,三連単,0.794118,0.898529,0.823529,0.885000
23,5,三連複,0.794118,0.876176,0.823529,0.884118
24,5,単勝,0.941176,0.738235,1.000000,0.797647
25,5,複勝,1.000000,0.747647,1.000000,0.772353
26,5,馬単,0.852941,0.803676,0.941176,0.881324
27,5,馬連,0.852941,0.577647,0.941176,0.690588

In [239]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_mizusawa_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_mizusawa_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_mizusawa_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_mizusawa_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_mizusawa_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.28,0.620000,0.52,0.976000
1,1,複勝,0.68,0.964000,0.76,0.912000
2,2,ワイド,0.36,0.712000,0.40,0.604000
3,2,単勝,0.64,1.098000,0.68,0.888000
4,2,複勝,0.92,0.930000,0.88,0.776000
5,2,馬単,0.24,1.462000,0.16,0.568000
6,2,馬連,0.24,1.444000,0.16,0.452000
7,3,ワイド,0.68,0.994667,0.60,0.609333
8,3,三連単,0.12,0.879333,0.16,0.731333
9,3,三連複,0.12,0.864000,0.16,0.664000
10,3,単勝,0.72,0.824000,0.80,0.809333
11,3,複勝,1.00,0.993333,0.96,0.733333
12,3,馬単,0.36,0.801333,0.36,0.700000
13,3,馬連,0.36,0.814667,0.36,0.642667
14,4,ワイド,0.84,1.303333,0.88,0.652667
15,4,三連単,0.44,2.552667,0.28,0.313667
16,4,三連複,0.44,3.209000,0.28,0.371000
17,4,単勝,0.84,0.856000,0.88,0.764000
18,4,複勝,1.00,0.968000,1.00,0.808000
19,4,馬単,0.56,1.267667,0.56,0.936667
20,4,馬連,0.56,1.294667,0.56,0.954000
21,5,ワイド,0.92,0.900400,0.96,0.859200
22,5,三連単,0.52,1.068400,0.64,0.523267
23,5,三連複,0.52,1.399200,0.64,0.699600
24,5,単勝,0.88,0.703200,0.92,0.694400
25,5,複勝,1.00,0.835200,1.00,0.896000
26,5,馬単,0.68,0.830200,0.84,0.815400
27,5,馬連,0.68,0.879200,0.84,0.896000

In [240]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kouti_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kouti_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kouti_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kouti_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_kouti_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.43750,0.843750,0.46875,0.662500
1,1,複勝,0.71875,0.834375,0.78125,0.850000
2,2,ワイド,0.31250,0.525000,0.53125,0.837500
3,2,単勝,0.59375,0.728125,0.71875,0.762500
4,2,複勝,0.84375,0.704688,0.87500,0.825000
5,2,馬単,0.18750,0.557813,0.31250,0.662500
6,2,馬連,0.18750,0.475000,0.31250,0.725000
7,3,ワイド,0.59375,0.798958,0.75000,0.705208
8,3,三連単,0.15625,0.416667,0.15625,0.206250
9,3,三連複,0.15625,0.584375,0.15625,0.490625
10,3,単勝,0.78125,0.697917,0.81250,0.719792
11,3,複勝,0.96875,0.808333,1.00000,0.805208
12,3,馬単,0.31250,0.339062,0.43750,0.438021
13,3,馬連,0.31250,0.364583,0.43750,0.429167
14,4,ワイド,0.75000,0.640104,0.87500,0.777083
15,4,三連単,0.28125,0.332422,0.34375,0.455339
16,4,三連複,0.28125,0.367188,0.34375,0.681250
17,4,単勝,0.84375,0.591406,0.87500,0.649219
18,4,複勝,0.96875,0.741406,1.00000,0.778906
19,4,馬単,0.43750,0.458333,0.56250,0.404427
20,4,馬連,0.43750,0.461979,0.56250,0.409896
21,5,ワイド,0.84375,0.701562,0.93750,0.748437
22,5,三連単,0.46875,0.609167,0.53125,0.730469
23,5,三連複,0.46875,0.559063,0.53125,0.764687
24,5,単勝,0.87500,0.738750,0.90625,0.596875
25,5,複勝,0.96875,0.714375,1.00000,0.758125
26,5,馬単,0.68750,0.621250,0.71875,0.706562
27,5,馬連,0.68750,0.584688,0.71875,0.701562

In [241]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kawasaki_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kawasaki_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kawasaki_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kawasaki_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_kawasaki_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.345679,0.980658,0.378601,0.812757
1,1,複勝,0.650206,0.916872,0.670782,0.829630
2,2,ワイド,0.279835,0.797531,0.316872,0.703704
3,2,単勝,0.502058,0.864403,0.555556,0.755967
4,2,複勝,0.851852,0.860082,0.880658,0.816255
5,2,馬単,0.123457,0.653704,0.144033,0.608848
6,2,馬連,0.123457,0.648971,0.144033,0.601235
7,3,ワイド,0.572016,0.951440,0.646091,0.890809
8,3,三連単,0.082305,0.524280,0.111111,0.834774
9,3,三連複,0.082305,0.770370,0.111111,1.005761
10,3,単勝,0.621399,0.868724,0.707819,0.818519
11,3,複勝,0.934156,0.893278,0.958848,0.858162
12,3,馬単,0.292181,0.972497,0.358025,0.779973
13,3,馬連,0.292181,1.089849,0.358025,0.759945
14,4,ワイド,0.732510,0.904184,0.810700,0.845062
15,4,三連単,0.242798,0.922599,0.275720,0.856310
16,4,三連複,0.242798,0.966667,0.275720,0.891872
17,4,単勝,0.761317,0.902263,0.802469,0.799897
18,4,複勝,0.975309,0.864609,0.991770,0.826749
19,4,馬単,0.469136,0.942627,0.526749,0.790466
20,4,馬連,0.469136,0.983265,0.526749,0.772634
21,5,ワイド,0.851852,0.900247,0.909465,0.899259
22,5,三連単,0.386831,1.016427,0.497942,0.895041
23,5,三連複,0.386831,0.978272,0.497942,0.938272
24,5,単勝,0.835391,0.866749,0.880658,0.819177
25,5,複勝,0.995885,0.838601,0.995885,0.817778
26,5,馬単,0.584362,0.863416,0.691358,0.827469
27,5,馬連,0.584362,0.885556,0.691358,0.810741

In [242]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kasamatu_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kasamatu_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kasamatu_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kasamatu_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_kasamatu_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.380952,0.790476,0.380952,0.619048
1,1,複勝,0.666667,0.900000,0.714286,0.795238
2,2,ワイド,0.333333,0.866667,0.476190,0.752381
3,2,単勝,0.523810,0.702381,0.666667,0.802381
4,2,複勝,0.809524,0.757143,1.000000,0.919048
5,2,馬単,0.238095,2.009524,0.190476,0.588095
6,2,馬連,0.238095,2.004762,0.190476,0.642857
7,3,ワイド,0.380952,0.444444,0.857143,0.879365
8,3,三連単,0.095238,0.390476,0.142857,0.420635
9,3,三連複,0.095238,0.309524,0.142857,0.380952
10,3,単勝,0.619048,0.557143,0.761905,0.663492
11,3,複勝,0.952381,0.666667,1.000000,0.893651
12,3,馬単,0.238095,0.669841,0.333333,0.388095
13,3,馬連,0.238095,0.668254,0.333333,0.393651
14,4,ワイド,0.666667,0.511111,0.952381,0.801587
15,4,三連単,0.238095,0.426984,0.380952,0.583135
16,4,三連複,0.238095,0.547619,0.380952,0.783333
17,4,単勝,0.714286,0.471429,0.809524,0.566667
18,4,複勝,0.952381,0.652381,1.000000,0.828571
19,4,馬単,0.476190,0.503175,0.523810,0.457143
20,4,馬連,0.476190,0.542857,0.523810,0.493651
21,5,ワイド,0.904762,0.762381,0.952381,0.810476
22,5,三連単,0.571429,0.654921,0.619048,0.755476
23,5,三連複,0.571429,0.722381,0.619048,0.942381
24,5,単勝,0.857143,0.820000,0.857143,0.521905
25,5,複勝,0.952381,0.743810,1.000000,0.768571
26,5,馬単,0.714286,0.579286,0.714286,0.584048
27,5,馬連,0.714286,0.539048,0.714286,0.677143

In [243]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kanazawa_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kanazawa_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kanazawa_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kanazawa_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_kanazawa_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.431034,0.603448,0.637931,0.937931
1,1,複勝,0.672414,0.750000,0.844828,0.929310
2,2,ワイド,0.465517,0.794828,0.551724,0.781034
3,2,単勝,0.724138,0.785345,0.793103,0.720690
4,2,複勝,0.879310,0.804310,0.948276,0.846552
5,2,馬単,0.310345,0.907759,0.327586,0.672414
6,2,馬連,0.310345,0.855172,0.327586,0.779310
7,3,ワイド,0.793103,0.932184,0.844828,0.841379
8,3,三連単,0.189655,0.608908,0.224138,0.727586
9,3,三連複,0.189655,0.979310,0.224138,0.787931
10,3,単勝,0.810345,0.629310,0.827586,0.589655
11,3,複勝,0.965517,0.854023,0.965517,0.816092
12,3,馬単,0.551724,0.674425,0.568966,0.654598
13,3,馬連,0.551724,0.782759,0.568966,0.738506
14,4,ワイド,0.844828,0.947126,0.896552,0.833046
15,4,三連単,0.448276,0.880460,0.517241,0.868247
16,4,三連複,0.448276,1.303448,0.517241,0.909483
17,4,単勝,0.844828,0.547414,0.931034,0.660345
18,4,複勝,0.982759,0.796552,1.000000,0.787069
19,4,馬単,0.672414,0.625575,0.689655,0.516379
20,4,馬連,0.672414,0.733908,0.689655,0.544828
21,5,ワイド,0.913793,0.708103,0.931034,0.737931
22,5,三連単,0.586207,0.435460,0.724138,0.548305
23,5,三連複,0.586207,0.632759,0.724138,0.587241
24,5,単勝,0.913793,0.560690,0.965517,0.613448
25,5,複勝,1.000000,0.737931,1.000000,0.765172
26,5,馬単,0.741379,0.447845,0.810345,0.484741
27,5,馬連,0.741379,0.497069,0.810345,0.520172

In [244]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_funabasi_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_funabasi_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_funabasi_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_funabasi_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_funabasi_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.335938,0.982031,0.375000,0.820312
1,1,複勝,0.622047,0.944882,0.661417,0.864567
2,2,ワイド,0.367188,0.934375,0.351562,0.770312
3,2,単勝,0.500000,0.802344,0.570312,0.787109
4,2,複勝,0.850394,0.914567,0.874016,0.844094
5,2,馬単,0.148438,0.782031,0.195312,0.934375
6,2,馬連,0.148438,0.817187,0.195312,0.922656
7,3,ワイド,0.601562,0.916406,0.656250,0.761198
8,3,三連単,0.117188,0.977214,0.093750,0.639583
9,3,三連複,0.117188,1.026563,0.093750,0.703906
10,3,単勝,0.648438,0.781771,0.687500,0.723698
11,3,複勝,0.897638,0.844882,0.944882,0.825197
12,3,馬単,0.343750,0.941927,0.351562,0.750260
13,3,馬連,0.343750,0.992448,0.351562,0.755990
14,4,ワイド,0.734375,0.780859,0.773438,0.691927
15,4,三連単,0.234375,0.952832,0.265625,0.623633
16,4,三連複,0.234375,0.939453,0.265625,0.599805
17,4,単勝,0.750000,0.808203,0.765625,0.685742
18,4,複勝,0.952756,0.815945,0.968504,0.768110
19,4,馬単,0.468750,0.836198,0.515625,0.710677
20,4,馬連,0.468750,0.838672,0.515625,0.726432
21,5,ワイド,0.835938,0.844453,0.867188,0.692969
22,5,三連単,0.414062,1.300521,0.445312,0.593607
23,5,三連複,0.414062,0.951328,0.445312,0.608281
24,5,単勝,0.835938,1.043906,0.828125,0.689063
25,5,複勝,0.976378,0.818583,0.992126,0.761890
26,5,馬単,0.625000,1.093125,0.664062,0.659023
27,5,馬連,0.625000,0.987656,0.664062,0.676094

In [109]:
#展開

In [245]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_sonoda_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_sonoda_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_sonoda_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_sonoda_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_sonoda_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.307692,0.665385,0.500000,0.823077
1,1,複勝,0.653846,0.807692,0.769231,0.846154
2,2,ワイド,0.384615,0.861538,0.615385,0.923077
3,2,単勝,0.500000,0.540385,0.692308,0.765385
4,2,複勝,0.884615,0.848077,0.923077,0.876923
5,2,馬単,0.192308,0.642308,0.384615,0.913462
6,2,馬連,0.192308,0.696154,0.384615,0.930769
7,3,ワイド,0.615385,0.898718,0.769231,0.862821
8,3,三連単,0.153846,0.511538,0.269231,1.280128
9,3,三連複,0.153846,0.826923,0.269231,1.284615
10,3,単勝,0.576923,0.494872,0.807692,0.742308
11,3,複勝,0.961538,0.773077,0.961538,0.791026
12,3,馬単,0.307692,0.369872,0.461538,0.529487
13,3,馬連,0.307692,0.342308,0.461538,0.453846
14,4,ワイド,0.846154,0.785897,0.961538,0.684615
15,4,三連単,0.307692,0.371635,0.423077,0.470513
16,4,三連複,0.307692,0.607692,0.423077,0.537500
17,4,単勝,0.653846,0.477885,0.884615,0.665385
18,4,複勝,1.000000,0.748077,1.000000,0.765385
19,4,馬単,0.500000,0.316987,0.576923,0.379487
20,4,馬連,0.500000,0.358333,0.576923,0.396795
21,5,ワイド,0.961538,0.688462,0.961538,0.820385
22,5,三連単,0.500000,0.371218,0.769231,1.031731
23,5,三連複,0.500000,0.426923,0.769231,0.836154
24,5,単勝,0.730769,0.453846,0.961538,0.776154
25,5,複勝,1.000000,0.737692,1.000000,0.778462
26,5,馬単,0.730769,0.431538,0.884615,0.763269
27,5,馬連,0.730769,0.583846,0.884615,0.819615

In [246]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_urawa_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_urawa_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_urawa_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_urawa_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_urawa_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.251309,0.785864,0.267016,0.595812
1,1,複勝,0.586387,0.840314,0.664921,0.853403
2,2,ワイド,0.329843,1.292670,0.329843,0.757592
3,2,単勝,0.434555,0.896859,0.481675,0.703927
4,2,複勝,0.806283,0.917277,0.869110,0.815445
5,2,馬単,0.109948,0.771728,0.141361,0.736126
6,2,馬連,0.109948,0.900524,0.141361,0.688482
7,3,ワイド,0.534031,0.969634,0.570681,0.808726
8,3,三連単,0.099476,1.148168,0.136126,1.076178
9,3,三連複,0.099476,1.052880,0.136126,0.936649
10,3,単勝,0.534031,0.808028,0.633508,0.751309
11,3,複勝,0.931937,0.890750,0.989529,0.851134
12,3,馬単,0.298429,0.994939,0.371728,0.881501
13,3,馬連,0.298429,1.019721,0.371728,0.856370
14,4,ワイド,0.738220,0.962129,0.801047,0.858639
15,4,三連単,0.230366,0.977487,0.298429,0.796401
16,4,三連複,0.230366,0.948037,0.298429,0.790969
17,4,単勝,0.659686,0.854319,0.748691,0.792932
18,4,複勝,0.963351,0.870026,0.989529,0.841885
19,4,馬単,0.450262,0.903054,0.539267,0.852705
20,4,馬連,0.450262,0.885689,0.539267,0.832548
21,5,ワイド,0.869110,0.969634,0.895288,0.812251
22,5,三連単,0.424084,0.988098,0.450262,0.834127
23,5,三連複,0.424084,1.041204,0.450262,0.865707
24,5,単勝,0.774869,0.867435,0.832461,0.828901
25,5,複勝,0.984293,0.872251,0.994764,0.797801
26,5,馬単,0.643979,0.923168,0.654450,0.780000
27,5,馬連,0.643979,0.910052,0.654450,0.744188

In [247]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_saga_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_saga_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_saga_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_saga_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_saga_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.300,0.680000,0.450,0.725000
1,1,複勝,0.700,0.877500,0.775,0.847500
2,2,ワイド,0.325,0.920000,0.600,0.970000
3,2,単勝,0.475,0.688750,0.725,0.837500
4,2,複勝,0.850,0.871250,0.875,0.887500
5,2,馬単,0.125,0.537500,0.250,0.637500
6,2,馬連,0.125,0.602500,0.250,0.665000
7,3,ワイド,0.550,0.789167,0.725,0.660000
8,3,三連単,0.075,2.788333,0.150,0.282500
9,3,三連複,0.075,1.647500,0.150,0.575000
10,3,単勝,0.625,0.728333,0.850,0.867500
11,3,複勝,0.975,0.850000,0.975,0.795833
12,3,馬単,0.275,1.205000,0.450,0.497083
13,3,馬連,0.275,1.200833,0.450,0.558333
14,4,ワイド,0.800,0.939583,0.950,0.832917
15,4,三連単,0.275,1.094271,0.375,0.649375
16,4,三連複,0.275,1.231875,0.375,0.701875
17,4,単勝,0.775,0.729375,0.875,0.718125
18,4,複勝,1.000,0.858750,0.975,0.831250
19,4,馬単,0.475,1.303750,0.650,0.685208
20,4,馬連,0.475,1.204167,0.650,0.779583
21,5,ワイド,0.900,0.693500,1.000,0.856750
22,5,三連単,0.375,0.564875,0.600,1.350417
23,5,三連複,0.375,0.599750,0.600,1.178000
24,5,単勝,0.825,0.618500,0.900,0.655500
25,5,複勝,1.000,0.776500,1.000,0.823500
26,5,馬単,0.625,0.966625,0.750,0.834000
27,5,馬連,0.625,0.956000,0.750,0.874250

In [248]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_ooi_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_ooi_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_ooi_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_ooi_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_ooi_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.247525,0.770297,0.356436,0.792079
1,1,複勝,0.603960,0.933663,0.693069,0.876238
2,2,ワイド,0.306931,1.229703,0.405941,0.882178
3,2,単勝,0.366337,0.553960,0.584158,0.837624
4,2,複勝,0.772277,0.871287,0.910891,0.886139
5,2,馬単,0.099010,0.412376,0.207921,0.825743
6,2,馬連,0.099010,0.507921,0.207921,0.890099
7,3,ワイド,0.485149,0.950165,0.663366,0.772277
8,3,三連単,0.089109,2.456106,0.089109,0.422772
9,3,三連複,0.089109,2.583168,0.089109,0.544554
10,3,単勝,0.524752,0.703630,0.693069,0.766007
11,3,複勝,0.871287,0.798350,0.960396,0.823762
12,3,馬単,0.267327,0.821452,0.346535,0.644719
13,3,馬連,0.267327,0.786799,0.346535,0.665017
14,4,ワイド,0.633663,0.881188,0.792079,0.787624
15,4,三連単,0.188119,1.279703,0.306931,0.765264
16,4,三連複,0.188119,1.186881,0.306931,0.828218
17,4,単勝,0.643564,0.729703,0.821782,0.803713
18,4,複勝,0.940594,0.807426,0.980198,0.794554
19,4,馬単,0.386139,0.756931,0.514851,0.691172
20,4,馬連,0.386139,0.828878,0.514851,0.688779
21,5,ワイド,0.821782,0.876634,0.861386,0.736931
22,5,三連単,0.297030,0.752525,0.475248,0.708135
23,5,三連複,0.297030,0.668713,0.475248,0.708317
24,5,単勝,0.742574,0.757228,0.871287,0.765743
25,5,複勝,0.970297,0.838218,0.990099,0.765149
26,5,馬単,0.534653,0.701634,0.683168,0.774406
27,5,馬連,0.534653,0.718713,0.683168,0.777723

In [249]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_nagoya_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_nagoya_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_nagoya_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_nagoya_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_nagoya_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.406977,1.461628,0.348837,0.582558
1,1,複勝,0.639535,0.873256,0.755814,0.868605
2,2,ワイド,0.360465,1.017442,0.406977,0.695349
3,2,単勝,0.523256,0.984302,0.604651,0.757558
4,2,複勝,0.790698,0.833721,0.930233,0.827907
5,2,馬単,0.151163,0.945349,0.267442,0.824419
6,2,馬連,0.151163,0.903488,0.267442,0.890698
7,3,ワイド,0.534884,1.060078,0.697674,0.782558
8,3,三連単,0.151163,1.846899,0.139535,0.843411
9,3,三連複,0.151163,2.458140,0.139535,0.675581
10,3,単勝,0.686047,1.008140,0.720930,0.725194
11,3,複勝,0.906977,0.850000,0.988372,0.823256
12,3,馬単,0.325581,0.754651,0.465116,0.947481
13,3,馬連,0.325581,0.717054,0.465116,0.951163
14,4,ワイド,0.732558,1.040698,0.872093,0.896318
15,4,三連単,0.279070,0.854070,0.360465,0.998353
16,4,三連複,0.279070,1.093605,0.360465,1.046802
17,4,単勝,0.755814,0.904360,0.802326,0.776744
18,4,複勝,0.941860,0.858430,1.000000,0.838663
19,4,馬単,0.500000,1.514922,0.651163,0.982558
20,4,馬連,0.500000,1.606977,0.651163,0.936628
21,5,ワイド,0.848837,0.844070,0.918605,0.873721
22,5,三連単,0.418605,0.697655,0.604651,0.921047
23,5,三連複,0.418605,0.798256,0.604651,0.917209
24,5,単勝,0.802326,0.756047,0.860465,0.786977
25,5,複勝,1.000000,0.787209,1.000000,0.812791
26,5,馬単,0.627907,1.008721,0.779070,0.838314
27,5,馬連,0.627907,1.064419,0.779070,0.769767

In [250]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_morioka_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_morioka_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_morioka_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_morioka_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_morioka_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.190476,0.485714,0.380952,0.619048
1,1,複勝,0.523810,0.800000,0.714286,0.795238
2,2,ワイド,0.333333,0.657143,0.476190,0.752381
3,2,単勝,0.380952,0.409524,0.666667,0.802381
4,2,複勝,0.761905,0.797619,1.000000,0.919048
5,2,馬単,0.095238,0.373810,0.190476,0.588095
6,2,馬連,0.095238,0.485714,0.190476,0.642857
7,3,ワイド,0.571429,0.680952,0.857143,0.879365
8,3,三連単,0.142857,0.246032,0.142857,0.420635
9,3,三連複,0.142857,0.280952,0.142857,0.380952
10,3,単勝,0.571429,0.495238,0.761905,0.663492
11,3,複勝,0.857143,0.750794,1.000000,0.893651
12,3,馬単,0.285714,0.423016,0.333333,0.388095
13,3,馬連,0.285714,0.511111,0.333333,0.393651
14,4,ワイド,0.714286,0.665079,0.952381,0.801587
15,4,三連単,0.285714,0.255952,0.380952,0.583135
16,4,三連複,0.285714,0.330952,0.380952,0.783333
17,4,単勝,0.666667,0.491667,0.809524,0.566667
18,4,複勝,0.952381,0.722619,1.000000,0.828571
19,4,馬単,0.476190,0.532540,0.523810,0.457143
20,4,馬連,0.476190,0.584921,0.523810,0.493651
21,5,ワイド,0.809524,0.596667,0.952381,0.810476
22,5,三連単,0.380952,0.288968,0.619048,0.755476
23,5,三連複,0.380952,0.434762,0.619048,0.942381
24,5,単勝,0.714286,0.647619,0.857143,0.521905
25,5,複勝,1.000000,0.686667,1.000000,0.768571
26,5,馬単,0.571429,0.461429,0.714286,0.584048
27,5,馬連,0.571429,0.412381,0.714286,0.677143

In [251]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_monbetu_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_monbetu_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_monbetu_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_monbetu_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_monbetu_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.500000,0.926471,0.500000,0.776471
1,1,複勝,0.676471,0.805882,0.882353,1.005882
2,2,ワイド,0.470588,0.926471,0.647059,1.008824
3,2,単勝,0.676471,0.901471,0.794118,0.913235
4,2,複勝,0.970588,0.939706,0.970588,0.933824
5,2,馬単,0.294118,1.191176,0.441176,1.398529
6,2,馬連,0.294118,1.102941,0.441176,1.361765
7,3,ワイド,0.764706,0.887255,0.911765,0.947059
8,3,三連単,0.235294,0.516667,0.294118,0.816667
9,3,三連複,0.235294,0.882353,0.294118,0.926471
10,3,単勝,0.794118,0.749020,0.882353,0.785294
11,3,複勝,1.000000,0.837255,1.000000,0.869608
12,3,馬単,0.500000,0.776471,0.676471,0.846078
13,3,馬連,0.500000,0.825490,0.676471,0.837255
14,4,ワイド,0.882353,1.171569,1.000000,0.921569
15,4,三連単,0.588235,1.018505,0.647059,1.563971
16,4,三連複,0.588235,1.557353,0.647059,1.079412
17,4,単勝,0.852941,0.686765,0.941176,0.815441
18,4,複勝,1.000000,0.820588,1.000000,0.816912
19,4,馬単,0.676471,0.595343,0.852941,1.265196
20,4,馬連,0.676471,0.593137,0.852941,0.991176
21,5,ワイド,0.970588,0.938235,1.000000,0.885588
22,5,三連単,0.764706,1.113088,0.823529,0.885000
23,5,三連複,0.764706,1.161471,0.823529,0.884118
24,5,単勝,0.941176,0.734118,1.000000,0.797647
25,5,複勝,1.000000,0.754706,1.000000,0.772353
26,5,馬単,0.794118,0.812794,0.941176,0.881324
27,5,馬連,0.794118,0.616176,0.941176,0.690588

In [252]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_mizusawa_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_mizusawa_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_mizusawa_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_mizusawa_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_mizusawa_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.28,0.760000,0.52,0.976000
1,1,複勝,0.64,0.940000,0.76,0.912000
2,2,ワイド,0.32,0.948000,0.40,0.604000
3,2,単勝,0.48,0.880000,0.68,0.888000
4,2,複勝,0.92,0.934000,0.88,0.776000
5,2,馬単,0.12,0.790000,0.16,0.568000
6,2,馬連,0.12,0.556000,0.16,0.452000
7,3,ワイド,0.52,0.801333,0.60,0.609333
8,3,三連単,0.08,0.466000,0.16,0.731333
9,3,三連複,0.08,0.460000,0.16,0.664000
10,3,単勝,0.64,0.768000,0.80,0.809333
11,3,複勝,0.96,0.813333,0.96,0.733333
12,3,馬単,0.20,0.446667,0.36,0.700000
13,3,馬連,0.20,0.366667,0.36,0.642667
14,4,ワイド,0.84,1.166000,0.88,0.652667
15,4,三連単,0.28,1.298167,0.28,0.313667
16,4,三連複,0.28,1.241000,0.28,0.371000
17,4,単勝,0.80,0.873000,0.88,0.764000
18,4,複勝,0.96,0.890000,1.00,0.808000
19,4,馬単,0.44,1.150333,0.56,0.936667
20,4,馬連,0.44,1.191333,0.56,0.954000
21,5,ワイド,0.96,0.884000,0.96,0.859200
22,5,三連単,0.44,0.599667,0.64,0.523267
23,5,三連複,0.44,0.648400,0.64,0.699600
24,5,単勝,0.88,0.731200,0.92,0.694400
25,5,複勝,1.00,0.914400,1.00,0.896000
26,5,馬単,0.56,0.735600,0.84,0.815400
27,5,馬連,0.56,0.772000,0.84,0.896000

In [253]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kouti_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_kouti_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kouti_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kouti_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kouti_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.31250,0.496875,0.46875,0.662500
1,1,複勝,0.62500,0.728125,0.78125,0.850000
2,2,ワイド,0.40625,0.821875,0.53125,0.837500
3,2,単勝,0.53125,0.628125,0.71875,0.762500
4,2,複勝,0.81250,0.775000,0.87500,0.825000
5,2,馬単,0.18750,0.645312,0.31250,0.662500
6,2,馬連,0.18750,0.521875,0.31250,0.725000
7,3,ワイド,0.53125,0.854167,0.75000,0.705208
8,3,三連単,0.18750,0.620313,0.15625,0.206250
9,3,三連複,0.18750,1.365625,0.15625,0.490625
10,3,単勝,0.68750,0.595833,0.81250,0.719792
11,3,複勝,0.93750,0.764583,1.00000,0.805208
12,3,馬単,0.28125,0.266667,0.43750,0.438021
13,3,馬連,0.28125,0.254167,0.43750,0.429167
14,4,ワイド,0.68750,0.641667,0.87500,0.777083
15,4,三連単,0.28125,0.262630,0.34375,0.455339
16,4,三連複,0.28125,0.457031,0.34375,0.681250
17,4,単勝,0.75000,0.514844,0.87500,0.649219
18,4,複勝,0.96875,0.748437,1.00000,0.778906
19,4,馬単,0.40625,0.283333,0.56250,0.404427
20,4,馬連,0.40625,0.307812,0.56250,0.409896
21,5,ワイド,0.78125,0.780625,0.93750,0.748437
22,5,三連単,0.43750,0.505313,0.53125,0.730469
23,5,三連複,0.43750,0.681562,0.53125,0.764687
24,5,単勝,0.81250,0.635000,0.90625,0.596875
25,5,複勝,1.00000,0.726875,1.00000,0.758125
26,5,馬単,0.50000,0.195312,0.71875,0.706562
27,5,馬連,0.50000,0.208437,0.71875,0.701562

In [254]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kawasaki_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_kawasaki_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kawasaki_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kawasaki_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kawasaki_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.312757,0.877366,0.378601,0.812757
1,1,複勝,0.621399,0.910288,0.670782,0.829630
2,2,ワイド,0.296296,0.998765,0.316872,0.703704
3,2,単勝,0.473251,0.817078,0.555556,0.755967
4,2,複勝,0.818930,0.857819,0.880658,0.816255
5,2,馬単,0.119342,0.643004,0.144033,0.608848
6,2,馬連,0.119342,0.627160,0.144033,0.601235
7,3,ワイド,0.510288,0.766667,0.646091,0.890809
8,3,三連単,0.057613,0.587243,0.111111,0.834774
9,3,三連複,0.057613,0.636626,0.111111,1.005761
10,3,単勝,0.613169,0.784636,0.707819,0.818519
11,3,複勝,0.930041,0.818930,0.958848,0.858162
12,3,馬単,0.267490,0.654527,0.358025,0.779973
13,3,馬連,0.267490,0.675720,0.358025,0.759945
14,4,ワイド,0.683128,0.783265,0.810700,0.845062
15,4,三連単,0.185185,0.581396,0.275720,0.856310
16,4,三連複,0.185185,0.668621,0.275720,0.891872
17,4,単勝,0.720165,0.867901,0.802469,0.799897
18,4,複勝,0.971193,0.797428,0.991770,0.826749
19,4,馬単,0.399177,0.679424,0.526749,0.790466
20,4,馬連,0.399177,0.684019,0.526749,0.772634
21,5,ワイド,0.831276,0.768889,0.909465,0.899259
22,5,三連単,0.329218,0.647085,0.497942,0.895041
23,5,三連複,0.329218,0.686420,0.497942,0.938272
24,5,単勝,0.810700,0.842387,0.880658,0.819177
25,5,複勝,0.987654,0.800741,0.995885,0.817778
26,5,馬単,0.551440,0.674733,0.691358,0.827469
27,5,馬連,0.551440,0.671893,0.691358,0.810741

In [255]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kasamatu_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_kasamatu_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kasamatu_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kasamatu_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kasamatu_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.190476,0.485714,0.380952,0.619048
1,1,複勝,0.523810,0.800000,0.714286,0.795238
2,2,ワイド,0.333333,0.657143,0.476190,0.752381
3,2,単勝,0.380952,0.409524,0.666667,0.802381
4,2,複勝,0.761905,0.797619,1.000000,0.919048
5,2,馬単,0.095238,0.373810,0.190476,0.588095
6,2,馬連,0.095238,0.485714,0.190476,0.642857
7,3,ワイド,0.571429,0.680952,0.857143,0.879365
8,3,三連単,0.142857,0.246032,0.142857,0.420635
9,3,三連複,0.142857,0.280952,0.142857,0.380952
10,3,単勝,0.571429,0.495238,0.761905,0.663492
11,3,複勝,0.857143,0.750794,1.000000,0.893651
12,3,馬単,0.285714,0.423016,0.333333,0.388095
13,3,馬連,0.285714,0.511111,0.333333,0.393651
14,4,ワイド,0.714286,0.665079,0.952381,0.801587
15,4,三連単,0.285714,0.255952,0.380952,0.583135
16,4,三連複,0.285714,0.330952,0.380952,0.783333
17,4,単勝,0.666667,0.491667,0.809524,0.566667
18,4,複勝,0.952381,0.722619,1.000000,0.828571
19,4,馬単,0.476190,0.532540,0.523810,0.457143
20,4,馬連,0.476190,0.584921,0.523810,0.493651
21,5,ワイド,0.809524,0.596667,0.952381,0.810476
22,5,三連単,0.380952,0.288968,0.619048,0.755476
23,5,三連複,0.380952,0.434762,0.619048,0.942381
24,5,単勝,0.714286,0.647619,0.857143,0.521905
25,5,複勝,1.000000,0.686667,1.000000,0.768571
26,5,馬単,0.571429,0.461429,0.714286,0.584048
27,5,馬連,0.571429,0.412381,0.714286,0.677143

In [256]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_kanazawa_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_kanazawa_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kanazawa_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kanazawa_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_kanazawa_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.448276,1.070690,0.637931,0.937931
1,1,複勝,0.758621,0.934483,0.844828,0.929310
2,2,ワイド,0.534483,1.305172,0.551724,0.781034
3,2,単勝,0.620690,0.721552,0.793103,0.720690
4,2,複勝,0.879310,0.900000,0.948276,0.846552
5,2,馬単,0.275862,0.931897,0.327586,0.672414
6,2,馬連,0.275862,0.912069,0.327586,0.779310
7,3,ワイド,0.758621,0.876437,0.844828,0.841379
8,3,三連単,0.189655,0.819253,0.224138,0.727586
9,3,三連複,0.189655,1.055172,0.224138,0.787931
10,3,単勝,0.758621,0.605747,0.827586,0.589655
11,3,複勝,0.913793,0.795402,0.965517,0.816092
12,3,馬単,0.517241,0.635057,0.568966,0.654598
13,3,馬連,0.517241,0.694253,0.568966,0.738506
14,4,ワイド,0.827586,0.724425,0.896552,0.833046
15,4,三連単,0.396552,0.650790,0.517241,0.868247
16,4,三連複,0.396552,0.646552,0.517241,0.909483
17,4,単勝,0.827586,0.574138,0.931034,0.660345
18,4,複勝,0.982759,0.777155,1.000000,0.787069
19,4,馬単,0.637931,0.615661,0.689655,0.516379
20,4,馬連,0.637931,0.695115,0.689655,0.544828
21,5,ワイド,0.896552,0.704655,0.931034,0.737931
22,5,三連単,0.534483,0.487356,0.724138,0.548305
23,5,三連複,0.534483,0.638966,0.724138,0.587241
24,5,単勝,0.913793,0.578966,0.965517,0.613448
25,5,複勝,1.000000,0.719310,1.000000,0.765172
26,5,馬単,0.741379,0.501121,0.810345,0.484741
27,5,馬連,0.741379,0.580000,0.810345,0.520172

In [257]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_weight_funabasi_in3.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight_funabasi_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_funabasi_in3")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_funabasi_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight_funabasi_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.375000,1.102344,0.375000,0.820312
1,1,複勝,0.574803,0.856693,0.661417,0.864567
2,2,ワイド,0.375000,1.096875,0.351562,0.770312
3,2,単勝,0.578125,1.084766,0.570312,0.787109
4,2,複勝,0.850394,0.988976,0.874016,0.844094
5,2,馬単,0.179688,1.178906,0.195312,0.934375
6,2,馬連,0.179688,1.263281,0.195312,0.922656
7,3,ワイド,0.617188,0.917969,0.656250,0.761198
8,3,三連単,0.101562,1.035937,0.093750,0.639583
9,3,三連複,0.101562,1.029688,0.093750,0.703906
10,3,単勝,0.679688,0.910937,0.687500,0.723698
11,3,複勝,0.944882,0.927559,0.944882,0.825197
12,3,馬単,0.367188,0.965755,0.351562,0.750260
13,3,馬連,0.367188,1.034635,0.351562,0.755990
14,4,ワイド,0.765625,0.896875,0.773438,0.691927
15,4,三連単,0.226562,0.950065,0.265625,0.623633
16,4,三連複,0.226562,0.864844,0.265625,0.599805
17,4,単勝,0.773438,1.159570,0.765625,0.685742
18,4,複勝,0.976378,0.909449,0.968504,0.768110
19,4,馬単,0.539062,1.116471,0.515625,0.710677
20,4,馬連,0.539062,1.139323,0.515625,0.726432
21,5,ワイド,0.906250,0.942500,0.867188,0.692969
22,5,三連単,0.367188,0.772266,0.445312,0.593607
23,5,三連複,0.367188,0.932813,0.445312,0.608281
24,5,単勝,0.867188,1.158906,0.828125,0.689063
25,5,複勝,0.976378,0.875906,0.992126,0.761890
26,5,馬単,0.656250,1.050469,0.664062,0.659023
27,5,馬連,0.656250,1.063594,0.664062,0.676094

###　状況

# 精度評価
- popは人気列にかけた場合の回収率、的中率です
- topnはそのモデルが評価した上からn番目にかけた場合の的中回収です
- 例えばtop4の馬単にかけた場合上から4つの馬をかけた、4*3=12通りの的中率、回収率を計算します
- なので、馬単と馬連などの的中率は同じになりますが、回収率は変わります

In [318]:
%autoreload

### 二値分類

In [4]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_sonoda.csv",
    return_tables_filename = "return_tables_all.pickle",
)


evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_sonoda.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_sonoda")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_sonoda,returnrate_lightgbm_rank_niti_cross_dev_dirt_sonoda,hitrate_pop,returnrate_pop
0,1,単勝,0.359684,0.688538,0.426877,0.698024
1,1,複勝,0.671937,0.835968,0.723320,0.836759
2,2,ワイド,0.430830,0.905534,0.442688,0.693281
3,2,単勝,0.616601,0.803360,0.636364,0.730435
4,2,複勝,0.885375,0.878063,0.905138,0.815613
5,2,馬単,0.252964,1.185573,0.276680,0.779842
6,2,馬連,0.252964,1.248617,0.276680,0.811067
7,3,ワイド,0.683794,0.859684,0.703557,0.733333
8,3,三連単,0.162055,1.361726,0.173913,0.742292
9,3,三連複,0.162055,1.416206,0.173913,0.753755
10,3,単勝,0.754941,0.767457,0.774704,0.755731
11,3,複勝,0.972332,0.829381,0.964427,0.784717
12,3,馬単,0.458498,0.829513,0.474308,0.702964
13,3,馬連,0.458498,0.858893,0.474308,0.708827
14,4,ワイド,0.837945,0.795455,0.845850,0.713109
15,4,三連単,0.328063,0.786973,0.379447,0.700642
16,4,三連複,0.328063,0.856522,0.379447,0.781818
17,4,単勝,0.849802,0.805830,0.877470,0.779249
18,4,複勝,0.988142,0.800889,0.988142,0.753162
19,4,馬単,0.628458,0.835804,0.636364,0.671146
20,4,馬連,0.628458,0.840382,0.636364,0.669104
21,5,ワイド,0.920949,0.787549,0.932806,0.680830
22,5,三連単,0.529644,0.721739,0.557312,0.632312
23,5,三連複,0.529644,0.757470,0.557312,0.629763
24,5,単勝,0.909091,0.812727,0.932806,0.799368
25,5,複勝,1.000000,0.798498,1.000000,0.743478
26,5,馬単,0.766798,0.756798,0.782609,0.728755
27,5,馬連,0.766798,0.744743,0.782609,0.710711

In [259]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_urawa.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_urawa.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_urawa")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_urawa,returnrate_lightgbm_rank_niti_cross_dev_dirt_urawa,hitrate_pop,returnrate_pop
0,1,単勝,0.219895,0.712042,0.267016,0.595812
1,1,複勝,0.544503,0.783770,0.664921,0.853403
2,2,ワイド,0.287958,0.856021,0.329843,0.757592
3,2,単勝,0.397906,0.696859,0.481675,0.703927
4,2,複勝,0.748691,0.782723,0.869110,0.815445
5,2,馬単,0.136126,0.877225,0.141361,0.736126
6,2,馬連,0.136126,0.906283,0.141361,0.688482
7,3,ワイド,0.492147,0.770855,0.570681,0.808726
8,3,三連単,0.109948,0.882024,0.136126,1.076178
9,3,三連複,0.109948,0.912042,0.136126,0.936649
10,3,単勝,0.513089,0.686038,0.633508,0.751309
11,3,複勝,0.879581,0.776963,0.989529,0.851134
12,3,馬単,0.251309,0.679494,0.371728,0.881501
13,3,馬連,0.251309,0.646073,0.371728,0.856370
14,4,ワイド,0.696335,0.740925,0.801047,0.858639
15,4,三連単,0.204188,0.649913,0.298429,0.796401
16,4,三連複,0.204188,0.624346,0.298429,0.790969
17,4,単勝,0.649215,0.750785,0.748691,0.792932
18,4,複勝,0.963351,0.793194,0.989529,0.841885
19,4,馬単,0.413613,0.713264,0.539267,0.852705
20,4,馬連,0.413613,0.694066,0.539267,0.832548
21,5,ワイド,0.821990,0.738429,0.895288,0.812251
22,5,三連単,0.335079,0.686745,0.450262,0.834127
23,5,三連複,0.335079,0.655236,0.450262,0.865707
24,5,単勝,0.727749,0.726073,0.832461,0.828901
25,5,複勝,0.979058,0.758220,0.994764,0.797801
26,5,馬単,0.534031,0.648874,0.654450,0.780000
27,5,馬連,0.534031,0.607016,0.654450,0.744188

In [260]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_saga.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_saga.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_saga")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_saga,returnrate_lightgbm_rank_niti_cross_dev_dirt_saga,hitrate_pop,returnrate_pop
0,1,単勝,0.300,0.510000,0.450,0.725000
1,1,複勝,0.650,0.840000,0.775,0.847500
2,2,ワイド,0.400,0.860000,0.600,0.970000
3,2,単勝,0.550,0.777500,0.725,0.837500
4,2,複勝,0.800,0.790000,0.875,0.887500
5,2,馬単,0.200,1.005000,0.250,0.637500
6,2,馬連,0.200,1.057500,0.250,0.665000
7,3,ワイド,0.600,0.751667,0.725,0.660000
8,3,三連単,0.150,1.447500,0.150,0.282500
9,3,三連複,0.150,0.895000,0.150,0.575000
10,3,単勝,0.675,0.658333,0.850,0.867500
11,3,複勝,0.900,0.775000,0.975,0.795833
12,3,馬単,0.375,0.790000,0.450,0.497083
13,3,馬連,0.375,0.901667,0.450,0.558333
14,4,ワイド,0.850,0.685417,0.950,0.832917
15,4,三連単,0.275,0.545104,0.375,0.649375
16,4,三連複,0.275,0.419375,0.375,0.701875
17,4,単勝,0.850,0.732500,0.875,0.718125
18,4,複勝,1.000,0.798750,0.975,0.831250
19,4,馬単,0.525,0.524583,0.650,0.685208
20,4,馬連,0.525,0.640000,0.650,0.779583
21,5,ワイド,0.925,0.586000,1.000,0.856750
22,5,三連単,0.450,0.436667,0.600,1.350417
23,5,三連複,0.450,0.509000,0.600,1.178000
24,5,単勝,0.900,0.655500,0.900,0.655500
25,5,複勝,1.000,0.716500,1.000,0.823500
26,5,馬単,0.675,0.483000,0.750,0.834000
27,5,馬連,0.675,0.555250,0.750,0.874250

In [261]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_ooi.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_ooi.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_ooi")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_ooi,returnrate_lightgbm_rank_niti_cross_dev_dirt_ooi,hitrate_pop,returnrate_pop
0,1,単勝,0.267327,0.662376,0.356436,0.792079
1,1,複勝,0.564356,0.819802,0.693069,0.876238
2,2,ワイド,0.366337,0.948515,0.405941,0.882178
3,2,単勝,0.485149,0.859406,0.584158,0.837624
4,2,複勝,0.841584,0.912376,0.910891,0.886139
5,2,馬単,0.168317,0.883663,0.207921,0.825743
6,2,馬連,0.168317,1.004950,0.207921,0.890099
7,3,ワイド,0.574257,1.010561,0.663366,0.772277
8,3,三連単,0.079208,0.616997,0.089109,0.422772
9,3,三連複,0.079208,0.642574,0.089109,0.544554
10,3,単勝,0.603960,0.842574,0.693069,0.766007
11,3,複勝,0.920792,0.888119,0.960396,0.823762
12,3,馬単,0.316832,0.723762,0.346535,0.644719
13,3,馬連,0.316832,0.814191,0.346535,0.665017
14,4,ワイド,0.702970,0.801980,0.792079,0.787624
15,4,三連単,0.198020,0.508746,0.306931,0.765264
16,4,三連複,0.198020,0.635396,0.306931,0.828218
17,4,単勝,0.722772,0.812624,0.821782,0.803713
18,4,複勝,0.960396,0.813614,0.980198,0.794554
19,4,馬単,0.485149,0.756518,0.514851,0.691172
20,4,馬連,0.485149,0.794224,0.514851,0.688779
21,5,ワイド,0.792079,0.780792,0.861386,0.736931
22,5,三連単,0.336634,0.688647,0.475248,0.708135
23,5,三連複,0.336634,0.677426,0.475248,0.708317
24,5,単勝,0.801980,0.790891,0.871287,0.765743
25,5,複勝,0.990099,0.797228,0.990099,0.765149
26,5,馬単,0.613861,0.805099,0.683168,0.774406
27,5,馬連,0.613861,0.915743,0.683168,0.777723

In [262]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nagoya.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nagoya.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nagoya")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nagoya,returnrate_lightgbm_rank_niti_cross_dev_dirt_nagoya,hitrate_pop,returnrate_pop
0,1,単勝,0.395349,0.904651,0.348837,0.582558
1,1,複勝,0.674419,0.915116,0.755814,0.868605
2,2,ワイド,0.395349,1.106977,0.406977,0.695349
3,2,単勝,0.593023,1.115698,0.604651,0.757558
4,2,複勝,0.906977,0.950000,0.930233,0.827907
5,2,馬単,0.220930,1.580814,0.267442,0.824419
6,2,馬連,0.220930,1.506977,0.267442,0.890698
7,3,ワイド,0.604651,1.228295,0.697674,0.782558
8,3,三連単,0.197674,2.060078,0.139535,0.843411
9,3,三連複,0.197674,2.611628,0.139535,0.675581
10,3,単勝,0.697674,1.027132,0.720930,0.725194
11,3,複勝,0.965116,0.967442,0.988372,0.823256
12,3,馬単,0.418605,1.106008,0.465116,0.947481
13,3,馬連,0.418605,1.035271,0.465116,0.951163
14,4,ワイド,0.767442,0.911628,0.872093,0.896318
15,4,三連単,0.290698,0.729603,0.360465,0.998353
16,4,三連複,0.290698,0.882849,0.360465,1.046802
17,4,単勝,0.744186,0.896802,0.802326,0.776744
18,4,複勝,0.976744,0.862791,1.000000,0.838663
19,4,馬単,0.523256,0.834981,0.651163,0.982558
20,4,馬連,0.523256,0.755233,0.651163,0.936628
21,5,ワイド,0.895349,0.786047,0.918605,0.873721
22,5,三連単,0.430233,0.472151,0.604651,0.921047
23,5,三連複,0.430233,0.596744,0.604651,0.917209
24,5,単勝,0.837209,0.820698,0.860465,0.786977
25,5,複勝,0.988372,0.788837,1.000000,0.812791
26,5,馬単,0.674419,0.869244,0.779070,0.838314
27,5,馬連,0.674419,0.896047,0.779070,0.769767

In [263]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_morioka.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_morioka.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_morioka")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_morioka,returnrate_lightgbm_rank_niti_cross_dev_dirt_morioka,hitrate_pop,returnrate_pop
0,1,単勝,0.333333,0.723810,0.380952,0.619048
1,1,複勝,0.571429,0.800000,0.714286,0.795238
2,2,ワイド,0.285714,0.747619,0.476190,0.752381
3,2,単勝,0.476190,0.588095,0.666667,0.802381
4,2,複勝,0.809524,0.721429,1.000000,0.919048
5,2,馬単,0.142857,1.447619,0.190476,0.588095
6,2,馬連,0.142857,1.528571,0.190476,0.642857
7,3,ワイド,0.476190,0.441270,0.857143,0.879365
8,3,三連単,0.047619,0.119048,0.142857,0.420635
9,3,三連複,0.047619,0.080952,0.142857,0.380952
10,3,単勝,0.523810,0.420635,0.761905,0.663492
11,3,複勝,0.904762,0.638095,1.000000,0.893651
12,3,馬単,0.285714,0.748413,0.333333,0.388095
13,3,馬連,0.285714,0.847619,0.333333,0.393651
14,4,ワイド,0.761905,0.496825,0.952381,0.801587
15,4,三連単,0.238095,0.195040,0.380952,0.583135
16,4,三連複,0.238095,0.175000,0.380952,0.783333
17,4,単勝,0.714286,0.757143,0.809524,0.566667
18,4,複勝,0.952381,0.678571,1.000000,0.828571
19,4,馬単,0.571429,0.766270,0.523810,0.457143
20,4,馬連,0.571429,0.707143,0.523810,0.493651
21,5,ワイド,0.952381,0.687143,0.952381,0.810476
22,5,三連単,0.428571,0.369603,0.619048,0.755476
23,5,三連複,0.428571,0.535714,0.619048,0.942381
24,5,単勝,0.857143,0.747619,0.857143,0.521905
25,5,複勝,0.952381,0.700952,1.000000,0.768571
26,5,馬単,0.714286,0.689048,0.714286,0.584048
27,5,馬連,0.714286,0.670476,0.714286,0.677143

In [264]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_monbetu.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_monbetu.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_monbetu")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_monbetu,returnrate_lightgbm_rank_niti_cross_dev_dirt_monbetu,hitrate_pop,returnrate_pop
0,1,単勝,0.529412,0.982353,0.500000,0.776471
1,1,複勝,0.764706,0.891176,0.882353,1.005882
2,2,ワイド,0.558824,1.129412,0.647059,1.008824
3,2,単勝,0.823529,1.247059,0.794118,0.913235
4,2,複勝,1.000000,0.966176,0.970588,0.933824
5,2,馬単,0.294118,0.764706,0.441176,1.398529
6,2,馬連,0.294118,0.838235,0.441176,1.361765
7,3,ワイド,0.911765,1.297059,0.911765,0.947059
8,3,三連単,0.352941,1.287255,0.294118,0.816667
9,3,三連複,0.352941,1.752941,0.294118,0.926471
10,3,単勝,0.941176,1.055882,0.882353,0.785294
11,3,複勝,1.000000,0.950000,1.000000,0.869608
12,3,馬単,0.676471,1.258333,0.676471,0.846078
13,3,馬連,0.676471,1.168627,0.676471,0.837255
14,4,ワイド,0.941176,0.899510,1.000000,0.921569
15,4,三連単,0.647059,0.660294,0.647059,1.563971
16,4,三連複,0.647059,0.819853,0.647059,1.079412
17,4,単勝,0.941176,0.791912,0.941176,0.815441
18,4,複勝,1.000000,0.800735,1.000000,0.816912
19,4,馬単,0.823529,0.719608,0.852941,1.265196
20,4,馬連,0.823529,0.702941,0.852941,0.991176
21,5,ワイド,1.000000,0.795882,1.000000,0.885588
22,5,三連単,0.764706,0.822843,0.823529,0.885000
23,5,三連複,0.764706,0.766765,0.823529,0.884118
24,5,単勝,1.000000,0.797647,1.000000,0.797647
25,5,複勝,1.000000,0.742353,1.000000,0.772353
26,5,馬単,0.911765,0.866029,0.941176,0.881324
27,5,馬連,0.911765,0.662353,0.941176,0.690588

In [265]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_mizusawa.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_mizusawa.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_mizusawa")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_mizusawa,returnrate_lightgbm_rank_niti_cross_dev_dirt_mizusawa,hitrate_pop,returnrate_pop
0,1,単勝,0.40,0.928000,0.52,0.976000
1,1,複勝,0.72,0.928000,0.76,0.912000
2,2,ワイド,0.40,0.840000,0.40,0.604000
3,2,単勝,0.52,0.794000,0.68,0.888000
4,2,複勝,0.84,0.908000,0.88,0.776000
5,2,馬単,0.20,1.008000,0.16,0.568000
6,2,馬連,0.20,0.832000,0.16,0.452000
7,3,ワイド,0.60,0.769333,0.60,0.609333
8,3,三連単,0.04,0.370667,0.16,0.731333
9,3,三連複,0.04,0.324000,0.16,0.664000
10,3,単勝,0.72,0.760000,0.80,0.809333
11,3,複勝,0.96,0.786667,0.96,0.733333
12,3,馬単,0.28,0.520000,0.36,0.700000
13,3,馬連,0.28,0.438667,0.36,0.642667
14,4,ワイド,0.80,0.880667,0.88,0.652667
15,4,三連単,0.24,1.960500,0.28,0.313667
16,4,三連複,0.24,2.598000,0.28,0.371000
17,4,単勝,0.84,0.856000,0.88,0.764000
18,4,複勝,1.00,0.835000,1.00,0.808000
19,4,馬単,0.48,1.156667,0.56,0.936667
20,4,馬連,0.48,1.162000,0.56,0.954000
21,5,ワイド,0.92,0.919600,0.96,0.859200
22,5,三連単,0.52,1.805133,0.64,0.523267
23,5,三連複,0.52,1.850000,0.64,0.699600
24,5,単勝,0.88,0.703200,0.92,0.694400
25,5,複勝,1.00,0.868000,1.00,0.896000
26,5,馬単,0.68,0.862000,0.84,0.815400
27,5,馬連,0.68,0.910800,0.84,0.896000

In [266]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kouti.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kouti.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kouti")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kouti,returnrate_lightgbm_rank_niti_cross_dev_dirt_kouti,hitrate_pop,returnrate_pop
0,1,単勝,0.53125,1.040625,0.46875,0.662500
1,1,複勝,0.84375,0.987500,0.78125,0.850000
2,2,ワイド,0.40625,0.762500,0.53125,0.837500
3,2,単勝,0.75000,0.992188,0.71875,0.762500
4,2,複勝,0.93750,0.837500,0.87500,0.825000
5,2,馬単,0.25000,0.895312,0.31250,0.662500
6,2,馬連,0.25000,0.859375,0.31250,0.725000
7,3,ワイド,0.62500,0.687500,0.75000,0.705208
8,3,三連単,0.15625,0.252083,0.15625,0.206250
9,3,三連複,0.15625,0.578125,0.15625,0.490625
10,3,単勝,0.78125,0.697917,0.81250,0.719792
11,3,複勝,0.96875,0.757292,1.00000,0.805208
12,3,馬単,0.43750,0.441146,0.43750,0.438021
13,3,馬連,0.43750,0.471875,0.43750,0.429167
14,4,ワイド,0.87500,0.752083,0.87500,0.777083
15,4,三連単,0.25000,0.278385,0.34375,0.455339
16,4,三連複,0.25000,0.616406,0.34375,0.681250
17,4,単勝,0.81250,0.539844,0.87500,0.649219
18,4,複勝,0.96875,0.776563,1.00000,0.778906
19,4,馬単,0.43750,0.220573,0.56250,0.404427
20,4,馬連,0.43750,0.235937,0.56250,0.409896
21,5,ワイド,0.93750,0.640938,0.93750,0.748437
22,5,三連単,0.37500,0.283958,0.53125,0.730469
23,5,三連複,0.37500,0.393125,0.53125,0.764687
24,5,単勝,0.84375,0.478125,0.90625,0.596875
25,5,複勝,1.00000,0.753125,1.00000,0.758125
26,5,馬単,0.56250,0.338438,0.71875,0.706562
27,5,馬連,0.56250,0.435312,0.71875,0.701562

In [267]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kawasaki.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kawasaki.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kawasaki")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kawasaki,returnrate_lightgbm_rank_niti_cross_dev_dirt_kawasaki,hitrate_pop,returnrate_pop
0,1,単勝,0.329218,0.979012,0.378601,0.812757
1,1,複勝,0.637860,0.924280,0.670782,0.829630
2,2,ワイド,0.283951,0.944444,0.316872,0.703704
3,2,単勝,0.522634,1.003909,0.555556,0.755967
4,2,複勝,0.847737,0.878395,0.880658,0.816255
5,2,馬単,0.156379,1.236626,0.144033,0.608848
6,2,馬連,0.156379,1.228807,0.144033,0.601235
7,3,ワイド,0.547325,0.872291,0.646091,0.890809
8,3,三連単,0.078189,0.516872,0.111111,0.834774
9,3,三連複,0.078189,0.656790,0.111111,1.005761
10,3,単勝,0.658436,0.873525,0.707819,0.818519
11,3,複勝,0.930041,0.850343,0.958848,0.858162
12,3,馬単,0.329218,1.053361,0.358025,0.779973
13,3,馬連,0.329218,1.068038,0.358025,0.759945
14,4,ワイド,0.720165,0.768656,0.810700,0.845062
15,4,三連単,0.209877,0.573834,0.275720,0.856310
16,4,三連複,0.209877,0.659568,0.275720,0.891872
17,4,単勝,0.736626,0.803704,0.802469,0.799897
18,4,複勝,0.975309,0.822531,0.991770,0.826749
19,4,馬単,0.448560,0.751269,0.526749,0.790466
20,4,馬連,0.448560,0.754458,0.526749,0.772634
21,5,ワイド,0.839506,0.863086,0.909465,0.899259
22,5,三連単,0.382716,0.996454,0.497942,0.895041
23,5,三連複,0.382716,1.035473,0.497942,0.938272
24,5,単勝,0.835391,0.849465,0.880658,0.819177
25,5,複勝,0.991770,0.811934,0.995885,0.817778
26,5,馬単,0.584362,0.730412,0.691358,0.827469
27,5,馬連,0.584362,0.698519,0.691358,0.810741

In [268]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kasamatu.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kasamatu.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kasamatu")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kasamatu,returnrate_lightgbm_rank_niti_cross_dev_dirt_kasamatu,hitrate_pop,returnrate_pop
0,1,単勝,0.333333,0.723810,0.380952,0.619048
1,1,複勝,0.571429,0.800000,0.714286,0.795238
2,2,ワイド,0.285714,0.747619,0.476190,0.752381
3,2,単勝,0.476190,0.588095,0.666667,0.802381
4,2,複勝,0.809524,0.721429,1.000000,0.919048
5,2,馬単,0.142857,1.447619,0.190476,0.588095
6,2,馬連,0.142857,1.528571,0.190476,0.642857
7,3,ワイド,0.476190,0.441270,0.857143,0.879365
8,3,三連単,0.047619,0.119048,0.142857,0.420635
9,3,三連複,0.047619,0.080952,0.142857,0.380952
10,3,単勝,0.523810,0.420635,0.761905,0.663492
11,3,複勝,0.904762,0.638095,1.000000,0.893651
12,3,馬単,0.285714,0.748413,0.333333,0.388095
13,3,馬連,0.285714,0.847619,0.333333,0.393651
14,4,ワイド,0.761905,0.496825,0.952381,0.801587
15,4,三連単,0.238095,0.195040,0.380952,0.583135
16,4,三連複,0.238095,0.175000,0.380952,0.783333
17,4,単勝,0.714286,0.757143,0.809524,0.566667
18,4,複勝,0.952381,0.678571,1.000000,0.828571
19,4,馬単,0.571429,0.766270,0.523810,0.457143
20,4,馬連,0.571429,0.707143,0.523810,0.493651
21,5,ワイド,0.952381,0.687143,0.952381,0.810476
22,5,三連単,0.428571,0.369603,0.619048,0.755476
23,5,三連複,0.428571,0.535714,0.619048,0.942381
24,5,単勝,0.857143,0.747619,0.857143,0.521905
25,5,複勝,0.952381,0.700952,1.000000,0.768571
26,5,馬単,0.714286,0.689048,0.714286,0.584048
27,5,馬連,0.714286,0.670476,0.714286,0.677143

In [269]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_kanazawa.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_kanazawa.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_kanazawa")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_kanazawa,returnrate_lightgbm_rank_niti_cross_dev_dirt_kanazawa,hitrate_pop,returnrate_pop
0,1,単勝,0.413793,0.665517,0.637931,0.937931
1,1,複勝,0.689655,0.824138,0.844828,0.929310
2,2,ワイド,0.500000,1.041379,0.551724,0.781034
3,2,単勝,0.655172,0.589655,0.793103,0.720690
4,2,複勝,0.879310,0.865517,0.948276,0.846552
5,2,馬単,0.258621,0.493966,0.327586,0.672414
6,2,馬連,0.258621,0.646552,0.327586,0.779310
7,3,ワイド,0.758621,0.828736,0.844828,0.841379
8,3,三連単,0.137931,0.280460,0.224138,0.727586
9,3,三連複,0.137931,0.539655,0.224138,0.787931
10,3,単勝,0.758621,0.589655,0.827586,0.589655
11,3,複勝,0.965517,0.801724,0.965517,0.816092
12,3,馬単,0.465517,0.504310,0.568966,0.654598
13,3,馬連,0.465517,0.540230,0.568966,0.738506
14,4,ワイド,0.844828,0.858333,0.896552,0.833046
15,4,三連単,0.413793,0.496121,0.517241,0.868247
16,4,三連複,0.413793,0.904310,0.517241,0.909483
17,4,単勝,0.862069,0.518103,0.931034,0.660345
18,4,複勝,1.000000,0.782759,1.000000,0.787069
19,4,馬単,0.620690,0.389943,0.689655,0.516379
20,4,馬連,0.620690,0.472989,0.689655,0.544828
21,5,ワイド,0.879310,0.732586,0.931034,0.737931
22,5,三連単,0.603448,0.455029,0.724138,0.548305
23,5,三連複,0.603448,0.586034,0.724138,0.587241
24,5,単勝,0.931034,0.539310,0.965517,0.613448
25,5,複勝,1.000000,0.728621,1.000000,0.765172
26,5,馬単,0.706897,0.366897,0.810345,0.484741
27,5,馬連,0.706897,0.417069,0.810345,0.520172

In [270]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_funabasi.csv",
    return_tables_filename = "return_tables_all.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_funabasi.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_funabasi")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_funabasi,returnrate_lightgbm_rank_niti_cross_dev_dirt_funabasi,hitrate_pop,returnrate_pop
0,1,単勝,0.335938,0.953125,0.375000,0.820312
1,1,複勝,0.637795,0.962992,0.661417,0.864567
2,2,ワイド,0.328125,0.972656,0.351562,0.770312
3,2,単勝,0.507812,0.829297,0.570312,0.787109
4,2,複勝,0.866142,0.922835,0.874016,0.844094
5,2,馬単,0.195312,1.488672,0.195312,0.934375
6,2,馬連,0.195312,1.517187,0.195312,0.922656
7,3,ワイド,0.609375,0.878906,0.656250,0.761198
8,3,三連単,0.109375,1.023307,0.093750,0.639583
9,3,三連複,0.109375,0.967969,0.093750,0.703906
10,3,単勝,0.664062,0.810937,0.687500,0.723698
11,3,複勝,0.905512,0.849344,0.944882,0.825197
12,3,馬単,0.351562,1.036979,0.351562,0.750260
13,3,馬連,0.351562,1.071875,0.351562,0.755990
14,4,ワイド,0.726562,0.815755,0.773438,0.691927
15,4,三連単,0.242188,0.774642,0.265625,0.623633
16,4,三連複,0.242188,0.869531,0.265625,0.599805
17,4,単勝,0.750000,0.820312,0.765625,0.685742
18,4,複勝,0.944882,0.820079,0.968504,0.768110
19,4,馬単,0.492188,0.943034,0.515625,0.710677
20,4,馬連,0.492188,0.919010,0.515625,0.726432
21,5,ワイド,0.820312,0.759453,0.867188,0.692969
22,5,三連単,0.359375,1.083867,0.445312,0.593607
23,5,三連複,0.359375,0.716328,0.445312,0.608281
24,5,単勝,0.804688,0.965156,0.828125,0.689063
25,5,複勝,0.984252,0.800472,0.992126,0.761890
26,5,馬単,0.601562,0.986758,0.664062,0.659023
27,5,馬連,0.601562,0.878594,0.664062,0.676094

# 予測当日の処理

## 事前準備
**当日出走馬が確定した時点**で実行できる

In [271]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [272]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

NameError: name 'preprocessing' is not defined

In [ ]:
population = create_population.create(from_="2016-01-01", to_="2024-11-31")

In [ ]:
# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

In [ ]:
pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

In [ ]:
# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

## 当日の予測処理
レース直前出走直前に実行する

In [ ]:
#当日にやらないと、天気や馬場状態がわからないので、当日に実行してください、
# 特徴量の更新
features = pfc.create_features(
    race_id="202408060411",  # 予測するレースidを指定
    date_content_a = "2024年11月10日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

In [ ]:
pfc.results

In [ ]:
pfc.race_info

### pred列は全て降順（大きい順）で表示されます
### 二値予測のrankはpred列が大きい順で評価がよく、回帰のrankとtimeは小さい順で評価が良いです
### 順番が逆になっているので気をつけてください

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)