# インポート

In [180]:
import create_population_turf
import create_population_turf_newbie
import create_population_turf_nowin
import create_population_obstract
import create_population_dirt
import create_population
import create_population_dirt_newbie
import create_population_dirt_nowin
import preprocessing
from feature_engineering import FeatureCreator


import pandas as pd
import numpy as np
import race_grade_maker


from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_niti_cross_in3 import Trainer_lightgbm_rank_niti_cv_in3

from train_lightgbm_time import Trainer_lightgbm_time
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki

from evaluation_shaft_time_kaiki_cross import Evaluator_lightgbm_time_kaiki_shaft

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross
from evaluation_shaft_rank_cross import Evaluator_lightgbm_rank_niti_shaft

from evaluation_lgbm_rank_niti_cross_ex_value import Evaluator_lightgbm_rank_niti_cross_ex_value

from evaluation_lgbm_rank_niti_cross_in3 import Evaluator_lightgbm_rank_niti_cross_in3

%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [181]:
%autoreload

In [3]:

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 800)

# 学習母集団の作成
- ここで何年までのデータを使うか設定してください
- 2016-01-01から、2024-11-30まではスクレイピングしてあります
- 特徴量が多いため、あまり年月が嵩むと処理が止まる恐れがあります

In [4]:
# population_turf = create_population_turf.create(from_="2016-01-01", to_="2023-12-31")
# population_turf = create_population_turf.create(from_="2020-01-01", to_="2023-12-31")
# population_turf = create_population_turf.create(from_="2016-01-01", to_="2023-12-31")
# population_turf = create_population_turf.create(from_="2023-12-01", to_="2023-12-31")
population_turf = create_population_turf.create(from_="2016-01-01", to_="2025-04-30")
population_turf

             race_id       date    horse_id
0       201606010110 2016-01-05  2013104475
1       201606010110 2016-01-05  2013105872
2       201606010110 2016-01-05  2013101006
3       201606010110 2016-01-05  2013105860
4       201606010110 2016-01-05  2013102323
...              ...        ...         ...
117840  202508020211 2025-04-27  2018103489
117841  202508020211 2025-04-27  2017110138
117842  202508020211 2025-04-27  2020110155
117843  202508020211 2025-04-27  2019101348
117844  202508020211 2025-04-27  2021105856

[117902 rows x 3 columns]

In [5]:
population_all = create_population.create(from_="2016-01-01",to_="2025-04-30")
population_all

             race_id       date    horse_id
0       201606010101 2016-01-05  2013100513
1       201606010101 2016-01-05  2013102845
2       201606010101 2016-01-05  2013102932
3       201606010101 2016-01-05  2013103416
4       201606010101 2016-01-05  2013100107
...              ...        ...         ...
445513  202508020212 2025-04-27  2020103556
445514  202508020212 2025-04-27  2018102956
445515  202508020212 2025-04-27  2020103045
445516  202508020212 2025-04-27  2021103197
445517  202508020212 2025-04-27  2021110159

[445693 rows x 3 columns]

In [ ]:
# # population_turf_newbie = create_population_turf_newbie.create(from_="2016-01-01", to_="2023-12-31")
# # population_turf_newbie = create_population_turf_newbie.create(from_="2020-01-01", to_="2023-12-31")
# # population_turf_newbie = create_population_turf_newbie.create(from_="2016-01-01", to_="2023-12-31")
# # population_turf_newbie = create_population_turf_newbie.create(from_="2023-01-01", to_="2023-12-31")
# population_turf_newbie = create_population_turf_newbie.create(from_="2016-01-01", to_="2024-12-31")
# population_turf_newbie

In [6]:
# population_turf_nowin = create_population_turf_nowin.create(from_="2016-01-01", to_="2023-12-31")
# population_turf_nowin = create_population_turf_nowin.create(from_="2020-01-01", to_="2023-12-31")
# population_turf_nowin = create_population_turf_nowin.create(from_="2016-01-01", to_="2023-12-31")
# population_turf_nowin = create_population_turf_nowin.create(from_="2023-01-01", to_="2023-12-31")
population_turf_nowin = create_population_turf_nowin.create(from_="2016-01-01", to_="2025-04-30")
population_turf_nowin

            race_id       date    horse_id
0      201606010105 2016-01-05  2013105304
1      201606010105 2016-01-05  2013105661
2      201606010105 2016-01-05  2013109072
3      201606010105 2016-01-05  2013105769
4      201606010105 2016-01-05  2013106030
...             ...        ...         ...
67560  202508020205 2025-04-27  2022103459
67561  202508020205 2025-04-27  2022105706
67562  202508020205 2025-04-27  2022103015
67563  202508020205 2025-04-27  2022105229
67564  202508020205 2025-04-27  2022101921

[67611 rows x 3 columns]

In [ ]:
# # population_dirt_newbie = create_population_dirt_newbie.create(from_="2016-01-01", to_="2023-12-31")
# # population_dirt_newbie = create_population_dirt_newbie.create(from_="2020-01-01", to_="2023-12-31")
# # population_dirt_newbie = create_population_dirt_newbie.create(from_="2016-01-01", to_="2023-12-31")
# # population_dirt_newbie = create_population_dirt_newbie.create(from_="2023-01-01", to_="2023-12-31")
# population_dirt_newbie = create_population_dirt_newbie.create(from_="2016-01-01",to_="2024-12-31")
# population_dirt_newbie

In [7]:
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2016-01-01", to_="2023-12-31")
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2020-01-01", to_="2023-12-31")
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2016-01-01", to_="2023-12-31")
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2023-01-01", to_="2023-12-31")
population_dirt_nowin = create_population_dirt_nowin.create(from_="2016-01-01", to_="2025-04-30")
population_dirt_nowin

            race_id       date    horse_id
0      201606010101 2016-01-05  2013100513
1      201606010101 2016-01-05  2013102845
2      201606010101 2016-01-05  2013102932
3      201606010101 2016-01-05  2013103416
4      201606010101 2016-01-05  2013100107
...             ...        ...         ...
89157  202508020202 2025-04-27  2022103615
89158  202508020202 2025-04-27  2022103599
89159  202508020202 2025-04-27  2022103632
89160  202508020202 2025-04-27  2022100897
89161  202508020202 2025-04-27  2022100529

[89193 rows x 3 columns]

In [5]:
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2016-01-01", to_="2023-12-31")
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2020-01-01", to_="2023-12-31")
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2016-01-01", to_="2023-12-31")
# population_dirt_nowin = create_population_dirt_nowin.create(from_="2023-01-01", to_="2023-12-31")
population_dirt = create_population_dirt.create(from_="2016-01-01",  to_="2025-04-30")
population_dirt

             race_id       date    horse_id
0       201606010103 2016-01-05  2011102141
1       201606010103 2016-01-05  2011101687
2       201606010103 2016-01-05  2012100798
3       201606010103 2016-01-05  2011102712
4       201606010103 2016-01-05  2011105378
...              ...        ...         ...
120870  202508020212 2025-04-27  2020103556
120871  202508020212 2025-04-27  2018102956
120872  202508020212 2025-04-27  2020103045
120873  202508020212 2025-04-27  2021103197
120874  202508020212 2025-04-27  2021110159

[120916 rows x 3 columns]

In [9]:
# population_obstract = create_population_obstract.create(from_="2016-01-01", to_="2023-12-31")
# population_obstract = create_population_obstract.create(from_="2020-01-01", to_="2023-12-31")
# population_obstract = create_population_obstract.create(from_="2016-01-01", to_="2023-12-31")
# population_obstract = create_population_obstract.create(from_="2023-01-01", to_="2023-12-31")
population_obstract = create_population_obstract.create(from_="2016-01-01", to_="2025-04-30")
population_obstract

            race_id       date    horse_id
0      201606010208 2016-01-09  2010103225
1      201606010208 2016-01-09  2012100619
2      201606010208 2016-01-09  2010104479
3      201606010208 2016-01-09  2010100880
4      201606010208 2016-01-09  2011102192
...             ...        ...         ...
13595  202508020204 2025-04-27  2019103634
13596  202508020204 2025-04-27  2019106387
13597  202508020204 2025-04-27  2017100641
13598  202508020204 2025-04-27  2021104597
13599  202508020204 2025-04-27  2019104983

[13600 rows x 3 columns]

In [ ]:
# population_dirt_newbie = create_population_dirt_newbie.create(from_="2016-01-01", to_="2023-12-31")
# population_dirt_newbie = create_population_dirt_newbie.create(from_="2020-01-01", to_="2023-12-31")
# population_dirt_newbie = create_population_dirt_newbie.create(from_="2016-01-01", to_="2023-12-31")
# population_dirt_newbie = create_population_dirt_newbie.create(from_="2023-01-01", to_="2023-12-31")
population_dirt = create_population_dirt.create(from_="2016-01-01",to_="2024-12-31")
population_dirt

# データ加工

In [4]:
#まとめて実行_turf
# レース結果テーブルの前処理
results_preprocessed_turf = preprocessing.process_results(
    populaton_filename = "population_turf.csv",
    output_filename = "results_turf.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_turf = preprocessing.process_horse_results(
    populaton_filename = "population_turf.csv",
    output_filename = "horse_results_turf.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_turf = preprocessing.process_race_info(
    populaton_filename = "population_turf.csv",
    output_filename = "race_info_turf_before.csv",       
)
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    populaton_filename = "population_turf.csv",  
    output_filename= "peds_turf.csv",    
)
# 種牡馬リーディングテーブルの前処理
sire_leading_preprocessed = preprocessing.process_sire_leading()
bms_leading_preprocessed = preprocessing.process_sire_leading(
    input_filename="bms_leading.csv",
    output_filename = "bms_leading.csv",
    id_col = "bms_id",
)
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_turf = preprocessing.process_return_tables(
    populaton_filename = "population_turf.csv",
    output_filename = "return_tables_turf.pickle",    
)

In [5]:
# 重複チェック
results_preprocessed_turf.duplicated(subset=["race_id", "horse_id"]).sum()

0

In [6]:
# 欠損チェック
results_preprocessed_turf.isnull().sum()

race_id                   0
horse_id                  0
jockey_id                 0
trainer_id                0
owner_id                  0
rank                      0
rank_per_horse            0
time                      0
nobori                    0
umaban                    0
wakuban                   0
tansho_odds               0
popularity                0
impost                    0
sex                       0
age                       0
weight                    0
weight_diff               0
impost_percent            0
n_horses                  0
corner_1_per_horse        0
corner_2_per_horse     2571
corner_3_per_horse    60953
corner_4_per_horse    74976
mean_age                  0
median_age                0
mean_age_kirisute         0
umaban_odd                0
corner_1                  0
corner_2               2571
corner_3              60953
corner_4              74976
dtype: int64

In [14]:
# 欠損チェック
horse_results_preprocessed_turf.isnull().sum()

horse_id                                                         0
rank_per_horse                                                   0
date                                                             0
rank                                                             0
prize                                                            0
rank_diff                                                        0
umaban                                                           0
wakuban                                                          0
weather                                                          0
race_type                                                        0
course_len                                                       0
impost                                                           0
ground_state                                                     0
race_class                                                       0
n_horses                                                         0
time                                                             0
time_courselen                                                   0
nobori                                                          26
win                                                              0
rentai                                                           0
show                                                             0
place                                                            0
goal_range                                                       0
curve                                                            0
goal_slope                                                       0
goal_range_100                                                7618
place_course_category                                            0
place_course_tough                                               0
weight                                                          25
weight_diff                                                     25
corner_1_per_horse                                               0
corner_2_per_horse                                            3404
corner_3_per_horse                                          152553
corner_4_per_horse                                          182626
race_position                                                    0
race_grade                                                       0
race_grade_scaled                                                0
pace_diff                                                     8423
pace_category                                                 8423
place_season_condition_type_categori                          8081
course_len_type                                                  0
course_type                                                      0
age_n                                                            0
umaban_odd                                                       0
season                                                           0
place_season                                                     0
place_season_type                                                0
place_season_condition_type                                      0
season_turf_condition                                            0
curve_amount                                                     0
start_point                                                      0
start_range                                                      0
straight_total                                                   0
curve_total                                                      0
curve_R12                                                        0
curve_R34                                                        0
height_diff                                                      0
width                                                            0
start_slope                                                      0
flont_slope                                                      0
first_curve_slope                                                0
last_curve_slope                                                 0
season_turf                                                      0
day_season_turf                                                  0
umaban_judge                                                     0
first_corner                                                     0
nobori_pace_diff_slope_range_groundstate_position            16277
nobori_pace_diff_slope_range_groundstate_position_umaban     16277
waku_1                                                           0
waku_2                                                           0
waku_3                                                           0
waku_4                                                           0
waku_5                                                           0
waku_6                                                           0
waku_7                                                           0
waku_8                                                           0
position_1                                                       0
position_2                                                       0
position_3                                                       0
position_4                                                       0
course_len_diff_-500                                             0
course_len_diff_-350                                             0
course_len_diff_-150                                             0
course_len_diff_0                                                0
course_len_diff_150                                              0
course_len_diff_350                                              0
course_len_diff_500                                              0
class_diff_up                                                    0
class_diff_stay                                                  0
class_diff_down                                                  0
age_3                                                            0
age_4                                                            0
age_5                                                            0
age_6                                                            0
sex_men                                                          0
sex_women                                                        0
sex_nosex                                                        0
waku_1_EX                                                        0
waku_2_EX                                                        0
waku_3_EX                                                        0
waku_4_EX                                                        0
waku_5_EX                                                        0
waku_6_EX                                                        0
waku_7_EX                                                        0
waku_8_EX                                                        0
position_1_EX                                                    0
position_2_EX                                                    0
position_3_EX                                                    0
position_4_EX                                                    0
course_len_diff_-500_EX                                          0
course_len_diff_-350_EX                                          0
course_len_diff_-150_EX                                          0
course_len_diff_0_EX                                             0
course_len_diff_150_EX                                           0
course_len_diff_350_EX                                           0
course_len_diff_500_EX                                           0
class_diff_up_EX                                                 0
class_diff_stay_EX                                               0
class_diff_down_EX                                               0
age_3_EX                                                         0
age_4_EX                                                         0
age_5_EX                                                         0
age_6_EX                                                         0
sex_men_EX                                                       0
sex_women_EX                                                     0
sex_nosex_EX                                                     0
course_len_allfix                                            16274
corner_1                                                         0
corner_2                                                      3404
corner_3                                                    152553
corner_4                                                    182626
pace_1                                                        8423
pace_2                                                        8423
dtype: int64

In [13]:
# 重複チェック
horse_results_preprocessed_turf.duplicated(subset=["horse_id", "date"]).sum()

0

In [22]:
horse_results_preprocessed_turf.tail(100)

,horse_id,rank_per_horse,date,rank,prize,rank_diff,umaban,wakuban,weather,race_type,course_len,impost,ground_state,race_class,n_horses,time,time_courselen,nobori,win,rentai,show,place,goal_range,curve,goal_slope,goal_range_100,place_course_category,place_course_tough,weight,weight_diff,corner_1_per_horse,corner_2_per_horse,corner_3_per_horse,corner_4_per_horse,race_position,race_grade,race_grade_scaled,pace_diff,pace_category,place_season_condition_type_categori,course_len_type,course_type,age_n,umaban_odd,season,place_season,place_season_type,place_season_condition_type,season_turf_condition,curve_amount,start_point,start_range,straight_total,curve_total,curve_R12,curve_R34,height_diff,width,start_slope,flont_slope,first_curve_slope,last_curve_slope,season_turf,day_season_turf,umaban_judge,first_corner,nobori_pace_diff_slope_range_groundstate_position,nobori_pace_diff_slope_range_groundstate_position_umaban,waku_1,waku_2,waku_3,waku_4,waku_5,waku_6,waku_7,waku_8,position_1,position_2,position_3,position_4,course_len_diff_-500,course_len_diff_-350,course_len_diff_-150,course_len_diff_0,course_len_diff_150,course_len_diff_350,course_len_diff_500,class_diff_up,class_diff_stay,class_diff_down,age_3,age_4,age_5,age_6,sex_men,sex_women,sex_nosex,waku_1_EX,waku_2_EX,waku_3_EX,waku_4_EX,waku_5_EX,waku_6_EX,waku_7_EX,waku_8_EX,position_1_EX,position_2_EX,position_3_EX,position_4_EX,course_len_diff_-500_EX,course_len_diff_-350_EX,course_len_diff_-150_EX,course_len_diff_0_EX,course_len_diff_150_EX,course_len_diff_350_EX,course_len_diff_500_EX,class_diff_up_EX,class_diff_stay_EX,class_diff_down_EX,age_3_EX,age_4_EX,age_5_EX,age_6_EX,sex_men_EX,sex_women_EX,sex_nosex_EX,course_len_allfix,corner_1,corner_2,corner_3,corner_4,pace_1,pace_2
1106734,2018104347,0.538462,2021-10-24,7.0,0.0,2.60,12,8,2,1,1200,55.0,0,3,13.0,68.9,0.057417,33.9,0,0,0,9,357.0,5.0,1.9,3.570,901,1,482.0,-2.0,0.923077,0.923077,<NA>,<NA>,4,79,2.9,0.90,2.0,5.0,1,9112001,5.0,0,3,93,931,931,7.8,2.0,1.0,258.2,615.0,585.0,0.0,170.0,1.8,24.0,-0.2,-0.4,-0.70,-0.50,2.0,62,0.373077,170.0,30.379745,30.390828,25.7,27.1,32.1,22.0,25.0,17.5,21.4,15.6,26.3,27.9,25.0,27.3,0.0,0.0,16.7,22.0,27.2,17.7,2.9,25.5,21.1,28.8,27.6,27.1,17.0,13.9,24.0,22.7,11.1,86.0,85.0,104.0,79.0,92.0,72.0,75.0,57.0,88.0,85.0,70.0,70.0,0.0,0.0,88.0,79.0,94.0,72.0,25.0,82.0,82.0,71.0,75.0,94.0,70.0,83.0,80.0,83.0,51.0,1327.622771,12,12,<NA>,<NA>,33.70,34.6
1106735,2018104347,0.312500,2021-10-02,5.0,150.0,2.30,6,3,1,1,1200,55.0,0,3,16.0,68.7,0.057250,33.1,0,0,0,6,310.0,5.0,3.0,3.100,602,1,484.0,-12.0,0.8125,0.6875,<NA>,<NA>,4,79,2.9,-0.20,3.0,4.0,1,6112001,5.0,0,3,63,631,631,10.4,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,2.0,82,-0.175000,190.0,30.146176,30.103924,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,1807.848818,13,11,<NA>,<NA>,34.30,34.1
1106736,2018104347,0.437500,2021-09-04,7.0,0.0,2.80,4,2,1,1,1200,55.0,0,3,16.0,69.8,0.058167,34.2,0,0,0,1,266.0,5.0,0.0,2.660,1,1,496.0,28.0,1.0,0.875,<NA>,<NA>,4,79,2.9,0.40,2.0,1.0,1,1112001,5.0,0,3,13,131,131,9.1,2.0,1.0,410.0,670.0,530.0,0.0,167.0,0.6,20.0,-0.2,0.3,-0.20,-0.10,2.0,72,-0.300000,167.0,33.239231,33.193756,23.3,22.7,17.1,23.4,19.3,20.5,24.0,25.8,27.4,25.1,30.2,30.2,0.0,0.0,15.6,22.1,30.5,25.4,11.1,26.9,20.3,50.0,25.9,19.2,17.8,15.5,20.7,22.7,29.8,80.0,78.0,64.0,79.0,89.0,76.0,89.0,91.0,77.0,80.0,69.0,81.0,0.0,0.0,83.0,78.0,102.0,88.0,92.0,82.0,79.0,115.0,81.0,75.0,83.0,95.0,71.0,84.0,165.0,1537.217253,16,14,<NA>,<NA>,34.30,34.7
1106737,2018104347,0.066667,2021-03-14,1.0,730.0,1.79,7,4,1,1,1200,56.0,1,2,15.0,71.5,0.059583,35.6,1,1,1,6,310.0,5.0,3.0,3.100,602,1,468.0,-2.0,0.933333,1.0,<NA>,<NA>,4,70,2.0,1.30,1.0,2.0,1,6112001,3.0,1,1,61,611,611,8.8,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,3.0,63,-0.083333,190.0,32.842822,32.809769,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,2400.492114,14,15,<NA>,<NA>,35.10,36.4
1106738,2018104347,0.428571,2021-02-28,3.0,180.0,2.40,6,6,1,1,1600,56.0,0,2,7.0,93.8,0.058625,34.4,0,0,1,6,310.0,5.0,3.0,3.100,602,1,470.0,-2.0,0.857143,0.714286,0.428571,<NA>,2,70,2.0,-1.00,3.0,2.0,1,6116001,3.0,0,4,64,641,641,2.0,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.00,-0.40,4.0,24,0.307143,0.0,32.858896,32.852351,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0,2431.941677,6,5,3,<NA>,35.50,34.5
1106739,2018104347,0.700000,2021-01-30,7.0,0.0,2.70,3,3,1,1,1400,56.0,0,5,10.0,82.9,0.059214,33.2,0,0,0,5,526.0,5.0,1.0,5.260,5,3,472.0,6.0,0.9,1.0,<NA>,<NA>,4,89,3.9,-3.60,4.0,4.0,1,5114001,5.0,1,4,54,541,541,1.0,2.0,1.0,342.7,869.0,531.0,0.0,187.0,2.7,31.0,1.7,1.7,-1.70,0.30,4.0,14,-0.250000,187.0,30.469096,30.671705,17.8,16.9,20.3,19.6,22.0,19.6,21.7,21.7,20.7,25.1,34.8,33.3,0.0,3.2,14.9,24.8,24.4,11.8,13.0,23.8,19.6,30.0,35.0,22.0,17.6,9.9,21.3,20.5,7.3,74.0,68.0,81.0,77.0,85.0,81.0,82.0,95.0,79.0,83.0,82.0,84.0,0.0,88.0,79.0,83.0,80.0,76.0,154.0,82.0,82.0,83.0,94.0,74.0,79.0,75.0,77.0,87.0,53.0,1538.280040,9,10,<NA>,<NA>,37.00,33.4
1106740,2018104347,0.062500,2020-12-19,1.0,510.0,1.65,8,4,1,1,1200,55.0,0,1,16.0,70.3,0.058583,35.5,1,1,1,6,310.0,5.0,3.0,3.100,602,1,466.0,-4.0,0.375,0.3125,<NA>,<NA>,2,60,1.0,2.30,1.0,2.0,1,6112001,2.0,0,4,64,641,641,10.4,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,4.0,54,-0.050000,190.0,33.528651,33.500439,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,2104.495618,6,5,<NA>,<NA>,34.00,36.3
1106741,2018104347,0.187500,2020-12-06,3.0,130.0,2.00,12,6,1,1,1200,55.0,2,1,16.0,69.9,0.058250,34.7,0,0,1,6,310.0,5.0,3.0,3.100,602,1,470.0,-2.0,0.5625,0.5625,<NA>,<NA>,3,60,1.0,1.70,1.0,2.0,1,6112001,2.0,0,4,64,641,641,2.0,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,4.0,24,0.200000,190.0,32.803859,32.784335,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,2031.534948,9,9,<NA>,<NA>,34.10,35.8
1106742,2018104347,0.277778,2020-11-22,5.0,51.0,2.40,10,5,1,1,1400,55.0,0,1,18.0,82.5,0.058929,33.8,0,0,0,5,526.0,5.0,1.0,5.260,5,3,472.0,0.0,0.944444,0.611111,<NA>,<NA>,3,60,1.0,-1.00,3.0,4.0,1,5114001,2.0,0,3,53,531,531,8.8,2.0,1.0,342.7,869.0,531.0,0.0,187.0,2.7,31.0,1.7,1.7,-1.70,0.30,3.0,63,0.005556,187.0,31.045810,31.060789,17.8,16.9,20.3,19.6,22.0,19.6,21.7,21.7,20.7,25.1,34.8,33.3,0.0,3.2,14.9,24.8,24.4,11.8,13.0,23.8,19.6,30.0,35.0,22.0,17.6,9.9,21.3,20.5,7.3,74.0,68.0,81.0,77.0,85.0,81.0,82.0,95.0,79.0,83.0,82.0,84.0,0.0,88.0,79.0,83.0,80.0,76.0,154.0,82.0,82.0,83.0,94.0,74.0,79.0,75.0,77.0,87.0,53.0,1638.328284,17,11,<NA>,<NA>,35.60,34.6
1106743,2018104347,0.187500,2020-10-24,3.0,130.0,2.30,1,1,1,1,1400,55.0,2,1,16.0,83.6,0.059714,34.0,0,0,1,5,526.0,5.0,1.0,5.260,5,3,472.0,4.0,0.9375,0.75,<NA>,<NA>,4,60,1.0,-1.20,4.0,4.0,1,5114001,2.0,1,3,53,531,531,6.5,2.0,1.0,342.7,869.0,531.0,0.0,187.0,2.7,31.0,1.7,1.7,-1.70,0.30,2.0,52,-0.487500,187.0,30.986454,30.985701,17.8,16.9,20.3,19.6,22.0,19.6,21.7,21.7,20.7,25.1,34.8,33.3,0.0,3.2,14.9,24.8,24.4,11.8,13.0,23.8,19.6,30.0,35.0,22.0,17.6,9.9,21.3,20.5,7.3,74.0,68.0,81.0,77.0,85.0,81.0,82.0,95.0,79.0,83.0,82.0,84.0,0.0,88.0,79.0,83.0,80.0,76.0,154.0,82.0,82.0,83.0,94.0,74.0,79.0,75.0,77.0,87.0,53.0,1705.025867,15,12,<NA>,<NA>,36.10,34.9
1106744,2018104347,0.250000,2020-09-20,4.0,110.0,2.40,4,2,2,1,1200,54.0,0,0,16.0,71.2,0.059333,34.6,0,0,0,6,310.0,5.0,3.0,3.100,602,1,468.0,0.0,0.875,0.875,<NA>,<NA>,4,55,0.5,1.40,1.0,4.0,1,6112001,2.0,0,3,63,631,631,5.2,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,2.0,42,-0.300000,190.0,31.619199,31.738684,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,1691.174509,14,14,<NA>,<NA>,34.70,36.1
1106745,2020105295,0.937500,2025-04-27,15.0,0.0,3.00,7,4,1,1,1200,59.0,0,5,16.0,69.5,0.057917,33.8,0,0,0,3,292.0,3.0,1.0,2.920,3,2,466.0,-30.0,0.9375,0.9375,<NA>,<NA>,4,89,3.9,0.10,2.0,3.0,1,3112001,5.0,1,1,31,311,311,8.8,2.0,1.0,411.7,702.0,498.0,0.0,167.0,1.8,25.0,1.7,1.7,0.00,-0.80,3.0,63,-0.112500,167.0,31.520962,31.597357,25.4,24.9,18.3,19.5,14.4,21.3,19.5,21.3,22.7,26.3,31.8,30.8,0.0,0.0,14.7,21.9,22.1,16.7,9.1,20.4,20.3,25.7,25.1,20.7,18.4,14.0,23.2,19.3,12.5,90.0,89.0,74.0,77.0,60.0,81.0,79.0,92.0,71.0,83.0,78.0,83.0,0.0,0.0,84.0,80.0,84.0,73.0,71.0,82.0,80.0,81.0,76.0,84.0,74.0,81.0,83.0,80.0,54.0,1497.006848,15,15,<NA>,<NA>,34.20,34.3
1106746,2020105295,0.937500,2025-01-18,15.0,0.0,3.50,7,4,1,1,1200,57.5,0,5,16.0,68.9,0.057417,34.8,0,0,0,6,310.0,5.0,3.0,3.100,602,1,496.0,6.0,0.8125,0.75,<NA>,<NA>,4,89,3.9,1.00,2.0,2.0,1,6112001,5.0,1,4,64,641,641,11.7,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,4.0,64,-0.112500,190.0,33.184285,33.090529,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,2225.092273,13,12,<NA>,<NA>,33.20,34.2
1106747,2020105295,0.687500,2024-12-01,11.0,0.0,3.10,5,3,1,1,1200,59.0,0,5,16.0,68.3,0.056917,34.1,0,0,0,6,310.0,5.0,3.0,3.100,602,1,490.0,4.0,0.375,0.4375,<NA>,<NA>,3,89,3.9,-0.20,3.0,2.0,1,6112001,5.0,1,4,64,641,641,2.0,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.00,-0.40,4.0,24,-0.237500,190.0,32.499597,32.659994,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0,1944.781407,6,7,<NA>,<NA>,33.70,33.5
1106748,2020105295,1.000000,2024-09-29,14.0,0.0,4.80,14,8,2,1,1600,59.0,2,5,14.0,97.2,0.060750,39.3,0,0,0,7,412.5,4.0,1.6,4.125,7,2,486.0,-4.0,0.571429,0.071429,0.071429,<NA>,2,89,3.9,1.60,1.0,5.0,1,7116001,5.0,0,3,73,731,731,11.7,3.0,1.0,199.0,1028.0,572.0,120.0,140.0,3.5,28.0,0.5,-0.6,0.50,-1.00,2.0,92,0.450000,0.0,35.409942,35.463479,23.4,28.0,20.9,24.6,22.4,24.5,20.4,20.5,28.3,28.8,39.9,20.7,0.0,8.3,22.1,29.7,20.1,17.1,22.2,26.1,22.2,33.3,30.0,23.4,20.7,11.7,25.2,21.4,16.8,91.0,90.0,78.0,82.0,81.0,87.0,71.0,75.0,75.0,84.0,92.0,62.0,0.0,66.0,100.0,81.0,77.0,80.0,103.0,83.0,81.0,87.0,87.0,79.0,81.0,59.0,84.0,80.0,79.0,2188.050063,8,1,1,<NA>,34.90,36.5
1106749,2020105295,0.687500,2024-09-08,11.0,0.0,3.00,6,3,1,1,1600,57.5,0,6,16.0,91.8,0.057375,34.1,0,0,0,6,310.0,5.0,3.0,3.100,602,1,490.0,12.0,0.3125,0.1875,0.125,<NA>,2,91,4.1,-0.70,3.0,4.0,1,6116001,5.0,0,3,63,631,631,2.0,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.00,-0.40,2.0,22,-0.175000,0.0,31.255590,31.301088,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0,2264.676241,5,3,2,<NA>,34.20,33.5
1106750,2020105295,1.000000,2024-04-21,17.0,0.0,5.20,17,8,0,1,1600,57.0,2,7,17.0,95.7,0.059813,38.5,0,0,0,8,404.0,5.0,0.2,4.040,803,2,478.0,-6.0,0.117647,0.176471,<NA>,<NA>,2,94,4.4,1.30,1.0,4.0,2,8116002,5.0,1,1,81,811,811,2.0,2.0,1.0,711.7,1116.0,484.0,0.0,190.0,4.3,28.0,0.0,4.0,-3.70,-0.40,3.0,23,0.450000,190.0,35.233836,35.104534,28.2,21.3,20.4,25.5,25.0,20.8,20.1,25.9,17.8,27.8,29.5,20.0,0.0,11.6,18.5,25.2,27.7,24.1,7.1,30.4,22.1,27.3,27.8,30.0,20.5,13.8,25.2,20.9,15.0,96.0,71.0,76.0,87.0,80.0,87.0,66.0,87.0,72.0,86.0,74.0,51.0,0.0,90.0,91.0,77.0,83.0,109.0,37.0,88.0,80.0,56.0,73.0,88.0,77.0,79.0,82.0,78.0,76.0,2401.952546,2,3,<NA>,<NA>,34.10,35.4
1106751,2020105295,0.125000,2024-03-30,2.0,1616.0,2.10,10,5,1,1,1600,57.0,2,-10,16.0,93.0,0.058125,35.2,0,1,1,6,310.0,5.0,3.0,3.100,602,1,484.0,-8.0,0.125,0.0625,0.0625,<NA>,2,59,0.9,-0.40,3.0,2.0,1,6116001,5.0,0,1,61,611,611,5.5,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.00,-0.40,3.0,33,0.075000,0.0,33.321934,33.334380,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0,2594.274970,2,1,1,<NA>,35.50,35.1
1106752,2020105295,0.812500,2024-02-25,13.0,0.0,3.40,14,7,0,1,1800,57.0,2,7,16.0,109.5,0.060833,38.8,0,0,0,6,310.0,2.0,3.0,3.100,601,1,492.0,2.0,0.125,0.125,0.125,0.125,2,94,4.4,2.00,1.0,2.0,1,6118001,5.0,0,4,64,641,641,2.0,4.0,1.0,204.9,885.0,915.0,154.0,154.0,5.3,20.0,2.0,-2.0,2.00,-0.40,4.0,24,0.325000,154.0,36.645649,36.532136,25.9,22.7,24.0,25.9,19.6,21.1,22.1,19.8,32.3,28.0,33.8,36.8,0.0,14.7,21.1,26.5,22.7,17.1,22.0,22.6,22.6,32.9,28.0,30.5,22.2,7.6,24.3,19.8,19.4,88.0,86.0,83.0,86.0,74.0,80.0,82.0,70.0,95.0,82.0,79.0,89.0,0.0,99.0,77.0,86.0,76.0,69.0,101.0,82.0,80.0,80.0,80.0,84.0,89.0,45.0,82.0,80.0,76.0,3027.853616,2,2,2,2,35.60,37.6
1106753,2020105295,0.823529,2023-12-23,14.0,0.0,2.80,3,2,1,1,1400,57.0,0,7,17.0,80.1,0.057214,35.5,0,0,0,9,357.0,5.0,1.9,3.570,901,1,490.0,2.0,0.176471,0.176471,<NA>,<NA>,2,94,4.4,1.90,1.0,3.0,1,9114001,5.0,1,4,94,941,941,13.0,2.0,1.0,458.2,815.0,585.0,0.0,170.0,1.8,24.0,0.0,-0.4,-0.70,-0.50,4.0,74,-0.373529,170.0,33.172614,32.928706,25.7,26.3,25.0,21.4,21.0,24.3,17.7,14.8,25.2,27.9,26.1,29.6,0.0,7.7,15.6,25.6,25.5,15.8,14.6,24.2,21.5,23.3,27.1,24.4,23.1,11.0,22.5,8.6,22.0,96.0,91.0,83.0,75.0,82.0,92.0,71.0,62.0,80.0,85.0,73.0,76.0,0.0,52.0,73.0,82.0,81.0,101.0,87.0,75.0,83.0,71.0,75.0,84.0,88.0,65.0,82.0,81.0,58.0,2101.266646,3,3,<NA>,<NA>,33.10,35.0
1106754,2020105295,0.625000,2023-11-19,10.0,0.0,3.20,4,2,1,1,1600,57.0,0,8,16.0,93.7,0.058563,35.1,0,0,0,8,404.0,5.0,0.2,4.040,803,2,488.0,0.0,0.375,0.3125,<NA>,<NA>,2,98,4.8,0.00,3.0,4.0,2,8116002,5.0,0,3,83,831,831,8.8,2.0,1.0,711.7,1116.0,484.0,0.0,190.0,4.3,28.0,0.0,4.0,-3.70,-0.40,3.0,63,-0.300000,190.0,32.227030,32.212722,28.2,21.3,20.4,25.5,25.0,20.8,20.1,25.9,17.8,27.8,29.5,20.0,0.0,11.6,18.5,25.2,27.7,24.1,7.1,30.4,22.1,27.3,27.8,30.0,20.5,13.8,25.2,20.9,15.0,96.0,71.0,76.0,87.0,80.0,87.0,66.0,87.0,72.0,86.0,74.0,51.0,0.0,90.0,91.0,77.0,83.0,109.0,37.0,88.0,80.0,56.0,73.0,88.0,77.0,79.0,82.0,78.0,76.0,2394.122163,6,5,<NA>,<NA>,34.30,34.3
1106755,2020105295,0.666667,2023-10-08,8.0,0.0,2.60,2,2,2,1,1800,56.0,0,7,12.0,105.9,0.058833,34.3,0,0,0,5,526.0,5.0,1.0,5.260,5,3,488.0,4.0,0.25,0.333333,0.333333,<NA>,2,94,4.4,-1.90,4.0,4.0,1,5118001,5.0,0,3,53,531,531,2.0,3.0,1.0,156.6,1226.0,574.0,187.0,187.0,2.7,31.0,-0.7,1.7,-0.70,0.30,2.0,22,-0.383333,0.0,31.716152,31.748089,21.3,21.6,22.7,23.6,25.1,23.0,25.8,23.0,25.7,30.8,39.3,33.8,2.9,10.7,23.7,26.9,25.4,20.7,10.4,28.3,22.0,29.1,34.8,29.5,16.8,12.9,26.3,20.3,15.0,82.0,79.0,84.0,89.0,86.0,78.0,86.0,86.0,87.0,89.0,86.0,70.0,28.0,80.0,85.0,83.0,88.0,104.0,67.0,90.0,83.0,73.0,86.0,87.0,73.0,77.0,85.0,83.0,62.0,2054.056914,3,4,4,<NA>,36.00,34.1
1106756,2020105295,0.529412,2023-05-07,9.0,0.0,2.70,6,3,3,1,1600,57.0,2,8,17.0,94.5,0.059062,35.5,0,0,0,5,526.0,5.0,1.0,5.260,5,3,484.0,2.0,0.529412,0.411765,<NA>,<NA>,3,98,4.8,1.10,1.0,4.0,1,5116001,5.0,0,1,51,511,511,7.8,2.0,1.0,542.7,1069.0,531.0,0.0,187.0,2.7,31.0,1.7,1.7,-1.70,0.30,2.0,62,-0.197059,187.0,32.515482,32.509774,21.7,19.1,20.2,19.9,20.4,24.5,23.0,24.5,20.3,28.4,38.9,34.8,1.0,8.3,14.8,26.7,20.6,18.5,22.6,24.6,20.8,33.3,30.8,24.2,19.1,12.8,23.4,20.2,17.3,85.0,81.0,77.0,73.0,76.0,92.0,85.0,95.0,73.0,88.0,85.0,80.0,10.0,82.0,80.0,83.0,84.0,79.0,103.0,82.0,83.0,90.0,81.0,80.0,85.0,74.0,83.0,84.0,93.0,2338.354164,9,7,<NA>,<NA>,34.30,35.4
1106757,2020105295,0.062500,2023-04-08,1.0,5513.4,1.86,5,3,2,1,1600,56.0,2,7,16.0,93.7,0.058563,36.0,1,1,1,6,310.0,5.0,3.0,3.100,602,1,482.0,-10.0,0.25,0.125,0.1875,<NA>,2,94,4.4,1.00,2.0,2.0,1,6116001,5.0,1,1,61,611,611,7.7,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.00,-0.40,3.0,53,-0.237500,0.0,34.017670,33.914372,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0,2998.241187,4,2,3,<NA>,35.00,36.0
1106758,2020105295,0.083333,2023-02-26,1.0,780.0,1.65,4,4,1,1,1600,56.0,0,2,12.0,94.0,0.058750,34.7,1,1,1,6,310.0,5.0,3.0,3.100,602,1,492.0,-8.0,0.166667,0.166667,0.083333,<NA>,2,70,2.0,-1.20,4.0,2.0,1,6116001,3.0,0,4,64,641,641,2.0,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.00,-0.40,4.0,24,-0.216667,0.0,33.172891,33.240535,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0,2424.386385,2,2,1,<NA>,35.90,34.7
1106759,2020105295,0.062500,2023-01-15,1.0,550.0,1.86,9,5,2,1,1600,56.0,0,1,16.0,95.5,0.059687,35.7,1,1,1,6,310.0,5.0,3.0,3.100,602,1,500.0,6.0,0.25,0.1875,0.25,<NA>,2,60,1.0,0.90,2.0,2.0,1,6116001,3.0,1,4,64,641,641,11.7,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.00,-0.40,4.0,64,0.012500,0.0,34.011983,34.078768,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0,2719.602723,4,3,4,<NA>,35.40,36.3
1106760,2020105295,0.555556,2022-10-29,5.0,52.0,3.50,3,3,1,1,1800,55.0,0,1,9.0,107.9,0.059944,38.3,0,0,0,5,526.0,5.0,1.0,5.260,5,3,494.0,2.0,0.111111,0.111111,0.111111,<NA>,2,60,1.0,2.00,1.0,4.0,1,5118001,2.0,1,3,53,531,531,10.4,3.0,1.0,156.6,1226.0,574.0,187.0,187.0,2.7,31.0,-0.7,1.7,-0.70,0.30,2.0,82,-0.216667,0.0,35.431920,35.180730,21.3,21.6,22.7,23.6,25.1,23.0,25.8,23.0,25.7,30.8,39.3,33.8,2.9,10.7,23.7,26.9,25.4,20.7,10.4,28.3,22.0,29.1,34.8,29.5,16.8,12.9,26.3,20.3,15.0,82.0,79.0,84.0,89.0,86.0,78.0,86.0,86.0,87.0,89.0,86.0,70.0,28.0,80.0,85.0,83.0,88.0,104.0,67.0,90.0,83.0,73.0,86.0,87.0,73.0,77.0,85.0,83.0,62.0,2231.309746,1,1,1,<NA>,34.80,36.8

In [ ]:
from pathlib import Path
from tqdm.notebook import tqdm
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from tqdm.notebook import tqdm
from webdriver_manager.chrome import ChromeDriverManager
from io import StringIO 

DATA_DIR = Path("..", "data")
POPULATION_DIR = DATA_DIR / "00_population"
INPUT_DIR = DATA_DIR / "01_preprocessed"
OUTPUT_DIR = DATA_DIR / "02_features"
OUTPUT_INFO_DIR = Path("..", "data", "01_preprocessed")

OUTPUT_DIR.mkdir(exist_ok=True, parents=True)
output_dir_info: Path = OUTPUT_INFO_DIR  # カンマを削除
output_filename_info: str = "race_info_turf.csv"

features_s = pd.read_csv(output_dir_info / output_filename_info, sep="\t")

features_s.head(100)

In [23]:
race_info_preprocessed_turf.tail(100)

,race_id,date,race_type,around,course_len,weather,ground_state,race_class,place,season_level,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,place_season_type_course_len,lap_type,race_day_count,race_date_day_count,goal_range_100,course_type,course_len_type,curve_amount,start_point,start_range,straight_total,curve_total,curve_R12,curve_R34,height_diff,width,start_slope,flont_slope,first_curve_slope,last_curve_slope,season_turf,day_season_turf,season_turf_condition,waku_1,waku_2,waku_3,waku_4,waku_5,waku_6,waku_7,waku_8,position_1,position_2,position_3,position_4,course_len_diff_-500,course_len_diff_-350,course_len_diff_-150,course_len_diff_0,course_len_diff_150,course_len_diff_350,course_len_diff_500,class_diff_up,class_diff_stay,class_diff_down,age_3,age_4,age_5,age_6,sex_men,sex_women,sex_nosex,waku_1_EX,waku_2_EX,waku_3_EX,waku_4_EX,waku_5_EX,waku_6_EX,waku_7_EX,waku_8_EX,position_1_EX,position_2_EX,position_3_EX,position_4_EX,course_len_diff_-500_EX,course_len_diff_-350_EX,course_len_diff_-150_EX,course_len_diff_0_EX,course_len_diff_150_EX,course_len_diff_350_EX,course_len_diff_500_EX,class_diff_up_EX,class_diff_stay_EX,class_diff_down_EX,age_3_EX,age_4_EX,age_5_EX,age_6_EX,sex_men_EX,sex_women_EX,sex_nosex_EX
31613,202506030105,2025-03-29,1,0,1200,3,2,2,6,1,1,61,611,5,51,1,11,3,31,61011,2,6121,2,602,1,310.0,5.0,3.0,6111200,1,05,73884805,3.100,6112002,2,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.0,-0.4,3.0,13,1.0,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0
31614,202506030106,2025-03-29,1,0,1800,3,2,2,6,1,1,61,611,6,61,1,11,3,31,61011,2,6121,2,601,1,310.0,2.0,3.0,6111800,2,06,73884806,3.100,6118001,1,4.0,1.0,204.9,885.0,915.0,154.0,154.0,5.3,20.0,2.0,-2.0,2.0,-0.4,3.0,13,1.0,25.9,22.7,24.0,25.9,19.6,21.1,22.1,19.8,32.3,28.0,33.8,36.8,0.0,14.7,21.1,26.5,22.7,17.1,22.0,22.6,22.6,32.9,28.0,30.5,22.2,7.6,24.3,19.8,19.4,88.0,86.0,83.0,86.0,74.0,80.0,82.0,70.0,95.0,82.0,79.0,89.0,0.0,99.0,77.0,86.0,76.0,69.0,101.0,82.0,80.0,80.0,80.0,84.0,89.0,45.0,82.0,80.0,76.0
31616,202506030108,2025-03-29,1,0,1800,3,2,3,6,1,1,61,611,8,81,1,11,3,31,61011,2,6121,2,601,1,310.0,2.0,3.0,6111800,2,08,73884808,3.100,6118001,1,4.0,1.0,204.9,885.0,915.0,154.0,154.0,5.3,20.0,2.0,-2.0,2.0,-0.4,3.0,13,1.0,25.9,22.7,24.0,25.9,19.6,21.1,22.1,19.8,32.3,28.0,33.8,36.8,0.0,14.7,21.1,26.5,22.7,17.1,22.0,22.6,22.6,32.9,28.0,30.5,22.2,7.6,24.3,19.8,19.4,88.0,86.0,83.0,86.0,74.0,80.0,82.0,70.0,95.0,82.0,79.0,89.0,0.0,99.0,77.0,86.0,76.0,69.0,101.0,82.0,80.0,80.0,80.0,84.0,89.0,45.0,82.0,80.0,76.0
31619,202506030111,2025-03-29,1,0,2500,2,2,7,6,1,1,61,611,11,111,1,11,3,31,61011,2,6121,2,601,1,310.0,2.0,3.0,6112500,-1,11,73884811,3.100,6125001,1,6.0,1.0,192.0,1277.0,1223.0,154.0,154.0,5.3,20.0,0.0,-2.0,0.0,-0.4,3.0,13,1.0,17.7,24.2,20.5,21.1,34.9,25.8,23.7,21.4,26.3,24.6,34.8,34.8,20.0,27.0,27.1,20.3,26.4,1.0,19.6,33.8,22.0,38.1,40.2,28.9,21.3,11.7,23.0,28.0,18.0,70.0,93.0,78.0,73.0,109.0,89.0,67.0,86.0,91.0,80.0,94.0,114.0,96.0,88.0,91.0,62.0,86.0,1.0,59.0,96.0,80.0,92.0,90.0,86.0,83.0,63.0,81.0,85.0,98.0
31626,202509020106,2025-03-29,1,0,1400,1,0,2,9,1,1,91,911,6,61,1,11,2,21,91011,2,9121,2,901,1,357.0,5.0,1.9,9111400,4,06,73884806,3.570,9114001,1,2.0,1.0,458.2,815.0,585.0,0.0,170.0,1.8,24.0,0.0,-0.4,-0.7,-0.5,3.0,13,1.0,25.7,26.3,25.0,21.4,21.0,24.3,17.7,14.8,25.2,27.9,26.1,29.6,0.0,7.7,15.6,25.6,25.5,15.8,14.6,24.2,21.5,23.3,27.1,24.4,23.1,11.0,22.5,8.6,22.0,96.0,91.0,83.0,75.0,82.0,92.0,71.0,62.0,80.0,85.0,73.0,76.0,0.0,52.0,73.0,82.0,81.0,101.0,87.0,75.0,83.0,71.0,75.0,84.0,88.0,65.0,82.0,81.0,58.0
31629,202509020109,2025-03-29,1,0,1800,1,0,2,9,1,1,91,911,9,91,1,11,2,21,91011,2,9121,2,902,3,474.0,5.0,1.9,9111800,3,09,73884809,4.740,9118002,2,2.0,1.0,644.4,1118.0,682.0,0.0,192.0,2.3,24.0,0.0,0.4,-0.2,-2.2,3.0,13,1.0,30.0,27.1,30.2,28.0,19.1,24.9,21.8,22.1,26.7,31.2,41.9,41.9,12.8,8.4,24.3,28.3,28.2,27.1,17.9,27.2,24.1,39.4,38.3,30.9,18.0,13.4,27.8,22.6,14.3,91.0,87.0,88.0,83.0,70.0,83.0,77.0,81.0,75.0,80.0,90.0,79.0,95.0,77.0,79.0,86.0,81.0,79.0,75.0,78.0,85.0,82.0,90.0,83.0,75.0,84.0,85.0,78.0,72.0
31630,202509020110,2025-03-29,1,0,1600,2,0,3,9,1,1,91,911,10,101,1,11,2,21,91011,2,9121,2,902,3,474.0,5.0,1.9,9111600,3,10,73884810,4.740,9116002,2,2.0,1.0,444.4,918.0,682.0,0.0,192.0,2.3,24.0,-0.2,0.4,-0.2,-2.2,3.0,13,1.0,26.0,24.4,25.4,21.0,19.8,22.5,21.4,17.9,19.6,26.7,32.1,32.1,1.0,11.4,14.4,27.4,24.5,14.4,25.0,23.0,21.9,32.5,29.4,30.5,21.9,10.2,24.0,20.0,15.8,100.0,87.0,87.0,80.0,78.0,81.0,81.0,65.0,79.0,83.0,80.0,95.0,1.0,85.0,74.0,83.0,86.0,66.0,102.0,79.0,83.0,75.0,82.0,83.0,83.0,64.0,82.0,79.0,98.0
31631,202509020111,2025-03-29,1,0,1800,2,0,6,9,1,1,91,911,11,111,1,11,2,21,91011,2,9121,2,902,3,474.0,5.0,1.9,9111800,3,11,73884811,4.740,9118002,2,2.0,1.0,644.4,1118.0,682.0,0.0,192.0,2.3,24.0,0.0,0.4,-0.2,-2.2,3.0,13,1.0,30.0,27.1,30.2,28.0,19.1,24.9,21.8,22.1,26.7,31.2,41.9,41.9,12.8,8.4,24.3,28.3,28.2,27.1,17.9,27.2,24.1,39.4,38.3,30.9,18.0,13.4,27.8,22.6,14.3,91.0,87.0,88.0,83.0,70.0,83.0,77.0,81.0,75.0,80.0,90.0,79.0,95.0,77.0,79.0,86.0,81.0,79.0,75.0,78.0,85.0,82.0,90.0,83.0,75.0,84.0,85.0,78.0,72.0
31638,202507020506,2025-03-29,1,1,2000,1,1,2,7,1,1,71,711,6,61,5,51,2,21,71051,1,7111,3,7,2,412.5,4.0,1.6,7112000,-1,06,73884806,4.125,7120001,1,4.0,1.0,314.1,1142.0,858.0,120.0,140.0,3.5,28.0,2.0,-0.6,0.2,-1.0,3.0,53,7.7,29.8,28.8,25.7,24.9,25.6,23.5,22.4,20.4,28.1,31.2,40.1,50.8,6.2,19.3,23.1,27.7,28.4,29.7,21.1,25.4,24.1,39.3,30.7,30.8,22.0,11.9,28.0,11.4,20.9,97.0,84.0,84.0,86.0,82.0,80.0,78.0,73.0,91.0,82.0,85.0,96.0,76.0,91.0,81.0,82.0,91.0,76.0,100.0,78.0,84.0,94.0,86.0,85.0,76.0,66.0,85.0,77.0,73.0
31640,202507020508,2025-03-29,1,1,1600,1,2,2,7,1,1,71,711,8,81,5,51,2,21,71051,1,7111,3,7,2,412.5,4.0,1.6,7111600,-1,08,73884808,4.125,7116001,1,3.0,1.0,199.0,1028.0,572.0,120.0,140.0,3.5,28.0,0.5,-0.6,0.5,-1.0,3.0,53,7.7,23.4,28.0,20.9,24.6,22.4,24.5,20.4,20.5,28.3,28.8,39.9,20.7,0.0,8.3,22.1,29.7,20.1,17.1,22.2,26.1,22.2,33.3,30.0,23.4,20.7,11.7,25.2,21.4,16.8,91.0,90.0,78.0,82.0,81.0,87.0,71.0,75.0,75.0,84.0,92.0,62.0,0.0,66.0,100.0,81.0,77.0,80.0,103.0,83.0,81.0,87.0,87.0,79.0,81.0,59.0,84.0,80.0,79.0
31642,202507020510,2025-03-29,1,1,2200,1,2,3,7,1,1,71,711,10,101,5,51,2,21,71051,1,7111,3,7,2,412.5,4.0,1.6,7112200,-1,10,73884810,4.125,7122001,1,4.0,1.0,514.1,1342.0,858.0,120.0,140.0,3.5,28.0,2.0,-0.6,0.2,-1.0,3.0,53,7.7,24.5,31.1,25.3,30.4,28.4,27.9,20.9,23.9,22.0,29.6,41.4,47.8,1.4,19.0,27.2,32.0,30.8,20.7,22.2,24.0,24.8,47.7,30.6,30.3,23.6,13.0,27.3,18.2,16.1,80.0,95.0,73.0,87.0,82.0,81.0,82.0,81.0,67.0,81.0,83.0,84.0,12.0,96.0,78.0,86.0,79.0,73.0,106.0,79.0,79.0,101.0,87.0,80.0,75.0,73.0,82.0,68.0,82.0
31643,202507020511,2025-03-29,1,1,1600,1,2,4,7,1,1,71,711,11,111,5,51,2,21,71051,1,7111,3,7,2,412.5,4.0,1.6,7111600,-1,11,73884811,4.125,7116001,1,3.0,1.0,199.0,1028.0,572.0,120.0,140.0,3.5,28.0,0.5,-0.6,0.5,-1.0,3.0,53,7.7,23.4,28.0,20.9,24.6,22.4,24.5,20.4,20.5,28.3,28.8,39.9,20.7,0.0,8.3,22.1,29.7,20.1,17.1,22.2,26.1,22.2,33.3,30.0,23.4,20.7,11.7,25.2,21.4,16.8,91.0,90.0,78.0,82.0,81.0,87.0,71.0,75.0,75.0,84.0,92.0,62.0,0.0,66.0,100.0,81.0,77.0,80.0,103.0,83.0,81.0,87.0,87.0,79.0,81.0,59.0,84.0,80.0,79.0
31653,202506030209,2025-03-30,1,0,2000,1,0,2,6,1,1,61,611,9,91,2,21,3,31,61021,2,6121,2,601,1,310.0,2.0,3.0,6112000,2,09,73884909,3.100,6120001,1,4.0,1.0,404.9,1085.0,915.0,154.0,154.0,5.3,20.0,2.0,-2.0,2.0,-0.4,3.0,23,2.0,23.9,17.6,18.0,22.8,22.1,25.2,21.6,20.1,22.2,27.7,35.3,29.7,5.7,13.5,21.3,24.6,24.5,28.4,16.7,22.2,21.5,20.8,25.2,30.0,20.0,11.3,23.4,17.7,11.0,84.0,67.0,77.0,86.0,83.0,91.0,86.0,79.0,77.0,84.0,80.0,75.0,38.0,80.0,83.0,83.0,81.0,93.0,66.0,84.0,83.0,62.0,73.0,89.0,81.0,71.0,84.0,80.0,50.0
31654,202506030210,2025-03-30,1,0,1200,1,0,4,6,1,1,61,611,10,101,2,21,3,31,61021,2,6121,2,602,1,310.0,5.0,3.0,6111200,1,10,73884910,3.100,6112002,2,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.0,-0.4,3.0,23,2.0,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0
31656,202506030212,2025-03-30,1,0,1200,1,0,3,6,1,1,61,611,12,121,2,21,3,31,61021,2,6121,2,602,1,310.0,5.0,3.0,6111200,1,12,73884912,3.100,6112002,2,2.0,1.0,275.1,585.0,615.0,0.0,190.0,5.3,24.0,-3.7,-2.0,-1.0,-0.4,3.0,23,2.0,27.2,22.8,22.9,22.7,19.4,16.7,20.5,14.8,22.1,25.9,23.8,33.3,0.0,0.0,13.4,21.8,20.0,22.7,9.8,24.4,19.9,24.1,30.7,23.5,19.0,12.1,21.9,20.4,14.7,97.0,80.0,90.0,85.0,72.0,75.0,77.0,69.0,72.0,84.0,77.0,100.0,0.0,0.0,78.0,81.0,78.0,90.0,78.0,87.0,79.0,84.0,88.0,80.0,80.0,69.0,81.0,81.0,70.0
31663,202509020207,2025-03-30,1,0,1400,2,0,2,9,1,1,91,911,7,71,2,21,2,21,91021,2,9121,2,901,1,357.0,5.0,1.9,9111400,4,07,73884907,3.570,9114001,1,2.0,1.0,458.2,815.0,585.0,0.0,170.0,1.8,24.0,0.0,-0.4,-0.7,-0.5,3.0,23,2.0,25.7,26.3,25.0,21.4,21.0,24.3,17.7,14.8,25.2,27.9,26.1,29.6,0.0,7.7,15.6,25.6,25.5,15.8,14.6,24.2,21.5,23.3,27.1,24.4,23.1,11.0,22.5,8.6,22.0,96.0,91.0,83.0,75.0,82.0,92.0,71.0,62.0,80.0,85.0,73.0,76.0,0.0,52.0,73.0,82.0,81.0,101.0,87.0,75.0,83.0,71.0,75.0,84.0,88.0,65.0,82.0,81.0,58.0
31665,202509020209,2025-03-30,1,0,2000,2,0,3,9,1,1,91,911,9,91,2,21,2,21,91021,2,9121,2,901,1,357.0,5.0,1.9,9112000,-1,09,73884909,3.570,9120001,1,4.0,1.0,330.5,1067.0,933.0,133.0,170.0,1.8,24.0,1.9,-0.4,0.0,-1.8,3.0,23,2.0,30.0,25.2,23.7,29.6,24.4,28.5,26.3,22.5,23.5,32.5,38.0,29.3,4.6,19.9,23.0,30.0,28.9,30.1,17.3,27.2,24.8,37.7,41.6,33.2,21.2,12.9,28.9,20.3,17.3,90.0,77.0,72.0,85.0,78.0,84.0,92.0,74.0,70.0,83.0,83.0,69.0,41.0,75.0,83.0,80.0,82.0,95.0,62.0,81.0,80.0,91.0,82.0,82.0,76.0,76.0,84.0,71.0,77.0
31666,202509020210,2025-03-30,1,0,2400,2,0,4,9,1,1,91,911,10,101,2,21,2,21,91021,2,9121,2,902,3,474.0,5.0,1.9,9112400,3,10,73884910,4.740,9124002,2,4.0,1.0,309.0,1370.0,1030.0,133.0,192.0,2.3,24.0,1.9,0.4,0.0,-2.2,3.0,23,2.0,26.7,32.6,31.1,37.5,18.3,28.8,28.0,23.2,28.6,31.7,44.3,44.3,11.5,29.2,30.2,38.7,32.3,1.0,18.5,33.0,26.2,46.7,46.1,38.0,24.3,14.3,31.4,20.0,17.3,93.0,85.0,85.0,105.0,60.0,85.0,86.0,75.0,108.0,78.0,93.0,88.0,61.0,90.0,79.0,85.0,91.0,1.0,90.0,89.0,82.0,98.0,84.0,96.0,71.0,61.0,89.0,68.0,57.0
31667,202509020211,2025-03-30,1,0,1600,2,0,5,9,1,1,91,911,11,111,2,21,2,21,91021,2,9121,2,902,3,474.0,5.0,1.9,9111600,3,11,73884911,4.740,9116002,2,2.0,1.0,444.4,918.0,682.0,0.0,192.0,2.3,24.0,-0.2,0.4,-0.2,-2.2,3.0,23,2.0,26.0,24.4,25.4,21.0,19.8,22.5,21.4,17.9,19.6,26.7,32.1,32.1,1.0,11.4,14.4,27.4,24.5,14.4,25.0,23.0,21.9,32.5,29.4,30.5,21.9,10.2,24.0,20.0,15.8,100.0,87.0,87.0,80.0,78.0,81.0,81.0,65.0,79.0,83.0,80.0,95.0,1.0,85.0,74.0,83.0,86.0,66.0,102.0,79.0,83.0,75.0,82.0,83.0,83.0,64.0,82.0,79.0,98.0
31674,202507020606,2025-03-30,1,1,2200,1,0,2,7,1,1,71,711,6,61,6,61,2,21,71061,1,7111,3,7,2,412.5,4.0,1.6,7112200,-1,06,73884906,4.125,7122001,1,4.0,1.0,514.1,1342.0,858.0,120.0,140.0,3.5,28.0,2.0,-0.6,0.2,-1.0,3.0,63,8.8,24.5,31.1,25.3,30.4,28.4,27.9,20.9,23.9,22.0,29.6,41.4,47.8,1.4,19.0,27.2,32.0,30.8,20.7,22.2,24.0,24.8,47.7,30.6,30.3,23.6,13.0,27.3,18.2,16.1,80.0,95.0,73.0,87.0,82.0,81.0,82.0,81.0,67.0,81.0,83.0,84.0,12.0,96.0,78.0,86.0,79.0,73.0,106.0,79.0,79.0,101.0,87.0,80.0,75.0,73.0,82.0,68.0,82.0
31676,202507020608,2025-03-30,1,1,2200,1,0,2,7,1,1,71,711,8,81,6,61,2,21,71061,1,7111,3,7,2,412.5,4.0,1.6,7112200,-1,08,73884908,4.125,7122001,1,4.0,1.0,514.1,1342.0,858.0,120.0,140.0,3.5,28.0,2.0,-0.6,0.2,-1.0,3.0,63,8.8,24.5,31.1,25.3,30.4,28.4,27.9,20.9,23.9,22.0,29.6,41.4,47.8,1.4,19.0,27.2,32.0,30.8,20.7,22.2,24.0,24.8,47.7,30.6,30.3,23.6,13.0,27.3,18.2,16.1,80.0,95.0,73.0,87.0,82.0,81.0,82.0,81.0,67.0,81.0,83.0,84.0,12.0,96.0,78.0,86.0,79.0,73.0,106.0,79.0,79.0,101.0,87.0,80.0,75.0,73.0,82.0,68.0,82.0
31679,202507020611,2025-03-30,1,1,1200,1,0,8,7,1,1,71,711,11,111,6,61,2,21,71061,1,7111,3,7,2,412.5,4.0,1.6,7111200,1,11,73884911,4.125,7112001,1,2.0,1.0,315.5,728.0,472.0,0.0,140.0,3.5,28.0,-0.5,-0.6,-1.4,-1.0,3.0,63,8.8,22.5,27.1,26.3,22.5,25.8,13.4,16.1,11.3,31.1,21.4,26.1,38.5,0.0,0.0,12.5,19.7,21.9,18.8,5.0,23.3,18.9,18.2,21.0,20.7,20.8,12.6,22.3,18.3,16.1,95.0,103.0,86.0,86.0,92.0,58.0,75.0,53.0,106.0,77.0,70.0,90.0,0.0,0.0,83.0,77.0,87.0,90.0,53.0,76.0,81.0,67.0,69.0,84.0,84.0,75.0,83.0,76.0,102.0
31688,202506030308,2025-04-05,1,0,1600,1,0,3,6,2,1,61,611,8,81,3,31,3,31,61031,2,6121,2,602,1,310.0,5.0,3.0,6111600,4,08,73885508,3.100,6116002,2,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.0,-0.4,3.0,33,5.5,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0
31689,202506030309,2025-04-05,1,0,2200,1,0,2,6,2,1,61,611,9,91,3,31,3,31,61031,2,6121,2,602,1,310.0,5.0,3.0,6112200,2,09,73885509,3.100,6122002,2,5.0,1.0,432.3,1017.0,1183.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.0,-0.4,3.0,33,5.5,27.9,22.6,17.9,24.0,16.9,18.5,22.3,23.0,25.0,28.6,36.0,36.0,1.5,14.9,24.8,25.5,24.8,24.2,21.7,19.8,21.6,37.5,23.6,30.8,21.7,11.2,23.1,19.9,10.6,102.0,86.0,71.0,77.0,72.0,58.0,89.0,98.0,100.0,81.0,86.0,86.0,16.0,79.0,88.0,76.0,75.0,100.0,59.0,78.0,81.0,82.0,75.0,81.0,83.0,78.0,82.0,80.0,57.0
31691,202506030311,2025-04-05,1,0,1600,1,0,-10,6,2,1,61,611,11,111,3,31,3,31,61031,2,6121,2,602,1,310.0,5.0,3.0,6111600,4,11,73885511,3.100,6116002,2,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.0,-0.4,3.0,33,5.5,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0
31700,202509020308,2025-04-05,1,0,1800,1,0,3,9,2,1,91,911,8,81,3,31,2,21,91031,2,9121,2,902,3,474.0,5.0,1.9,9111800,3,08,73885508,4.740,9118002,2,2.0,1.0,644.4,1118.0,682.0,0.0,192.0,2.3,24.0,0.0,0.4,-0.2,-2.2,3.0,33,5.5,30.0,27.1,30.2,28.0,19.1,24.9,21.8,22.1,26.7,31.2,41.9,41.9,12.8,8.4,24.3,28.3,28.2,27.1,17.9,27.2,24.1,39.4,38.3,30.9,18.0,13.4,27.8,22.6,14.3,91.0,87.0,88.0,83.0,70.0,83.0,77.0,81.0,75.0,80.0,90.0,79.0,95.0,77.0,79.0,86.0,81.0,79.0,75.0,78.0,85.0,82.0,90.0,83.0,75.0,84.0,85.0,78.0,72.0
31701,202509020309,2025-04-05,1,0,2400,1,0,2,9,2,1,91,911,9,91,3,31,2,21,91031,2,9121,2,902,3,474.0,5.0,1.9,9112400,3,09,73885509,4.740,9124002,2,4.0,1.0,309.0,1370.0,1030.0,133.0,192.0,2.3,24.0,1.9,0.4,0.0,-2.2,3.0,33,5.5,26.7,32.6,31.1,37.5,18.3,28.8,28.0,23.2,28.6,31.7,44.3,44.3,11.5,29.2,30.2,38.7,32.3,1.0,18.5,33.0,26.2,46.7,46.1,38.0,24.3,14.3,31.4,20.0,17.3,93.0,85.0,85.0,105.0,60.0,85.0,86.0,75.0,108.0,78.0,93.0,88.0,61.0,90.0,79.0,85.0,91.0,1.0,90.0,89.0,82.0,98.0,84.0,96.0,71.0,61.0,89.0,68.0,57.0
31703,202509020311,2025-04-05,1,0,1600,1,0,6,9,2,1,91,911,11,111,3,31,2,21,91031,2,9121,2,902,3,474.0,5.0,1.9,9111600,3,11,73885511,4.740,9116002,2,2.0,1.0,444.4,918.0,682.0,0.0,192.0,2.3,24.0,-0.2,0.4,-0.2,-2.2,3.0,33,5.5,26.0,24.4,25.4,21.0,19.8,22.5,21.4,17.9,19.6,26.7,32.1,32.1,1.0,11.4,14.4,27.4,24.5,14.4,25.0,23.0,21.9,32.5,29.4,30.5,21.9,10.2,24.0,20.0,15.8,100.0,87.0,87.0,80.0,78.0,81.0,81.0,65.0,79.0,83.0,80.0,95.0,1.0,85.0,74.0,83.0,86.0,66.0,102.0,79.0,83.0,75.0,82.0,83.0,83.0,64.0,82.0,79.0,98.0
31711,202506030407,2025-04-06,1,0,1600,2,0,2,6,2,1,61,611,7,71,4,41,3,31,61041,1,6111,3,602,1,310.0,5.0,3.0,6111600,4,07,73885607,3.100,6116002,2,3.0,1.0,239.8,825.0,775.0,190.0,190.0,5.3,24.0,2.0,-2.0,2.0,-0.4,3.0,43,6.6,24.6,21.6,21.6,22.5,22.5,18.5,18.4,19.9,20.3,28.0,32.3,32.3,0.0,7.3,18.7,26.8,21.0,19.6,12.9,24.0,21.0,29.2,25.6,25.2,19.7,14.7,81.0,74.0,105.0,92.0,77.0,79.0,77.0,83.0,73.0,76.0,87.0,72.0,86.0,74.0,98.0,0.0,60.0,77.0,82.0,80.0,86.0,70.0,83.0,79.0,78.0,73.0,79.0,90.0,79.0,81.0,79.0,93.0
31712,202506030408,2025-04-06,1,0,1800,0,0,2,6,2,1,61,611,8,81,4,41,3,31,61041,1,6111,3,601,1,310.0,2.0,3.0,6111800,2,08,73885608,3.100,6118001,1,4.0,1.0,204.9,885.0,915.0,154.0,154.0,5.3,20.0,2.0,-2.0,2.0,-0.4,3.0,43,6.6,25.9,22.7,24.0,25.9,19.6,21.1,22.1,19.8,32.3,28.0,33.8,36.8,0.0,14.7,21.1,26.5,22.7,17.1,22.0,22.6,22.6,32.9,28.0,30.5,22.2,7.6,24.3,19.8,19.4,88.0,86.0,83.0,86.0,74.0,80.0,82.0,70.0,95.0,82.0,79.0,89.0,0.0,99.0,77.0,86.0,76.0,69.0,101.0,82.0,80.0,80.0,80.0,84.0,89.0,45.0,82.0,80.0,76.0
31713,202506030409,2025-04-06,1,0,2500,0,0,3,6,2,1,61,611,9,91,4,41,3,31,61041,1,6111,3,601,1,310.0,2.0,3.0,6112500,-1,09,73885609,3.100,6125001,1,6.0,1.0,192.0,1277.0,1223.0,154.0,154.0,5.3,20.0,0.0,-2.0,0.0,-0.4,3.0,43,6.6,17.7,24.2,20.5,21.1,34.9,25.8,23.7,21.4,26.3,24.6,34.8,34.8,20.0,27.0,27.1,20.3,26.4,1.0,19.6,33.8,22.0,38.1,40.2,28.9,21.3,11.7,23.0,28.0,18.0,70.0,93.0,78.0,73.0,109.0,89.0,67.0,86.0,91.0,80.0,94.0,114.0,96.0,88.0,91.0,62.0,86.0,1.0,59.0,96.0,80.0,92.0,90.0,86.0,83.0,63.0,81.0,85.0,98.0
31715,202506030411,2025-04-06,1,0,2000,1,0,4,6,2,1,61,611,11,111,4,41,3,31,61041,1,6111,3,601,1,310.0,2.0,3.0,6112000,2,11,73885611,3.100,6120001,1,4.0,1.0,404.9,1085.0,915.0,154.0,154.0,5.3,20.0,2.0,-2.0,2.0,-0.4,3.0,43,6.6,23.9,17.6,18.0,22.8,22.1,25.2,21.6,20.1,22.2,27.7,35.3,29.7,5.7,13.5,21.3,24.6,24.5,28.4,16.7,22.2,21.5,20.8,25.2,30.0,20.0,11.3,23.4,17.7,11.0,84.0,67.0,77.0,86.0,83.0,91.0,86.0,79.0,77.0,84.0,80.0,75.0,38.0,80.0,83.0,83.0,81.0,93.0,66.0,84.0,83.0,62.0,73.0,89.0,81.0,71.0,84.0,80.0,50.0
31722,202509020406,2025-04-06,1,0,2000,1,0,2,9,2,1,91,911,6,61,4,41,2,21,91041,1,9111,3,901,1,357.0,5.0,1.9,9112000,-1,06,73885606,3.570,9120001,1,4.0,1.0,330.5,1067.0,933.0,133.0,170.0,1.8,24.0,1.9,-0.4,0.0,-1.8,3.0,43,6.6,30.0,25.2,23.7,29.6,24.4,28.5,26.3,22.5,23.5,32.5,38.0,29.3,4.6,19.9,23.0,30.0,28.9,30.1,17.3,27.2,24.8,37.7,41.6,33.2,21.2,12.9,28.9,20.3,17.3,90.0,77.0,72.0,85.0,78.0,84.0,92.0,74.0,70.0,83.0,83.0,69.0,41.0,75.0,83.0,80.0,82.0,95.0,62.0,81.0,80.0,91.0,82.0,82.0,76.0,76.0,84.0,71.0,77.0
31724,202509020408,2025-04-06,1,0,1200,1,0,3,9,2,1,91,911,8,81,4,41,2,21,91041,1,9111,3,901,1,357.0,5.0,1.9,9111200,3,08,73885608,3.570,9112001,1,2.0,1.0,258.2,615.0,585.0,0.0,170.0,1.8,24.0,-0.2,-0.4,-0.7,-0.5,3.0,43,6.6,25.7,27.1,32.1,22.0,25.0,17.5,21.4,15.6,26.3,27.9,25.0,27.3,0.0,0.0,16.7,22.0,27.2,17.7,2.9,25.5,21.1,28.8,27.6,27.1,17.0,13.9,24.0,22.7,11.1,86.0,85.0,104.0,79.0,92.0,72.0,75.0,57.0,88.0,85.0,70.0,70.0,0.0,0.0,88.0,79.0,94.0,72.0,25.0,82.0,82.0,71.0,75.0,94.0,70.0,83.0,80.0,83.0,51.0
31726,202509020410,2025-04-06,1,0,1600,1,0,4,9,2,1,91,911,10,101,4,41,2,21,91041,1,9111,3,902,3,474.0,5.0,1.9,9111600,3,10,73885610,4.740,9116002,2,2.0,1.0,444.4,918.0,682.0,0.0,192.0,2.3,24.0,-0.2,0.4,-0.2,-2.2,3.0,43,6.6,26.0,24.4,25.4,21.0,19.8,22.5,21.4,17.9,19.6,26.7,32.1,32.1,1.0,11.4,14.4,27.4,24.5,14.4,25.0,23.0,21.9,32.5,29.4,30.5,21.9,10.2,24.0,20.0,15.8,100.0,87.0,87.0,80.0,78.0,81.0,81.0,65.0,79.0,83.0,80.0,95.0,1.0,85.0,74.0,83.0,86.0,66.0,102.0,79.0,83.0,75.0,82.0,83.0,83.0,64.0,82.0,79.0,98.0
31727,202509020411,2025-04-06,1,0,2000,1,0,8,9,2,1,91,911,11,111,4,41,2,21,91041,1,9111,3,901,1,357.0,5.0,1.9,9112000,-1,11,73885611,3.570,9120001,1,4.0,1.0,330.5,1067.0,933.0,133.0,170.0,1.8,24.0,1.9,-0.4,0.0,-1.8,3.0,43,6.6,30.0,25.2,23.7,29.6,24.4,28.5,26.3,22.5,23.5,32.5,38.0,29.3,4.6,19.9,23.0,30.0,28.9,30.1,17.3,27.2,24.8,37.7,41.6,33.2,21.2,12.9,28.9,20.3,17.3,90.0,77.0,72.0,85.0,78.0,84.0,92.0,74.0,70.0,83.0,83.0,69.0,41.0,75.0,83.0,80.0,82.0,95.0,62.0,81.0,80.0,91.0,82.0,82.0,76.0,76.0,84.0,71.0,77.0

In [24]:
race_info_preprocessed_turf["waku_8_EX"]

9         87.0
10        79.0
11        87.0
21       152.0
22        87.0
         ...
31931     87.0
31939     92.0
31940     66.0
31941     92.0
31943     92.0
Name: waku_8_EX, Length: 8937, dtype: float64

In [ ]:
# #まとめて実行_turf_newbie
# # レース結果テーブルの前処理
# results_preprocessed_turf_newbie = preprocessing.process_results(
#     populaton_filename = "population_turf_newbie.csv",
#     output_filename = "results_turf_newbie.csv",
# )
# # 馬の過去成績テーブルの加工
# horse_results_preprocessed_turf_newbie = preprocessing.process_horse_results(
#     populaton_filename = "population_turf_newbie.csv",
#     output_filename = "horse_results_turf_newbie.csv",    
# )
# # レース情報テーブルの前処理
# race_info_preprocessed_turf_newbie = preprocessing.process_race_info(
#     populaton_filename = "population_turf_newbie.csv",
#     output_filename = "race_info_turf_newbie.csv",       
# )
# # 騎手リーディングテーブルの前処理
# jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# # 調教師リーディングテーブルの前処理
# trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# # 血統テーブルの前処理
# peds_preprocessed = preprocessing.process_peds(
#     populaton_filename = "population_turf_newbie.csv", 
#     output_filename= "peds_turf_newbie.csv",    
# )
# # 種牡馬リーディングテーブルの前処理
# sire_leading_preprocessed = preprocessing.process_sire_leading()
# bms_leading_preprocessed = preprocessing.process_sire_leading(
#     input_filename="bms_leading.csv",
#     output_filename = "bms_leading.csv",
#     id_col = "bms_id",
# )
# # 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
# return_tables_preprocessed_turf_newbie = preprocessing.process_return_tables(
#     populaton_filename = "population_turf_newbie.csv",
#     output_filename = "return_tables_turf_newbie.pickle",
# )

In [7]:
#まとめて実行_turf_nowin
# レース結果テーブルの前処理
results_preprocessed_turf_nowin = preprocessing.process_results(
    populaton_filename = "population_turf_nowin.csv",
    output_filename = "results_turf_nowin.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_turf_nowin = preprocessing.process_horse_results(
    populaton_filename = "population_turf_nowin.csv",
    output_filename = "horse_results_turf_nowin.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_turf_nowin = preprocessing.process_race_info(
    populaton_filename = "population_turf_nowin.csv",
    output_filename = "race_info_turf_nowin_before.csv",       
)
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    populaton_filename = "population_turf_nowin.csv",    
    output_filename= "peds_turf_nowin.csv",    
)
# 種牡馬リーディングテーブルの前処理
sire_leading_preprocessed = preprocessing.process_sire_leading()
bms_leading_preprocessed = preprocessing.process_sire_leading(
    input_filename="bms_leading.csv",
    output_filename = "bms_leading.csv",
    id_col = "bms_id",
)
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_turf_nowin = preprocessing.process_return_tables(
    populaton_filename = "population_turf_nowin.csv",
    output_filename = "return_tables_turf_nowin.pickle",    
)

In [8]:
#まとめて実行_dirt
# レース結果テーブルの前処理
results_preprocessed_dirt = preprocessing.process_results(
    populaton_filename = "population_dirt.csv",
    output_filename = "results_dirt.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_dirt = preprocessing.process_horse_results(
    populaton_filename = "population_dirt.csv",
    output_filename = "horse_results_dirt.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_dirt = preprocessing.process_race_info(
    populaton_filename = "population_dirt.csv",
    output_filename = "race_info_dirt_before.csv",       
)
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    populaton_filename = "population_dirt.csv",  
    output_filename= "peds_dirt.csv",  
)
# 種牡馬リーディングテーブルの前処理
sire_leading_preprocessed = preprocessing.process_sire_leading()
bms_leading_preprocessed = preprocessing.process_sire_leading(
    input_filename="bms_leading.csv",
    output_filename = "bms_leading.csv",
    id_col = "bms_id",
)
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_dirt = preprocessing.process_return_tables(
    populaton_filename = "population_dirt.csv",
    output_filename = "return_tables_dirt.pickle",    
)

In [9]:
# #まとめて実行_dirt_newbie
# # レース結果テーブルの前処理
# results_preprocessed_dirt_newbie = preprocessing.process_results(
#     populaton_filename = "population_dirt_newbie.csv",
#     output_filename = "results_dirt_newbie.csv",
# )
# # 馬の過去成績テーブルの加工
# horse_results_preprocessed_dirt_newbie = preprocessing.process_horse_results(
#     populaton_filename = "population_dirt_newbie.csv",
#     output_filename = "horse_results_dirt_newbie.csv",    
# )
# # レース情報テーブルの前処理
# race_info_preprocessed_dirt_newbie = preprocessing.process_race_info(
#     populaton_filename = "population_dirt_newbie.csv",
#     output_filename = "race_info_dirt_newbie.csv",       
# )
# # 騎手リーディングテーブルの前処理
# jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# # 調教師リーディングテーブルの前処理
# trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# # 血統テーブルの前処理
# peds_preprocessed = preprocessing.process_peds(
#     populaton_filename = "population_dirt_newbie.csv",  
#     output_filename= "peds_dirt_newbie.csv",  
# )
# # 種牡馬リーディングテーブルの前処理
# sire_leading_preprocessed = preprocessing.process_sire_leading()
# bms_leading_preprocessed = preprocessing.process_sire_leading(
#     input_filename="bms_leading.csv",
#     output_filename = "bms_leading.csv",
#     id_col = "bms_id",
# )
# # 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
# return_tables_preprocessed_dirt_newbie = preprocessing.process_return_tables(
#     populaton_filename = "population_dirt_newbie.csv",
#     output_filename = "return_tables_dirt_newbie.pickle",    
# )

In [10]:
#まとめて実行_dirt_nowin
# レース結果テーブルの前処理
results_preprocessed_dirt_nowin = preprocessing.process_results(
    populaton_filename = "population_dirt_nowin.csv",
    output_filename = "results_dirt_nowin.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_dirt_nowin = preprocessing.process_horse_results(
    populaton_filename = "population_dirt_nowin.csv",
    output_filename = "horse_results_dirt_nowin.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_dirt_nowin = preprocessing.process_race_info(
    populaton_filename = "population_dirt_nowin.csv",
    output_filename = "race_info_dirt_nowin_before.csv",       
)
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    populaton_filename = "population_dirt_nowin.csv",  
    output_filename= "peds_dirt_nowin.csv",  
)
# 種牡馬リーディングテーブルの前処理
sire_leading_preprocessed = preprocessing.process_sire_leading()
bms_leading_preprocessed = preprocessing.process_sire_leading(
    input_filename="bms_leading.csv",
    output_filename = "bms_leading.csv",
    id_col = "bms_id",
)
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_dirt_nowin = preprocessing.process_return_tables(
    populaton_filename = "population_dirt_nowin.csv",
    output_filename = "return_tables_dirt_nowin.pickle",    
)

In [11]:
#まとめて実行_obstract
# レース結果テーブルの前処理
results_preprocessed_obstract = preprocessing.process_results(
    populaton_filename = "population_obstract.csv",
    output_filename = "results_obstract.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_obstract = preprocessing.process_horse_results(
    populaton_filename = "population_obstract.csv",
    output_filename = "horse_results_obstract.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_obstract = preprocessing.process_race_info(
    populaton_filename = "population_obstract.csv",
    output_filename = "race_info_obstract_before.csv",       
)
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    populaton_filename = "population_obstract.csv",  
    output_filename= "peds_obstract.csv",  
)
# 種牡馬リーディングテーブルの前処理
sire_leading_preprocessed = preprocessing.process_sire_leading()
bms_leading_preprocessed = preprocessing.process_sire_leading(
    input_filename="bms_leading.csv",
    output_filename = "bms_leading.csv",
    id_col = "bms_id",
)
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_obstract = preprocessing.process_return_tables(
    populaton_filename = "population_obstract.csv",
    output_filename = "return_tables_obstract.pickle",    
)

/Users/gotoumasafumi/Downloads/GitHub/horse_racing/main/src/keiba_exp/preprocessing.py:606: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/gotoumasafumi/Downloads/GitHub/horse_racing/main/src/keiba_exp/preprocessing.py:5024: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[columns_to_convert_x] = df[columns_to_convert_x].fillna(-10000).astype(float)
/Users/gotoumasafumi/Downloads/GitHub/horse_racing/main/src/keiba_exp/preprocessing.py:5049: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[cols_to_int] = df[cols_to_int].fillna(30).astype(float)
/Users/gotoumasafumi/Downloads/GitHub/horse_racing/main/src/keiba_exp/preprocessing.py:5050: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[cols_to_int2] = df[cols_to_int2].fillna(70).astype(float)

In [12]:
#まとめて実行_all
# レース結果テーブルの前処理
results_preprocessed_all = preprocessing.process_results(
    populaton_filename = "population_all.csv",
    output_filename = "results_all.csv",
)
# 馬の過去成績テーブルの加工
horse_results_preprocessed_all = preprocessing.process_horse_results(
    populaton_filename = "population_all.csv",
    output_filename = "horse_results_all.csv",    
)
# レース情報テーブルの前処理
race_info_preprocessed_all = preprocessing.process_race_info(
    populaton_filename = "population_all.csv",
    output_filename = "race_info_all_before.csv",       
)
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    populaton_filename = "population_all.csv",  
    output_filename= "peds_all.csv",    
)
# 払い戻しテーブルの前処理_２度目をするならcsvファイルを消さないとダメ
return_tables_preprocessed_all = preprocessing.process_return_tables(
    populaton_filename = "population_all.csv",
    output_filename = "return_tables_all.pickle",    
)

In [13]:
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_all.csv",
    results_filename="results_all.csv",
    race_info_filename="race_info_all_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_all.csv",
)
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_turf.csv",
    results_filename="results_turf.csv",
    race_info_filename="race_info_turf_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_turf.csv",
)
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_dirt.csv",
    results_filename="results_dirt.csv",
    race_info_filename="race_info_dirt_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_dirt.csv",
)
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_turf_nowin.csv",
    results_filename="results_turf_nowin.csv",
    race_info_filename="race_info_turf_nowin_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_turf_nowin.csv",
)
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_dirt_nowin.csv",
    results_filename="results_dirt_nowin.csv",
    race_info_filename="race_info_dirt_nowin_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_dirt_nowin.csv",
)
fc_grade = race_grade_maker.create_race_grade(
    poplation_filename="population_obstract.csv",
    results_filename="results_obstract.csv",
    race_info_filename="race_info_obstract_before.csv",
    # peds_filename = "peds_all.csv",
    output_filename_info = "race_info_obstract.csv",
)

In [ ]:
# horse_results_preprocessed_turf

In [ ]:
print(race_info_preprocessed_all.dtypes)

In [21]:
%autoreload

#  特徴量作成

In [4]:
#_turfの特徴量作成
fc_turf = FeatureCreator(
    poplation_filename="population_turf.csv",
    results_filename="results_turf.csv",
    race_info_filename="race_info_turf.csv",
    horse_results_filename="horse_results_turf.csv",
    output_filename = "features_turf.csv",
    peds_filename = "peds_turf.csv",
    output_filename_info = "race_info_turf.csv",
    
    poplation_all_filename = "population_turf.csv",
    results_all_filename = "results_turf.csv",
    race_info_all_filename = "race_info_turf.csv",
    horse_results_all_filename = "horse_results_turf.csv",
    peds_all_filename = "peds_turf.csv",
)
features_turf = fc_turf.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [ ]:
# 重複チェック
features_turf.duplicated(subset=["race_id", "horse_id"]).sum()

In [ ]:
#特徴量を変更した場合に実行、"config_lightgbm_niti_new.yaml"に特徴量リストが入る
list(features_turf.columns)
import yaml
feature_cols = {
    "features": features_turf.columns.drop(
        ["date","rank","rank_per_horse","time","nobori","corner_1","corner_2","corner_3","corner_4",
                        "corner_1_per_horse","corner_2_per_horse",
                        "corner_3_per_horse",
                        "corner_4_per_horse", "owner_id"]
    ).to_list()
}
print(feature_cols)
with open("config_lightgbm_niti_new.yaml","w") as file:
    yaml.dump(feature_cols,file
              )
                        #     'time_diff_sp',
                        # 'nobori_diff_sp',
                        # 'time_points_course_index',
                        # 'nobori_points_course_index',
                        # 'time_points_impost',
                        # 'nobori_points_impost',
                        # 'time_diff_grade',
                        # 'nobori_diff_grade',
                        # 'time_points_grade_index',
                        # 'nobori_points_grade_index',
                        # 'time_condition_index',
                        # 'nobori_condition_index',
                        # 'speed_index',
                        # 'nobori_index',

In [ ]:
features_turf.head(100)

In [ ]:
features_dirt.head(100)

In [ ]:
#もしもカーネルがリセットした場合、ここからfeatureをとる
features_turf = pd.read_csv("../data/02_features/features_turf.csv", sep="\t")

In [ ]:
#もしもカーネルがリセットした場合、ここからfeatureをとる
features_dirt = pd.read_csv("../data/02_features/features_dirt.csv", sep="\t")

In [ ]:
#もしもカーネルがリセットした場合、ここからfeatureをとる
features_obstract = pd.read_csv("../data/02_features/features_obstract.csv", sep="\t")

In [ ]:
# rank_1races 列が None の行を抽出
none_rows = features_turf[features_turf["rank_1races"].isna()]
# none_rows の行数を確認
num_rows = none_rows.shape[0]
print(f"rank_1races が None の行数: {num_rows}")
# 表示したい列を指定
columns_to_display = ["horse_id", "date","rank_1races", "race_id"]  # 必要な列名をリストで指定
filtered_none_rows = none_rows[columns_to_display]

filtered_none_rows 
# horse_id 列をリストに変換
horse_id_list = filtered_none_rows["horse_id"].tolist()

# 結果を表示
print(horse_id_list)

In [ ]:
# rank_1races 列が None の行を抽出
none_rows = features_dirt[features_dirt["rank_1races"].isna()]
# none_rows の行数を確認
num_rows = none_rows.shape[0]
print(f"rank_1races が None の行数: {num_rows}")
# 表示したい列を指定
columns_to_display = ["horse_id", "date","rank_1races", "race_id"]  # 必要な列名をリストで指定
filtered_none_rows = none_rows[columns_to_display]

filtered_none_rows 
# horse_id 列をリストに変換
horse_id_list = filtered_none_rows["horse_id"].tolist()

# 結果を表示
print(horse_id_list)

In [ ]:
# rank_1races 列が None の行を抽出
none_rows = features_obstract[features_obstract["rank_1races"].isna()]
# none_rows の行数を確認
num_rows = none_rows.shape[0]
print(f"rank_1races が None の行数: {num_rows}")
# 表示したい列を指定
columns_to_display = ["horse_id", "date","rank_1races", "race_id"]  # 必要な列名をリストで指定
filtered_none_rows = none_rows[columns_to_display]

filtered_none_rows 
# horse_id 列をリストに変換
horse_id_list = filtered_none_rows["horse_id"].tolist()

# 結果を表示
print(horse_id_list)

In [5]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_ex.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_ex_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.4997
[200]	valid_0's binary_logloss: 0.485182
[300]	valid_0's binary_logloss: 0.478464
[400]	valid_0's binary_logloss: 0.475034
[500]	valid_0's binary_logloss: 0.473106
[600]	valid_0's binary_logloss: 0.472037
[700]	valid_0's binary_logloss: 0.471385
[800]	valid_0's binary_logloss: 0.470938
[900]	valid_0's binary_logloss: 0.470842
Early stopping, best iteration is:
[839]	valid_0's binary_logloss: 0.4708
-------------------- Metrics --------------------
Accuracy: 0.3425
Precision: 0.2574
Recall: 0.9804
F1 Score: 0.4078
ROC AUC: 0.7452
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.482805
[1000]	valid_0's binary_logloss: 0.481661
[1100]	valid_0's binary_logloss: 0.481103
[1200]	valid_0's binary_logloss: 0.480758
[1300]	valid_0's binary_logloss: 0.48047
[1400]	valid_0's binary_logloss: 0.480211
[1500]	valid_0's binary_logloss: 0.480156
[1600]	valid_0's binary_logloss: 0.480052
Early stopping, best iteration is:
[1596]	valid_0's binary_logloss: 0.480025
-------------------- Metrics --------------------
Accuracy: 0.3606
Precision: 0.2635
Recall: 0.9747
F1 Score: 0.4148
ROC AUC: 0.7313
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1600]	valid_0's binary_logloss: 0.467987
[1700]	valid_0's binary_logloss: 0.466641
[1800]	valid_0's binary_logloss: 0.466019
[1900]	valid_0's binary_logloss: 0.465728
[2000]	valid_0's binary_logloss: 0.465453
[2100]	valid_0's binary_logloss: 0.465388
[2200]	valid_0's binary_logloss: 0.465383
[2300]	valid_0's binary_logloss: 0.465298
Early stopping, best iteration is:
[2261]	valid_0's binary_logloss: 0.465224
-------------------- Metrics --------------------
Accuracy: 0.3605
Precision: 0.2622
Recall: 0.9780
F1 Score: 0.4136
ROC AUC: 0.7516
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2300]	valid_0's binary_logloss: 0.469886
[2400]	valid_0's binary_logloss: 0.469447
[2500]	valid_0's binary_logloss: 0.469313
[2600]	valid_0's binary_logloss: 0.469263
[2700]	valid_0's binary_logloss: 0.469155
[2800]	valid_0's binary_logloss: 0.469044
[2900]	valid_0's binary_logloss: 0.468992
[3000]	valid_0's binary_logloss: 0.46895
[3100]	valid_0's binary_logloss: 0.468895
[3200]	valid_0's binary_logloss: 0.468926
Early stopping, best iteration is:
[3104]	valid_0's binary_logloss: 0.468888
-------------------- Metrics --------------------
Accuracy: 0.3793
Precision: 0.2661
Recall: 0.9704
F1 Score: 0.4177
ROC AUC: 0.7443
Training final model using all data...
Final model training completed.

In [6]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.505974
[200]	valid_0's binary_logloss: 0.493792
[300]	valid_0's binary_logloss: 0.488227
[400]	valid_0's binary_logloss: 0.485241
[500]	valid_0's binary_logloss: 0.483292
[600]	valid_0's binary_logloss: 0.482338
[700]	valid_0's binary_logloss: 0.481865
[800]	valid_0's binary_logloss: 0.481393
[900]	valid_0's binary_logloss: 0.481218
[1000]	valid_0's binary_logloss: 0.481026
[1100]	valid_0's binary_logloss: 0.480878
[1200]	valid_0's binary_logloss: 0.480729
Early stopping, best iteration is:
[1194]	valid_0's binary_logloss: 0.480689
-------------------- Metrics --------------------
Accuracy: 0.3135
Precision: 0.2499
Recall: 0.9860
F1 Score: 0.3988
ROC AUC: 0.7272
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.490176
[1300]	valid_0's binary_logloss: 0.488118
[1400]	valid_0's binary_logloss: 0.487583
[1500]	valid_0's binary_logloss: 0.487239
[1600]	valid_0's binary_logloss: 0.486865
[1700]	valid_0's binary_logloss: 0.48685
Early stopping, best iteration is:
[1615]	valid_0's binary_logloss: 0.486796
-------------------- Metrics --------------------
Accuracy: 0.3264
Precision: 0.2544
Recall: 0.9824
F1 Score: 0.4042
ROC AUC: 0.7184
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's binary_logloss: 0.479449
[1800]	valid_0's binary_logloss: 0.478459
[1900]	valid_0's binary_logloss: 0.477893
[2000]	valid_0's binary_logloss: 0.477509
[2100]	valid_0's binary_logloss: 0.47727
[2200]	valid_0's binary_logloss: 0.477157
[2300]	valid_0's binary_logloss: 0.476934
[2400]	valid_0's binary_logloss: 0.476837
[2500]	valid_0's binary_logloss: 0.476795
[2600]	valid_0's binary_logloss: 0.476722
[2700]	valid_0's binary_logloss: 0.476758
[2800]	valid_0's binary_logloss: 0.476704
Early stopping, best iteration is:
[2756]	valid_0's binary_logloss: 0.476618
-------------------- Metrics --------------------
Accuracy: 0.3379
Precision: 0.2552
Recall: 0.9756
F1 Score: 0.4046
ROC AUC: 0.7325
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2800]	valid_0's binary_logloss: 0.479998
[2900]	valid_0's binary_logloss: 0.479288
[3000]	valid_0's binary_logloss: 0.479078
[3100]	valid_0's binary_logloss: 0.478888
[3200]	valid_0's binary_logloss: 0.478922
Early stopping, best iteration is:
[3140]	valid_0's binary_logloss: 0.478795
-------------------- Metrics --------------------
Accuracy: 0.3430
Precision: 0.2558
Recall: 0.9762
F1 Score: 0.4054
ROC AUC: 0.7278
Training final model using all data...
Final model training completed.

In [7]:
%autoreload

In [8]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.207206,0.971078,0.312211,0.774050
1,1,複勝,0.502734,1.001023,0.613066,0.820735
2,2,ワイド,0.199776,1.247512,0.303098,0.780191
3,2,単勝,0.359736,0.920980,0.508902,0.793383
4,2,複勝,0.727604,0.965772,0.829385,0.829230
5,2,馬単,0.081593,1.111258,0.150568,0.752643
6,2,馬連,0.081593,1.152909,0.150568,0.791098
7,3,ワイド,0.397308,1.178644,0.544932,0.792224
8,3,三連単,0.050049,2.267454,0.086920,0.635925
9,3,三連複,0.050049,2.764265,0.086920,0.748058
10,3,単勝,0.491518,0.913440,0.643067,0.789565
11,3,複勝,0.847890,0.938357,0.918267,0.819169
12,3,馬単,0.191785,1.012120,0.309267,0.747689
13,3,馬連,0.191785,1.054288,0.309267,0.778289
14,4,ワイド,0.567924,1.106664,0.709379,0.804900
15,4,三連単,0.130520,1.683107,0.224310,0.733082
16,4,三連複,0.130520,1.790446,0.224310,0.800060
17,4,単勝,0.595261,0.908338,0.739240,0.781554
18,4,複勝,0.915744,0.926037,0.961867,0.811987
19,4,馬単,0.308426,1.017808,0.455489,0.748449
20,4,馬連,0.308426,1.036964,0.455489,0.772293
21,5,ワイド,0.698023,1.036218,0.821954,0.796232
22,5,三連単,0.244918,1.368729,0.363802,0.732656
23,5,三連複,0.244918,1.416958,0.363802,0.777684
24,5,単勝,0.680639,0.888678,0.814524,0.788151
25,5,複勝,0.956680,0.906752,0.981214,0.804164
26,5,馬単,0.425067,0.943946,0.585308,0.757507
27,5,馬連,0.425067,0.958281,0.585308,0.774926

In [9]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_ex_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_in3,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.228515,0.900603,0.312211,0.774050
1,1,複勝,0.525445,0.917861,0.613066,0.820735
2,2,ワイド,0.213655,1.046741,0.303098,0.780191
3,2,単勝,0.400393,0.924709,0.508902,0.793383
4,2,複勝,0.760409,0.918723,0.829385,0.829230
5,2,馬単,0.089724,1.043509,0.150568,0.752643
6,2,馬連,0.089724,1.068162,0.150568,0.791098
7,3,ワイド,0.426889,1.066998,0.544932,0.792224
8,3,三連単,0.052432,2.210634,0.086920,0.635925
9,3,三連複,0.052432,2.440782,0.086920,0.748058
10,3,単勝,0.530913,0.912561,0.643067,0.789565
11,3,複勝,0.871583,0.905799,0.918267,0.819169
12,3,馬単,0.212954,0.965557,0.309267,0.747689
13,3,馬連,0.212954,0.975611,0.309267,0.778289
14,4,ワイド,0.605636,0.994782,0.709379,0.804900
15,4,三連単,0.140894,1.283944,0.224310,0.733082
16,4,三連複,0.140894,1.382497,0.224310,0.800060
17,4,単勝,0.631431,0.885774,0.739240,0.781554
18,4,複勝,0.932287,0.893968,0.961867,0.811987
19,4,馬単,0.337586,0.901428,0.455489,0.748449
20,4,馬連,0.337586,0.928672,0.455489,0.772293
21,5,ワイド,0.724660,0.960014,0.821954,0.796232
22,5,三連単,0.260620,1.085643,0.363802,0.732656
23,5,三連複,0.260620,1.128193,0.363802,0.777684
24,5,単勝,0.712043,0.857824,0.814524,0.788151
25,5,複勝,0.963970,0.874549,0.981214,0.804164
26,5,馬単,0.453946,0.861278,0.585308,0.757507
27,5,馬連,0.453946,0.877272,0.585308,0.774926

In [10]:
#_dirtの特徴量作成
fc_dirt = FeatureCreator(
    poplation_filename="population_dirt.csv",
    results_filename="results_dirt.csv",
    race_info_filename="race_info_dirt.csv",
    horse_results_filename="horse_results_dirt.csv",
    output_filename = "features_dirt.csv",
    peds_filename = "peds_dirt.csv",
    output_filename_info = "race_info_dirt.csv",
)
features_dirt = fc_dirt.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [11]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_only_tenkai_weight_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.47858
[200]	valid_0's binary_logloss: 0.467291
[300]	valid_0's binary_logloss: 0.462477
[400]	valid_0's binary_logloss: 0.460367
[500]	valid_0's binary_logloss: 0.459059
[600]	valid_0's binary_logloss: 0.458797
[700]	valid_0's binary_logloss: 0.458428
[800]	valid_0's binary_logloss: 0.458374
[900]	valid_0's binary_logloss: 0.458249
Early stopping, best iteration is:
[888]	valid_0's binary_logloss: 0.458215
-------------------- Metrics --------------------
Accuracy: 0.3103
Precision: 0.2320
Recall: 0.9834
F1 Score: 0.3754
ROC AUC: 0.7310
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.477421
[1000]	valid_0's binary_logloss: 0.47458
[1100]	valid_0's binary_logloss: 0.473971
[1200]	valid_0's binary_logloss: 0.473819
[1300]	valid_0's binary_logloss: 0.473736
Early stopping, best iteration is:
[1288]	valid_0's binary_logloss: 0.473679
-------------------- Metrics --------------------
Accuracy: 0.3184
Precision: 0.2364
Recall: 0.9706
F1 Score: 0.3802
ROC AUC: 0.7097
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.465517
[1400]	valid_0's binary_logloss: 0.46404
[1500]	valid_0's binary_logloss: 0.463642
Early stopping, best iteration is:
[1479]	valid_0's binary_logloss: 0.463528
-------------------- Metrics --------------------
Accuracy: 0.3040
Precision: 0.2323
Recall: 0.9797
F1 Score: 0.3756
ROC AUC: 0.7282
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.469783
[1600]	valid_0's binary_logloss: 0.46595
[1700]	valid_0's binary_logloss: 0.464933
[1800]	valid_0's binary_logloss: 0.464421
[1900]	valid_0's binary_logloss: 0.464159
[2000]	valid_0's binary_logloss: 0.463953
[2100]	valid_0's binary_logloss: 0.463829
[2200]	valid_0's binary_logloss: 0.463767
[2300]	valid_0's binary_logloss: 0.463664
[2400]	valid_0's binary_logloss: 0.463639
[2500]	valid_0's binary_logloss: 0.463554
[2600]	valid_0's binary_logloss: 0.463478
[2700]	valid_0's binary_logloss: 0.46345
Early stopping, best iteration is:
[2672]	valid_0's binary_logloss: 0.463432
-------------------- Metrics --------------------
Accuracy: 0.3651
Precision: 0.2483
Recall: 0.9606
F1 Score: 0.3946
ROC AUC: 0.7288
Training final model using all data...
Final model training completed.

In [12]:
%autoreload

In [13]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.221911,0.846656,0.325557,0.817821
1,1,複勝,0.497712,0.892175,0.616270,0.841355
2,2,ワイド,0.185737,1.021423,0.286284,0.820537
3,2,単勝,0.368817,0.812018,0.507456,0.797483
4,2,複勝,0.723166,0.889990,0.822235,0.834136
5,2,馬単,0.075742,0.920596,0.141001,0.792263
6,2,馬連,0.075742,0.979404,0.141001,0.833279
7,3,ワイド,0.376938,0.980329,0.517644,0.822447
8,3,三連単,0.040307,1.163298,0.074708,0.713345
9,3,三連複,0.040307,1.315237,0.074708,0.833634
10,3,単勝,0.494611,0.805109,0.640189,0.797643
11,3,複勝,0.850140,0.878080,0.918205,0.826906
12,3,馬単,0.184556,0.906831,0.290861,0.763278
13,3,馬連,0.184556,0.951302,0.290861,0.793105
14,4,ワイド,0.537871,0.956218,0.676805,0.793400
15,4,三連単,0.115606,1.039577,0.184704,0.697709
16,4,三連複,0.115606,1.117872,0.184704,0.774240
17,4,単勝,0.588070,0.787745,0.730105,0.776085
18,4,複勝,0.915547,0.866245,0.957183,0.802735
19,4,馬単,0.285250,0.836532,0.426547,0.747495
20,4,馬連,0.285250,0.867875,0.426547,0.772048
21,5,ワイド,0.672228,0.904608,0.795512,0.802652
22,5,三連単,0.197992,0.947965,0.316846,0.734386
23,5,三連複,0.197992,0.958345,0.316846,0.790759
24,5,単勝,0.671047,0.791747,0.805699,0.783768
25,5,複勝,0.952163,0.854570,0.981692,0.801364
26,5,馬単,0.393031,0.868253,0.554998,0.758900
27,5,馬連,0.393031,0.904779,0.554998,0.779848

In [ ]:
# #_turf_newbieの特徴量作成
# fc_turf_newbie = FeatureCreator(
#     poplation_filename="population_turf_newbie.csv",
#     results_filename="results_turf_newbie.csv",
#     race_info_filename="race_info_turf_newbie.csv",
#     horse_results_filename="horse_results_turf_newbie.csv",
#     output_filename = "features_turf_newbie.csv",
#     peds_filename = "peds_turf_newbie.csv",
#     output_filename_info = "race_info_turf_newbie.csv",
# )
# features_turf_newbie = fc_turf_newbie.create_features()

In [14]:
#_turf_nowinの特徴量作成
fc_turf_nowin = FeatureCreator(
    poplation_filename="population_turf_nowin.csv",
    results_filename="results_turf_nowin.csv",
    race_info_filename="race_info_turf_nowin.csv",
    horse_results_filename="horse_results_turf_nowin.csv",
    output_filename = "features_turf_nowin.csv",
    peds_filename = "peds_turf_nowin.csv",
    output_filename_info = "race_info_turf_nowin.csv",
)
features_turf_nowin = fc_turf_nowin.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [ ]:
# #_dirtの特徴量作成
# fc_dirt = FeatureCreator(
#     poplation_filename="population_dirt.csv",
#     results_filename="results_dirt.csv",
#     race_info_filename="race_info_dirt.csv",
#     horse_results_filename="horse_results_dirt.csv",
#     output_filename = "features_dirt.csv",
#     peds_filename = "peds_dirt.csv",
#     output_filename_info = "race_info_dirt.csv",
# )
# features_d = fc_dirt.create_race_grade()

KeyboardInterrupt:

In [15]:
#_dirt_nowinの特徴量作成
fc_dirt_nowin = FeatureCreator(
    poplation_filename="population_dirt_nowin.csv",
    results_filename="results_dirt_nowin.csv",
    race_info_filename="race_info_dirt_nowin.csv",
    horse_results_filename="horse_results_dirt_nowin.csv",
    output_filename = "features_dirt_nowin.csv",
    peds_filename = "peds_dirt_nowin.csv",
    output_filename_info = "race_info_dirt_nowin.csv",
)
features_dirt_nowin = fc_dirt_nowin.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [ ]:
# #_dirt_newbieの特徴量作成
# fc_dirt_newbie = FeatureCreator(
#     poplation_filename="population_dirt_newbie.csv",
#     results_filename="results_dirt_newbie.csv",
#     race_info_filename="race_info_dirt_newbie.csv",
#     horse_results_filename="horse_results_dirt_newbie.csv",
#     output_filename = "features_dirt_newbie.csv",
#     peds_filename = "peds_dirt_newbie.csv",
#     output_filename_info = "race_info_dirt_newbie.csv",
# )
# features_dirt_newbie = fc_dirt_newbie.create_features()

In [16]:
#_obstractの特徴量作成
fc_obstract = FeatureCreator(
    poplation_filename="population_obstract.csv",
    results_filename="results_obstract.csv",
    race_info_filename="race_info_obstract.csv",
    horse_results_filename="horse_results_obstract.csv",
    output_filename = "features_obstract.csv",
    peds_filename = "peds_obstract.csv",
    output_filename_info = "race_info_obstract.csv",

)
features_obstract = fc_obstract.create_features()

course_len_relative:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_rank_diff ...comp

rank_diff:   0%|          | 0/4 [00:00<?, ?it/s]

agg_cross_time ...comp

計算中:   0%|          | 0/4 [00:00<?, ?it/s]

agg_race_type_True:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp
running cross_features_17()...comp
running agg_position_results()...comp
running agg_weight_weather()...comp
running agg_umaban_good()...comp

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

merging all features...
merging all features...comp

In [ ]:
%autoreload

In [ ]:
%autoreload

# 学習
- 特徴量にオッズを利用したもの、利用していないもの
- rank列を二値分類で予測したもの、回帰で予測したもの、time列を予測したもの
- ホールドアウト法、cv(クロスバリデーション)を利用したもの
- その他、独自の特徴量のみを利用したものなど、さまざまな学習モデルを作成する段階です
- config_filepath="config_lightgbm_kaiki_odds_removed.yaml"の部分を変更することで、特徴量やハイパーパラメータを変更できます
- 好きな特徴量を選んで、学習させてください（保存先のファイル名の変更も忘れずに）

### time

In [ ]:
# # _turfオッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_turf",
#     model_filename="model_lightgbm_time_cv_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_turf.csv",
#     final_model_filename = "model_lightgbm_time_cv_turf.pkl"
# )

In [ ]:
# # _turfオッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_turf",
#     model_filename="model_lightgbm_time_cv_nopast_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_turf.pkl"
# )

In [ ]:
# # _turfオッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf",
#     model_filename="model_lightgbm_time_cv_dev_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf.pkl"
# )

In [ ]:
# # _turfオッズと人気を特徴量から省いたindex、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_index_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_index_cv_dev_turf",
#     model_filename="model_lightgbm_index_cv_dev_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_index_cv_dev_turf.csv",
#     final_model_filename = "model_lightgbm_index_cv_full_dev_turf.pkl"
# )

In [ ]:
# #_turf_newbie オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_turf_newbie",
#     model_filename="model_lightgbm_time_cv_turf_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_turf_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_turf_newbie.pkl"
# )

In [ ]:
# # _turf_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_turf_newbie",
#     model_filename="model_lightgbm_time_cv_nopast_turf_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_turf_newbie.pkl"
# )

In [ ]:
# # _turf_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf_newbie",
#     model_filename="model_lightgbm_time_cv_dev_turf_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf_newbie.pkl"
# )

In [ ]:
# #_turf_nowin オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_turf_nowin",
#     model_filename="model_lightgbm_time_cv_turf_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_turf_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_turf_nowin.pkl"
# )

In [ ]:
# # _turf_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_turf_nowin",
#     model_filename="model_lightgbm_time_cv_nopast_turf_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_turf_nowin.pkl"
# )

In [ ]:
# # _turf_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_dev.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf_nowin",
#     model_filename="model_lightgbm_time_cv_dev_turf_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf_nowin.pkl"
# )

In [ ]:
# #_dirt オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dirt",
#     model_filename="model_lightgbm_time_cv_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dirt.csv",
#     final_model_filename = "model_lightgbm_time_cv_dirt.pkl"
# )

In [ ]:
# # _dirt オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_dirt",
#     model_filename="model_lightgbm_time_cv_nopast_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_dirt.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_dirt.pkl"
# )

In [ ]:
# # _dirt オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt",
#     model_filename="model_lightgbm_time_cv_dev_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dirt.pkl"
# )

In [ ]:
# #_dirt_newbie オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dirt_newbie",
#     model_filename="model_lightgbm_time_cv_dirt_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dirt_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_dirt_newbie.pkl"
# )

In [ ]:
# # _dirt_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_dirt_newbie",
#     model_filename="model_lightgbm_time_cv_nopast_dirt_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_dirt_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_dirt_newbie.pkl"
# )

In [ ]:
# # _dirt_newbie オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_newbie.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt_newbie",
#     model_filename="model_lightgbm_time_cv_dev_dirt_newbie.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_newbie.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dirt_newbie.pkl"
# )

In [ ]:
# #_dirt_nowin オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dirt_nowin",
#     model_filename="model_lightgbm_time_cv_dirt_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dirt_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_dirt_nowin.pkl"
# )

In [ ]:
# # _dirt_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_dirt_nowin",
#     model_filename="model_lightgbm_time_cv_nopast_dirt_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_dirt_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_dirt_nowin.pkl"
# )

In [ ]:
# # _dirt_nowin オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt_nowin",
#     model_filename="model_lightgbm_time_cv_dev_dirt_nowin.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_nowin.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dirt_nowin.pkl"
# )

In [ ]:
# #_obstract オッズありタイム回帰、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_obstract",
#     model_filename="model_lightgbm_time_cv_obstract.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_obstract.csv",
#     final_model_filename = "model_lightgbm_time_cv_obstract.pkl"
# )

In [ ]:
# # _obstract オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション/nopast
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki_nopast.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_nopast_obstract",
#     model_filename="model_lightgbm_time_cv_nopast_obstract.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_nopast_obstract.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_nopast_obstract.pkl"
# )

In [ ]:
# # _obstract オッズと人気を特徴量から省いたタイム、回帰、クロスバリデーション_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_obstract.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 3,
#     importance_filename="importance_lightgbm_time_cv_dev_obstract",
#     model_filename="model_lightgbm_time_cv_dev_obstract.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_obstract.pkl"
# )

### speed_index

In [ ]:
# missing_count = features_turf["speed_index"].isna().sum()
# print(f"speed_index の欠損数: {missing_count}")
# # missing_rows = features_dirt[features_dirt["speed_index"].isna()]
# # missing_rows[["race_id","horse_id","umaban","speed_index"]].tail(32)

In [ ]:
# # オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_kaiki_cv_dev_turf",
#     model_filename="model_lightgbm_kaiki_cv_dev_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_kaiki_cv_dev_turf.csv",
#     final_model_filename = "model_lightgbm_kaiki_cv_full_dev_turf.pkl",
#     final_num_boost_round = 2000
# )

In [ ]:
# # オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_turf_only_tenkai.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_kaiki_cv_dev_turf",
#     model_filename="model_lightgbm_kaiki_cv_dev_turf.pkl",
#     evaluation_filename="evaluation_lightgbm_kaiki_cv_dev_turf.csv",
#     final_model_filename = "model_lightgbm_kaiki_cv_full_dev_turf.pkl",
#     final_num_boost_round = 2000
# )

In [ ]:
# # オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
# evaluator = Evaluator_lightgbm_time_kaiki(
#     evaluation_filename="evaluation_lightgbm_kaiki_cv_dev_turf.csv",
#     return_tables_filename = "return_tables_dirt.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="box_summary_kaiki_dev_turf.csv")
# summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_kaiki_dev_turf")
# summary_df_noodds_gbm

### 二値分類

In [17]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.244974
[200]	valid_0's binary_logloss: 0.238486
[300]	valid_0's binary_logloss: 0.236243
[400]	valid_0's binary_logloss: 0.235232
[500]	valid_0's binary_logloss: 0.234837
[600]	valid_0's binary_logloss: 0.234815
[700]	valid_0's binary_logloss: 0.235009
Early stopping, best iteration is:
[603]	valid_0's binary_logloss: 0.234778
-------------------- Metrics --------------------
Accuracy: 0.6985
Precision: 0.1622
Recall: 0.6989
F1 Score: 0.2633
ROC AUC: 0.7729
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.24055
[800]	valid_0's binary_logloss: 0.24031
[900]	valid_0's binary_logloss: 0.240284
[1000]	valid_0's binary_logloss: 0.240245
Early stopping, best iteration is:
[990]	valid_0's binary_logloss: 0.240205
-------------------- Metrics --------------------
Accuracy: 0.6699
Precision: 0.1530
Recall: 0.7174
F1 Score: 0.2522
ROC AUC: 0.7607
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.235294
[1100]	valid_0's binary_logloss: 0.234709
[1200]	valid_0's binary_logloss: 0.234482
[1300]	valid_0's binary_logloss: 0.234378
Early stopping, best iteration is:
[1295]	valid_0's binary_logloss: 0.23437
-------------------- Metrics --------------------
Accuracy: 0.6731
Precision: 0.1582
Recall: 0.7508
F1 Score: 0.2614
ROC AUC: 0.7778
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.233745
[1400]	valid_0's binary_logloss: 0.233491
[1500]	valid_0's binary_logloss: 0.233344
[1600]	valid_0's binary_logloss: 0.233263
[1700]	valid_0's binary_logloss: 0.233194
[1800]	valid_0's binary_logloss: 0.233166
[1900]	valid_0's binary_logloss: 0.233099
Early stopping, best iteration is:
[1822]	valid_0's binary_logloss: 0.233086
-------------------- Metrics --------------------
Accuracy: 0.6805
Precision: 0.1593
Recall: 0.7429
F1 Score: 0.2623
ROC AUC: 0.7788
Training final model using all data...
Final model training completed.

In [18]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.227963
[200]	valid_0's binary_logloss: 0.222034
[300]	valid_0's binary_logloss: 0.220077
[400]	valid_0's binary_logloss: 0.21944
[500]	valid_0's binary_logloss: 0.219111
[600]	valid_0's binary_logloss: 0.219082
Early stopping, best iteration is:
[536]	valid_0's binary_logloss: 0.219048
-------------------- Metrics --------------------
Accuracy: 0.7319
Precision: 0.1636
Recall: 0.6834
F1 Score: 0.2640
ROC AUC: 0.7824
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.224708
[700]	valid_0's binary_logloss: 0.224271
[800]	valid_0's binary_logloss: 0.224207
Early stopping, best iteration is:
[757]	valid_0's binary_logloss: 0.224164
-------------------- Metrics --------------------
Accuracy: 0.7062
Precision: 0.1567
Recall: 0.7037
F1 Score: 0.2563
ROC AUC: 0.7744
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.222041
[900]	valid_0's binary_logloss: 0.2217
[1000]	valid_0's binary_logloss: 0.221645
[1100]	valid_0's binary_logloss: 0.221647
[1200]	valid_0's binary_logloss: 0.221509
[1300]	valid_0's binary_logloss: 0.221513
Early stopping, best iteration is:
[1247]	valid_0's binary_logloss: 0.221487
-------------------- Metrics --------------------
Accuracy: 0.6946
Precision: 0.1529
Recall: 0.7231
F1 Score: 0.2524
ROC AUC: 0.7792
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.223008
[1400]	valid_0's binary_logloss: 0.22266
[1500]	valid_0's binary_logloss: 0.222436
[1600]	valid_0's binary_logloss: 0.222323
[1700]	valid_0's binary_logloss: 0.222181
[1800]	valid_0's binary_logloss: 0.222091
[1900]	valid_0's binary_logloss: 0.222073
[2000]	valid_0's binary_logloss: 0.222034
[2100]	valid_0's binary_logloss: 0.222046
Early stopping, best iteration is:
[2017]	valid_0's binary_logloss: 0.22202
-------------------- Metrics --------------------
Accuracy: 0.7064
Precision: 0.1576
Recall: 0.7093
F1 Score: 0.2579
ROC AUC: 0.7800
Training final model using all data...
Final model training completed.

In [19]:
# オッズと人気を特徴量から省いたランク、二値、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_obstract.csv", 
    config_filepath="config_lightgbm_niti_dev_obstract.yaml",
)
evaluation_df = trainer.run(
    n_splits = 3,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_obstract",
    model_filename="model_lightgbm_rank_niti_cv_dev_obstract.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_obstract.pkl"
)

Training fold 1/3...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.26217
[200]	valid_0's binary_logloss: 0.256753
[300]	valid_0's binary_logloss: 0.257313
Early stopping, best iteration is:
[234]	valid_0's binary_logloss: 0.256173
-------------------- Metrics --------------------
Accuracy: 0.7228
Precision: 0.1880
Recall: 0.6739
F1 Score: 0.2940
ROC AUC: 0.7648
Training fold 2/3...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.265903
[400]	valid_0's binary_logloss: 0.264039
[500]	valid_0's binary_logloss: 0.263604
Early stopping, best iteration is:
[493]	valid_0's binary_logloss: 0.263457
-------------------- Metrics --------------------
Accuracy: 0.6818
Precision: 0.2001
Recall: 0.7926
F1 Score: 0.3196
ROC AUC: 0.7931
Training final model using all data...
Final model training completed.

In [ ]:
# #全体のレースを学習した際、最後のブースト回数よりも多いか確認
# import lightgbm as lgb
# import pickle

# from pathlib import Path
# DATA_DIR = Path("..", "data")
# INPUT_DIR = DATA_DIR / "02_features"
# OUTPUT_DIR = DATA_DIR / "03_train"

# # モデルの読み込み
# with open(OUTPUT_DIR/"model_lightgbm_rank_niti_cv_full_dev_turf.pkl", "rb") as f:
#     model = pickle.load(f)

# # ブースト回数の取得
# num_trees = model.num_trees()

# print(f"ブースト回数（num_boost_round）: {num_trees}")

### 未勝利

In [20]:

trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.214022
[200]	valid_0's binary_logloss: 0.208721
[300]	valid_0's binary_logloss: 0.207319
[400]	valid_0's binary_logloss: 0.207007
Early stopping, best iteration is:
[376]	valid_0's binary_logloss: 0.206907
-------------------- Metrics --------------------
Accuracy: 0.7440
Precision: 0.1702
Recall: 0.7149
F1 Score: 0.2750
ROC AUC: 0.8045
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.211893
[500]	valid_0's binary_logloss: 0.211135
[600]	valid_0's binary_logloss: 0.211024
[700]	valid_0's binary_logloss: 0.210892
[800]	valid_0's binary_logloss: 0.210907
Early stopping, best iteration is:
[786]	valid_0's binary_logloss: 0.210866
-------------------- Metrics --------------------
Accuracy: 0.7450
Precision: 0.1672
Recall: 0.6919
F1 Score: 0.2693
ROC AUC: 0.7984
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.20888
[900]	valid_0's binary_logloss: 0.20838
[1000]	valid_0's binary_logloss: 0.208342
[1100]	valid_0's binary_logloss: 0.208285
Early stopping, best iteration is:
[1067]	valid_0's binary_logloss: 0.208232
-------------------- Metrics --------------------
Accuracy: 0.7502
Precision: 0.1735
Recall: 0.7033
F1 Score: 0.2783
ROC AUC: 0.8046
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.20953
[1200]	valid_0's binary_logloss: 0.209331
Early stopping, best iteration is:
[1151]	valid_0's binary_logloss: 0.209197
-------------------- Metrics --------------------
Accuracy: 0.7489
Precision: 0.1805
Recall: 0.7316
F1 Score: 0.2895
ROC AUC: 0.8110
Training final model using all data...
Final model training completed.

In [21]:
# オッズと人気を特徴量から省いたランク、回帰、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.219495
[200]	valid_0's binary_logloss: 0.214228
[300]	valid_0's binary_logloss: 0.212974
[400]	valid_0's binary_logloss: 0.212821
Early stopping, best iteration is:
[383]	valid_0's binary_logloss: 0.212764
-------------------- Metrics --------------------
Accuracy: 0.7565
Precision: 0.1757
Recall: 0.6897
F1 Score: 0.2800
ROC AUC: 0.7945
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.212132
[500]	valid_0's binary_logloss: 0.211542
Early stopping, best iteration is:
[498]	valid_0's binary_logloss: 0.211535
-------------------- Metrics --------------------
Accuracy: 0.7297
Precision: 0.1681
Recall: 0.7349
F1 Score: 0.2737
ROC AUC: 0.8027
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.214748
[600]	valid_0's binary_logloss: 0.214055
[700]	valid_0's binary_logloss: 0.213761
[800]	valid_0's binary_logloss: 0.213741
[900]	valid_0's binary_logloss: 0.213694
[1000]	valid_0's binary_logloss: 0.213784
Early stopping, best iteration is:
[918]	valid_0's binary_logloss: 0.213642
-------------------- Metrics --------------------
Accuracy: 0.7428
Precision: 0.1748
Recall: 0.7127
F1 Score: 0.2807
ROC AUC: 0.7998
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.211716
Early stopping, best iteration is:
[940]	valid_0's binary_logloss: 0.211336
-------------------- Metrics --------------------
Accuracy: 0.7461
Precision: 0.1763
Recall: 0.7182
F1 Score: 0.2831
ROC AUC: 0.8071
Training final model using all data...
Final model training completed.

### 体重なし

In [22]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_noweight.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.245147
[200]	valid_0's binary_logloss: 0.238633
[300]	valid_0's binary_logloss: 0.236405
[400]	valid_0's binary_logloss: 0.235679
[500]	valid_0's binary_logloss: 0.235434
[600]	valid_0's binary_logloss: 0.235518
Early stopping, best iteration is:
[533]	valid_0's binary_logloss: 0.235357
-------------------- Metrics --------------------
Accuracy: 0.6908
Precision: 0.1577
Recall: 0.6940
F1 Score: 0.2570
ROC AUC: 0.7710
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.241491
[700]	valid_0's binary_logloss: 0.241057
[800]	valid_0's binary_logloss: 0.241013
[900]	valid_0's binary_logloss: 0.240975
Early stopping, best iteration is:
[881]	valid_0's binary_logloss: 0.240924
-------------------- Metrics --------------------
Accuracy: 0.6669
Precision: 0.1503
Recall: 0.7075
F1 Score: 0.2479
ROC AUC: 0.7571
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.235548
[1000]	valid_0's binary_logloss: 0.235129
[1100]	valid_0's binary_logloss: 0.234953
[1200]	valid_0's binary_logloss: 0.234852
[1300]	valid_0's binary_logloss: 0.234842
Early stopping, best iteration is:
[1245]	valid_0's binary_logloss: 0.234798
-------------------- Metrics --------------------
Accuracy: 0.6708
Precision: 0.1569
Recall: 0.7481
F1 Score: 0.2593
ROC AUC: 0.7767
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.234259
[1400]	valid_0's binary_logloss: 0.234122
[1500]	valid_0's binary_logloss: 0.234
[1600]	valid_0's binary_logloss: 0.233907
[1700]	valid_0's binary_logloss: 0.233832
[1800]	valid_0's binary_logloss: 0.233794
[1900]	valid_0's binary_logloss: 0.233747
Early stopping, best iteration is:
[1884]	valid_0's binary_logloss: 0.233686
-------------------- Metrics --------------------
Accuracy: 0.6746
Precision: 0.1574
Recall: 0.7479
F1 Score: 0.2601
ROC AUC: 0.7772
Training final model using all data...
Final model training completed.

In [23]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.227771
[200]	valid_0's binary_logloss: 0.222095
[300]	valid_0's binary_logloss: 0.22021
[400]	valid_0's binary_logloss: 0.219619
[500]	valid_0's binary_logloss: 0.219465
[600]	valid_0's binary_logloss: 0.219436
Early stopping, best iteration is:
[551]	valid_0's binary_logloss: 0.219344
-------------------- Metrics --------------------
Accuracy: 0.7340
Precision: 0.1647
Recall: 0.6828
F1 Score: 0.2654
ROC AUC: 0.7818
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.224197
[700]	valid_0's binary_logloss: 0.223833
[800]	valid_0's binary_logloss: 0.223786
Early stopping, best iteration is:
[737]	valid_0's binary_logloss: 0.223747
-------------------- Metrics --------------------
Accuracy: 0.7020
Precision: 0.1549
Recall: 0.7049
F1 Score: 0.2539
ROC AUC: 0.7747
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.222312
[900]	valid_0's binary_logloss: 0.222117
[1000]	valid_0's binary_logloss: 0.222025
Early stopping, best iteration is:
[977]	valid_0's binary_logloss: 0.221993
-------------------- Metrics --------------------
Accuracy: 0.6896
Precision: 0.1513
Recall: 0.7278
F1 Score: 0.2505
ROC AUC: 0.7780
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.223949
[1100]	valid_0's binary_logloss: 0.223423
[1200]	valid_0's binary_logloss: 0.223129
[1300]	valid_0's binary_logloss: 0.222916
[1400]	valid_0's binary_logloss: 0.222746
[1500]	valid_0's binary_logloss: 0.222765
Early stopping, best iteration is:
[1415]	valid_0's binary_logloss: 0.22272
-------------------- Metrics --------------------
Accuracy: 0.7005
Precision: 0.1547
Recall: 0.7087
F1 Score: 0.2539
ROC AUC: 0.7774
Training final model using all data...
Final model training completed.

In [24]:
# オッズと人気を特徴量から省いたランク、二値、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_obstract.csv", 
    config_filepath="config_lightgbm_niti_dev_obstract_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 3,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_obstract_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_obstract_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_obstract_noweight.pkl"
)

Training fold 1/3...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.262413
[200]	valid_0's binary_logloss: 0.256791
[300]	valid_0's binary_logloss: 0.257174
Early stopping, best iteration is:
[232]	valid_0's binary_logloss: 0.256326
-------------------- Metrics --------------------
Accuracy: 0.7153
Precision: 0.1822
Recall: 0.6658
F1 Score: 0.2860
ROC AUC: 0.7649
Training fold 2/3...
Training until validation scores don't improve for 100 rounds
[300]	valid_0's binary_logloss: 0.266769
[400]	valid_0's binary_logloss: 0.264558
[500]	valid_0's binary_logloss: 0.264142
Early stopping, best iteration is:
[469]	valid_0's binary_logloss: 0.263878
-------------------- Metrics --------------------
Accuracy: 0.6783
Precision: 0.1956
Recall: 0.7753
F1 Score: 0.3124
ROC AUC: 0.7906
Training final model using all data...
Final model training completed.

In [25]:

trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_nowin_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_noweight.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.214564
[200]	valid_0's binary_logloss: 0.209767
[300]	valid_0's binary_logloss: 0.208852
[400]	valid_0's binary_logloss: 0.208647
Early stopping, best iteration is:
[397]	valid_0's binary_logloss: 0.208603
-------------------- Metrics --------------------
Accuracy: 0.7477
Precision: 0.1730
Recall: 0.7182
F1 Score: 0.2788
ROC AUC: 0.8003
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.212749
[500]	valid_0's binary_logloss: 0.211988
[600]	valid_0's binary_logloss: 0.211768
[700]	valid_0's binary_logloss: 0.211741
[800]	valid_0's binary_logloss: 0.211739
Early stopping, best iteration is:
[720]	valid_0's binary_logloss: 0.211674
-------------------- Metrics --------------------
Accuracy: 0.7474
Precision: 0.1684
Recall: 0.6908
F1 Score: 0.2708
ROC AUC: 0.7958
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.211151
[900]	valid_0's binary_logloss: 0.211238
Early stopping, best iteration is:
[825]	valid_0's binary_logloss: 0.211084
-------------------- Metrics --------------------
Accuracy: 0.7438
Precision: 0.1694
Recall: 0.7022
F1 Score: 0.2730
ROC AUC: 0.7961
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.211196
[1000]	valid_0's binary_logloss: 0.210707
[1100]	valid_0's binary_logloss: 0.210661
Early stopping, best iteration is:
[1056]	valid_0's binary_logloss: 0.210512
-------------------- Metrics --------------------
Accuracy: 0.7390
Precision: 0.1747
Recall: 0.7338
F1 Score: 0.2822
ROC AUC: 0.8050
Training final model using all data...
Final model training completed.

In [26]:
# オッズと人気を特徴量から省いたランク、回帰、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_nowin_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_noweight.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.21803
[200]	valid_0's binary_logloss: 0.213065
[300]	valid_0's binary_logloss: 0.21201
[400]	valid_0's binary_logloss: 0.211763
Early stopping, best iteration is:
[363]	valid_0's binary_logloss: 0.211729
-------------------- Metrics --------------------
Accuracy: 0.7601
Precision: 0.1764
Recall: 0.6798
F1 Score: 0.2801
ROC AUC: 0.7959
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.21191
[500]	valid_0's binary_logloss: 0.211678
Early stopping, best iteration is:
[458]	valid_0's binary_logloss: 0.211602
-------------------- Metrics --------------------
Accuracy: 0.7392
Precision: 0.1702
Recall: 0.7129
F1 Score: 0.2748
ROC AUC: 0.8024
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.213575
[600]	valid_0's binary_logloss: 0.213075
[700]	valid_0's binary_logloss: 0.213018
[800]	valid_0's binary_logloss: 0.212901
[900]	valid_0's binary_logloss: 0.213012
Early stopping, best iteration is:
[835]	valid_0's binary_logloss: 0.212874
-------------------- Metrics --------------------
Accuracy: 0.7477
Precision: 0.1787
Recall: 0.7183
F1 Score: 0.2862
ROC AUC: 0.8023
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.210742
Early stopping, best iteration is:
[876]	valid_0's binary_logloss: 0.210547
-------------------- Metrics --------------------
Accuracy: 0.7444
Precision: 0.1770
Recall: 0.7296
F1 Score: 0.2849
ROC AUC: 0.8103
Training final model using all data...
Final model training completed.

### オッズあり、芝ダート障害・学習

In [ ]:
# # _turf_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_odds.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_turf_odds",
#     model_filename="model_lightgbm_time_cv_dev_turf_odds.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_odds.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_turf_odds.pkl"
# )

In [ ]:
# # _dirt_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_dirt_odds.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_time_cv_dev_dirt_odds",
#     model_filename="model_lightgbm_time_cv_dev_dirt_odds.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_odds.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_dir_oddst.pkl"
# )

In [ ]:
# # _obstract_dev（最新型を随時更新）
# trainer = Trainer_lightgbm_time_cv(
#     features_filename = "features_obstract.csv", 
#     config_filepath="config_lightgbm_kaiki_dev_obstract_odds.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 3,
#     importance_filename="importance_lightgbm_time_cv_dev_obstract_odds",
#     model_filename="model_lightgbm_time_cv_dev_obstract_odds.pkl",
#     evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract_odds.csv",
#     final_model_filename = "model_lightgbm_time_cv_full_dev_obstract_odds.pkl"
# )

### 体重あり、onlyモデル、実験

####  体重あり芝、1racesなし

In [ ]:
# # オッズと人気を特徴量から省いたランク、日、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv(
    
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_niti_dev_turf_only.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only",
#     model_filename="model_lightgbm_rank_niti_cv_dev_turf_only.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only.pkl",
#     final_num_boost_round = 1000
# )

In [ ]:
# # オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
# evaluator = Evaluator_lightgbm_rank_niti_cross(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only.csv")
# summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only")
# summary_df_noodds_gbm

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_only.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only")
# summary_df_shaft

In [ ]:
# # オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv(
    
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_niti_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt",
#     model_filename="model_lightgbm_rank_niti_cv_dev_dirt.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt.pkl",
#     final_num_boost_round = 1200
# )

In [ ]:
# # オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
# evaluator = Evaluator_lightgbm_rank_niti_cross(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
#     return_tables_filename = "return_tables_dirt.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt.csv")
# summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
# summary_df_noodds_gbm

### only_tenkai

In [31]:
%autoreload

In [27]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.257145
[200]	valid_0's binary_logloss: 0.252826
[300]	valid_0's binary_logloss: 0.25119
[400]	valid_0's binary_logloss: 0.250461
[500]	valid_0's binary_logloss: 0.250245
Early stopping, best iteration is:
[499]	valid_0's binary_logloss: 0.250237
-------------------- Metrics --------------------
Accuracy: 0.5977
Precision: 0.1295
Recall: 0.7371
F1 Score: 0.2203
ROC AUC: 0.7179
Training fold 2/5...
[500]	valid_0's binary_logloss: 0.255592
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.254542
[700]	valid_0's binary_logloss: 0.254219
[800]	valid_0's binary_logloss: 0.254018
[900]	valid_0's binary_logloss: 0.253984
[1000]	valid_0's binary_logloss: 0.254014
Early stopping, best iteration is:
[973]	valid_0's binary_logloss: 0.253904
-------------------- Metrics --------------------
Accuracy: 0.5943
Precision: 0.1266
Recall: 0.7169
F1 Score: 0.2152
ROC AUC: 0.7077
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.250272
[1100]	valid_0's binary_logloss: 0.249397
[1200]	valid_0's binary_logloss: 0.249155
[1300]	valid_0's binary_logloss: 0.249042
[1400]	valid_0's binary_logloss: 0.248885
[1500]	valid_0's binary_logloss: 0.248963
Early stopping, best iteration is:
[1417]	valid_0's binary_logloss: 0.248827
-------------------- Metrics --------------------
Accuracy: 0.6076
Precision: 0.1299
Recall: 0.7182
F1 Score: 0.2199
ROC AUC: 0.7217
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.248137
[1600]	valid_0's binary_logloss: 0.248012
[1700]	valid_0's binary_logloss: 0.247994
Early stopping, best iteration is:
[1626]	valid_0's binary_logloss: 0.247955
-------------------- Metrics --------------------
Accuracy: 0.6061
Precision: 0.1314
Recall: 0.7395
F1 Score: 0.2231
ROC AUC: 0.7238
Training final model using all data...
Final model training completed.

In [28]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_only_tenkai.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.225722
[200]	valid_0's binary_logloss: 0.221478
[300]	valid_0's binary_logloss: 0.220249
[400]	valid_0's binary_logloss: 0.219722
[500]	valid_0's binary_logloss: 0.219664
Early stopping, best iteration is:
[496]	valid_0's binary_logloss: 0.219617
-------------------- Metrics --------------------
Accuracy: 0.6990
Precision: 0.1409
Recall: 0.6732
F1 Score: 0.2330
ROC AUC: 0.7613
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.222676
[600]	valid_0's binary_logloss: 0.221864
[700]	valid_0's binary_logloss: 0.221538
Early stopping, best iteration is:
[697]	valid_0's binary_logloss: 0.221464
-------------------- Metrics --------------------
Accuracy: 0.7043
Precision: 0.1402
Recall: 0.6535
F1 Score: 0.2309
ROC AUC: 0.7545
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.218513
[800]	valid_0's binary_logloss: 0.217938
[900]	valid_0's binary_logloss: 0.217509
[1000]	valid_0's binary_logloss: 0.217526
Early stopping, best iteration is:
[941]	valid_0's binary_logloss: 0.217384
-------------------- Metrics --------------------
Accuracy: 0.7276
Precision: 0.1558
Recall: 0.6739
F1 Score: 0.2531
ROC AUC: 0.7724
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.21975
[1100]	valid_0's binary_logloss: 0.219473
[1200]	valid_0's binary_logloss: 0.219415
Early stopping, best iteration is:
[1132]	valid_0's binary_logloss: 0.219316
-------------------- Metrics --------------------
Accuracy: 0.7146
Precision: 0.1571
Recall: 0.7061
F1 Score: 0.2570
ROC AUC: 0.7798
Training final model using all data...
Final model training completed.

In [29]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_noweight.pkl",
    final_num_boost_round = 1400
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.253336
[200]	valid_0's binary_logloss: 0.247995
[300]	valid_0's binary_logloss: 0.245721
[400]	valid_0's binary_logloss: 0.244843
[500]	valid_0's binary_logloss: 0.244413
[600]	valid_0's binary_logloss: 0.244396
Early stopping, best iteration is:
[512]	valid_0's binary_logloss: 0.244317
-------------------- Metrics --------------------
Accuracy: 0.6538
Precision: 0.1447
Recall: 0.7111
F1 Score: 0.2405
ROC AUC: 0.7430
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.248396
[700]	valid_0's binary_logloss: 0.247981
[800]	valid_0's binary_logloss: 0.247721
[900]	valid_0's binary_logloss: 0.247731
Early stopping, best iteration is:
[862]	valid_0's binary_logloss: 0.247632
-------------------- Metrics --------------------
Accuracy: 0.6255
Precision: 0.1361
Recall: 0.7152
F1 Score: 0.2286
ROC AUC: 0.7351
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.24454
[1000]	valid_0's binary_logloss: 0.244019
[1100]	valid_0's binary_logloss: 0.243925
[1200]	valid_0's binary_logloss: 0.24385
Early stopping, best iteration is:
[1185]	valid_0's binary_logloss: 0.243811
-------------------- Metrics --------------------
Accuracy: 0.6390
Precision: 0.1410
Recall: 0.7237
F1 Score: 0.2360
ROC AUC: 0.7436
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.24421
[1300]	valid_0's binary_logloss: 0.243482
[1400]	valid_0's binary_logloss: 0.243184
[1500]	valid_0's binary_logloss: 0.24301
[1600]	valid_0's binary_logloss: 0.242903
[1700]	valid_0's binary_logloss: 0.242848
Early stopping, best iteration is:
[1674]	valid_0's binary_logloss: 0.24282
-------------------- Metrics --------------------
Accuracy: 0.6503
Precision: 0.1415
Recall: 0.7050
F1 Score: 0.2357
ROC AUC: 0.7444
Training final model using all data...
Final model training completed.

In [30]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_noweight_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_only_tenkai_noweight.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.2254
[200]	valid_0's binary_logloss: 0.221479
[300]	valid_0's binary_logloss: 0.220381
[400]	valid_0's binary_logloss: 0.219819
[500]	valid_0's binary_logloss: 0.219672
[600]	valid_0's binary_logloss: 0.219577
Early stopping, best iteration is:
[580]	valid_0's binary_logloss: 0.219516
-------------------- Metrics --------------------
Accuracy: 0.7119
Precision: 0.1469
Recall: 0.6743
F1 Score: 0.2412
ROC AUC: 0.7618
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.222476
[700]	valid_0's binary_logloss: 0.221856
[800]	valid_0's binary_logloss: 0.221828
Early stopping, best iteration is:
[733]	valid_0's binary_logloss: 0.221734
-------------------- Metrics --------------------
Accuracy: 0.6994
Precision: 0.1372
Recall: 0.6480
F1 Score: 0.2265
ROC AUC: 0.7535
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.218909
[900]	valid_0's binary_logloss: 0.218212
[1000]	valid_0's binary_logloss: 0.218062
[1100]	valid_0's binary_logloss: 0.218011
Early stopping, best iteration is:
[1028]	valid_0's binary_logloss: 0.217884
-------------------- Metrics --------------------
Accuracy: 0.7249
Precision: 0.1561
Recall: 0.6848
F1 Score: 0.2543
ROC AUC: 0.7723
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.220671
[1200]	valid_0's binary_logloss: 0.220293
[1300]	valid_0's binary_logloss: 0.220303
Early stopping, best iteration is:
[1217]	valid_0's binary_logloss: 0.220254
-------------------- Metrics --------------------
Accuracy: 0.7176
Precision: 0.1580
Recall: 0.7018
F1 Score: 0.2579
ROC AUC: 0.7777
Training final model using all data...
Final model training completed.

In [ ]:
#以下ダート

In [32]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_only_tenkai",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_only_tenkai.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_only_tenkai.pkl",
    final_num_boost_round = 1400
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.235174
[200]	valid_0's binary_logloss: 0.229943
[300]	valid_0's binary_logloss: 0.228011
[400]	valid_0's binary_logloss: 0.227121
[500]	valid_0's binary_logloss: 0.226815
[600]	valid_0's binary_logloss: 0.226715
Early stopping, best iteration is:
[587]	valid_0's binary_logloss: 0.226699
-------------------- Metrics --------------------
Accuracy: 0.6937
Precision: 0.1449
Recall: 0.6840
F1 Score: 0.2391
ROC AUC: 0.7537
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.234464
[700]	valid_0's binary_logloss: 0.233794
[800]	valid_0's binary_logloss: 0.233599
[900]	valid_0's binary_logloss: 0.233572
[1000]	valid_0's binary_logloss: 0.233643
Early stopping, best iteration is:
[960]	valid_0's binary_logloss: 0.233546
-------------------- Metrics --------------------
Accuracy: 0.6613
Precision: 0.1369
Recall: 0.6991
F1 Score: 0.2290
ROC AUC: 0.7410
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.232999
[1100]	valid_0's binary_logloss: 0.232393
[1200]	valid_0's binary_logloss: 0.232334
[1300]	valid_0's binary_logloss: 0.232366
[1400]	valid_0's binary_logloss: 0.232282
[1500]	valid_0's binary_logloss: 0.232183
Early stopping, best iteration is:
[1492]	valid_0's binary_logloss: 0.232164
-------------------- Metrics --------------------
Accuracy: 0.6652
Precision: 0.1362
Recall: 0.6922
F1 Score: 0.2276
ROC AUC: 0.7426
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.232081
[1600]	valid_0's binary_logloss: 0.231276
[1700]	valid_0's binary_logloss: 0.230924
[1800]	valid_0's binary_logloss: 0.230799
[1900]	valid_0's binary_logloss: 0.230751
[2000]	valid_0's binary_logloss: 0.230689
[2100]	valid_0's binary_logloss: 0.2306
[2200]	valid_0's binary_logloss: 0.230608
Early stopping, best iteration is:
[2174]	valid_0's binary_logloss: 0.23058
-------------------- Metrics --------------------
Accuracy: 0.6824
Precision: 0.1433
Recall: 0.6862
F1 Score: 0.2370
ROC AUC: 0.7479
Training final model using all data...
Final model training completed.

In [33]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_only_tenkai_weight.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.238805
[200]	valid_0's binary_logloss: 0.234008
[300]	valid_0's binary_logloss: 0.232155
[400]	valid_0's binary_logloss: 0.231544
[500]	valid_0's binary_logloss: 0.231285
[600]	valid_0's binary_logloss: 0.231177
[700]	valid_0's binary_logloss: 0.231225
Early stopping, best iteration is:
[620]	valid_0's binary_logloss: 0.231154
-------------------- Metrics --------------------
Accuracy: 0.6678
Precision: 0.1338
Recall: 0.6799
F1 Score: 0.2236
ROC AUC: 0.7335
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.238622
[800]	valid_0's binary_logloss: 0.238425
[900]	valid_0's binary_logloss: 0.23871
Early stopping, best iteration is:
[804]	valid_0's binary_logloss: 0.238415
-------------------- Metrics --------------------
Accuracy: 0.6493
Precision: 0.1282
Recall: 0.6678
F1 Score: 0.2151
ROC AUC: 0.7158
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.235462
[1000]	valid_0's binary_logloss: 0.234829
[1100]	valid_0's binary_logloss: 0.234577
[1200]	valid_0's binary_logloss: 0.234492
[1300]	valid_0's binary_logloss: 0.234452
Early stopping, best iteration is:
[1248]	valid_0's binary_logloss: 0.234419
-------------------- Metrics --------------------
Accuracy: 0.6552
Precision: 0.1327
Recall: 0.6933
F1 Score: 0.2228
ROC AUC: 0.7328
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.235562
[1400]	valid_0's binary_logloss: 0.235046
[1500]	valid_0's binary_logloss: 0.234832
[1600]	valid_0's binary_logloss: 0.234698
[1700]	valid_0's binary_logloss: 0.234615
[1800]	valid_0's binary_logloss: 0.234538
[1900]	valid_0's binary_logloss: 0.234588
Early stopping, best iteration is:
[1805]	valid_0's binary_logloss: 0.234527
-------------------- Metrics --------------------
Accuracy: 0.6671
Precision: 0.1339
Recall: 0.6636
F1 Score: 0.2228
ROC AUC: 0.7304
Training final model using all data...
Final model training completed.

In [34]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_only_tenkai_weight.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.227688
[200]	valid_0's binary_logloss: 0.223277
[300]	valid_0's binary_logloss: 0.222114
[400]	valid_0's binary_logloss: 0.222163
Early stopping, best iteration is:
[348]	valid_0's binary_logloss: 0.222034
-------------------- Metrics --------------------
Accuracy: 0.6985
Precision: 0.1450
Recall: 0.6922
F1 Score: 0.2397
ROC AUC: 0.7571
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[400]	valid_0's binary_logloss: 0.222497
[500]	valid_0's binary_logloss: 0.222106
[600]	valid_0's binary_logloss: 0.221802
[700]	valid_0's binary_logloss: 0.221979
Early stopping, best iteration is:
[609]	valid_0's binary_logloss: 0.221764
-------------------- Metrics --------------------
Accuracy: 0.6817
Precision: 0.1447
Recall: 0.7316
F1 Score: 0.2416
ROC AUC: 0.7656
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.224924
[800]	valid_0's binary_logloss: 0.224542
[900]	valid_0's binary_logloss: 0.224501
Early stopping, best iteration is:
[859]	valid_0's binary_logloss: 0.224439
-------------------- Metrics --------------------
Accuracy: 0.7100
Precision: 0.1523
Recall: 0.6830
F1 Score: 0.2490
ROC AUC: 0.7633
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.219133
[1000]	valid_0's binary_logloss: 0.218757
[1100]	valid_0's binary_logloss: 0.218581
[1200]	valid_0's binary_logloss: 0.21858
Early stopping, best iteration is:
[1199]	valid_0's binary_logloss: 0.218561
-------------------- Metrics --------------------
Accuracy: 0.7132
Precision: 0.1553
Recall: 0.7004
F1 Score: 0.2542
ROC AUC: 0.7829
Training final model using all data...
Final model training completed.

In [35]:






# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv(
    
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_only_tenkai.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.226004
[200]	valid_0's binary_logloss: 0.22184
[300]	valid_0's binary_logloss: 0.220535
[400]	valid_0's binary_logloss: 0.220345
[500]	valid_0's binary_logloss: 0.22062
Early stopping, best iteration is:
[405]	valid_0's binary_logloss: 0.220304
-------------------- Metrics --------------------
Accuracy: 0.7299
Precision: 0.1541
Recall: 0.6535
F1 Score: 0.2494
ROC AUC: 0.7656
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.219971
[600]	valid_0's binary_logloss: 0.219905
[700]	valid_0's binary_logloss: 0.219875
Early stopping, best iteration is:
[677]	valid_0's binary_logloss: 0.219781
-------------------- Metrics --------------------
Accuracy: 0.7029
Precision: 0.1493
Recall: 0.6998
F1 Score: 0.2461
ROC AUC: 0.7739
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.223009
[800]	valid_0's binary_logloss: 0.222497
[900]	valid_0's binary_logloss: 0.222008
[1000]	valid_0's binary_logloss: 0.221953
Early stopping, best iteration is:
[933]	valid_0's binary_logloss: 0.221894
-------------------- Metrics --------------------
Accuracy: 0.7224
Precision: 0.1569
Recall: 0.6726
F1 Score: 0.2544
ROC AUC: 0.7735
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.217195
Early stopping, best iteration is:
[992]	valid_0's binary_logloss: 0.217178
-------------------- Metrics --------------------
Accuracy: 0.7277
Precision: 0.1654
Recall: 0.7174
F1 Score: 0.2689
ROC AUC: 0.7881
Training final model using all data...
Final model training completed.

In [39]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_only_tenkai.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai")
# summary_df_shaft

In [40]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai.csv",
#     return_tables_filename = "return_tables_turf_nowin.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_nowin_only_tenkai.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai")
# summary_df_shaft

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_only_tenkai_noweight.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_noweight")
# summary_df_shaft

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight.csv",
#     return_tables_filename = "return_tables_turf_nowin.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_nowin_only_tenkai_noweight.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_noweight")
# summary_df_shaft

In [ ]:
%autoreload

In [ ]:
#以下ダート

### ３位以内モデル

In [36]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf.yaml",
)
evaluation_df = trainer_in3.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.478612
[200]	valid_0's binary_logloss: 0.461225
[300]	valid_0's binary_logloss: 0.454086
[400]	valid_0's binary_logloss: 0.451066
[500]	valid_0's binary_logloss: 0.449544
[600]	valid_0's binary_logloss: 0.448618
[700]	valid_0's binary_logloss: 0.448177
[800]	valid_0's binary_logloss: 0.448127
Early stopping, best iteration is:
[770]	valid_0's binary_logloss: 0.44806
-------------------- Metrics --------------------
Accuracy: 0.4223
Precision: 0.2817
Recall: 0.9693
F1 Score: 0.4365
ROC AUC: 0.7781
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.460608
[900]	valid_0's binary_logloss: 0.459486
[1000]	valid_0's binary_logloss: 0.458907
[1100]	valid_0's binary_logloss: 0.458521
[1200]	valid_0's binary_logloss: 0.458432
[1300]	valid_0's binary_logloss: 0.458345
[1400]	valid_0's binary_logloss: 0.45841
Early stopping, best iteration is:
[1301]	valid_0's binary_logloss: 0.458332
-------------------- Metrics --------------------
Accuracy: 0.4195
Precision: 0.2811
Recall: 0.9609
F1 Score: 0.4350
ROC AUC: 0.7651
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.450249
[1500]	valid_0's binary_logloss: 0.4498
[1600]	valid_0's binary_logloss: 0.449507
[1700]	valid_0's binary_logloss: 0.449382
[1800]	valid_0's binary_logloss: 0.449391
Early stopping, best iteration is:
[1728]	valid_0's binary_logloss: 0.449336
-------------------- Metrics --------------------
Accuracy: 0.4185
Precision: 0.2799
Recall: 0.9682
F1 Score: 0.4343
ROC AUC: 0.7756
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1800]	valid_0's binary_logloss: 0.450079
[1900]	valid_0's binary_logloss: 0.449709
[2000]	valid_0's binary_logloss: 0.449389
[2100]	valid_0's binary_logloss: 0.449298
[2200]	valid_0's binary_logloss: 0.449253
[2300]	valid_0's binary_logloss: 0.449144
[2400]	valid_0's binary_logloss: 0.449163
Early stopping, best iteration is:
[2360]	valid_0's binary_logloss: 0.449135
-------------------- Metrics --------------------
Accuracy: 0.4314
Precision: 0.2831
Recall: 0.9649
F1 Score: 0.4377
ROC AUC: 0.7747
Training final model using all data...
Final model training completed.

In [37]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.456709
[200]	valid_0's binary_logloss: 0.441683
[300]	valid_0's binary_logloss: 0.436038
[400]	valid_0's binary_logloss: 0.433302
[500]	valid_0's binary_logloss: 0.431806
[600]	valid_0's binary_logloss: 0.431073
[700]	valid_0's binary_logloss: 0.430781
[800]	valid_0's binary_logloss: 0.430631
[900]	valid_0's binary_logloss: 0.430625
Early stopping, best iteration is:
[802]	valid_0's binary_logloss: 0.430599
-------------------- Metrics --------------------
Accuracy: 0.4145
Precision: 0.2598
Recall: 0.9615
F1 Score: 0.4091
ROC AUC: 0.7744
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.448846
[1000]	valid_0's binary_logloss: 0.44829
[1100]	valid_0's binary_logloss: 0.447927
[1200]	valid_0's binary_logloss: 0.447706
[1300]	valid_0's binary_logloss: 0.447661
[1400]	valid_0's binary_logloss: 0.44769
Early stopping, best iteration is:
[1325]	valid_0's binary_logloss: 0.447641
-------------------- Metrics --------------------
Accuracy: 0.4014
Precision: 0.2592
Recall: 0.9582
F1 Score: 0.4081
ROC AUC: 0.7553
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.438441
[1500]	valid_0's binary_logloss: 0.438038
[1600]	valid_0's binary_logloss: 0.437877
[1700]	valid_0's binary_logloss: 0.437746
[1800]	valid_0's binary_logloss: 0.437702
Early stopping, best iteration is:
[1768]	valid_0's binary_logloss: 0.437652
-------------------- Metrics --------------------
Accuracy: 0.3967
Precision: 0.2569
Recall: 0.9632
F1 Score: 0.4056
ROC AUC: 0.7686
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1800]	valid_0's binary_logloss: 0.441075
[1900]	valid_0's binary_logloss: 0.439996
[2000]	valid_0's binary_logloss: 0.439652
[2100]	valid_0's binary_logloss: 0.439381
[2200]	valid_0's binary_logloss: 0.439226
[2300]	valid_0's binary_logloss: 0.439173
[2400]	valid_0's binary_logloss: 0.439085
[2500]	valid_0's binary_logloss: 0.438953
[2600]	valid_0's binary_logloss: 0.43889
[2700]	valid_0's binary_logloss: 0.438813
[2800]	valid_0's binary_logloss: 0.438813
[2900]	valid_0's binary_logloss: 0.438739
[3000]	valid_0's binary_logloss: 0.438689
[3100]	valid_0's binary_logloss: 0.438703
Early stopping, best iteration is:
[3084]	valid_0's binary_logloss: 0.438674
-------------------- Metrics --------------------
Accuracy: 0.4207
Precision: 0.2657
Recall: 0.9581
F1 Score: 0.4160
ROC AUC: 0.7696
Training final model using all data...
Final model training completed.

In [38]:
# オッズと人気を特徴量から省いたランク、二値、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_obstract.csv", 
    config_filepath="config_lightgbm_niti_dev_obstract.yaml",
)
evaluation_df = trainer.run(
    n_splits = 3,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_obstract_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_obstract_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_obstract_in3.pkl"
)

Training fold 1/3...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.496892
[200]	valid_0's binary_logloss: 0.476092
[300]	valid_0's binary_logloss: 0.470076
[400]	valid_0's binary_logloss: 0.467236
[500]	valid_0's binary_logloss: 0.466808
Early stopping, best iteration is:
[442]	valid_0's binary_logloss: 0.466556
-------------------- Metrics --------------------
Accuracy: 0.4257
Precision: 0.3057
Recall: 0.9692
F1 Score: 0.4647
ROC AUC: 0.7831
Training fold 2/3...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.490838
[600]	valid_0's binary_logloss: 0.490774
Early stopping, best iteration is:
[524]	valid_0's binary_logloss: 0.490254
-------------------- Metrics --------------------
Accuracy: 0.4260
Precision: 0.3255
Recall: 0.9670
F1 Score: 0.4871
ROC AUC: 0.7793
Training final model using all data...
Final model training completed.

In [39]:

trainer = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_in3.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.430355
[200]	valid_0's binary_logloss: 0.413642
[300]	valid_0's binary_logloss: 0.407514
[400]	valid_0's binary_logloss: 0.405134
[500]	valid_0's binary_logloss: 0.404241
[600]	valid_0's binary_logloss: 0.403772
[700]	valid_0's binary_logloss: 0.403694
Early stopping, best iteration is:
[636]	valid_0's binary_logloss: 0.403568
-------------------- Metrics --------------------
Accuracy: 0.4907
Precision: 0.2777
Recall: 0.9361
F1 Score: 0.4283
ROC AUC: 0.8025
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.40808
[800]	valid_0's binary_logloss: 0.407381
[900]	valid_0's binary_logloss: 0.407065
Early stopping, best iteration is:
[863]	valid_0's binary_logloss: 0.407019
-------------------- Metrics --------------------
Accuracy: 0.4782
Precision: 0.2734
Recall: 0.9465
F1 Score: 0.4243
ROC AUC: 0.7995
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.403688
[1000]	valid_0's binary_logloss: 0.403212
[1100]	valid_0's binary_logloss: 0.402874
[1200]	valid_0's binary_logloss: 0.40287
[1300]	valid_0's binary_logloss: 0.402813
[1400]	valid_0's binary_logloss: 0.402825
Early stopping, best iteration is:
[1309]	valid_0's binary_logloss: 0.40274
-------------------- Metrics --------------------
Accuracy: 0.5082
Precision: 0.2854
Recall: 0.9299
F1 Score: 0.4368
ROC AUC: 0.8061
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.403675
[1500]	valid_0's binary_logloss: 0.403399
[1600]	valid_0's binary_logloss: 0.403511
Early stopping, best iteration is:
[1557]	valid_0's binary_logloss: 0.40339
-------------------- Metrics --------------------
Accuracy: 0.5091
Precision: 0.2908
Recall: 0.9359
F1 Score: 0.4437
ROC AUC: 0.8092
Training final model using all data...
Final model training completed.

In [40]:
# オッズと人気を特徴量から省いたランク、回帰、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_in3.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.430073
[200]	valid_0's binary_logloss: 0.413279
[300]	valid_0's binary_logloss: 0.408195
[400]	valid_0's binary_logloss: 0.406225
[500]	valid_0's binary_logloss: 0.405687
[600]	valid_0's binary_logloss: 0.40548
[700]	valid_0's binary_logloss: 0.405278
[800]	valid_0's binary_logloss: 0.405761
Early stopping, best iteration is:
[701]	valid_0's binary_logloss: 0.405277
-------------------- Metrics --------------------
Accuracy: 0.5249
Precision: 0.2938
Recall: 0.9346
F1 Score: 0.4471
ROC AUC: 0.8047
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.402002
[900]	valid_0's binary_logloss: 0.401541
[1000]	valid_0's binary_logloss: 0.401466
[1100]	valid_0's binary_logloss: 0.401367
Early stopping, best iteration is:
[1096]	valid_0's binary_logloss: 0.401293
-------------------- Metrics --------------------
Accuracy: 0.4859
Precision: 0.2814
Recall: 0.9510
F1 Score: 0.4343
ROC AUC: 0.8111
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.410229
[1200]	valid_0's binary_logloss: 0.409548
[1300]	valid_0's binary_logloss: 0.409487
[1400]	valid_0's binary_logloss: 0.409452
Early stopping, best iteration is:
[1385]	valid_0's binary_logloss: 0.409432
-------------------- Metrics --------------------
Accuracy: 0.5311
Precision: 0.3011
Recall: 0.9230
F1 Score: 0.4541
ROC AUC: 0.8059
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.413977
[1500]	valid_0's binary_logloss: 0.41376
Early stopping, best iteration is:
[1441]	valid_0's binary_logloss: 0.413238
-------------------- Metrics --------------------
Accuracy: 0.5108
Precision: 0.2906
Recall: 0.9269
F1 Score: 0.4425
ROC AUC: 0.7985
Training final model using all data...
Final model training completed.

In [ ]:
#体重なし

In [41]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_noweight_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.478519
[200]	valid_0's binary_logloss: 0.461116
[300]	valid_0's binary_logloss: 0.454003
[400]	valid_0's binary_logloss: 0.450887
[500]	valid_0's binary_logloss: 0.449438
[600]	valid_0's binary_logloss: 0.44885
[700]	valid_0's binary_logloss: 0.448449
[800]	valid_0's binary_logloss: 0.448418
[900]	valid_0's binary_logloss: 0.448376
Early stopping, best iteration is:
[830]	valid_0's binary_logloss: 0.44832
-------------------- Metrics --------------------
Accuracy: 0.4243
Precision: 0.2816
Recall: 0.9631
F1 Score: 0.4358
ROC AUC: 0.7777
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.461346
[1000]	valid_0's binary_logloss: 0.460507
[1100]	valid_0's binary_logloss: 0.460199
[1200]	valid_0's binary_logloss: 0.460095
[1300]	valid_0's binary_logloss: 0.45999
[1400]	valid_0's binary_logloss: 0.459921
Early stopping, best iteration is:
[1342]	valid_0's binary_logloss: 0.459886
-------------------- Metrics --------------------
Accuracy: 0.4217
Precision: 0.2816
Recall: 0.9584
F1 Score: 0.4353
ROC AUC: 0.7631
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.451782
[1500]	valid_0's binary_logloss: 0.451277
[1600]	valid_0's binary_logloss: 0.45093
[1700]	valid_0's binary_logloss: 0.450726
[1800]	valid_0's binary_logloss: 0.450595
[1900]	valid_0's binary_logloss: 0.450578
[2000]	valid_0's binary_logloss: 0.450574
Early stopping, best iteration is:
[1945]	valid_0's binary_logloss: 0.45052
-------------------- Metrics --------------------
Accuracy: 0.4198
Precision: 0.2799
Recall: 0.9639
F1 Score: 0.4338
ROC AUC: 0.7736
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2000]	valid_0's binary_logloss: 0.451435
[2100]	valid_0's binary_logloss: 0.451001
[2200]	valid_0's binary_logloss: 0.450753
[2300]	valid_0's binary_logloss: 0.450669
[2400]	valid_0's binary_logloss: 0.450654
[2500]	valid_0's binary_logloss: 0.450531
[2600]	valid_0's binary_logloss: 0.450533
Early stopping, best iteration is:
[2548]	valid_0's binary_logloss: 0.450506
-------------------- Metrics --------------------
Accuracy: 0.4287
Precision: 0.2822
Recall: 0.9660
F1 Score: 0.4368
ROC AUC: 0.7728
Training final model using all data...
Final model training completed.

In [42]:
# オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_noweight_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.45638
[200]	valid_0's binary_logloss: 0.441423
[300]	valid_0's binary_logloss: 0.436019
[400]	valid_0's binary_logloss: 0.43351
[500]	valid_0's binary_logloss: 0.432376
[600]	valid_0's binary_logloss: 0.431998
[700]	valid_0's binary_logloss: 0.43162
[800]	valid_0's binary_logloss: 0.431487
[900]	valid_0's binary_logloss: 0.431552
Early stopping, best iteration is:
[815]	valid_0's binary_logloss: 0.43144
-------------------- Metrics --------------------
Accuracy: 0.4117
Precision: 0.2590
Recall: 0.9621
F1 Score: 0.4081
ROC AUC: 0.7732
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.450182
[1000]	valid_0's binary_logloss: 0.449608
[1100]	valid_0's binary_logloss: 0.449358
[1200]	valid_0's binary_logloss: 0.449312
[1300]	valid_0's binary_logloss: 0.449196
[1400]	valid_0's binary_logloss: 0.449202
Early stopping, best iteration is:
[1313]	valid_0's binary_logloss: 0.449178
-------------------- Metrics --------------------
Accuracy: 0.3946
Precision: 0.2570
Recall: 0.9578
F1 Score: 0.4053
ROC AUC: 0.7531
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.439175
[1500]	valid_0's binary_logloss: 0.438801
[1600]	valid_0's binary_logloss: 0.438746
[1700]	valid_0's binary_logloss: 0.438733
Early stopping, best iteration is:
[1670]	valid_0's binary_logloss: 0.438667
-------------------- Metrics --------------------
Accuracy: 0.3937
Precision: 0.2561
Recall: 0.9645
F1 Score: 0.4047
ROC AUC: 0.7673
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's binary_logloss: 0.44161
[1800]	valid_0's binary_logloss: 0.440459
[1900]	valid_0's binary_logloss: 0.44014
[2000]	valid_0's binary_logloss: 0.439783
[2100]	valid_0's binary_logloss: 0.439632
[2200]	valid_0's binary_logloss: 0.439448
[2300]	valid_0's binary_logloss: 0.439368
[2400]	valid_0's binary_logloss: 0.439297
[2500]	valid_0's binary_logloss: 0.439196
[2600]	valid_0's binary_logloss: 0.43915
Early stopping, best iteration is:
[2576]	valid_0's binary_logloss: 0.439111
-------------------- Metrics --------------------
Accuracy: 0.4164
Precision: 0.2643
Recall: 0.9586
F1 Score: 0.4144
ROC AUC: 0.7692
Training final model using all data...
Final model training completed.

In [43]:
# オッズと人気を特徴量から省いたランク、二値、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_obstract.csv", 
    config_filepath="config_lightgbm_niti_dev_obstract_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 3,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_obstract_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_obstract_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_obstract_noweight_in3.pkl"
)

Training fold 1/3...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.497472
[200]	valid_0's binary_logloss: 0.476735
[300]	valid_0's binary_logloss: 0.470298
[400]	valid_0's binary_logloss: 0.467592
[500]	valid_0's binary_logloss: 0.46752
Early stopping, best iteration is:
[443]	valid_0's binary_logloss: 0.46722
-------------------- Metrics --------------------
Accuracy: 0.4243
Precision: 0.3049
Recall: 0.9674
F1 Score: 0.4637
ROC AUC: 0.7824
Training fold 2/3...
Training until validation scores don't improve for 100 rounds
[500]	valid_0's binary_logloss: 0.489484
[600]	valid_0's binary_logloss: 0.48771
[700]	valid_0's binary_logloss: 0.487884
Early stopping, best iteration is:
[648]	valid_0's binary_logloss: 0.487285
-------------------- Metrics --------------------
Accuracy: 0.4399
Precision: 0.3308
Recall: 0.9645
F1 Score: 0.4926
ROC AUC: 0.7830
Training final model using all data...
Final model training completed.

In [44]:
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_nowin_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_noweight_in3.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.430073
[200]	valid_0's binary_logloss: 0.41408
[300]	valid_0's binary_logloss: 0.408286
[400]	valid_0's binary_logloss: 0.406415
[500]	valid_0's binary_logloss: 0.405771
[600]	valid_0's binary_logloss: 0.405545
[700]	valid_0's binary_logloss: 0.405491
Early stopping, best iteration is:
[635]	valid_0's binary_logloss: 0.405428
-------------------- Metrics --------------------
Accuracy: 0.4859
Precision: 0.2754
Recall: 0.9339
F1 Score: 0.4254
ROC AUC: 0.8003
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.411774
[800]	valid_0's binary_logloss: 0.410876
[900]	valid_0's binary_logloss: 0.410973
Early stopping, best iteration is:
[829]	valid_0's binary_logloss: 0.410778
-------------------- Metrics --------------------
Accuracy: 0.4682
Precision: 0.2692
Recall: 0.9435
F1 Score: 0.4189
ROC AUC: 0.7946
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.405999
[1000]	valid_0's binary_logloss: 0.405674
[1100]	valid_0's binary_logloss: 0.405457
Early stopping, best iteration is:
[1096]	valid_0's binary_logloss: 0.405443
-------------------- Metrics --------------------
Accuracy: 0.5034
Precision: 0.2828
Recall: 0.9256
F1 Score: 0.4332
ROC AUC: 0.8027
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.408756
[1200]	valid_0's binary_logloss: 0.407322
[1300]	valid_0's binary_logloss: 0.407134
Early stopping, best iteration is:
[1294]	valid_0's binary_logloss: 0.40712
-------------------- Metrics --------------------
Accuracy: 0.4932
Precision: 0.2844
Recall: 0.9388
F1 Score: 0.4366
ROC AUC: 0.8035
Training final model using all data...
Final model training completed.

In [45]:
# オッズと人気を特徴量から省いたランク、回帰、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_nowin_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_noweight_in3.pkl"
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.426445
[200]	valid_0's binary_logloss: 0.410165
[300]	valid_0's binary_logloss: 0.405821
[400]	valid_0's binary_logloss: 0.403966
[500]	valid_0's binary_logloss: 0.403296
[600]	valid_0's binary_logloss: 0.403259
[700]	valid_0's binary_logloss: 0.403363
Early stopping, best iteration is:
[643]	valid_0's binary_logloss: 0.403182
-------------------- Metrics --------------------
Accuracy: 0.5277
Precision: 0.2942
Recall: 0.9274
F1 Score: 0.4467
ROC AUC: 0.8069
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[700]	valid_0's binary_logloss: 0.399909
[800]	valid_0's binary_logloss: 0.399499
[900]	valid_0's binary_logloss: 0.399297
[1000]	valid_0's binary_logloss: 0.399424
Early stopping, best iteration is:
[928]	valid_0's binary_logloss: 0.399247
-------------------- Metrics --------------------
Accuracy: 0.4907
Precision: 0.2829
Recall: 0.9477
F1 Score: 0.4358
ROC AUC: 0.8134
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.408784
[1100]	valid_0's binary_logloss: 0.408504
[1200]	valid_0's binary_logloss: 0.408275
Early stopping, best iteration is:
[1180]	valid_0's binary_logloss: 0.408171
-------------------- Metrics --------------------
Accuracy: 0.5281
Precision: 0.3001
Recall: 0.9262
F1 Score: 0.4534
ROC AUC: 0.8070
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.41162
[1300]	valid_0's binary_logloss: 0.412121
Early stopping, best iteration is:
[1225]	valid_0's binary_logloss: 0.411473
-------------------- Metrics --------------------
Accuracy: 0.5028
Precision: 0.2876
Recall: 0.9296
F1 Score: 0.4393
ROC AUC: 0.8002
Training final model using all data...
Final model training completed.

In [46]:
#展開

In [47]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.505974
[200]	valid_0's binary_logloss: 0.493792
[300]	valid_0's binary_logloss: 0.488227
[400]	valid_0's binary_logloss: 0.485241
[500]	valid_0's binary_logloss: 0.483292
[600]	valid_0's binary_logloss: 0.482338
[700]	valid_0's binary_logloss: 0.481865
[800]	valid_0's binary_logloss: 0.481393
[900]	valid_0's binary_logloss: 0.481218
[1000]	valid_0's binary_logloss: 0.481026
[1100]	valid_0's binary_logloss: 0.480878
[1200]	valid_0's binary_logloss: 0.480729
Early stopping, best iteration is:
[1194]	valid_0's binary_logloss: 0.480689
-------------------- Metrics --------------------
Accuracy: 0.3135
Precision: 0.2499
Recall: 0.9860
F1 Score: 0.3988
ROC AUC: 0.7272
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.490176
[1300]	valid_0's binary_logloss: 0.488118
[1400]	valid_0's binary_logloss: 0.487583
[1500]	valid_0's binary_logloss: 0.487239
[1600]	valid_0's binary_logloss: 0.486865
[1700]	valid_0's binary_logloss: 0.48685
Early stopping, best iteration is:
[1615]	valid_0's binary_logloss: 0.486796
-------------------- Metrics --------------------
Accuracy: 0.3264
Precision: 0.2544
Recall: 0.9824
F1 Score: 0.4042
ROC AUC: 0.7184
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1700]	valid_0's binary_logloss: 0.479449
[1800]	valid_0's binary_logloss: 0.478459
[1900]	valid_0's binary_logloss: 0.477893
[2000]	valid_0's binary_logloss: 0.477509
[2100]	valid_0's binary_logloss: 0.47727
[2200]	valid_0's binary_logloss: 0.477157
[2300]	valid_0's binary_logloss: 0.476934
[2400]	valid_0's binary_logloss: 0.476837
[2500]	valid_0's binary_logloss: 0.476795
[2600]	valid_0's binary_logloss: 0.476722
[2700]	valid_0's binary_logloss: 0.476758
[2800]	valid_0's binary_logloss: 0.476704
Early stopping, best iteration is:
[2756]	valid_0's binary_logloss: 0.476618
-------------------- Metrics --------------------
Accuracy: 0.3379
Precision: 0.2552
Recall: 0.9756
F1 Score: 0.4046
ROC AUC: 0.7325
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2800]	valid_0's binary_logloss: 0.479998
[2900]	valid_0's binary_logloss: 0.479288
[3000]	valid_0's binary_logloss: 0.479078
[3100]	valid_0's binary_logloss: 0.478888
[3200]	valid_0's binary_logloss: 0.478922
Early stopping, best iteration is:
[3140]	valid_0's binary_logloss: 0.478795
-------------------- Metrics --------------------
Accuracy: 0.3430
Precision: 0.2558
Recall: 0.9762
F1 Score: 0.4054
ROC AUC: 0.7278
Training final model using all data...
Final model training completed.

In [48]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_only_tenkai_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.449885
[200]	valid_0's binary_logloss: 0.435929
[300]	valid_0's binary_logloss: 0.430394
[400]	valid_0's binary_logloss: 0.428326
[500]	valid_0's binary_logloss: 0.427296
[600]	valid_0's binary_logloss: 0.427194
[700]	valid_0's binary_logloss: 0.427232
[800]	valid_0's binary_logloss: 0.427256
Early stopping, best iteration is:
[725]	valid_0's binary_logloss: 0.426962
-------------------- Metrics --------------------
Accuracy: 0.4408
Precision: 0.2597
Recall: 0.9423
F1 Score: 0.4072
ROC AUC: 0.7709
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.432036
[900]	valid_0's binary_logloss: 0.431394
[1000]	valid_0's binary_logloss: 0.431256
Early stopping, best iteration is:
[984]	valid_0's binary_logloss: 0.431093
-------------------- Metrics --------------------
Accuracy: 0.4203
Precision: 0.2532
Recall: 0.9512
F1 Score: 0.4000
ROC AUC: 0.7611
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.426048
[1100]	valid_0's binary_logloss: 0.424887
[1200]	valid_0's binary_logloss: 0.424805
[1300]	valid_0's binary_logloss: 0.424849
Early stopping, best iteration is:
[1234]	valid_0's binary_logloss: 0.424696
-------------------- Metrics --------------------
Accuracy: 0.4543
Precision: 0.2651
Recall: 0.9372
F1 Score: 0.4133
ROC AUC: 0.7756
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.423152
[1400]	valid_0's binary_logloss: 0.422702
[1500]	valid_0's binary_logloss: 0.422727
Early stopping, best iteration is:
[1407]	valid_0's binary_logloss: 0.422668
-------------------- Metrics --------------------
Accuracy: 0.4417
Precision: 0.2660
Recall: 0.9491
F1 Score: 0.4156
ROC AUC: 0.7833
Training final model using all data...
Final model training completed.

In [49]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_noweight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_noweight_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.499742
[200]	valid_0's binary_logloss: 0.485348
[300]	valid_0's binary_logloss: 0.479258
[400]	valid_0's binary_logloss: 0.476173
[500]	valid_0's binary_logloss: 0.474564
[600]	valid_0's binary_logloss: 0.473493
[700]	valid_0's binary_logloss: 0.472985
[800]	valid_0's binary_logloss: 0.472733
[900]	valid_0's binary_logloss: 0.472345
[1000]	valid_0's binary_logloss: 0.4724
Early stopping, best iteration is:
[900]	valid_0's binary_logloss: 0.472345
-------------------- Metrics --------------------
Accuracy: 0.3435
Precision: 0.2574
Recall: 0.9780
F1 Score: 0.4076
ROC AUC: 0.7423
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.48169
[1100]	valid_0's binary_logloss: 0.480728
[1200]	valid_0's binary_logloss: 0.480187
[1300]	valid_0's binary_logloss: 0.479881
[1400]	valid_0's binary_logloss: 0.479516
[1500]	valid_0's binary_logloss: 0.479404
[1600]	valid_0's binary_logloss: 0.479454
Early stopping, best iteration is:
[1500]	valid_0's binary_logloss: 0.479404
-------------------- Metrics --------------------
Accuracy: 0.3507
Precision: 0.2609
Recall: 0.9774
F1 Score: 0.4118
ROC AUC: 0.7317
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1600]	valid_0's binary_logloss: 0.468903
[1700]	valid_0's binary_logloss: 0.468081
[1800]	valid_0's binary_logloss: 0.467616
[1900]	valid_0's binary_logloss: 0.467367
[2000]	valid_0's binary_logloss: 0.46721
Early stopping, best iteration is:
[1989]	valid_0's binary_logloss: 0.4672
-------------------- Metrics --------------------
Accuracy: 0.3582
Precision: 0.2615
Recall: 0.9780
F1 Score: 0.4127
ROC AUC: 0.7481
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2000]	valid_0's binary_logloss: 0.470997
[2100]	valid_0's binary_logloss: 0.470158
[2200]	valid_0's binary_logloss: 0.469848
[2300]	valid_0's binary_logloss: 0.469677
[2400]	valid_0's binary_logloss: 0.469545
[2500]	valid_0's binary_logloss: 0.469424
[2600]	valid_0's binary_logloss: 0.469272
[2700]	valid_0's binary_logloss: 0.469263
[2800]	valid_0's binary_logloss: 0.469257
[2900]	valid_0's binary_logloss: 0.469254
Early stopping, best iteration is:
[2865]	valid_0's binary_logloss: 0.469205
-------------------- Metrics --------------------
Accuracy: 0.3778
Precision: 0.2657
Recall: 0.9706
F1 Score: 0.4171
ROC AUC: 0.7446
Training final model using all data...
Final model training completed.

In [50]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_noweight_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_only_tenkai_noweight_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.450291
[200]	valid_0's binary_logloss: 0.436423
[300]	valid_0's binary_logloss: 0.43066
[400]	valid_0's binary_logloss: 0.428481
[500]	valid_0's binary_logloss: 0.427624
[600]	valid_0's binary_logloss: 0.427118
[700]	valid_0's binary_logloss: 0.426945
[800]	valid_0's binary_logloss: 0.426788
[900]	valid_0's binary_logloss: 0.426643
Early stopping, best iteration is:
[834]	valid_0's binary_logloss: 0.426577
-------------------- Metrics --------------------
Accuracy: 0.4502
Precision: 0.2629
Recall: 0.9415
F1 Score: 0.4111
ROC AUC: 0.7715
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.432901
[1000]	valid_0's binary_logloss: 0.43243
[1100]	valid_0's binary_logloss: 0.432325
Early stopping, best iteration is:
[1034]	valid_0's binary_logloss: 0.432273
-------------------- Metrics --------------------
Accuracy: 0.4168
Precision: 0.2517
Recall: 0.9483
F1 Score: 0.3978
ROC AUC: 0.7591
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1100]	valid_0's binary_logloss: 0.425002
[1200]	valid_0's binary_logloss: 0.424531
[1300]	valid_0's binary_logloss: 0.424327
[1400]	valid_0's binary_logloss: 0.424199
Early stopping, best iteration is:
[1333]	valid_0's binary_logloss: 0.424081
-------------------- Metrics --------------------
Accuracy: 0.4506
Precision: 0.2641
Recall: 0.9397
F1 Score: 0.4123
ROC AUC: 0.7762
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1400]	valid_0's binary_logloss: 0.424304
[1500]	valid_0's binary_logloss: 0.423872
[1600]	valid_0's binary_logloss: 0.423728
[1700]	valid_0's binary_logloss: 0.423609
[1800]	valid_0's binary_logloss: 0.423558
[1900]	valid_0's binary_logloss: 0.423404
[2000]	valid_0's binary_logloss: 0.423466
Early stopping, best iteration is:
[1915]	valid_0's binary_logloss: 0.423372
-------------------- Metrics --------------------
Accuracy: 0.4538
Precision: 0.2698
Recall: 0.9445
F1 Score: 0.4197
ROC AUC: 0.7830
Training final model using all data...
Final model training completed.

In [51]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_only_tenkai_in3.pkl",
    final_num_boost_round = 1400
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.471979
[200]	valid_0's binary_logloss: 0.4595
[300]	valid_0's binary_logloss: 0.454183
[400]	valid_0's binary_logloss: 0.451572
[500]	valid_0's binary_logloss: 0.450495
[600]	valid_0's binary_logloss: 0.450114
[700]	valid_0's binary_logloss: 0.449939
[800]	valid_0's binary_logloss: 0.449875
Early stopping, best iteration is:
[744]	valid_0's binary_logloss: 0.449809
-------------------- Metrics --------------------
Accuracy: 0.3354
Precision: 0.2376
Recall: 0.9749
F1 Score: 0.3821
ROC AUC: 0.7454
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.465972
[900]	valid_0's binary_logloss: 0.464939
[1000]	valid_0's binary_logloss: 0.464437
[1100]	valid_0's binary_logloss: 0.464303
[1200]	valid_0's binary_logloss: 0.464349
Early stopping, best iteration is:
[1133]	valid_0's binary_logloss: 0.46427
-------------------- Metrics --------------------
Accuracy: 0.3425
Precision: 0.2431
Recall: 0.9716
F1 Score: 0.3889
ROC AUC: 0.7276
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1200]	valid_0's binary_logloss: 0.458014
[1300]	valid_0's binary_logloss: 0.4577
[1400]	valid_0's binary_logloss: 0.457532
[1500]	valid_0's binary_logloss: 0.457359
[1600]	valid_0's binary_logloss: 0.457344
Early stopping, best iteration is:
[1575]	valid_0's binary_logloss: 0.45728
-------------------- Metrics --------------------
Accuracy: 0.3401
Precision: 0.2408
Recall: 0.9698
F1 Score: 0.3858
ROC AUC: 0.7382
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1600]	valid_0's binary_logloss: 0.462679
[1700]	valid_0's binary_logloss: 0.459884
[1800]	valid_0's binary_logloss: 0.459187
[1900]	valid_0's binary_logloss: 0.458766
[2000]	valid_0's binary_logloss: 0.458631
[2100]	valid_0's binary_logloss: 0.458437
[2200]	valid_0's binary_logloss: 0.458322
[2300]	valid_0's binary_logloss: 0.45823
[2400]	valid_0's binary_logloss: 0.458212
[2500]	valid_0's binary_logloss: 0.458263
Early stopping, best iteration is:
[2410]	valid_0's binary_logloss: 0.458203
-------------------- Metrics --------------------
Accuracy: 0.3726
Precision: 0.2510
Recall: 0.9640
F1 Score: 0.3983
ROC AUC: 0.7393
Training final model using all data...
Final model training completed.

In [52]:

# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_only_tenkai_weight_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.47858
[200]	valid_0's binary_logloss: 0.467291
[300]	valid_0's binary_logloss: 0.462477
[400]	valid_0's binary_logloss: 0.460367
[500]	valid_0's binary_logloss: 0.459059
[600]	valid_0's binary_logloss: 0.458797
[700]	valid_0's binary_logloss: 0.458428
[800]	valid_0's binary_logloss: 0.458374
[900]	valid_0's binary_logloss: 0.458249
Early stopping, best iteration is:
[888]	valid_0's binary_logloss: 0.458215
-------------------- Metrics --------------------
Accuracy: 0.3103
Precision: 0.2320
Recall: 0.9834
F1 Score: 0.3754
ROC AUC: 0.7310
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.477421
[1000]	valid_0's binary_logloss: 0.47458
[1100]	valid_0's binary_logloss: 0.473971
[1200]	valid_0's binary_logloss: 0.473819
[1300]	valid_0's binary_logloss: 0.473736
Early stopping, best iteration is:
[1288]	valid_0's binary_logloss: 0.473679
-------------------- Metrics --------------------
Accuracy: 0.3184
Precision: 0.2364
Recall: 0.9706
F1 Score: 0.3802
ROC AUC: 0.7097
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.465517
[1400]	valid_0's binary_logloss: 0.46404
[1500]	valid_0's binary_logloss: 0.463642
Early stopping, best iteration is:
[1479]	valid_0's binary_logloss: 0.463528
-------------------- Metrics --------------------
Accuracy: 0.3040
Precision: 0.2323
Recall: 0.9797
F1 Score: 0.3756
ROC AUC: 0.7282
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1500]	valid_0's binary_logloss: 0.469783
[1600]	valid_0's binary_logloss: 0.46595
[1700]	valid_0's binary_logloss: 0.464933
[1800]	valid_0's binary_logloss: 0.464421
[1900]	valid_0's binary_logloss: 0.464159
[2000]	valid_0's binary_logloss: 0.463953
[2100]	valid_0's binary_logloss: 0.463829
[2200]	valid_0's binary_logloss: 0.463767
[2300]	valid_0's binary_logloss: 0.463664
[2400]	valid_0's binary_logloss: 0.463639
[2500]	valid_0's binary_logloss: 0.463554
[2600]	valid_0's binary_logloss: 0.463478
[2700]	valid_0's binary_logloss: 0.46345
Early stopping, best iteration is:
[2672]	valid_0's binary_logloss: 0.463432
-------------------- Metrics --------------------
Accuracy: 0.3651
Precision: 0.2483
Recall: 0.9606
F1 Score: 0.3946
ROC AUC: 0.7288
Training final model using all data...
Final model training completed.

In [53]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai_weight.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_only_tenkai_weight_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.447219
[200]	valid_0's binary_logloss: 0.433961
[300]	valid_0's binary_logloss: 0.429675
[400]	valid_0's binary_logloss: 0.428007
[500]	valid_0's binary_logloss: 0.427602
[600]	valid_0's binary_logloss: 0.427662
Early stopping, best iteration is:
[526]	valid_0's binary_logloss: 0.427563
-------------------- Metrics --------------------
Accuracy: 0.4209
Precision: 0.2558
Recall: 0.9519
F1 Score: 0.4032
ROC AUC: 0.7719
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.426243
[700]	valid_0's binary_logloss: 0.425881
[800]	valid_0's binary_logloss: 0.426047
Early stopping, best iteration is:
[771]	valid_0's binary_logloss: 0.4257
-------------------- Metrics --------------------
Accuracy: 0.4083
Precision: 0.2547
Recall: 0.9613
F1 Score: 0.4027
ROC AUC: 0.7780
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[800]	valid_0's binary_logloss: 0.43053
[900]	valid_0's binary_logloss: 0.429561
[1000]	valid_0's binary_logloss: 0.4292
[1100]	valid_0's binary_logloss: 0.429205
[1200]	valid_0's binary_logloss: 0.429098
[1300]	valid_0's binary_logloss: 0.429186
Early stopping, best iteration is:
[1206]	valid_0's binary_logloss: 0.429052
-------------------- Metrics --------------------
Accuracy: 0.4782
Precision: 0.2786
Recall: 0.9248
F1 Score: 0.4283
ROC AUC: 0.7790
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1300]	valid_0's binary_logloss: 0.427589
[1400]	valid_0's binary_logloss: 0.427564
Early stopping, best iteration is:
[1351]	valid_0's binary_logloss: 0.427431
-------------------- Metrics --------------------
Accuracy: 0.4538
Precision: 0.2699
Recall: 0.9428
F1 Score: 0.4197
ROC AUC: 0.7780
Training final model using all data...
Final model training completed.

In [54]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_dirt_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_only_tenkai_in3.pkl",
    final_num_boost_round = 1000
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.443259
[200]	valid_0's binary_logloss: 0.429232
[300]	valid_0's binary_logloss: 0.424539
[400]	valid_0's binary_logloss: 0.422795
[500]	valid_0's binary_logloss: 0.422089
[600]	valid_0's binary_logloss: 0.422154
Early stopping, best iteration is:
[509]	valid_0's binary_logloss: 0.422056
-------------------- Metrics --------------------
Accuracy: 0.4545
Precision: 0.2664
Recall: 0.9428
F1 Score: 0.4154
ROC AUC: 0.7806
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[600]	valid_0's binary_logloss: 0.420471
[700]	valid_0's binary_logloss: 0.419886
[800]	valid_0's binary_logloss: 0.419771
[900]	valid_0's binary_logloss: 0.419722
Early stopping, best iteration is:
[862]	valid_0's binary_logloss: 0.419674
-------------------- Metrics --------------------
Accuracy: 0.4197
Precision: 0.2577
Recall: 0.9551
F1 Score: 0.4058
ROC AUC: 0.7868
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.425697
[1000]	valid_0's binary_logloss: 0.425467
Early stopping, best iteration is:
[950]	valid_0's binary_logloss: 0.425418
-------------------- Metrics --------------------
Accuracy: 0.4565
Precision: 0.2724
Recall: 0.9406
F1 Score: 0.4224
ROC AUC: 0.7838
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's binary_logloss: 0.423709
Early stopping, best iteration is:
[967]	valid_0's binary_logloss: 0.423528
-------------------- Metrics --------------------
Accuracy: 0.4684
Precision: 0.2748
Recall: 0.9380
F1 Score: 0.4250
ROC AUC: 0.7838
Training final model using all data...
Final model training completed.

In [55]:
# オッズと人気を特徴量から省いたランク、日、クロスバリデーション
trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
    features_filename = "features_turf.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_only_tenkai_ex.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_ex_in3.pkl",
    final_num_boost_round = 1500
)

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.4997
[200]	valid_0's binary_logloss: 0.485182
[300]	valid_0's binary_logloss: 0.478464
[400]	valid_0's binary_logloss: 0.475034
[500]	valid_0's binary_logloss: 0.473106
[600]	valid_0's binary_logloss: 0.472037
[700]	valid_0's binary_logloss: 0.471385
[800]	valid_0's binary_logloss: 0.470938
[900]	valid_0's binary_logloss: 0.470842
Early stopping, best iteration is:
[839]	valid_0's binary_logloss: 0.4708
-------------------- Metrics --------------------
Accuracy: 0.3425
Precision: 0.2574
Recall: 0.9804
F1 Score: 0.4078
ROC AUC: 0.7452
Training fold 2/5...
Training until validation scores don't improve for 100 rounds
[900]	valid_0's binary_logloss: 0.482805
[1000]	valid_0's binary_logloss: 0.481661
[1100]	valid_0's binary_logloss: 0.481103
[1200]	valid_0's binary_logloss: 0.480758
[1300]	valid_0's binary_logloss: 0.48047
[1400]	valid_0's binary_logloss: 0.480211
[1500]	valid_0's binary_logloss: 0.480156
[1600]	valid_0's binary_logloss: 0.480052
Early stopping, best iteration is:
[1596]	valid_0's binary_logloss: 0.480025
-------------------- Metrics --------------------
Accuracy: 0.3606
Precision: 0.2635
Recall: 0.9747
F1 Score: 0.4148
ROC AUC: 0.7313
Training fold 3/5...
Training until validation scores don't improve for 100 rounds
[1600]	valid_0's binary_logloss: 0.467987
[1700]	valid_0's binary_logloss: 0.466641
[1800]	valid_0's binary_logloss: 0.466019
[1900]	valid_0's binary_logloss: 0.465728
[2000]	valid_0's binary_logloss: 0.465453
[2100]	valid_0's binary_logloss: 0.465388
[2200]	valid_0's binary_logloss: 0.465383
[2300]	valid_0's binary_logloss: 0.465298
Early stopping, best iteration is:
[2261]	valid_0's binary_logloss: 0.465224
-------------------- Metrics --------------------
Accuracy: 0.3605
Precision: 0.2622
Recall: 0.9780
F1 Score: 0.4136
ROC AUC: 0.7516
Training fold 4/5...
Training until validation scores don't improve for 100 rounds
[2300]	valid_0's binary_logloss: 0.469886
[2400]	valid_0's binary_logloss: 0.469447
[2500]	valid_0's binary_logloss: 0.469313
[2600]	valid_0's binary_logloss: 0.469263
[2700]	valid_0's binary_logloss: 0.469155
[2800]	valid_0's binary_logloss: 0.469044
[2900]	valid_0's binary_logloss: 0.468992
[3000]	valid_0's binary_logloss: 0.46895
[3100]	valid_0's binary_logloss: 0.468895
[3200]	valid_0's binary_logloss: 0.468926
Early stopping, best iteration is:
[3104]	valid_0's binary_logloss: 0.468888
-------------------- Metrics --------------------
Accuracy: 0.3793
Precision: 0.2661
Recall: 0.9704
F1 Score: 0.4177
ROC AUC: 0.7443
Training final model using all data...
Final model training completed.

In [ ]:
#ターフ、オンリー展開

In [56]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai,hitrate_pop,returnrate_pop
0,1,単勝,0.206084,0.969298,0.312211,0.774050
1,1,複勝,0.478200,0.937656,0.613066,0.820735
2,2,ワイド,0.187999,1.088112,0.303098,0.780191
3,2,単勝,0.364503,0.916949,0.508902,0.793383
4,2,複勝,0.716809,0.925382,0.829385,0.829230
5,2,馬単,0.076546,0.959807,0.150568,0.752643
6,2,馬連,0.076546,0.996832,0.150568,0.791098
7,3,ワイド,0.378803,1.033983,0.544932,0.792224
8,3,三連単,0.045703,1.148033,0.086920,0.635925
9,3,三連複,0.045703,1.260241,0.086920,0.748058
10,3,単勝,0.487032,0.894621,0.643067,0.789565
11,3,複勝,0.840039,0.903505,0.918267,0.819169
12,3,馬単,0.184354,0.949507,0.309267,0.747689
13,3,馬連,0.184354,0.988658,0.309267,0.778289
14,4,ワイド,0.553063,1.001166,0.709379,0.804900
15,4,三連単,0.122950,1.165033,0.224310,0.733082
16,4,三連複,0.122950,1.169501,0.224310,0.800060
17,4,単勝,0.588953,0.877485,0.739240,0.781554
18,4,複勝,0.908313,0.890250,0.961867,0.811987
19,4,馬単,0.307725,0.987348,0.455489,0.748449
20,4,馬連,0.307725,1.010701,0.455489,0.772293
21,5,ワイド,0.683583,0.961096,0.821954,0.796232
22,5,三連単,0.233422,1.044990,0.363802,0.732656
23,5,三連複,0.233422,1.031601,0.363802,0.777684
24,5,単勝,0.678256,0.866104,0.814524,0.788151
25,5,複勝,0.948409,0.880690,0.981214,0.804164
26,5,馬単,0.426609,0.934080,0.585308,0.757507
27,5,馬連,0.426609,0.956125,0.585308,0.774926

In [57]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin_only_tenkai.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai,hitrate_pop,returnrate_pop
0,1,単勝,0.245179,0.844876,0.352066,0.811928
1,1,複勝,0.546832,0.877273,0.677410,0.861460
2,2,ワイド,0.220386,0.868871,0.352066,0.822727
3,2,単勝,0.406336,0.828140,0.554270,0.816983
4,2,複勝,0.771350,0.863471,0.876309,0.857796
5,2,馬単,0.096970,0.959986,0.185675,0.872700
6,2,馬連,0.096970,1.031433,0.185675,0.900689
7,3,ワイド,0.427273,0.842626,0.607989,0.822443
8,3,三連単,0.056474,1.004490,0.105510,0.723186
9,3,三連複,0.056474,1.087934,0.105510,0.782204
10,3,単勝,0.535537,0.854995,0.687879,0.816006
11,3,複勝,0.881818,0.851515,0.946006,0.841653
12,3,馬単,0.218457,0.851336,0.366942,0.820826
13,3,馬連,0.218457,0.876878,0.366942,0.846033
14,4,ワイド,0.584573,0.846612,0.768320,0.832392
15,4,三連単,0.142700,0.860250,0.261983,0.792011
16,4,三連複,0.142700,0.913189,0.261983,0.845523
17,4,単勝,0.634160,0.850213,0.780441,0.812555
18,4,複勝,0.934160,0.831660,0.976309,0.831563
19,4,馬単,0.338017,0.789917,0.520110,0.808404
20,4,馬連,0.338017,0.804389,0.520110,0.822635
21,5,ワイド,0.714050,0.801818,0.863085,0.804466
22,5,三連単,0.234986,0.778261,0.407989,0.766662
23,5,三連複,0.234986,0.800645,0.407989,0.794237
24,5,単勝,0.706336,0.809989,0.849587,0.817609
25,5,複勝,0.962534,0.816044,0.991460,0.814198
26,5,馬単,0.442700,0.727431,0.643526,0.787114
27,5,馬連,0.442700,0.746331,0.643526,0.797118

In [58]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_noweight.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_noweight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_noweight,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.228796,0.890677,0.312211,0.774050
1,1,複勝,0.510585,0.907949,0.613066,0.820735
2,2,ワイド,0.201879,1.000028,0.303098,0.780191
3,2,単勝,0.396187,0.894813,0.508902,0.793383
4,2,複勝,0.748072,0.898682,0.829385,0.829230
5,2,馬単,0.085238,0.864454,0.150568,0.752643
6,2,馬連,0.085238,0.911524,0.150568,0.791098
7,3,ワイド,0.409786,0.982499,0.544932,0.792224
8,3,三連単,0.050610,1.116975,0.086920,0.635925
9,3,三連複,0.050610,1.159877,0.086920,0.748058
10,3,単勝,0.521800,0.891546,0.643067,0.789565
11,3,複勝,0.859246,0.888284,0.918267,0.819169
12,3,馬単,0.205524,0.923022,0.309267,0.747689
13,3,馬連,0.205524,0.947619,0.309267,0.778289
14,4,ワイド,0.572690,0.930852,0.709379,0.804900
15,4,三連単,0.135567,1.135947,0.224310,0.733082
16,4,三連複,0.135567,1.128179,0.224310,0.800060
17,4,単勝,0.621898,0.868239,0.739240,0.781554
18,4,複勝,0.926679,0.866732,0.961867,0.811987
19,4,馬単,0.322866,0.856200,0.455489,0.748449
20,4,馬連,0.322866,0.877230,0.455489,0.772293
21,5,ワイド,0.709379,0.914350,0.821954,0.796232
22,5,三連単,0.248002,0.972370,0.363802,0.732656
23,5,三連複,0.248002,0.986355,0.363802,0.777684
24,5,単勝,0.715407,0.880861,0.814524,0.788151
25,5,複勝,0.963550,0.861483,0.981214,0.804164
26,5,馬単,0.445254,0.869778,0.585308,0.757507
27,5,馬連,0.445254,0.880942,0.585308,0.774926

In [59]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_noweight.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin_only_tenkai_noweight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_noweight,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.252617,0.921185,0.352066,0.811928
1,1,複勝,0.551791,0.897410,0.677410,0.861460
2,2,ワイド,0.225620,0.880579,0.352066,0.822727
3,2,単勝,0.417355,0.883678,0.554270,0.816983
4,2,複勝,0.774656,0.874642,0.876309,0.857796
5,2,馬単,0.101102,0.936570,0.185675,0.872700
6,2,馬連,0.101102,0.962810,0.185675,0.900689
7,3,ワイド,0.419835,0.844784,0.607989,0.822443
8,3,三連単,0.054545,0.894224,0.105510,0.723186
9,3,三連複,0.054545,0.944931,0.105510,0.782204
10,3,単勝,0.529752,0.845106,0.687879,0.816006
11,3,複勝,0.878788,0.845528,0.946006,0.841653
12,3,馬単,0.215978,0.864284,0.366942,0.820826
13,3,馬連,0.215978,0.884169,0.366942,0.846033
14,4,ワイド,0.596419,0.824008,0.768320,0.832392
15,4,三連単,0.135813,0.839860,0.261983,0.792011
16,4,三連複,0.135813,0.872631,0.261983,0.845523
17,4,単勝,0.630303,0.826123,0.780441,0.812555
18,4,複勝,0.933609,0.830647,0.976309,0.831563
19,4,馬単,0.333333,0.791942,0.520110,0.808404
20,4,馬連,0.333333,0.808636,0.520110,0.822635
21,5,ワイド,0.717355,0.830399,0.863085,0.804466
22,5,三連単,0.239945,0.842718,0.407989,0.766662
23,5,三連複,0.239945,0.875339,0.407989,0.794237
24,5,単勝,0.707438,0.794138,0.849587,0.817609
25,5,複勝,0.966391,0.827642,0.991460,0.814198
26,5,馬単,0.445455,0.739730,0.643526,0.787114
27,5,馬連,0.445455,0.757854,0.643526,0.797118

In [60]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_weight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_weight,hitrate_pop,returnrate_pop
0,1,単勝,0.219696,0.828717,0.325557,0.817821
1,1,複勝,0.490625,0.898494,0.616270,0.841355
2,2,ワイド,0.171711,0.908578,0.286284,0.820537
3,2,単勝,0.369556,0.822553,0.507456,0.797483
4,2,複勝,0.713126,0.870759,0.822235,0.834136
5,2,馬単,0.073084,0.779374,0.141001,0.792263
6,2,馬連,0.073084,0.845386,0.141001,0.833279
7,3,ワイド,0.353758,0.934377,0.517644,0.822447
8,3,三連単,0.036468,1.044493,0.074708,0.713345
9,3,三連複,0.036468,1.165289,0.074708,0.833634
10,3,単勝,0.494759,0.826148,0.640189,0.797643
11,3,複勝,0.841134,0.861150,0.918205,0.826906
12,3,馬単,0.174074,0.878870,0.290861,0.763278
13,3,馬連,0.174074,0.912338,0.290861,0.793105
14,4,ワイド,0.516019,0.907414,0.676805,0.793400
15,4,三連単,0.103056,0.891686,0.184704,0.697709
16,4,三連複,0.103056,0.958789,0.184704,0.774240
17,4,単勝,0.589547,0.804570,0.730105,0.776085
18,4,複勝,0.910084,0.847346,0.957183,0.802735
19,4,馬単,0.279344,0.836873,0.426547,0.747495
20,4,馬連,0.279344,0.869162,0.426547,0.772048
21,5,ワイド,0.647719,0.868376,0.795512,0.802652
22,5,三連単,0.186771,0.880553,0.316846,0.734386
23,5,三連複,0.186771,0.968609,0.316846,0.790759
24,5,単勝,0.664698,0.775999,0.805699,0.783768
25,5,複勝,0.948915,0.835895,0.981692,0.801364
26,5,馬単,0.379448,0.778318,0.554998,0.758900
27,5,馬連,0.379448,0.809305,0.554998,0.779848

In [61]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai,hitrate_pop,returnrate_pop
0,1,単勝,0.234903,0.830297,0.325557,0.817821
1,1,複勝,0.506423,0.880452,0.616270,0.841355
2,2,ワイド,0.189429,0.937236,0.286284,0.820537
3,2,単勝,0.391407,0.818507,0.507456,0.797483
4,2,複勝,0.737635,0.869401,0.822235,0.834136
5,2,馬単,0.084748,0.834113,0.141001,0.792263
6,2,馬連,0.084748,0.886963,0.141001,0.833279
7,3,ワイド,0.379005,0.920784,0.517644,0.822447
8,3,三連単,0.040159,1.097195,0.074708,0.713345
9,3,三連複,0.040159,1.198834,0.074708,0.833634
10,3,単勝,0.517496,0.825198,0.640189,0.797643
11,3,複勝,0.859442,0.862444,0.918205,0.826906
12,3,馬単,0.190314,0.846486,0.290861,0.763278
13,3,馬連,0.190314,0.886003,0.290861,0.793105
14,4,ワイド,0.552340,0.934812,0.676805,0.793400
15,4,三連単,0.109405,0.876298,0.184704,0.697709
16,4,三連複,0.109405,0.980932,0.184704,0.774240
17,4,単勝,0.615237,0.815628,0.730105,0.776085
18,4,複勝,0.921748,0.861295,0.957183,0.802735
19,4,馬単,0.300901,0.902632,0.426547,0.747495
20,4,馬連,0.300901,0.914646,0.426547,0.772048
21,5,ワイド,0.683597,0.909886,0.795512,0.802652
22,5,三連単,0.208770,0.864339,0.316846,0.734386
23,5,三連複,0.208770,0.920840,0.316846,0.790759
24,5,単勝,0.697032,0.807663,0.805699,0.783768
25,5,複勝,0.953639,0.849083,0.981692,0.801364
26,5,馬単,0.418574,0.879271,0.554998,0.758900
27,5,馬連,0.418574,0.898222,0.554998,0.779848

In [62]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nowin_only_tenkai.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nowin_only_tenkai")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nowin_only_tenkai,returnrate_lightgbm_rank_niti_cross_dev_dirt_nowin_only_tenkai,hitrate_pop,returnrate_pop
0,1,単勝,0.258962,0.794705,0.343222,0.758096
1,1,複勝,0.583642,0.868747,0.686856,0.853894
2,2,ワイド,0.254017,0.869118,0.345900,0.799794
3,2,単勝,0.433251,0.824681,0.546972,0.790132
4,2,複勝,0.799341,0.859034,0.883395,0.853234
5,2,馬単,0.116811,0.847445,0.164813,0.727204
6,2,馬連,0.116811,0.885332,0.164813,0.750082
7,3,ワイド,0.469716,0.877606,0.608982,0.836362
8,3,三連単,0.065925,0.875158,0.105274,0.751480
9,3,三連複,0.065925,0.977050,0.105274,0.817491
10,3,単勝,0.555212,0.788875,0.681500,0.796518
11,3,複勝,0.902555,0.853763,0.951792,0.845653
12,3,馬単,0.247013,0.772418,0.353935,0.792388
13,3,馬連,0.247013,0.805768,0.353935,0.817079
14,4,ワイド,0.637824,0.853334,0.769262,0.827572
15,4,三連単,0.152040,0.879068,0.254429,0.777640
16,4,三連複,0.152040,0.959523,0.254429,0.818505
17,4,単勝,0.653688,0.779769,0.778945,0.807746
18,4,複勝,0.950556,0.846003,0.981871,0.832339
19,4,馬単,0.361557,0.756551,0.509271,0.785121
20,4,馬連,0.361557,0.783320,0.509271,0.799224
21,5,ワイド,0.762670,0.814291,0.863618,0.797501
22,5,三連単,0.257520,0.784225,0.398640,0.723714
23,5,三連複,0.257520,0.830950,0.398640,0.760987
24,5,単勝,0.730119,0.760952,0.840544,0.786918
25,5,複勝,0.975278,0.834442,0.992171,0.813370
26,5,馬単,0.478368,0.735865,0.626494,0.745463
27,5,馬連,0.478368,0.760212,0.626494,0.758712

In [63]:
# # オッズと人気を特徴量から省いたランク、日、クロスバリデーション
# trainer_in3 = Trainer_lightgbm_rank_niti_cv_in3(
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_niti_dev_turf.yaml",
# )
# evaluation_df = trainer_in3.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_in3",
#     model_filename="model_lightgbm_rank_niti_cv_dev_turf_in3.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_in3.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_in3.pkl",
#     final_num_boost_round = 1500
# )

In [ ]:
%autoreload

In [ ]:
# # オッズと人気を特徴量から省いたランク、芝、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_niti_dev_dirt.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_in3",
#     model_filename="model_lightgbm_rank_niti_cv_dev_dirt_in3.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_in3.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_in3.pkl",
#     final_num_boost_round = 1500
# )

In [ ]:

trainer = Trainer_lightgbm_rank_niti_cv_in3(
    features_filename = "features_turf_nowin.csv", 
    config_filepath="config_lightgbm_niti_dev_turf_nowin.yaml",
)
evaluation_df = trainer.run(
    n_splits = 5,
    importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_nowin_in3",
    model_filename="model_lightgbm_rank_niti_cv_dev_turf_nowin_in3.pkl",
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_in3.csv",
    final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_nowin_in3.pkl"
)

In [ ]:
# # オッズと人気を特徴量から省いたランク、回帰、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv_in3(
#     features_filename = "features_dirt_nowin.csv", 
#     config_filepath="config_lightgbm_niti_dev_dirt_nowin.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_nowin_in3",
#     model_filename="model_lightgbm_rank_niti_cv_dev_dirt_nowin_in3.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_in3.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_nowin_in3.pkl"
# )

In [ ]:
# # オッズと人気を特徴量から省いたランク、日、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
#     features_filename = "features_dirt.csv", 
#     config_filepath="config_lightgbm_niti_dev_dirt_only_tenkai.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3",
#     model_filename="model_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_dirt_only_tenkai_in3.pkl",
#     final_num_boost_round = 1400
# )

In [ ]:
# # オッズと人気を特徴量から省いたランク、日、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_niti_dev_turf_only_tenkai.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3",
#     model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_in3.pkl",
#     final_num_boost_round = 1500
# )

In [ ]:
%autoreload

In [ ]:
#評価

In [64]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf,returnrate_lightgbm_rank_niti_cross_dev_turf,hitrate_pop,returnrate_pop
0,1,単勝,0.267069,0.860606,0.312211,0.774050
1,1,複勝,0.579420,0.895107,0.613066,0.820735
2,2,ワイド,0.266227,0.943684,0.303098,0.780191
3,2,単勝,0.446236,0.863746,0.508902,0.793383
4,2,複勝,0.798121,0.888301,0.829385,0.829230
5,2,馬単,0.120566,0.899026,0.150568,0.752643
6,2,馬連,0.120566,0.932567,0.150568,0.791098
7,3,ワイド,0.493761,0.939535,0.544932,0.792224
8,3,三連単,0.075424,0.904355,0.086920,0.635925
9,3,三連複,0.075424,1.011846,0.086920,0.748058
10,3,単勝,0.578719,0.841133,0.643067,0.789565
11,3,複勝,0.901865,0.878490,0.918267,0.819169
12,3,馬単,0.264124,0.892130,0.309267,0.747689
13,3,馬連,0.264124,0.926791,0.309267,0.778289
14,4,ワイド,0.662134,0.901902,0.709379,0.804900
15,4,三連単,0.182392,0.891825,0.224310,0.733082
16,4,三連複,0.182392,0.951223,0.224310,0.800060
17,4,単勝,0.681480,0.837547,0.739240,0.781554
18,4,複勝,0.950231,0.860557,0.961867,0.811987
19,4,馬単,0.392261,0.849874,0.455489,0.748449
20,4,馬連,0.392261,0.878826,0.455489,0.772293
21,5,ワイド,0.783401,0.913857,0.821954,0.796232
22,5,三連単,0.317959,0.938338,0.363802,0.732656
23,5,三連複,0.317959,0.978986,0.363802,0.777684
24,5,単勝,0.762092,0.834448,0.814524,0.788151
25,5,複勝,0.975606,0.857289,0.981214,0.804164
26,5,馬単,0.521800,0.868332,0.585308,0.757507
27,5,馬連,0.521800,0.891947,0.585308,0.774926

In [65]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_noweight_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_noweight_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_noweight,returnrate_lightgbm_rank_niti_cross_dev_turf_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.265246,0.839100,0.312211,0.774050
1,1,複勝,0.576616,0.884481,0.613066,0.820735
2,2,ワイド,0.263003,0.920777,0.303098,0.780191
3,2,単勝,0.441469,0.861832,0.508902,0.793383
4,2,複勝,0.794196,0.881375,0.829385,0.829230
5,2,馬単,0.115239,0.875733,0.150568,0.752643
6,2,馬連,0.115239,0.912645,0.150568,0.791098
7,3,ワイド,0.492920,0.940511,0.544932,0.792224
8,3,三連単,0.074303,0.908891,0.086920,0.635925
9,3,三連複,0.074303,0.991574,0.086920,0.748058
10,3,単勝,0.575214,0.844147,0.643067,0.789565
11,3,複勝,0.900603,0.878663,0.918267,0.819169
12,3,馬単,0.264405,0.918363,0.309267,0.747689
13,3,馬連,0.264405,0.942661,0.309267,0.778289
14,4,ワイド,0.665358,0.917344,0.709379,0.804900
15,4,三連単,0.182532,0.880552,0.224310,0.733082
16,4,三連複,0.182532,0.950799,0.224310,0.800060
17,4,単勝,0.678396,0.843085,0.739240,0.781554
18,4,複勝,0.950792,0.868737,0.961867,0.811987
19,4,馬単,0.391841,0.865384,0.455489,0.748449
20,4,馬連,0.391841,0.888198,0.455489,0.772293
21,5,ワイド,0.783401,0.914604,0.821954,0.796232
22,5,三連単,0.314594,0.925034,0.363802,0.732656
23,5,三連複,0.314594,0.983194,0.363802,0.777684
24,5,単勝,0.759007,0.838870,0.814524,0.788151
25,5,複勝,0.975326,0.858371,0.981214,0.804164
26,5,馬単,0.518155,0.865939,0.585308,0.757507
27,5,馬連,0.518155,0.886206,0.585308,0.774926

In [66]:
%autoreload

In [67]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_in3.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt,returnrate_lightgbm_rank_niti_cross_dev_dirt,hitrate_pop,returnrate_pop
0,1,単勝,0.273734,0.876775,0.325557,0.817821
1,1,複勝,0.581279,0.889665,0.616270,0.841355
2,2,ワイド,0.240366,0.887406,0.286284,0.820537
3,2,単勝,0.445150,0.848679,0.507456,0.797483
4,2,複勝,0.794035,0.869076,0.822235,0.834136
5,2,馬単,0.107486,0.822317,0.141001,0.792263
6,2,馬連,0.107486,0.862469,0.141001,0.833279
7,3,ワイド,0.456519,0.909784,0.517644,0.822447
8,3,三連単,0.058763,0.893039,0.074708,0.713345
9,3,三連複,0.058763,0.962203,0.074708,0.833634
10,3,単勝,0.569615,0.839367,0.640189,0.797643
11,3,複勝,0.895024,0.860835,0.918205,0.826906
12,3,馬単,0.229883,0.785769,0.290861,0.763278
13,3,馬連,0.229883,0.812506,0.290861,0.793105
14,4,ワイド,0.622619,0.896395,0.676805,0.793400
15,4,三連単,0.154584,0.872614,0.184704,0.697709
16,4,三連複,0.154584,0.954337,0.184704,0.774240
17,4,単勝,0.664846,0.822099,0.730105,0.776085
18,4,複勝,0.943009,0.846545,0.957183,0.802735
19,4,馬単,0.359368,0.819620,0.426547,0.747495
20,4,馬連,0.359368,0.837546,0.426547,0.772048
21,5,ワイド,0.747527,0.866030,0.795512,0.802652
22,5,三連単,0.263842,0.811904,0.316846,0.734386
23,5,三連複,0.263842,0.856845,0.316846,0.790759
24,5,単勝,0.742507,0.818252,0.805699,0.783768
25,5,複勝,0.971505,0.839513,0.981692,0.801364
26,5,馬単,0.477336,0.808033,0.554998,0.758900
27,5,馬連,0.477336,0.819226,0.554998,0.779848

In [68]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight_in3.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt,returnrate_lightgbm_rank_niti_cross_dev_dirt,hitrate_pop,returnrate_pop
0,1,単勝,0.270043,0.854230,0.325557,0.817821
1,1,複勝,0.577145,0.890787,0.616270,0.841355
2,2,ワイド,0.236823,0.868935,0.286284,0.820537
3,2,単勝,0.440573,0.838816,0.507456,0.797483
4,2,複勝,0.791820,0.865097,0.822235,0.834136
5,2,馬単,0.108371,0.823431,0.141001,0.792263
6,2,馬連,0.108371,0.859560,0.141001,0.833279
7,3,ワイド,0.454747,0.899700,0.517644,0.822447
8,3,三連単,0.059501,0.830339,0.074708,0.713345
9,3,三連複,0.059501,0.941119,0.074708,0.833634
10,3,単勝,0.565481,0.828564,0.640189,0.797643
11,3,複勝,0.892957,0.856755,0.918205,0.826906
12,3,馬単,0.232836,0.807759,0.290861,0.763278
13,3,馬連,0.232836,0.828894,0.290861,0.793105
14,4,ワイド,0.622472,0.884955,0.676805,0.793400
15,4,三連単,0.151336,0.824668,0.184704,0.697709
16,4,三連複,0.151336,0.922379,0.184704,0.774240
17,4,単勝,0.662631,0.820316,0.730105,0.776085
18,4,複勝,0.944190,0.847911,0.957183,0.802735
19,4,馬単,0.357892,0.823827,0.426547,0.747495
20,4,馬連,0.357892,0.842795,0.426547,0.772048
21,5,ワイド,0.741769,0.850943,0.795512,0.802652
22,5,三連単,0.257493,0.790690,0.316846,0.734386
23,5,三連複,0.257493,0.837492,0.316846,0.790759
24,5,単勝,0.740588,0.812878,0.805699,0.783768
25,5,複勝,0.971505,0.832263,0.981692,0.801364
26,5,馬単,0.477041,0.812664,0.554998,0.758900
27,5,馬連,0.477041,0.828992,0.554998,0.779848

In [69]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_noweight_in3.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_obstract_noweight_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_obstract_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_obstract_noweight,returnrate_lightgbm_rank_niti_cross_dev_obstract_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.340314,1.156021,0.369110,0.832723
1,1,複勝,0.678010,1.020419,0.697644,0.881414
2,2,ワイド,0.352094,1.249476,0.362565,0.862042
3,2,単勝,0.539267,1.042932,0.577225,0.851767
4,2,複勝,0.878272,0.984751,0.884817,0.876702
5,2,馬単,0.159686,1.232068,0.187173,0.963154
6,2,馬連,0.159686,1.284817,0.187173,0.977487
7,3,ワイド,0.600785,1.172513,0.623037,0.877312
8,3,三連単,0.103403,1.651658,0.106021,0.768695
9,3,三連複,0.103403,1.966230,0.106021,0.957592
10,3,単勝,0.668848,0.979319,0.695026,0.807373
11,3,複勝,0.952880,0.964834,0.956806,0.857330
12,3,馬単,0.325916,1.090140,0.353403,0.835013
13,3,馬連,0.325916,1.152487,0.353403,0.862086
14,4,ワイド,0.756545,1.195528,0.768325,0.877989
15,4,三連単,0.253927,1.547775,0.265707,0.893919
16,4,三連複,0.253927,1.712369,0.265707,0.995550
17,4,単勝,0.761780,0.972971,0.787958,0.803829
18,4,複勝,0.976440,0.958639,0.986911,0.839823
19,4,馬単,0.472513,1.059555,0.511780,0.827978
20,4,馬連,0.472513,1.097186,0.511780,0.858181
21,5,ワイド,0.852094,1.079529,0.888743,0.902029
22,5,三連単,0.412304,1.209891,0.442408,0.905366
23,5,三連複,0.412304,1.240445,0.442408,0.952984
24,5,単勝,0.820681,0.924764,0.857330,0.829136
25,5,複勝,0.993455,0.925838,0.994764,0.854817
26,5,馬単,0.592932,0.950785,0.655759,0.839791
27,5,馬連,0.592932,0.968783,0.655759,0.855157

In [70]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_in3.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_obstract_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_obstract")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_obstract,returnrate_lightgbm_rank_niti_cross_dev_obstract,hitrate_pop,returnrate_pop
0,1,単勝,0.345550,1.154712,0.369110,0.832723
1,1,複勝,0.685864,1.036387,0.697644,0.881414
2,2,ワイド,0.337696,1.207853,0.362565,0.862042
3,2,単勝,0.524869,1.033704,0.577225,0.851767
4,2,複勝,0.882199,0.988220,0.884817,0.876702
5,2,馬単,0.142670,1.101571,0.187173,0.963154
6,2,馬連,0.142670,1.144634,0.187173,0.977487
7,3,ワイド,0.607330,1.212827,0.623037,0.877312
8,3,三連単,0.096859,1.273778,0.106021,0.768695
9,3,三連複,0.096859,1.578665,0.106021,0.957592
10,3,単勝,0.670157,1.012435,0.695026,0.807373
11,3,複勝,0.954188,0.974302,0.956806,0.857330
12,3,馬単,0.329843,1.132657,0.353403,0.835013
13,3,馬連,0.329843,1.164005,0.353403,0.862086
14,4,ワイド,0.765707,1.220615,0.768325,0.877989
15,4,三連単,0.260471,1.582095,0.265707,0.893919
16,4,三連複,0.260471,1.754876,0.265707,0.995550
17,4,単勝,0.767016,0.989562,0.787958,0.803829
18,4,複勝,0.977749,0.970419,0.986911,0.839823
19,4,馬単,0.476440,1.046586,0.511780,0.827978
20,4,馬連,0.476440,1.074629,0.511780,0.858181
21,5,ワイド,0.865183,1.091086,0.888743,0.902029
22,5,三連単,0.412304,1.242090,0.442408,0.905366
23,5,三連複,0.412304,1.292251,0.442408,0.952984
24,5,単勝,0.827225,0.930681,0.857330,0.829136
25,5,複勝,0.990838,0.937565,0.994764,0.854817
26,5,馬単,0.606021,1.003809,0.655759,0.839791
27,5,馬連,0.606021,1.020510,0.655759,0.855157

In [71]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_in3.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin,hitrate_pop,returnrate_pop
0,1,単勝,0.295317,0.849201,0.352066,0.811928
1,1,複勝,0.623967,0.876501,0.677410,0.861460
2,2,ワイド,0.292562,0.902259,0.352066,0.822727
3,2,単勝,0.471901,0.821928,0.554270,0.816983
4,2,複勝,0.836915,0.866612,0.876309,0.857796
5,2,馬単,0.134711,0.849215,0.185675,0.872700
6,2,馬連,0.134711,0.897631,0.185675,0.900689
7,3,ワイド,0.531405,0.877658,0.607989,0.822443
8,3,三連単,0.078788,1.069986,0.105510,0.723186
9,3,三連複,0.078788,1.041873,0.105510,0.782204
10,3,単勝,0.607438,0.831570,0.687879,0.816006
11,3,複勝,0.928099,0.868825,0.946006,0.841653
12,3,馬単,0.284022,0.849591,0.366942,0.820826
13,3,馬連,0.284022,0.869752,0.366942,0.846033
14,4,ワイド,0.692837,0.873701,0.768320,0.832392
15,4,三連単,0.200826,0.946694,0.261983,0.792011
16,4,三連複,0.200826,0.983933,0.261983,0.845523
17,4,単勝,0.704132,0.811618,0.780441,0.812555
18,4,複勝,0.967493,0.850868,0.976309,0.831563
19,4,馬単,0.423691,0.817881,0.520110,0.808404
20,4,馬連,0.423691,0.840624,0.520110,0.822635
21,5,ワイド,0.805510,0.859138,0.863085,0.804466
22,5,三連単,0.325069,1.017837,0.407989,0.766662
23,5,三連複,0.325069,0.999948,0.407989,0.794237
24,5,単勝,0.779614,0.839989,0.849587,0.817609
25,5,複勝,0.982645,0.845047,0.991460,0.814198
26,5,馬単,0.549036,0.828625,0.643526,0.787114
27,5,馬連,0.549036,0.841394,0.643526,0.797118

In [72]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_noweight_in3.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin_noweight_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin_noweight,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.296419,0.859642,0.352066,0.811928
1,1,複勝,0.625069,0.885344,0.677410,0.861460
2,2,ワイド,0.284298,0.891983,0.352066,0.822727
3,2,単勝,0.473003,0.851543,0.554270,0.816983
4,2,複勝,0.829752,0.865744,0.876309,0.857796
5,2,馬単,0.130303,0.844614,0.185675,0.872700
6,2,馬連,0.130303,0.880000,0.185675,0.900689
7,3,ワイド,0.520937,0.872360,0.607989,0.822443
8,3,三連単,0.079890,1.032332,0.105510,0.723186
9,3,三連複,0.079890,1.062176,0.105510,0.782204
10,3,単勝,0.600551,0.836483,0.687879,0.816006
11,3,複勝,0.923967,0.858871,0.946006,0.841653
12,3,馬単,0.280992,0.874224,0.366942,0.820826
13,3,馬連,0.280992,0.880937,0.366942,0.846033
14,4,ワイド,0.684573,0.856997,0.768320,0.832392
15,4,三連単,0.195868,0.861567,0.261983,0.792011
16,4,三連複,0.195868,0.884676,0.261983,0.845523
17,4,単勝,0.699449,0.809848,0.780441,0.812555
18,4,複勝,0.964187,0.846825,0.976309,0.831563
19,4,馬単,0.422590,0.843595,0.520110,0.808404
20,4,馬連,0.422590,0.849155,0.520110,0.822635
21,5,ワイド,0.797796,0.844242,0.863085,0.804466
22,5,三連単,0.315427,0.982598,0.407989,0.766662
23,5,三連複,0.315427,0.962747,0.407989,0.794237
24,5,単勝,0.768595,0.819824,0.849587,0.817609
25,5,複勝,0.982094,0.834160,0.991460,0.814198
26,5,馬単,0.536364,0.803011,0.643526,0.787114
27,5,馬連,0.536364,0.812917,0.643526,0.797118

In [73]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight_in3.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nowin_noweight_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nowin_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nowin_noweight,returnrate_lightgbm_rank_niti_cross_dev_dirt_nowin_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.294190,0.764916,0.343222,0.758096
1,1,複勝,0.648537,0.862093,0.686856,0.853894
2,2,ワイド,0.313968,0.872703,0.345900,0.799794
3,2,単勝,0.487639,0.847476,0.546972,0.790132
4,2,複勝,0.847342,0.870313,0.883395,0.853234
5,2,馬単,0.145447,0.803863,0.164813,0.727204
6,2,馬連,0.145447,0.833519,0.164813,0.750082
7,3,ワイド,0.548002,0.858811,0.608982,0.836362
8,3,三連単,0.084260,0.769795,0.105274,0.751480
9,3,三連複,0.084260,0.809415,0.105274,0.817491
10,3,単勝,0.614133,0.835236,0.681500,0.796518
11,3,複勝,0.931809,0.860308,0.951792,0.845653
12,3,馬単,0.294602,0.783687,0.353935,0.792388
13,3,馬連,0.294602,0.809106,0.353935,0.817079
14,4,ワイド,0.714256,0.869053,0.769262,0.827572
15,4,三連単,0.199629,0.805299,0.254429,0.777640
16,4,三連複,0.199629,0.879151,0.254429,0.818505
17,4,単勝,0.708694,0.831443,0.778945,0.807746
18,4,複勝,0.964565,0.857185,0.981871,0.832339
19,4,馬単,0.429543,0.754575,0.509271,0.785121
20,4,馬連,0.429543,0.773397,0.509271,0.799224
21,5,ワイド,0.821590,0.852491,0.863618,0.797501
22,5,三連単,0.324063,0.832107,0.398640,0.723714
23,5,三連複,0.324063,0.885744,0.398640,0.760987
24,5,単勝,0.779151,0.812382,0.840544,0.786918
25,5,複勝,0.984343,0.850181,0.992171,0.813370
26,5,馬単,0.548414,0.779526,0.626494,0.745463
27,5,馬連,0.548414,0.799149,0.626494,0.758712

In [74]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_in3.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nowin_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nowin")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nowin,returnrate_lightgbm_rank_niti_cross_dev_dirt_nowin,hitrate_pop,returnrate_pop
0,1,単勝,0.291512,0.814318,0.343222,0.758096
1,1,複勝,0.643387,0.893511,0.686856,0.853894
2,2,ワイド,0.311908,0.915575,0.345900,0.799794
3,2,単勝,0.479192,0.845993,0.546972,0.790132
4,2,複勝,0.838072,0.880552,0.883395,0.853234
5,2,馬単,0.145241,0.856675,0.164813,0.727204
6,2,馬連,0.145241,0.895179,0.164813,0.750082
7,3,ワイド,0.540997,0.884528,0.608982,0.836362
8,3,三連単,0.081376,0.833969,0.105274,0.751480
9,3,三連複,0.081376,0.895756,0.105274,0.817491
10,3,単勝,0.608982,0.848929,0.681500,0.796518
11,3,複勝,0.928719,0.868205,0.951792,0.845653
12,3,馬単,0.288628,0.780507,0.353935,0.792388
13,3,馬連,0.288628,0.804525,0.353935,0.817079
14,4,ワイド,0.714668,0.890073,0.769262,0.827572
15,4,三連単,0.196539,0.859782,0.254429,0.777640
16,4,三連複,0.196539,0.947162,0.254429,0.818505
17,4,単勝,0.707046,0.841878,0.778945,0.807746
18,4,複勝,0.965389,0.867506,0.981871,0.832339
19,4,馬単,0.423774,0.772339,0.509271,0.785121
20,4,馬連,0.423774,0.802723,0.509271,0.799224
21,5,ワイド,0.816646,0.875766,0.863618,0.797501
22,5,三連単,0.329831,0.892607,0.398640,0.723714
23,5,三連複,0.329831,0.937456,0.398640,0.760987
24,5,単勝,0.777709,0.826873,0.840544,0.786918
25,5,複勝,0.985167,0.860791,0.992171,0.813370
26,5,馬単,0.542851,0.789170,0.626494,0.745463
27,5,馬連,0.542851,0.813727,0.626494,0.758712

In [98]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_only_tenkai_in3.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai")
# summary_df_shaft

KeyboardInterrupt:

In [178]:
%autoreload

In [179]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.220339,0.790395,0.319209,0.716667
1,1,複勝,0.533898,0.897175,0.618644,0.772316
2,2,ワイド,0.257062,0.918079,0.387006,0.826271
3,2,単勝,0.395480,0.770056,0.564972,0.823729
4,2,複勝,0.776836,0.887288,0.878531,0.870339
5,2,馬単,0.087571,0.621469,0.175141,0.722881
6,2,馬連,0.087571,0.637006,0.175141,0.754237
7,3,ワイド,0.463277,0.896893,0.641243,0.863089
8,3,三連単,0.059322,0.936582,0.135593,0.863136
9,3,三連複,0.059322,0.935028,0.135593,0.926554
10,3,単勝,0.531073,0.799058,0.706215,0.808380
11,3,複勝,0.898305,0.864030,0.949153,0.862806
12,3,馬単,0.214689,0.666667,0.370056,0.849718
13,3,馬連,0.214689,0.714124,0.370056,0.877966
14,4,ワイド,0.666667,0.943503,0.807910,0.823635
15,4,三連単,0.194915,0.889925,0.293785,0.747999
16,4,三連複,0.194915,0.891102,0.293785,0.782203
17,4,単勝,0.649718,0.826412,0.802260,0.795833
18,4,複勝,0.963277,0.879237,0.977401,0.831427
19,4,馬単,0.358757,0.846540,0.519774,0.760617
20,4,馬連,0.358757,0.883286,0.519774,0.791667
21,5,ワイド,0.816384,0.902599,0.898305,0.807910
22,5,三連単,0.333333,0.748842,0.480226,0.731332
23,5,三連複,0.333333,0.759520,0.480226,0.771441
24,5,単勝,0.745763,0.788983,0.867232,0.780678
25,5,複勝,0.988701,0.868249,0.988701,0.823446
26,5,馬単,0.519774,0.829915,0.669492,0.756751
27,5,馬連,0.519774,0.888333,0.669492,0.784915

In [76]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross_in3(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.235051,0.847881,0.325557,0.817821
1,1,複勝,0.519268,0.888971,0.616270,0.841355
2,2,ワイド,0.197992,0.937517,0.286284,0.820537
3,2,単勝,0.394951,0.823859,0.507456,0.797483
4,2,複勝,0.744426,0.875816,0.822235,0.834136
5,2,馬単,0.083715,0.828975,0.141001,0.792263
6,2,馬連,0.083715,0.886653,0.141001,0.833279
7,3,ワイド,0.394803,0.896166,0.517644,0.822447
8,3,三連単,0.041341,0.829559,0.074708,0.713345
9,3,三連複,0.041341,0.934283,0.074708,0.833634
10,3,単勝,0.520154,0.828299,0.640189,0.797643
11,3,複勝,0.864314,0.867469,0.918205,0.826906
12,3,馬単,0.195925,0.859877,0.290861,0.763278
13,3,馬連,0.195925,0.893700,0.290861,0.793105
14,4,ワイド,0.567695,0.937800,0.676805,0.793400
15,4,三連単,0.120626,0.915241,0.184704,0.697709
16,4,三連複,0.120626,1.002248,0.184704,0.774240
17,4,単勝,0.614646,0.810985,0.730105,0.776085
18,4,複勝,0.923225,0.866562,0.957183,0.802735
19,4,馬単,0.311826,0.864259,0.426547,0.747495
20,4,馬連,0.311826,0.892054,0.426547,0.772048
21,5,ワイド,0.693341,0.907998,0.795512,0.802652
22,5,三連単,0.219843,0.918575,0.316846,0.734386
23,5,三連複,0.219843,0.954838,0.316846,0.790759
24,5,単勝,0.693932,0.806177,0.805699,0.783768
25,5,複勝,0.958512,0.854209,0.981692,0.801364
26,5,馬単,0.424480,0.855547,0.554998,0.758900
27,5,馬連,0.424480,0.882539,0.554998,0.779848

In [77]:
%autoreload

In [78]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross_in3(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.250964,0.888127,0.352066,0.811928
1,1,複勝,0.558953,0.880303,0.677410,0.861460
2,2,ワイド,0.238567,0.962259,0.352066,0.822727
3,2,単勝,0.419284,0.865537,0.554270,0.816983
4,2,複勝,0.775758,0.865152,0.876309,0.857796
5,2,馬単,0.101102,0.860937,0.185675,0.872700
6,2,馬連,0.101102,0.906143,0.185675,0.900689
7,3,ワイド,0.455647,0.918494,0.607989,0.822443
8,3,三連単,0.061708,1.303990,0.105510,0.723186
9,3,三連複,0.061708,1.230882,0.105510,0.782204
10,3,単勝,0.550138,0.842617,0.687879,0.816006
11,3,複勝,0.884848,0.868540,0.946006,0.841653
12,3,馬単,0.235537,0.857342,0.366942,0.820826
13,3,馬連,0.235537,0.906905,0.366942,0.846033
14,4,ワイド,0.620110,0.864013,0.768320,0.832392
15,4,三連単,0.151240,0.901119,0.261983,0.792011
16,4,三連複,0.151240,0.902149,0.261983,0.845523
17,4,単勝,0.646281,0.808795,0.780441,0.812555
18,4,複勝,0.940771,0.843492,0.976309,0.831563
19,4,馬単,0.358953,0.834258,0.520110,0.808404
20,4,馬連,0.358953,0.870202,0.520110,0.822635
21,5,ワイド,0.743251,0.885336,0.863085,0.804466
22,5,三連単,0.254545,1.091803,0.407989,0.766662
23,5,三連複,0.254545,1.118482,0.407989,0.794237
24,5,単勝,0.715152,0.789466,0.849587,0.817609
25,5,複勝,0.967769,0.841218,0.991460,0.814198
26,5,馬単,0.471625,0.809620,0.643526,0.787114
27,5,馬連,0.471625,0.841780,0.643526,0.797118

In [79]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross_in3(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.261228,0.780614,0.343222,0.758096
1,1,複勝,0.602184,0.879316,0.686856,0.853894
2,2,ワイド,0.268438,0.860754,0.345900,0.799794
3,2,単勝,0.435517,0.786825,0.546972,0.790132
4,2,複勝,0.823239,0.879934,0.883395,0.853234
5,2,馬単,0.121343,0.852822,0.164813,0.727204
6,2,馬連,0.121343,0.897837,0.164813,0.750082
7,3,ワイド,0.491759,0.881575,0.608982,0.836362
8,3,三連単,0.069427,0.893717,0.105274,0.751480
9,3,三連複,0.069427,0.955789,0.105274,0.817491
10,3,単勝,0.563659,0.783855,0.681500,0.796518
11,3,複勝,0.914297,0.872099,0.951792,0.845653
12,3,馬単,0.254429,0.790056,0.353935,0.792388
13,3,馬連,0.254429,0.822456,0.353935,0.817079
14,4,ワイド,0.659044,0.865293,0.769262,0.827572
15,4,三連単,0.165019,0.896028,0.254429,0.777640
16,4,三連複,0.165019,0.966327,0.254429,0.818505
17,4,単勝,0.661310,0.796565,0.778945,0.807746
18,4,複勝,0.956119,0.855593,0.981871,0.832339
19,4,馬単,0.377833,0.760368,0.509271,0.785121
20,4,馬連,0.377833,0.782770,0.509271,0.799224
21,5,ワイド,0.781211,0.831108,0.863618,0.797501
22,5,三連単,0.273589,0.837278,0.398640,0.723714
23,5,三連複,0.273589,0.864001,0.398640,0.760987
24,5,単勝,0.730532,0.760552,0.840544,0.786918
25,5,複勝,0.977338,0.842208,0.992171,0.813370
26,5,馬単,0.485373,0.753536,0.626494,0.745463
27,5,馬連,0.485373,0.774539,0.626494,0.758712

In [80]:
%autoreload

In [81]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross_in3(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_only_tenkai_weight_in3.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.221911,0.846656,0.325557,0.817821
1,1,複勝,0.497712,0.892175,0.616270,0.841355
2,2,ワイド,0.185737,1.021423,0.286284,0.820537
3,2,単勝,0.368817,0.812018,0.507456,0.797483
4,2,複勝,0.723166,0.889990,0.822235,0.834136
5,2,馬単,0.075742,0.920596,0.141001,0.792263
6,2,馬連,0.075742,0.979404,0.141001,0.833279
7,3,ワイド,0.376938,0.980329,0.517644,0.822447
8,3,三連単,0.040307,1.163298,0.074708,0.713345
9,3,三連複,0.040307,1.315237,0.074708,0.833634
10,3,単勝,0.494611,0.805109,0.640189,0.797643
11,3,複勝,0.850140,0.878080,0.918205,0.826906
12,3,馬単,0.184556,0.906831,0.290861,0.763278
13,3,馬連,0.184556,0.951302,0.290861,0.793105
14,4,ワイド,0.537871,0.956218,0.676805,0.793400
15,4,三連単,0.115606,1.039577,0.184704,0.697709
16,4,三連複,0.115606,1.117872,0.184704,0.774240
17,4,単勝,0.588070,0.787745,0.730105,0.776085
18,4,複勝,0.915547,0.866245,0.957183,0.802735
19,4,馬単,0.285250,0.836532,0.426547,0.747495
20,4,馬連,0.285250,0.867875,0.426547,0.772048
21,5,ワイド,0.672228,0.904608,0.795512,0.802652
22,5,三連単,0.197992,0.947965,0.316846,0.734386
23,5,三連複,0.197992,0.958345,0.316846,0.790759
24,5,単勝,0.671047,0.791747,0.805699,0.783768
25,5,複勝,0.952163,0.854570,0.981692,0.801364
26,5,馬単,0.393031,0.868253,0.554998,0.758900
27,5,馬連,0.393031,0.904779,0.554998,0.779848

In [82]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross_in3(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_only_tenkai_weight_in3.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)


evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_dirt_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.252987,0.766770,0.343222,0.758096
1,1,複勝,0.588381,0.889905,0.686856,0.853894
2,2,ワイド,0.264936,0.928101,0.345900,0.799794
3,2,単勝,0.420478,0.809786,0.546972,0.790132
4,2,複勝,0.805727,0.893665,0.883395,0.853234
5,2,馬単,0.117429,0.863855,0.164813,0.727204
6,2,馬連,0.117429,0.895818,0.164813,0.750082
7,3,ワイド,0.476926,0.860109,0.608982,0.836362
8,3,三連単,0.064483,0.932877,0.105274,0.751480
9,3,三連複,0.064483,0.957066,0.105274,0.817491
10,3,単勝,0.546560,0.809648,0.681500,0.796518
11,3,複勝,0.906469,0.862814,0.951792,0.845653
12,3,馬単,0.240626,0.835081,0.353935,0.792388
13,3,馬連,0.240626,0.831541,0.353935,0.817079
14,4,ワイド,0.649773,0.872047,0.769262,0.827572
15,4,三連単,0.152658,1.136433,0.254429,0.777640
16,4,三連複,0.152658,1.011465,0.254429,0.818505
17,4,単勝,0.646271,0.792681,0.778945,0.807746
18,4,複勝,0.955913,0.850968,0.981871,0.832339
19,4,馬単,0.362794,0.898929,0.509271,0.785121
20,4,馬連,0.362794,0.910627,0.509271,0.799224
21,5,ワイド,0.772765,0.847165,0.863618,0.797501
22,5,三連単,0.265966,0.920211,0.398640,0.723714
23,5,三連複,0.265966,0.890816,0.398640,0.760987
24,5,単勝,0.726617,0.793795,0.840544,0.786918
25,5,複勝,0.975690,0.838937,0.992171,0.813370
26,5,馬単,0.484755,0.833279,0.626494,0.745463
27,5,馬連,0.484755,0.848578,0.626494,0.758712

In [250]:
%autoreload

In [251]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_ex_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_ex_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_in3,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.253521,0.870892,0.347418,0.898122
1,1,複勝,0.530516,0.926761,0.610329,0.818310
2,2,ワイド,0.230047,1.037559,0.305164,0.790141
3,2,単勝,0.483568,1.244131,0.568075,0.897887
4,2,複勝,0.798122,1.022770,0.877934,0.869718
5,2,馬単,0.112676,1.453286,0.164319,0.841549
6,2,馬連,0.112676,1.400469,0.164319,0.845070
7,3,ワイド,0.427230,0.982316,0.539906,0.780908
8,3,三連単,0.056338,1.288341,0.079812,0.542019
9,3,三連複,0.056338,1.389202,0.079812,0.676995
10,3,単勝,0.619718,1.046166,0.704225,0.854147
11,3,複勝,0.915493,0.972770,0.915493,0.802034
12,3,馬単,0.234742,1.082629,0.314554,0.771283
13,3,馬連,0.234742,1.136307,0.314554,0.770110
14,4,ワイド,0.676056,1.222692,0.718310,0.781455
15,4,三連単,0.154930,1.817527,0.211268,0.706671
16,4,三連複,0.154930,1.963263,0.211268,0.843545
17,4,単勝,0.732394,1.045423,0.798122,0.815376
18,4,複勝,0.967136,1.025822,0.962441,0.799178
19,4,馬単,0.394366,1.321401,0.427230,0.617723
20,4,馬連,0.394366,1.410485,0.427230,0.616745
21,5,ワイド,0.798122,1.123803,0.816901,0.831315
22,5,三連単,0.309859,1.232731,0.370892,0.829844
23,5,三連複,0.309859,1.309108,0.370892,0.977606
24,5,単勝,0.798122,1.008638,0.840376,0.744413
25,5,複勝,0.971831,0.989484,0.985915,0.810141
26,5,馬単,0.521127,1.247793,0.572770,0.695822
27,5,馬連,0.521127,1.262488,0.572770,0.723756

In [85]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_in3 = Evaluator_lightgbm_rank_niti_cross_in3(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_in3.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_in3.csv")
summary_df_noodds_gbm_in3 = evaluator_in3.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3")
summary_df_noodds_gbm_in3

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3,returnrate_lightgbm_rank_niti_cross_dev_turf_only_tenkai_in3,hitrate_pop,returnrate_pop
0,1,単勝,0.207206,0.971078,0.312211,0.774050
1,1,複勝,0.502734,1.001023,0.613066,0.820735
2,2,ワイド,0.199776,1.247512,0.303098,0.780191
3,2,単勝,0.359736,0.920980,0.508902,0.793383
4,2,複勝,0.727604,0.965772,0.829385,0.829230
5,2,馬単,0.081593,1.111258,0.150568,0.752643
6,2,馬連,0.081593,1.152909,0.150568,0.791098
7,3,ワイド,0.397308,1.178644,0.544932,0.792224
8,3,三連単,0.050049,2.267454,0.086920,0.635925
9,3,三連複,0.050049,2.764265,0.086920,0.748058
10,3,単勝,0.491518,0.913440,0.643067,0.789565
11,3,複勝,0.847890,0.938357,0.918267,0.819169
12,3,馬単,0.191785,1.012120,0.309267,0.747689
13,3,馬連,0.191785,1.054288,0.309267,0.778289
14,4,ワイド,0.567924,1.106664,0.709379,0.804900
15,4,三連単,0.130520,1.683107,0.224310,0.733082
16,4,三連複,0.130520,1.790446,0.224310,0.800060
17,4,単勝,0.595261,0.908338,0.739240,0.781554
18,4,複勝,0.915744,0.926037,0.961867,0.811987
19,4,馬単,0.308426,1.017808,0.455489,0.748449
20,4,馬連,0.308426,1.036964,0.455489,0.772293
21,5,ワイド,0.698023,1.036218,0.821954,0.796232
22,5,三連単,0.244918,1.368729,0.363802,0.732656
23,5,三連複,0.244918,1.416958,0.363802,0.777684
24,5,単勝,0.680639,0.888678,0.814524,0.788151
25,5,複勝,0.956680,0.906752,0.981214,0.804164
26,5,馬単,0.425067,0.943946,0.585308,0.757507
27,5,馬連,0.425067,0.958281,0.585308,0.774926

In [86]:
# # オッズと人気を特徴量から省いたランク、日、クロスバリデーション
# trainer = Trainer_lightgbm_rank_niti_cv_in3(
    
#     features_filename = "features_turf.csv", 
#     config_filepath="config_lightgbm_niti_dev_turf_only_tenkai.yaml",
# )
# evaluation_df = trainer.run(
#     n_splits = 5,
#     importance_filename="importance_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3",
#     model_filename="model_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.pkl",
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
#     final_model_filename = "model_lightgbm_rank_niti_cv_full_dev_turf_only_tenkai_in3.pkl",
#     final_num_boost_round = 1500
# )

Training fold 1/5...
Training until validation scores don't improve for 100 rounds
[100]	valid_0's binary_logloss: 0.505974

KeyboardInterrupt:

In [ ]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_in3.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai")
summary_df_noodds_gbm

In [ ]:
%autoreload

##　状況

In [188]:
import create_population_turf
import create_population_turf_newbie
import create_population_turf_nowin
import create_population_obstract
import create_population_dirt
import create_population
import create_population_dirt_newbie
import create_population_dirt_nowin
import preprocessing
from feature_engineering import FeatureCreator


import pandas as pd
import numpy as np
import race_grade_maker


from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_niti_cross_in3 import Trainer_lightgbm_rank_niti_cv_in3

from train_lightgbm_time import Trainer_lightgbm_time
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki

from evaluation_shaft_time_kaiki_cross import Evaluator_lightgbm_time_kaiki_shaft

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross
from evaluation_shaft_rank_cross import Evaluator_lightgbm_rank_niti_shaft

from evaluation_lgbm_rank_niti_cross_ex_value import Evaluator_lightgbm_rank_niti_cross_ex_value

from evaluation_lgbm_rank_niti_cross_in3 import Evaluator_lightgbm_rank_niti_cross_in3

%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### 期待値

In [ ]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_ex_value")
summary_df_noodds_gbm_ex_value

In [ ]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_ex_value")
summary_df_noodds_gbm_ex_value

In [ ]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_value")
summary_df_noodds_gbm_ex_value

In [ ]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_ex_value")
summary_df_noodds_gbm_ex_value

In [ ]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_in3.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_ex_value")
summary_df_noodds_gbm_ex_value

In [ ]:

# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_only_tenkai_in3.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_only_tenkai_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_only_tenkai_ex_value")
summary_df_noodds_gbm_ex_value

In [ ]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator_ex_value = Evaluator_lightgbm_rank_niti_cross_ex_value(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_in3.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator_ex_value.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_obstract_ex_value.csv")
summary_df_noodds_gbm_ex_value = evaluator_ex_value.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_obstract_ex_value")
summary_df_noodds_gbm_ex_value

# 精度評価
- popは人気列にかけた場合の回収率、的中率です
- topnはそのモデルが評価した上からn番目にかけた場合の的中回収です
- 例えばtop4の馬単にかけた場合上から4つの馬をかけた、4*3=12通りの的中率、回収率を計算します
- なので、馬単と馬連などの的中率は同じになりますが、回収率は変わります

In [ ]:
# オッズ_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_turf.csv",
    return_tables_filenamer = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_top3_turf.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_turf")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_nopast_turf.csv",
    return_tables_filenamer = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_past_top3_turf.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_nopast_turf")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_turf.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_turf.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_turf")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
evaluator = Evaluator_lightgbm_time_kaiki_shaft(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_turf.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_time_cross_dev_top3_turf.csv")
summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_dev_turf")
summary_df_shaft

In [ ]:
# オッズ_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_odds.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_turf_odds.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_turf_odds")
summary_df_noodds_gbm

In [ ]:
# オッズ_軸
evaluator = Evaluator_lightgbm_time_kaiki_shaft(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_odds.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_time_cross_dev_top3_turf_odds.csv")
summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_dev_turf_odds")
summary_df_shaft

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_newbie.csv",
    return_tables_filename = "return_tables_turf_newbie.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_turf_newbie.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_turf_newbie")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_turf_nowin.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_turf_nowin.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_turf_nowin")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_dirt.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_dirt")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
evaluator = Evaluator_lightgbm_time_kaiki_shaft(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_time_cross_dev_top3_dirt.csv")
summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_dev_dirt")
summary_df_shaft

In [ ]:
# オッズ_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_odds.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_dirt_odds.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_dirt_odds")
summary_df_noodds_gbm

In [ ]:
# オッズ_軸
evaluator = Evaluator_lightgbm_time_kaiki_shaft(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_odds.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_time_cross_dev_top3_dirt_odds.csv")
summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_dev_dirt_odds")
summary_df_shaft

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_newbie.csv",
    return_tables_filename = "return_tables_dirt_newbie.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_dirt_newbie.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_dirt_newbie")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_dirt_nowin.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_dirt_nowin.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_dirt_nowin")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_obstract.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_obstract")
summary_df_noodds_gbm

In [ ]:
# オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
evaluator = Evaluator_lightgbm_time_kaiki_shaft(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_time_cross_dev_top3_obstract.csv")
summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_dev_obstract")
summary_df_shaft

In [ ]:
# オッズ
evaluator = Evaluator_lightgbm_time_kaiki(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract_odds.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_time_cross_dev_top3_obstract_odds.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_time_dev_obstract_odds")
summary_df_noodds_gbm

In [ ]:
# オッズと_軸
evaluator = Evaluator_lightgbm_time_kaiki_shaft(
    evaluation_filename="evaluation_lightgbm_time_cv_dev_obstract_odds.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_time_cross_dev_top3_obstract_odds.csv")
summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_time_cross_dev_obstract_odds")
summary_df_shaft

In [85]:
%autoreload

In [92]:
%autoreload

### 二値分類

In [87]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf,returnrate_lightgbm_rank_niti_cross_dev_turf,hitrate_pop,returnrate_pop
0,1,単勝,0.264966,0.826118,0.312211,0.774050
1,1,複勝,0.565120,0.863438,0.613066,0.820735
2,2,ワイド,0.256133,0.871429,0.303098,0.780191
3,2,単勝,0.440628,0.827695,0.508902,0.793383
4,2,複勝,0.786485,0.857283,0.829385,0.829230
5,2,馬単,0.116781,0.826265,0.150568,0.752643
6,2,馬連,0.116781,0.873097,0.150568,0.791098
7,3,ワイド,0.479321,0.862423,0.544932,0.792224
8,3,三連単,0.069115,0.801397,0.086920,0.635925
9,3,三連複,0.069115,0.882756,0.086920,0.748058
10,3,単勝,0.572130,0.815842,0.643067,0.789565
11,3,複勝,0.891350,0.848993,0.918267,0.819169
12,3,馬単,0.252909,0.796147,0.309267,0.747689
13,3,馬連,0.252909,0.830469,0.309267,0.778289
14,4,ワイド,0.648815,0.854514,0.709379,0.804900
15,4,三連単,0.173840,0.807214,0.224310,0.733082
16,4,三連複,0.173840,0.857942,0.224310,0.800060
17,4,単勝,0.672648,0.805853,0.739240,0.781554
18,4,複勝,0.944063,0.840859,0.961867,0.811987
19,4,馬単,0.384270,0.799346,0.455489,0.748449
20,4,馬連,0.384270,0.825690,0.455489,0.772293
21,5,ワイド,0.769382,0.849989,0.821954,0.796232
22,5,三連単,0.300014,0.863616,0.363802,0.732656
23,5,三連複,0.300014,0.866670,0.363802,0.777684
24,5,単勝,0.751858,0.802795,0.814524,0.788151
25,5,複勝,0.971821,0.830843,0.981214,0.804164
26,5,馬単,0.509884,0.817244,0.585308,0.757507
27,5,馬連,0.509884,0.837451,0.585308,0.774926

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf.csv",
#     return_tables_filename = "return_tables_turf.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf")
# summary_df_shaft

In [88]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_noweight.csv",
    return_tables_filename = "return_tables_turf.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_noweight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_noweight,returnrate_lightgbm_rank_niti_cross_dev_turf_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.262162,0.824436,0.312211,0.774050
1,1,複勝,0.563157,0.859807,0.613066,0.820735
2,2,ワイド,0.255292,0.894855,0.303098,0.780191
3,2,単勝,0.438245,0.818793,0.508902,0.793383
4,2,複勝,0.783681,0.859694,0.829385,0.829230
5,2,馬単,0.115099,0.885560,0.150568,0.752643
6,2,馬連,0.115099,0.925375,0.150568,0.791098
7,3,ワイド,0.480723,0.892425,0.544932,0.792224
8,3,三連単,0.069816,0.923919,0.086920,0.635925
9,3,三連複,0.069816,1.009337,0.086920,0.748058
10,3,単勝,0.570447,0.816706,0.643067,0.789565
11,3,複勝,0.889948,0.855432,0.918267,0.819169
12,3,馬単,0.256274,0.864706,0.309267,0.747689
13,3,馬連,0.256274,0.893014,0.309267,0.778289
14,4,ワイド,0.646572,0.868090,0.709379,0.804900
15,4,三連単,0.178046,0.858321,0.224310,0.733082
16,4,三連複,0.178046,0.910034,0.224310,0.800060
17,4,単勝,0.673489,0.803529,0.739240,0.781554
18,4,複勝,0.946026,0.843996,0.961867,0.811987
19,4,馬単,0.387495,0.830823,0.455489,0.748449
20,4,馬連,0.387495,0.855199,0.455489,0.772293
21,5,ワイド,0.762372,0.840796,0.821954,0.796232
22,5,三連単,0.300995,0.831044,0.363802,0.732656
23,5,三連複,0.300995,0.847331,0.363802,0.777684
24,5,単勝,0.749614,0.793837,0.814524,0.788151
25,5,複勝,0.974345,0.829449,0.981214,0.804164
26,5,馬単,0.506098,0.802220,0.585308,0.757507
27,5,馬連,0.506098,0.819900,0.585308,0.774926

In [ ]:
%autoreload

### ダート

In [89]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt,returnrate_lightgbm_rank_niti_cross_dev_dirt,hitrate_pop,returnrate_pop
0,1,単勝,0.273734,0.848398,0.325557,0.817821
1,1,複勝,0.568581,0.868537,0.616270,0.841355
2,2,ワイド,0.233722,0.860505,0.286284,0.820537
3,2,単勝,0.442049,0.813044,0.507456,0.797483
4,2,複勝,0.781633,0.848014,0.822235,0.834136
5,2,馬単,0.108814,0.828466,0.141001,0.792263
6,2,馬連,0.108814,0.870486,0.141001,0.833279
7,3,ワイド,0.433338,0.834298,0.517644,0.822447
8,3,三連単,0.052414,0.844089,0.074708,0.713345
9,3,三連複,0.052414,0.905448,0.074708,0.833634
10,3,単勝,0.565038,0.799390,0.640189,0.797643
11,3,複勝,0.886756,0.830026,0.918205,0.826906
12,3,馬単,0.226930,0.779044,0.290861,0.763278
13,3,馬連,0.226930,0.808101,0.290861,0.793105
14,4,ワイド,0.605345,0.823264,0.676805,0.793400
15,4,三連単,0.138343,0.759225,0.184704,0.697709
16,4,三連複,0.138343,0.797966,0.184704,0.774240
17,4,単勝,0.659530,0.789351,0.730105,0.776085
18,4,複勝,0.937841,0.819980,0.957183,0.802735
19,4,馬単,0.348295,0.771845,0.426547,0.747495
20,4,馬連,0.348295,0.792620,0.426547,0.772048
21,5,ワイド,0.731729,0.815140,0.795512,0.802652
22,5,三連単,0.248191,0.778926,0.316846,0.734386
23,5,三連複,0.248191,0.797099,0.316846,0.790759
24,5,単勝,0.739554,0.795057,0.805699,0.783768
25,5,複勝,0.966928,0.815364,0.981692,0.801364
26,5,馬単,0.470397,0.782370,0.554998,0.758900
27,5,馬連,0.470397,0.798578,0.554998,0.779848

In [90]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight.csv",
    return_tables_filename = "return_tables_dirt.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt,returnrate_lightgbm_rank_niti_cross_dev_dirt,hitrate_pop,returnrate_pop
0,1,単勝,0.272996,0.841385,0.325557,0.817821
1,1,複勝,0.568729,0.869083,0.616270,0.841355
2,2,ワイド,0.234313,0.865997,0.286284,0.820537
3,2,単勝,0.439244,0.816123,0.507456,0.797483
4,2,複勝,0.780452,0.852067,0.822235,0.834136
5,2,馬単,0.107043,0.824450,0.141001,0.792263
6,2,馬連,0.107043,0.862129,0.141001,0.833279
7,3,ワイド,0.434372,0.857380,0.517644,0.822447
8,3,三連単,0.054333,0.885762,0.074708,0.713345
9,3,三連複,0.054333,0.974118,0.074708,0.833634
10,3,単勝,0.559132,0.796107,0.640189,0.797643
11,3,複勝,0.885723,0.834972,0.918205,0.826906
12,3,馬単,0.224420,0.766935,0.290861,0.763278
13,3,馬連,0.224420,0.794572,0.290861,0.793105
14,4,ワイド,0.605935,0.849397,0.676805,0.793400
15,4,三連単,0.142625,0.811355,0.184704,0.697709
16,4,三連複,0.142625,0.858663,0.184704,0.774240
17,4,単勝,0.661598,0.810575,0.730105,0.776085
18,4,複勝,0.939466,0.829348,0.957183,0.802735
19,4,馬単,0.351691,0.794916,0.426547,0.747495
20,4,馬連,0.351691,0.823852,0.426547,0.772048
21,5,ワイド,0.731729,0.841797,0.795512,0.802652
22,5,三連単,0.252030,0.800682,0.316846,0.734386
23,5,三連複,0.252030,0.845094,0.316846,0.790759
24,5,単勝,0.737192,0.799091,0.805699,0.783768
25,5,複勝,0.969437,0.824480,0.981692,0.801364
26,5,馬単,0.469216,0.792556,0.554998,0.758900
27,5,馬連,0.469216,0.811327,0.554998,0.779848

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_noweight.csv",
#     return_tables_filename = "return_tables_dirt.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_dirt.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
# summary_df_shaft

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt.csv",
#     return_tables_filename = "return_tables_dirt.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_dirt.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt")
# summary_df_shaft

### 障害

In [91]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_noweight.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_obstract_noweight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_obstract_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_obstract_noweight,returnrate_lightgbm_rank_niti_cross_dev_obstract_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.339005,1.032199,0.369110,0.832723
1,1,複勝,0.654450,0.959424,0.697644,0.881414
2,2,ワイド,0.308901,1.004712,0.362565,0.862042
3,2,単勝,0.518325,0.989856,0.577225,0.851767
4,2,複勝,0.848168,0.921597,0.884817,0.876702
5,2,馬単,0.147906,1.087565,0.187173,0.963154
6,2,馬連,0.147906,1.126571,0.187173,0.977487
7,3,ワイド,0.573298,1.035253,0.623037,0.877312
8,3,三連単,0.082461,1.353294,0.106021,0.768695
9,3,三連複,0.082461,1.425654,0.106021,0.957592
10,3,単勝,0.642670,0.934162,0.695026,0.807373
11,3,複勝,0.937173,0.932897,0.956806,0.857330
12,3,馬単,0.308901,1.045637,0.353403,0.835013
13,3,馬連,0.308901,1.088962,0.353403,0.862086
14,4,ワイド,0.726440,1.061235,0.768325,0.877989
15,4,三連単,0.226440,1.357030,0.265707,0.893919
16,4,三連複,0.226440,1.464169,0.265707,0.995550
17,4,単勝,0.750000,0.922611,0.787958,0.803829
18,4,複勝,0.975131,0.921401,0.986911,0.839823
19,4,馬単,0.459424,1.076025,0.511780,0.827978
20,4,馬連,0.459424,1.088918,0.511780,0.858181
21,5,ワイド,0.849476,0.996597,0.888743,0.902029
22,5,三連単,0.373037,1.202088,0.442408,0.905366
23,5,三連複,0.373037,1.170249,0.442408,0.952984
24,5,単勝,0.818063,0.872016,0.857330,0.829136
25,5,複勝,0.986911,0.900445,0.994764,0.854817
26,5,馬単,0.587696,0.950641,0.655759,0.839791
27,5,馬連,0.587696,0.964005,0.655759,0.855157

In [92]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract.csv",
    return_tables_filename = "return_tables_obstract.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_obstract.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_obstract")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_obstract,returnrate_lightgbm_rank_niti_cross_dev_obstract,hitrate_pop,returnrate_pop
0,1,単勝,0.327225,1.062827,0.369110,0.832723
1,1,複勝,0.637435,0.933770,0.697644,0.881414
2,2,ワイド,0.311518,1.012435,0.362565,0.862042
3,2,単勝,0.517016,0.963743,0.577225,0.851767
4,2,複勝,0.846859,0.929450,0.884817,0.876702
5,2,馬単,0.138743,0.963809,0.187173,0.963154
6,2,馬連,0.138743,0.991099,0.187173,0.977487
7,3,ワイド,0.565445,1.015794,0.623037,0.877312
8,3,三連単,0.079843,1.122535,0.106021,0.768695
9,3,三連複,0.079843,1.296990,0.106021,0.957592
10,3,単勝,0.646597,0.955803,0.695026,0.807373
11,3,複勝,0.935864,0.931588,0.956806,0.857330
12,3,馬単,0.295812,0.935362,0.353403,0.835013
13,3,馬連,0.295812,0.984424,0.353403,0.862086
14,4,ワイド,0.735602,1.044197,0.768325,0.877989
15,4,三連単,0.223822,1.205366,0.265707,0.893919
16,4,三連複,0.223822,1.292670,0.265707,0.995550
17,4,単勝,0.752618,0.942048,0.787958,0.803829
18,4,複勝,0.972513,0.930007,0.986911,0.839823
19,4,馬単,0.456806,1.056468,0.511780,0.827978
20,4,馬連,0.456806,1.069154,0.511780,0.858181
21,5,ワイド,0.854712,1.003482,0.888743,0.902029
22,5,三連単,0.369110,0.997334,0.442408,0.905366
23,5,三連複,0.369110,1.047094,0.442408,0.952984
24,5,単勝,0.819372,0.910785,0.857330,0.829136
25,5,複勝,0.985602,0.915576,0.994764,0.854817
26,5,馬単,0.583770,1.005785,0.655759,0.839791
27,5,馬連,0.583770,0.998233,0.655759,0.855157

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_obstract_noweight.csv",
#     return_tables_filename = "return_tables_obstract.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_obstract.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_obstract")
# summary_df_shaft

In [ ]:
%autoreload

### 未勝利

In [93]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin,hitrate_pop,returnrate_pop
0,1,単勝,0.291185,0.826198,0.352066,0.811928
1,1,複勝,0.620661,0.878017,0.677410,0.861460
2,2,ワイド,0.285124,0.928320,0.352066,0.822727
3,2,単勝,0.477135,0.844298,0.554270,0.816983
4,2,複勝,0.832782,0.872782,0.876309,0.857796
5,2,馬単,0.128926,0.857025,0.185675,0.872700
6,2,馬連,0.128926,0.926667,0.185675,0.900689
7,3,ワイド,0.519559,0.885455,0.607989,0.822443
8,3,三連単,0.074380,1.067957,0.105510,0.723186
9,3,三連複,0.074380,1.054959,0.105510,0.782204
10,3,単勝,0.601102,0.818714,0.687879,0.816006
11,3,複勝,0.918733,0.857916,0.946006,0.841653
12,3,馬単,0.274931,0.858379,0.366942,0.820826
13,3,馬連,0.274931,0.886804,0.366942,0.846033
14,4,ワイド,0.684848,0.899770,0.768320,0.832392
15,4,三連単,0.186501,1.090826,0.261983,0.792011
16,4,三連複,0.186501,1.006997,0.261983,0.845523
17,4,単勝,0.704408,0.856191,0.780441,0.812555
18,4,複勝,0.960331,0.853120,0.976309,0.831563
19,4,馬単,0.414050,0.875255,0.520110,0.808404
20,4,馬連,0.414050,0.894421,0.520110,0.822635
21,5,ワイド,0.792287,0.857457,0.863085,0.804466
22,5,三連単,0.306061,1.033100,0.407989,0.766662
23,5,三連複,0.306061,1.014501,0.407989,0.794237
24,5,単勝,0.769421,0.824281,0.849587,0.817609
25,5,複勝,0.982094,0.837829,0.991460,0.814198
26,5,馬単,0.530028,0.831041,0.643526,0.787114
27,5,馬連,0.530028,0.851416,0.643526,0.797118

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin.csv",
#     return_tables_filename = "return_tables_turf_nowin.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_turf_nowin.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin")
# summary_df_shaft

In [94]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_turf_nowin_noweight.csv",
    return_tables_filename = "return_tables_turf_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_turf_nowin_noweight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_turf_nowin_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_turf_nowin_noweight,returnrate_lightgbm_rank_niti_cross_dev_turf_nowin_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.286777,0.817107,0.352066,0.811928
1,1,複勝,0.607713,0.857410,0.677410,0.861460
2,2,ワイド,0.276584,0.885978,0.352066,0.822727
3,2,単勝,0.463912,0.816708,0.554270,0.816983
4,2,複勝,0.826997,0.867231,0.876309,0.857796
5,2,馬単,0.121763,0.762355,0.185675,0.872700
6,2,馬連,0.121763,0.797879,0.185675,0.900689
7,3,ワイド,0.499174,0.851359,0.607989,0.822443
8,3,三連単,0.075482,1.074940,0.105510,0.723186
9,3,三連複,0.075482,1.037300,0.105510,0.782204
10,3,単勝,0.589807,0.813848,0.687879,0.816006
11,3,複勝,0.915702,0.840156,0.946006,0.841653
12,3,馬単,0.263085,0.816598,0.366942,0.820826
13,3,馬連,0.263085,0.837511,0.366942,0.846033
14,4,ワイド,0.669697,0.850468,0.768320,0.832392
15,4,三連単,0.187879,0.952205,0.261983,0.792011
16,4,三連複,0.187879,0.966674,0.261983,0.845523
17,4,単勝,0.696419,0.829008,0.780441,0.812555
18,4,複勝,0.958678,0.835303,0.976309,0.831563
19,4,馬単,0.406061,0.815296,0.520110,0.808404
20,4,馬連,0.406061,0.831042,0.520110,0.822635
21,5,ワイド,0.785675,0.811645,0.863085,0.804466
22,5,三連単,0.293113,0.940583,0.407989,0.766662
23,5,三連複,0.293113,0.937945,0.407989,0.794237
24,5,単勝,0.765840,0.806871,0.849587,0.817609
25,5,複勝,0.981818,0.819366,0.991460,0.814198
26,5,馬単,0.514050,0.776023,0.643526,0.787114
27,5,馬連,0.514050,0.780386,0.643526,0.797118

In [ ]:
%autoreload

In [95]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nowin_noweight.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nowin_noweight")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nowin_noweight,returnrate_lightgbm_rank_niti_cross_dev_dirt_nowin_noweight,hitrate_pop,returnrate_pop
0,1,単勝,0.289246,0.763391,0.343222,0.758096
1,1,複勝,0.626082,0.844046,0.686856,0.853894
2,2,ワイド,0.293160,0.817862,0.345900,0.799794
3,2,単勝,0.474248,0.797136,0.546972,0.790132
4,2,複勝,0.830861,0.842697,0.883395,0.853234
5,2,馬単,0.134940,0.817985,0.164813,0.727204
6,2,馬連,0.134940,0.840194,0.164813,0.750082
7,3,ワイド,0.525752,0.844053,0.608982,0.836362
8,3,三連単,0.078904,0.897456,0.105274,0.751480
9,3,三連複,0.078904,1.006881,0.105274,0.817491
10,3,単勝,0.601360,0.790084,0.681500,0.796518
11,3,複勝,0.920066,0.841732,0.951792,0.845653
12,3,馬単,0.280181,0.753571,0.353935,0.792388
13,3,馬連,0.280181,0.777125,0.353935,0.817079
14,4,ワイド,0.688504,0.841007,0.769262,0.827572
15,4,三連単,0.186238,0.821243,0.254429,0.777640
16,4,三連複,0.186238,0.903904,0.254429,0.818505
17,4,単勝,0.697775,0.797899,0.778945,0.807746
18,4,複勝,0.961063,0.833514,0.981871,0.832339
19,4,馬単,0.412855,0.727338,0.509271,0.785121
20,4,馬連,0.412855,0.757890,0.509271,0.799224
21,5,ワイド,0.801813,0.838508,0.863618,0.797501
22,5,三連単,0.311908,0.853709,0.398640,0.723714
23,5,三連複,0.311908,0.912851,0.398640,0.760987
24,5,単勝,0.774001,0.801199,0.840544,0.786918
25,5,複勝,0.979604,0.836893,0.992171,0.813370
26,5,馬単,0.526782,0.711698,0.626494,0.745463
27,5,馬連,0.526782,0.741259,0.626494,0.758712

In [96]:
# オッズと人気を特徴量から省いた場合_ランク、二値、クロスバリデーション（最終番目）
evaluator = Evaluator_lightgbm_rank_niti_cross(
    evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin.csv",
    return_tables_filename = "return_tables_dirt_nowin.pickle",
)
evaluator.summarize_box_top_n(n=3,save_filename="box_summary_rank_niti_cross_dev_dirt_nowin.csv")
summary_df_noodds_gbm = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nowin")
summary_df_noodds_gbm

,topn,bet_type,hitrate_lightgbm_rank_niti_cross_dev_dirt_nowin,returnrate_lightgbm_rank_niti_cross_dev_dirt_nowin,hitrate_pop,returnrate_pop
0,1,単勝,0.283478,0.806139,0.343222,0.758096
1,1,複勝,0.617635,0.866502,0.686856,0.853894
2,2,ワイド,0.283478,0.875505,0.345900,0.799794
3,2,単勝,0.464359,0.804594,0.546972,0.790132
4,2,複勝,0.826947,0.862701,0.883395,0.853234
5,2,馬単,0.131850,0.800536,0.164813,0.727204
6,2,馬連,0.131850,0.837454,0.164813,0.750082
7,3,ワイド,0.509889,0.851586,0.608982,0.836362
8,3,三連単,0.071899,0.789747,0.105274,0.751480
9,3,三連複,0.071899,0.873877,0.105274,0.817491
10,3,単勝,0.595385,0.808344,0.681500,0.796518
11,3,複勝,0.920066,0.846106,0.951792,0.845653
12,3,馬単,0.273383,0.762522,0.353935,0.792388
13,3,馬連,0.273383,0.785496,0.353935,0.817079
14,4,ワイド,0.693243,0.869269,0.769262,0.827572
15,4,三連単,0.178616,0.789638,0.254429,0.777640
16,4,三連複,0.178616,0.908148,0.254429,0.818505
17,4,単勝,0.696539,0.818619,0.778945,0.807746
18,4,複勝,0.961681,0.850896,0.981871,0.832339
19,4,馬単,0.413267,0.758148,0.509271,0.785121
20,4,馬連,0.413267,0.786533,0.509271,0.799224
21,5,ワイド,0.799959,0.868962,0.863618,0.797501
22,5,三連単,0.307993,0.822251,0.398640,0.723714
23,5,三連複,0.307993,0.891792,0.398640,0.760987
24,5,単勝,0.772353,0.813375,0.840544,0.786918
25,5,複勝,0.982077,0.849683,0.992171,0.813370
26,5,馬単,0.531932,0.775540,0.626494,0.745463
27,5,馬連,0.531932,0.800546,0.626494,0.758712

In [ ]:
# # オッズと人気を特徴量から省いた場合_time、回帰、クロスバリデーション（最終番目）_軸
# evaluator = Evaluator_lightgbm_rank_niti_shaft(
#     evaluation_filename="evaluation_lightgbm_rank_niti_cv_dev_dirt_nowin_noweight.csv",
#     return_tables_filename = "return_tables_dirt_nowin.pickle",
# )
# evaluator.summarize_box_top_n(n=3,save_filename="shaft_summary_rank_niti_dev_top3_dirt_nowin_noweight.csv")
# summary_df_shaft = evaluator.summarize_box_exp(exp_name="lightgbm_rank_niti_cross_dev_dirt_nowin_noweight")
# summary_df_shaft

# 予測当日の処理

## 事前準備
**当日出走馬が確定した時点**で実行できる

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [ ]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

In [ ]:
population = create_population.create(from_="2016-01-01", to_="2024-11-31")

In [ ]:
# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

In [ ]:
pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

In [ ]:
# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

## 当日の予測処理
レース直前出走直前に実行する

In [ ]:
#当日にやらないと、天気や馬場状態がわからないので、当日に実行してください、
# 特徴量の更新
features = pfc.create_features(
    race_id="202408060411",  # 予測するレースidを指定
    date_content_a = "2024年11月10日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

In [ ]:
pfc.results

In [ ]:
pfc.race_info

### pred列は全て降順（大きい順）で表示されます
### 二値予測のrankはpred列が大きい順で評価がよく、回帰のrankとtimeは小さい順で評価が良いです
### 順番が逆になっているので気をつけてください

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)